### ISSUE TITLE
How to remove the background

### ISSUE THREAD

**Issue by shewangmu** [graphdeco-inria/gaussian-splatting#101]
If I only interested in the foreground object (with masks I already have for each image), how to avoid the reconstruction of the background?

**Comment by Snosixtyboo** [comment]
Hi,

it should work if you merge the masks and original image into combined RGBA images (where A is 0 for anything that should be masked away). A nice way to do this efficiently would be to use a Python script and imagemagick. We don't have one right now though, so maybe someone can provide this or you will have to wait until we get to it.

Best,
Bernhard

**Comment by shewangmu** [comment]
> Hi,
> 
> it should work if you merge the masks and original image into combined RGBA images (where A is 0 for anything that should be masked away). A nice way to do this efficiently would be to use a Python script and imagemagick. We don't have one right now though, so maybe someone can provide this or you will have to wait until we get to it.
> 
> Best, Bernhard

Hi Bernhard,
Thank you for your response and fantastic work! I can merge the channels. Additionally, is it possible to render the image with alpha channels? When I call render.py, the rendered image only contains 3 channels.

**Comment by shewangmu** [comment]
> > Hi,
> > it should work if you merge the masks and original image into combined RGBA images (where A is 0 for anything that should be masked away). A nice way to do this efficiently would be to use a Python script and imagemagick. We don't have one right now though, so maybe someone can provide this or you will have to wait until we get to it.
> > Best, Bernhard
> 
> Hi Bernhard, Thank you for your response and fantastic work! I can merge the channels. Additionally, is it possible to render the image with alpha channels? When I call render.py, the rendered image only contains 3 channels.

I add a channel for out_color and fill it with 1.0f - T in forward.cu, but the alpha channel contains so much floaters. I am wondering whether you use the alpha for training or not

**Comment by henrypearce4D** [comment]
@shewangmu does this perhaps answer your question? https://github.com/graphdeco-inria/gaussian-splatting/issues/64#issuecomment-1658597573
