### ISSUE TITLE
Rendered Output Image Quality Far Exceeds Viewer Display

### ISSUE THREAD

**Issue by Golbstein** [graphdeco-inria/gaussian-splatting#1012]
Hi, I've trained the model and used `render.py` to generate render images for my camera setup, and the results look great. However, when I visualize the splats (the point_cloud.ply) from the exact same camera in the viewer, the quality appears significantly worse. Could you help me understand why there's such a difference in the visualization?

### Examples:

**Rendered output**
<img width="1079" alt="image" src="https://github.com/user-attachments/assets/af5a1b5a-824f-4294-be62-bad53704c78a">

**Viewer display**
<img width="1718" alt="image" src="https://github.com/user-attachments/assets/ed126420-44ee-429e-b8a6-c87e1de06d0f">

**Rendered output**
<img width="1074" alt="image" src="https://github.com/user-attachments/assets/887ba8bf-a83c-418f-9a51-f504f97abfd9">
**Viewer display**
<img width="1725" alt="image" src="https://github.com/user-attachments/assets/1df5619a-980f-4785-80e7-e22b27f2960d">

PS
solved - the web GL viewer on full screen was zoomed, resized the screen and got same scenes

**Comment by jeff999955** [comment]
Hi, can I ask how did you resize the screen and got the same scene? I have tried zooming in and out but still observe the artifacts in the visualizer like this image of yours.

![Image](https://github.com/user-attachments/assets/6b172b6d-2f8d-44fa-9041-357f9beace9e)

> Hi, I've trained the model and used `render.py` to generate render images for my camera setup, and the results look great. However, when I visualize the splats (the point_cloud.ply) from the exact same camera in the viewer, the quality appears significantly worse. Could you help me understand why there's such a difference in the visualization?
> 
> ### Examples:
> **Rendered output** <img alt="image" width="1079" src="https://private-user-images.githubusercontent.com/31940058/376146402-af5a1b5a-824f-4294-be62-bad53704c78a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDMxMDk0NDEsIm5iZiI6MTc0MzEwOTE0MSwicGF0aCI6Ii8zMTk0MDA1OC8zNzYxNDY0MDItYWY1YTFiNWEtODI0Zi00Mjk0LWJlNjItYmFkNTM3MDRjNzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI3VDIwNTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNmY0MTVjZmU4YmZkYjY5NzdjNDM0MDcxMjMwOTA3Nzg1NmViZjMyODE4ZDIxMWMxNzIxOWE5OGFlODgwNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rDkQjcGyFOvK2OPNkQbShkn7G5HIsLPRtS6jlNxFj0w">
> 
> **Viewer display** <img alt="image" width="1718" src="https://private-user-images.githubusercontent.com/31940058/376147121-ed126420-44ee-429e-b8a6-c87e1de06d0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDMxMDk0NDEsIm5iZiI6MTc0MzEwOTE0MSwicGF0aCI6Ii8zMTk0MDA1OC8zNzYxNDcxMjEtZWQxMjY0MjAtNDRlZS00MjllLWI4YTYtYzg3ZTFkZTA2ZDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI3VDIwNTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1OGYzZTY4NGJhOWI4OGU2MTA1N2NhOWJmMTk3OWRjNzczMDczMjE3OTNjYWI0Yzk2MmIxZWJlY2ZhZDdhNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KWrzYHrYbpnO6nBxO9sCqKhTJejJtvMs_yaFX8euuak">
> 
> **Rendered output** <img alt="image" width="1074" src="https://private-user-images.githubusercontent.com/31940058/376147476-887ba8bf-a83c-418f-9a51-f504f97abfd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDMxMDk0NDEsIm5iZiI6MTc0MzEwOTE0MSwicGF0aCI6Ii8zMTk0MDA1OC8zNzYxNDc0NzYtODg3YmE4YmYtYTgzYy00MThmLTlhNTEtZjUwNGY5N2FiZmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI3VDIwNTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MGQxNTU4M2IzMWZjMTRhMGFjMzNjNzU3YzUwYmY2OTk0MThlNzFiOTAzZTI1OGQzMWRiNjM3NWZhYWJkYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h4aZNunLAHOGgjl9IE8OWdJR4ijQS7GwrpxPEHgVzRE"> **Viewer display** <img alt="image" width="1725" src="https://private-user-images.githubusercontent.com/31940058/376147746-1df5619a-980f-4785-80e7-e22b27f2960d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDMxMDk0NDEsIm5iZiI6MTc0MzEwOTE0MSwicGF0aCI6Ii8zMTk0MDA1OC8zNzYxNDc3NDYtMWRmNTYxOWEtOTgwZi00Nzg1LTgwZTctZTIyYjI3ZjI5NjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI3VDIwNTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZGFlMzE5NzhlNDFkMTRmNmJjYzU5ODJhYmVlMjNmNTQyZmY4ZmJhYzc1ZThjMWMyN2Y5Y2VhNGU0ZTc2YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cNqamJfpuC5k1HO_e0HK_dCGE0hlOa6B4CdaGkUpokA">
> 
> PS solved - the web GL viewer on full screen was zoomed, resized the screen and got same scenes
