### ISSUE TITLE
Changes in image size after processing my own data with "convert.py"

### ISSUE THREAD

**Issue by MnKnight1** [graphdeco-inria/gaussian-splatting#1024]
I put my own data in the directory `<location>/input`,the size of images is` [4032x2268]`.
After running the comannd` python convert.py -s <location>`, new folder `<location>/images` was created，but the size of new images is `[3919x2207]`,which is smaller than original size` [4032x2268]`.
I want the image to remain the original size. What should I do?

**Comment by jaco001** [comment]
In general you can use few more parameters from colmap.
Look there https://github.com/colmap/colmap/issues/2282

One more thing. You put very big images to convert.py that at the end will be converted (by default) to 1600 px. IMHO it is waste of time and VRAM. Convert it before to 3200 or 2400 if you need some fine datail and try run train.py with "-r 1" parameter. Or create just 1600 dataset before with optimized resized/sharpen algorithm.

**Comment by MnKnight1** [comment]
thank you for your help！

**Comment by MnKnight1** [comment]
There is still a difference between the images in the images folder (images processed by convert.py) and the images in the input folder (images entered by colmap). The former is distorted by colmap, as mentioned in https://github.com/graphdeco-inria/gaussian-splatting/issues/936#issuecomment-2296273482
Now I tried using Wonlows 'colmap ui to obtain camera parameters (colmap gui -> automatic reconstruction), but the image processed by colmap is still distorted, unlike https://github.com/graphdeco-inria/gaussian-splatting/issues/936#issuecomment-2297768969 mentioned that it will not be distorted.
What should I do to keep the images processed by colmap from distortion?
![QQ20241026-115324](https://github.com/user-attachments/assets/d17e4989-b9c1-4b7c-80dd-fd98c6c4db95)

**Comment by jaco001** [comment]
'Geometry' will always be changed, cuz there is conversion to pinhole camera. Colmap change geometry (in this workflow) and do some cropping to keep ratio and usually change size. That help you use masks or other software that need exactly images of the same size (even if there is some differences at pictures).

You can change convert.py to your likings, but algorithms in training can not work like should.

**Comment by MnKnight1** [comment]
ok,i have understood,thank you！
