### ISSUE TITLE
Is it possible to load GS ply file then do training again?

### ISSUE THREAD

**Issue by oUp2Uo** [graphdeco-inria/gaussian-splatting#1025]
Hi, I wonder if it is possible to load GS ply then do training?
For instance, since background usually is far away, so there wolud be "frog" points in the result GS ply file. We could manually delete these points by editing tool like `supersplat`. But this may make some parts of the remain objects be transparent. If we could re-train using this edited GS ply as starting point, we could only change the alpha of the points without densification. I guess if this method could get a better result for the main objects.
Thank you.

**Comment by jaco001** [comment]
You can and ppl do retraining.
