### ISSUE TITLE
run error： ValueError: only one element tensors can be converted to Python scalars

### ISSUE THREAD

**Issue by tianxiaguixin002** [graphdeco-inria/gaussian-splatting#104]
I run the code on my data,  when Training progress:  23%, error occur:

█████████▋                                                                                                                        Training progress:  23%|█████████████████▉                                                           | 7000/30000 [04:28<19:22, 19.78it/s, Loss=0.0469622]
[ITER 7000] Evaluating train: L1 0.032999453321099284 PSNR 24.910897445678714 [17/08 14:26:33]
<class 'torch.Tensor'> tensor([[0.4460],
        [0.2175],
        [0.9130],
        ...,
        [1.0000],
        [0.7575],
        [1.0000]], device='cuda:0') [17/08 14:26:33]
Traceback (most recent call last):
  File "train.py", line 217, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 104, in training
    training_report(tb_writer, iteration, Ll1, loss, l1_loss, iter_start.elapsed_time(iter_end), testing_iterations, scene, render, (pipe, background))
  File "train.py", line 187, in training_report
    tb_writer.add_histogram("scene/opacity_histogram", scene.gaussians.get_opacity, iteration)
ValueError: only one element tensors can be converted to Python scalars
Training progress:  23%|█████████████████▉                                                           | 7000/30000 [04:31<14:52, 25.78it/s, Loss=0.0469622]

result = scene.gaussians.get_opacity, the result becomes an vector, not one element . 
Please help me, thank you.

**Comment by Snosixtyboo** [comment]
Hi,

unfortunately I can't reproduce this. Can you print what is in both ```iteration``` and ```scene.gaussians.get_opacity``` before the line ```tb_writer.add_histogram("scene/opacity_histogram", scene.gaussians.get_opacity, iteration)``` is run?
