### ISSUE TITLE
How long does the training process usually take?

### ISSUE THREAD

**Issue by kirikunkun** [graphdeco-inria/gaussian-splatting#1049]
We are using the dataset provided in the paper, iterating 30,000 times on an RTX 3080 Ti. However, the training time is quite short, finishing in less than ten minutes. We’d like to know how long it typically takes others to train in order to help us troubleshoot further.

**Comment by kirikunkun** [comment]
![微信图片_20241105165143](https://github.com/user-attachments/assets/e69868dc-3400-41e7-867f-b3d41931e9b6)
We're not sure if this is a normal process.

**Comment by AsherJingkongChen** [comment]
The PSNR is generally greater than 16. You have got 4, which indicates low quality. You have fast training because the quality is broken.

**Comment by kirikunkun** [comment]
> The PSNR is generally greater than 16. You have got 4, which indicates low quality. You have fast training because the quality is broken.

We’re unsure which step is causing this issue, as we used the exact same configuration.
