### ISSUE TITLE
Loss not significantly decreasing 

### ISSUE THREAD

**Issue by lzfdw** [graphdeco-inria/gaussian-splatting#1050]
Hello, I am encountering some issues while training. Here are the details:

Loss: The Loss does not decrease significantly during training and remains relatively high.
Training time: The training time is much shorter than expected.
Output point cloud: The point cloud generated after training is sparse (both in quantity and quality).

I use [Here](https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/datasets/input/tandt_db.zip) to train. But the result is bad. Here are screenshots of my training process , the output point cloud file and the result.

training process:
![1](https://github.com/user-attachments/assets/b137f9e1-8867-480d-864a-60d89c96df60)

point cloud file:
![2](https://github.com/user-attachments/assets/5a6f23da-b844-4ff3-b49a-db81fe68cc6c)

 results:
![3](https://github.com/user-attachments/assets/8d879909-0132-42d7-8634-f2e79490be28)

![4](https://github.com/user-attachments/assets/da8aba4d-974c-4623-93d9-c78b0ba2dd65)

I can't find the problem

**Comment by AsherJingkongChen** [comment]
Please check the submodules manually, or checkout the previous versions (e.g. 9 months ago). I believe there is something wrong with upstream or your local revision.

```shell
git submodule update --init --recursive --remote
```

**Comment by lzfdw** [comment]
> Please check the submodules manually, or checkout the previous versions (e.g. 9 months ago). I believe there is something wrong with upstream or your local revision.
> 
> ```shell
> git submodule update --init --recursive --remote
> ```

Thank you very much for your response. I have modified the submodules and successfully started the training.

**Comment by scott198510** [comment]
@AsherJingkongChen Which module in the submodules has changed?
