### ISSUE TITLE
SIBR binary cudart64_12.dll

### ISSUE THREAD

**Issue by MustfizurRahaman** [graphdeco-inria/gaussian-splatting#1062]
SIBR binary execution is showing an error due to cudart64_12.dll not found. Using cuda 11.8. Is there any solution for it?

**Comment by tkomair** [comment]
same problem here. I've installed 11.8 as per the instructions. What am I missing?

**Comment by kjy5** [comment]
Also experiencing this issue as well

**Comment by MustfizurRahaman** [comment]
Fixed : 
Download the dll file from below site and place it on viewers/bin folder
[https://www.dllme.com/dll/files/cudart](https://www.dllme.com/dll/files/cudart)

**Comment by Baorunhui** [comment]
If you don't know which version to download from the site @MustfizurRahaman mentioned, like me, I found the dll file from below site.  I hope it will be useful to others.
https://github.com/LostRuins/koboldcpp/blob/concedo/cudart64_12.dll

**Comment by Elaine10** [comment]
conda install cudatoolkit
