### ISSUE TITLE
Is there a step-by-step tutorial for training customized data?

### ISSUE THREAD

**Issue by XinyueZ** [graphdeco-inria/gaussian-splatting#107]
Hello Team,

I believe you've done an excellent job, however, the README is rather long for beginners to get started with, particularly when working with the nerf and associated projects.

Could you dedicate some time to create a tutorial guiding us through step-by-step training with customized data?

Thank you.

**Comment by BennetLeff** [comment]
I think the README is long specifically to provide enough information to get going. A few notes I took that might help you:

There are two "necessary" stages: 

Convert Stage to generate colmap features
 * images must exist inside a folder called 'input'
 * run python convert.py -s <some folder with a subfolder called input containing the images>
 
Train Stage
 * run python train.py -s <same folder as convert stage path>
 * /output/ folder within the main folder is the default model output folder
 * example run:
	./SIBR_viewers/install/bin/SIBR_gaussianViewer_app -m ./output/b46bcb45-3

**Comment by Snosixtyboo** [comment]
Hi,

sorry, we won't have the capacity to provide additional documentation material in the form of videos. But this guy https://www.linkedin.com/in/jonathanstephens/recent-activity/all/ has been talking about making a step-by-step video, so this might be your best bet in the near future.

Best,
Bernhard

**Comment by Relif-me** [comment]
> @BennetLeff After running `convert.py`, I find that my input images are reduced to only 2 images.
> 
> ```
> (gpu) bryan@ito:/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/gaussian-splatting/images$ ls input | wc -l
> 131
> (gpu) bryan@ito:/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/gaussian-splatting/images$ ls images | wc -l
> 2
> ```
> 
> This is the end of the output of running convert. Any idea what could be going on?
> 
> ```
> Bundle adjustment report
> ------------------------
>     Residuals : 11574
>    Parameters : 1400
>    Iterations : 3
>          Time : 0.0248351 [s]
>  Initial cost : 0.861969 [px]
>    Final cost : 0.849642 [px]
>   Termination : Convergence
> 
>   => Merged observations: 0
>   => Completed observations: 86
>   => Filtered observations: 6
>   => Changed observations: 0.014624
> 
> ==============================================================================
> Registering image #74 (130)
> ==============================================================================
> 
>   => Image sees 494 / 665 points
> 
> Pose refinement report
> ----------------------
>     Residuals : 1424
>    Parameters : 6
>    Iterations : 13
>          Time : 0.0146799 [s]
>  Initial cost : 0.763847 [px]
>    Final cost : 0.745686 [px]
>   Termination : Convergence
> 
>   => Continued observations: 471
>   => Added observations: 350
> 
> Bundle adjustment report
> ------------------------
>     Residuals : 8162
>    Parameters : 1088
>    Iterations : 26
>          Time : 0.165197 [s]
>  Initial cost : 0.877543 [px]
>    Final cost : 0.857225 [px]
>   Termination : No convergence
> 
>   => Merged observations: 126
>   => Completed observations: 76
>   => Filtered observations: 261
>   => Changed observations: 0.100784
> 
> Bundle adjustment report
> ------------------------
>     Residuals : 7698
>    Parameters : 959
>    Iterations : 3
>          Time : 0.017916 [s]
>  Initial cost : 0.940212 [px]
>    Final cost : 0.924097 [px]
>   Termination : Convergence
> 
>   => Merged observations: 0
>   => Completed observations: 42
>   => Filtered observations: 0
>   => Changed observations: 0.009635
> 
> ==============================================================================
> Registering image #102 (131)
> ==============================================================================
> 
>   => Image sees 430 / 543 points
> 
> Pose refinement report
> ----------------------
>     Residuals : 1224
>    Parameters : 6
>    Iterations : 11
>          Time : 0.01074 [s]
>  Initial cost : 0.74868 [px]
>    Final cost : 0.740357 [px]
>   Termination : Convergence
> 
>   => Continued observations: 404
>   => Added observations: 365
> 
> Bundle adjustment report
> ------------------------
>     Residuals : 7126
>    Parameters : 797
>    Iterations : 23
>          Time : 0.124404 [s]
>  Initial cost : 1.01439 [px]
>    Final cost : 0.973928 [px]
>   Termination : Convergence
> 
>   => Merged observations: 5
>   => Completed observations: 56
>   => Filtered observations: 298
>   => Changed observations: 0.089772
> 
> Bundle adjustment report
> ------------------------
>     Residuals : 7190
>    Parameters : 695
>    Iterations : 3
>          Time : 0.0167029 [s]
>  Initial cost : 0.904007 [px]
>    Final cost : 0.889233 [px]
>   Termination : Convergence
> 
>   => Merged observations: 0
>   => Completed observations: 46
>   => Filtered observations: 3
>   => Changed observations: 0.012162
> 
> ==============================================================================
> Retriangulation
> ==============================================================================
> 
>   => Completed observations: 119
>   => Merged observations: 161
>   => Retriangulated observations: 0
> 
> ==============================================================================
> Global bundle adjustment
> ==============================================================================
> 
> iter      cost      cost_change  |gradient|   |step|    tr_ratio  tr_radius  ls_iter  iter_time  total_time
>    0  8.495662e+04    0.00e+00    1.55e+04   0.00e+00   0.00e+00  1.00e+04        0    2.60e-02    1.15e-01
> 
> CHOLMOD version 3.0.14, Oct 22, 2019: Symbolic Analysis: status: OK
>   Architecture: Linux
>     sizeof(int):      4
>     sizeof(SuiteSparse_long):  8
>     sizeof(void *):   8
>     sizeof(double):   8
>     sizeof(Int):      4 (CHOLMOD's basic integer)
>     sizeof(BLAS_INT): 4 (integer used in the BLAS)
>   Results from most recent analysis:
>     Cholesky flop count: 1.6155e+08
>     Nonzeros in L:       3.085e+05
>   memory blocks in use:          11
>   memory in use (MB):           0.0
>   peak memory usage (MB):       1.2
>   maxrank:    update/downdate rank:   8
>   supernodal control: 1 40 (supernodal if flops/lnz >= 40)
>   nmethods:   number of ordering methods to try: 1
>     method 0: natural
>         flop count: 1.6155e+08
>         nnz(L):     3.085e+05
>   OK
>    1  8.466775e+04    2.89e+02    2.62e+02   1.69e+00   1.00e+00  3.00e+04        1    2.49e-01    3.64e-01
>    2  8.466727e+04    4.83e-01    3.81e+02   4.62e-01   1.00e+00  9.00e+04        1    1.07e-01    4.71e-01
> 
> 
> Bundle adjustment report
> ------------------------
>     Residuals : 131468
>    Parameters : 21206
>    Iterations : 3
>          Time : 0.56161 [s]
>  Initial cost : 0.803875 [px]
>    Final cost : 0.802505 [px]
>   Termination : Convergence
> 
>   => Completed observations: 17
>   => Merged observations: 31
>   => Filtered observations: 27
>   => Changed observations: 0.001141
> 
> ==============================================================================
> Global bundle adjustment
> ==============================================================================
> 
> iter      cost      cost_change  |gradient|   |step|    tr_ratio  tr_radius  ls_iter  iter_time  total_time
>    0  8.458901e+04    0.00e+00    1.31e+04   0.00e+00   0.00e+00  1.00e+04        0    2.28e-02    1.15e-01
> 
> CHOLMOD version 3.0.14, Oct 22, 2019: Symbolic Analysis: status: OK
>   Architecture: Linux
>     sizeof(int):      4
>     sizeof(SuiteSparse_long):  8
>     sizeof(void *):   8
>     sizeof(double):   8
>     sizeof(Int):      4 (CHOLMOD's basic integer)
>     sizeof(BLAS_INT): 4 (integer used in the BLAS)
>   Results from most recent analysis:
>     Cholesky flop count: 1.6155e+08
>     Nonzeros in L:       3.085e+05
>   memory blocks in use:          11
>   memory in use (MB):           0.0
>   peak memory usage (MB):       1.2
>   maxrank:    update/downdate rank:   8
>   supernodal control: 1 40 (supernodal if flops/lnz >= 40)
>   nmethods:   number of ordering methods to try: 1
>     method 0: natural
>         flop count: 1.6155e+08
>         nnz(L):     3.085e+05
>   OK
>    1  8.454396e+04    4.50e+01    1.75e+02   7.90e-01   1.00e+00  3.00e+04        1    2.52e-01    3.66e-01
>    2  8.454382e+04    1.42e-01    2.21e+02   2.57e-01   1.00e+00  9.00e+04        1    1.09e-01    4.75e-01
> 
> 
> Bundle adjustment report
> ------------------------
>     Residuals : 131428
>    Parameters : 21185
>    Iterations : 3
>          Time : 0.568452 [s]
>  Initial cost : 0.802256 [px]
>    Final cost : 0.802042 [px]
>   Termination : Convergence
> 
>   => Completed observations: 9
>   => Merged observations: 47
>   => Filtered observations: 1
>   => Changed observations: 0.000867
> 
> ==============================================================================
> Global bundle adjustment
> ==============================================================================
> 
> iter      cost      cost_change  |gradient|   |step|    tr_ratio  tr_radius  ls_iter  iter_time  total_time
>    0  8.458780e+04    0.00e+00    1.59e+04   0.00e+00   0.00e+00  1.00e+04        0    2.50e-02    1.29e-01
> 
> CHOLMOD version 3.0.14, Oct 22, 2019: Symbolic Analysis: status: OK
>   Architecture: Linux
>     sizeof(int):      4
>     sizeof(SuiteSparse_long):  8
>     sizeof(void *):   8
>     sizeof(double):   8
>     sizeof(Int):      4 (CHOLMOD's basic integer)
>     sizeof(BLAS_INT): 4 (integer used in the BLAS)
>   Results from most recent analysis:
>     Cholesky flop count: 1.6155e+08
>     Nonzeros in L:       3.085e+05
>   memory blocks in use:          11
>   memory in use (MB):           0.0
>   peak memory usage (MB):       1.2
>   maxrank:    update/downdate rank:   8
>   supernodal control: 1 40 (supernodal if flops/lnz >= 40)
>   nmethods:   number of ordering methods to try: 1
>     method 0: natural
>         flop count: 1.6155e+08
>         nnz(L):     3.085e+05
>   OK
>    1  8.457852e+04    9.27e+00    1.06e+02   1.05e-01   1.00e+00  3.00e+04        1    2.48e-01    3.77e-01
> 
> 
> Bundle adjustment report
> ------------------------
>     Residuals : 131444
>    Parameters : 21182
>    Iterations : 2
>          Time : 0.464244 [s]
>  Initial cost : 0.802202 [px]
>    Final cost : 0.802158 [px]
>   Termination : Convergence
> 
>   => Completed observations: 2
>   => Merged observations: 0
>   => Filtered observations: 1
>   => Changed observations: 0.000046
>   => Filtered images: 0
> 
> Elapsed time: 1.124 [minutes]
> 
> ==============================================================================
> Reading reconstruction
> ==============================================================================
> 
>  => Reconstruction with 2 images and 28 points
> 
> ==============================================================================
> Image undistortion
> ==============================================================================
> 
> Undistorting image [1/2]
> Undistorting image [2/2]
> Writing reconstruction...
> Writing configuration...
> Writing scripts...
> Elapsed time: 0.004 [minutes]
> Done.
> ```

Hello! I had the same problem. Did you solve it?

**Comment by aruiplex** [comment]
Hello! I had the same problem. Did you solve it? I input ~40 images and there are only 2 images in the images folder.
