### ISSUE TITLE
OOM with only 14k points

### ISSUE THREAD

**Issue by rohitrango** [graphdeco-inria/gaussian-splatting#108]
I'm initializing a point cloud of around 14k points. I'm not sure why but the kernel tries to allocate 87000GB of memory. I'm suspecting something is wrong with the projective transform, but I used the `getProjectionMatrix` function.

What could be going wrong? I can share the dump if needed.

**Comment by grgkopanas** [comment]
In what kind of scene? did you modify the code?

**Comment by rohitrango** [comment]
I have a custom pointcloud of a mesh, which I'm approximating using Gaussians.

yes, I did modify the code (to generate my own covariance matrices), but not the rasterization or rendering itself. I have the snapshot dump generated if that helps.

**Comment by BennetLeff** [comment]
Can you place more checkpoints at iterations and check the size of the PLY files the program is generating?

**Comment by rohitrango** [comment]
Its just the first iteration. I'm not even training anything. Just the initial rendering is giving me an OOM error. I'm running it on an RTX3090

**Comment by BennetLeff** [comment]
How many images are in your dataset? Is the software capping them at 1.6K resolution?

**Comment by rohitrango** [comment]
I'm running it with a batch size of 1, and an image size of 512x512

**Comment by rohitrango** [comment]
I did a little more digging and it looks like the error occurs at this point inside the `Rasterizer::forward` function

```
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/15312514/c6290e24-ed41-4d70-9d47-1a746f9ef5c3)
```
Which leads to the output
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/15312514/191df1a1-edfc-4523-8294-ebbcbddc9740)

which corresponds to the number in the OOM error. I'm trying to investigate the `GeometryState` struct, but any ideas on what could be going wrong?

**Comment by rohitrango** [comment]
I think I finally zoned in on the error. The problem occurs with `cub::DeviceScan::InclusiveSum` inside the `fromChunk` function which returns a ridiculously large value for P = 13776.

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/15312514/c62fcf72-4e5e-4bda-8cee-504b03697611)

A log inside the `obtain` function reveals the following count values (note the second last value which is the value put inside `geom.scan_size`). Why is this happening? 

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/15312514/52ee8544-e125-4649-b4a0-4194894530ec)

**Comment by Snosixtyboo** [comment]
And one more thing: you say you compute your own means, I guess you made sure that your own tensors are also on the GPU?

**Comment by rohitrango** [comment]
Yes, they are on the GPU. It seems like some kind of an environment error, I'm able to run it on a different setup.
