### ISSUE TITLE
Error: 'ColormapRegistry' object has no attribute 'get_cmap'    When using DepthAnythingV2

### ISSUE THREAD

**Issue by Lithinem** [graphdeco-inria/gaussian-splatting#1087]
Hello together,

I followed the instructions you gave in the readme + installed the requirements given in the DepthAnything ReadMe. I used a fresh conda env using "conda create -n DepthAnything".

BUT

![Screenshot_2024-11-28_13-47-39](https://github.com/user-attachments/assets/48ce4275-d9a9-4e03-bef6-1d246060243c)

Can you see what I did wrong? Which code did you use for your results? Is there something missing in the ReadMe of this project? 
As nothing has changed in the DepthAnything Git for some time, I cannot see the error there.

Edit: Input Images are in .png format (if s.o. needs to know)

**Comment by seulqxq** [comment]
Hi, did you solve this problem?

**Comment by Lithinem** [comment]
@seulqxq Nope. It still does not work.

**Comment by seulqxq** [comment]
> @seulqxq Nope. It still does not work.

This seems to be a version issue, matplotlib installed with python>=3.8 or above will work.

**Comment by Aditya-Bajra** [comment]
It is indeed a version issue with matplotlib.
In line 50 of run.py,

Replace `cmap = matplotlib.colormaps.get_cmap('Spectral_r')`
with `cmap = plt.get_cmap('Spectral_r')`

This worked for me.

**Comment by Lithinem** [comment]
@seulqxq @Aditya-Bajra 
Both your ideas did not quite work for me. I used Python 3.10; so it's clearly above 3.8. But the "requirement for matplotlib was allready satified" after the installation of the reqirements.txt.

Regarding using `cmap = plt.get_cmap('Spectral_r')`: the variable plt is not defined. So is there something you forgot to post here? I also thought about using `cmap = matplotlib.get_cmap('Spectral_r')`as I assumed you might have changed names. but then I got this error:
![Screenshot_2024-12-05_12-06-46](https://github.com/user-attachments/assets/5f2544a2-9f30-41f0-a884-f4251d976e4d)


Do you have other suggestions for me?

**Comment by Aditya-Bajra** [comment]
@Lithinem my apologies. I did forget to mention that you need to import the pyplot module as well.

`import matplotlib.pyplot as plt`

The above line should work now.

**Comment by Lithinem** [comment]
@Aditya-Bajra 
Thank you. Now its running smoothly :D

**Comment by ZZy129326999** [comment]
> It is indeed a version issue with matplotlib. In line 50 of run.py,
> 
> Replace `cmap = matplotlib.colormaps.get_cmap('Spectral_r')` with `cmap = plt.get_cmap('Spectral_r')`
> 
> This worked for me.

You are best. 3ky
