### ISSUE TITLE
Too many floaters in NeRF synthetic dataset

### ISSUE THREAD

**Issue by xiao10ma** [graphdeco-inria/gaussian-splatting#1089]
I used the latest commit of `gaussian-splatting` to reconstruct the NeRF synthetic dataset. However, there are too many floaters in the NeRF synthetic dataset this time. 

![Screenshot](https://github.com/user-attachments/assets/ff7defc5-24e6-40b1-adbe-026359080c48)
![00010](https://github.com/user-attachments/assets/0a9b82ef-b63e-422d-8455-907cf18995d1)

Interestingly, I recall that when I reconstructed the NeRF synthetic dataset using `gaussian-splatting` earlier this year (2024), there didn’t seem to be any floaters. Can you tell me where did you modify the code? Thank you :)

My running command:
```
python train.py -s ./data/synthetic/lego --iterations 7000 --sh_degree 1 --resolution 1 -m ./output/lego
python render.py -m ./output/lego
```

**Comment by Xzzit** [comment]
You may refer to this [issue](https://github.com/graphdeco-inria/gaussian-splatting/issues/1038)

**Comment by xiao10ma** [comment]
Thank you! It solves my problem
