### ISSUE TITLE
Access to the Z-buffer

### ISSUE THREAD

**Issue by thuzhaowang** [graphdeco-inria/gaussian-splatting#109]
Thanks for the great work and the beautiful code release!

I'm wondering is there a way that we can access the depth/z-buffer info for each rendering process, besides current color and radii outputs?

Many thanks,

**Comment by Peamon** [comment]
Hi, is it planned to support it officially, someday ?

I tell that because i integrate the rasterizer module in a VR experiment, and depth is important for reprojection and 3D content mix.
