### ISSUE TITLE
bad render and high loss

### ISSUE THREAD

**Issue by luocha0107** [graphdeco-inria/gaussian-splatting#1095]
I referenced the answer to question #17 and tested it, but the results were still poor.
![08bb7fbb1c6f9d30d0b5a4f277c3c45](https://github.com/user-attachments/assets/306227c9-6c54-4c3e-8c8e-ea88535b59e8)

several output:
![frame_0005](https://github.com/user-attachments/assets/3c6d97d8-ddc4-4ba6-a6a8-904de0b676fd)
![frame_0145](https://github.com/user-attachments/assets/e54fe400-f8f7-4cd2-bd07-bc1b5421bbf9)
![frame_0521](https://github.com/user-attachments/assets/311ae6c9-9f79-4d8a-b927-a2c1e0228547)
What could be the reason for this? and what should i do.

**Comment by Golbstein** [comment]
can you share with us your dataset?

**Comment by luocha0107** [comment]
> can you share with us your dataset?

https://drive.google.com/drive/folders/15TlacRKhdJn3R5o1Ro7-e6rUX1EOUqkG?usp=drive_link

i'm sorry. Due to the agreement, I can only give you some pictures.

**Comment by Golbstein** [comment]
Please attach also the colmap files

**Comment by jaco001** [comment]
648 pic are more then enough for single object, for terain duno. If you at average need eg. 60 pasess by pic. So with this 40k sounds resonable. But if this is terrain, you need think about scale vs detail.  If you have time and enough VRAM try 400k and also push 'denoise' further (like 100k-200k). 
You can also try 'recycle' method that GS from 30k you use again and do next rounds.

If you don't have time for experiments look for GS papers that have 'chunks' of terrain  in mind.

**Comment by luocha0107** [comment]
> 648 pic are more then enough for single object, for terain duno. If you at average need eg. 60 pasess by pic. So with this 40k sounds resonable. But if this is terrain, you need think about scale vs detail. If you have time and enough VRAM try 400k and also push 'denoise' further (like 100k-200k). You can also try 'recycle' method that GS from 30k you use again and do next rounds.
> 
> If you don't have time for experiments look for GS papers that have 'chunks' of terrain in mind.


this is a power tower,i have time to test 400k,i will try later. Do I need to change any other parameters?

**Comment by jaco001** [comment]
Iterations + this set to resonable number 

self.densify_until_iter = 15_000

**Comment by luocha0107** [comment]
> Please attach also the colmap files

https://drive.google.com/drive/folders/1X9QQgavUs7LJxxnOuxodw2opzHIr0_3U?usp=drive_link

here,upload take me a lot of time.

**Comment by Golbstein** [comment]
I've replicated your results, and I agree—it looks bad and blurry. I'll take a closer look into it. Meanwhile, here's what I recommend:

1. Verify that your camera extrinsics are accurate.
2. It seems the model is converging to a local minimum, likely due to nearly 50% irrelevant pixels in each image (e.g., sky), as well as moving objects like clouds. You should consider masking these areas out.


<img width="964" alt="image" src="https://github.com/user-attachments/assets/cff83645-22e0-43eb-adc7-134081f70641">

On second thought, I’m now certain the issue lies with the sky being learned by the model as part of the tower. See the example here:
<img width="1526" alt="image" src="https://github.com/user-attachments/assets/7f68a581-9b39-49c7-96bb-c5187953305b">

https://github.com/user-attachments/assets/746ef013-7479-4d55-a64a-44c6a578bb54



I’ll re-run the training using the first 100 images, as they don’t contain skies.

**Comment by Golbstein** [comment]
### For comparison, training on the first 109 images resulted in 4M Gaussians and render images looks much better


<img width="787" alt="image" src="https://github.com/user-attachments/assets/03b16b53-7540-488f-94c2-51fa5577ff0e">


https://github.com/user-attachments/assets/6c9152bb-4b37-457f-9c9e-290ea5c37833

That said, I believe perforated structures present a significant challenge for Gaussian splatting. A possible approach to address this could involve performing classical SfM, followed by densification and mesh reconstruction. Alternatively, it’s essential to ensure that the Gaussians' means and scales align with the surface of the structure.

example on how to segment sky easily:
<img width="687" alt="image" src="https://github.com/user-attachments/assets/c5fad237-9e77-415d-b7e1-b15d15a2015e">
https://huggingface.co/docs/transformers/en/tasks/semantic_segmentation

**Comment by Golbstein** [comment]
After further investigation, I found that your sparse point cloud (from the COLMAP files) represents the terrain instead of the tower. This means the initial setup of your Gaussian splatting model is incorrect, making it impossible for the model to learn the tower.


see your point-cloud from the bin files:
<img width="880" alt="Screenshot 2024-12-06 at 21 02 29" src="https://github.com/user-attachments/assets/2e376036-01ae-417a-8e1b-3a07b2530a7c">

**Comment by jaco001** [comment]
This is only starting point. Gaussians are build in the process. (you see tower). Problem is a scale. With that big terrain your tower is 'tiny' and you loose details. I will look at your pictures and taking only pictures that show small part of terain and more tower can help.

**Comment by jaco001** [comment]
My try https://cavebytes.com/splats/tower/tower_best.mp4
Only 103 pic (angle drone to ground)
30k GS about 834MB (without cropping)

![image](https://github.com/user-attachments/assets/c34e8012-fb9b-41ad-813a-36ac1659ede2)
![image](https://github.com/user-attachments/assets/908f7052-09f8-4234-8a23-777dbf6472a6)

**Comment by Golbstein** [comment]
> My try https://cavebytes.com/splats/tower/tower_best.mp4 Only 103 pic (angle drone to ground) 30k GS about 834MB (without cropping)
> 

See the issue with bad initialization is that gaussians have to be pruned&splitted according to the scene. When in first place they are misplaced (you don’t have any depth info from the tower) it tries to color the terrain with the color of the tower. If you will export the centers of your Gaussians you will see that they are all lies on the terrain

**Comment by luocha0107** [comment]
> ### For comparison, training on the first 109 images resulted in 4M Gaussians and render images looks much better
> <img alt="image" width="787" src="https://private-user-images.githubusercontent.com/31940058/393348408-03b16b53-7540-488f-94c2-51fa5577ff0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Mzc3NzgsIm5iZiI6MTczMzUzNzQ3OCwicGF0aCI6Ii8zMTk0MDA1OC8zOTMzNDg0MDgtMDNiMTZiNTMtNzU0MC00ODhmLTk0YzItNTFmYTU1NzdmZjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDAyMTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMDI4Y2I4MzkwZjFjZTY2MzBhYThkYzk5ZDI2YWZiOGZjOThiZjEwNTMzN2Q0ZWE1ZTk4ZmUzODZhOTg5Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9VKWfzBlwPNd7wS0BifKuvpZN7ClKBSCSaSbwipxT84">
>  screen-recording-2024-12-06-at-195415_rEfGGtEy.mp4 
> That said, I believe perforated structures present a significant challenge for Gaussian splatting. A possible approach to address this could involve performing classical SfM, followed by densification and mesh reconstruction. Alternatively, it’s essential to ensure that the Gaussians' means and scales align with the surface of the structure.
> 
> example on how to segment sky easily: <img alt="image" width="687" src="https://private-user-images.githubusercontent.com/31940058/393346478-c5fad237-9e77-415d-b7e1-b15d15a2015e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Mzc3NzgsIm5iZiI6MTczMzUzNzQ3OCwicGF0aCI6Ii8zMTk0MDA1OC8zOTMzNDY0NzgtYzVmYWQyMzctOWU3Ny00MTVkLWI3ZTEtYjE1ZDE1YTIwMTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDAyMTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NGU0NWVjNzdiYWNjNjZlOTQ1MTQ5MjQ4MzJmYWYzYWEyNTk2YTY1OWYyNTQzMDEwMmRmNjYwMDM4OTI2NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LxK91fSpcdSSBvc7RPflFoCUID2Xp7JJXLwXY5uyllg"> https://huggingface.co/docs/transformers/en/tasks/semantic_segmentation



yes, When I tried it, I found that the background has a big impact on modeling.I removed the background and found that it worked fine.
![frame_0010](https://github.com/user-attachments/assets/02e7b517-dcfa-4f01-a692-eb2fc8dfed61)
![frame_0010-](https://github.com/user-attachments/assets/3f367aa7-93d6-4928-9d6a-7f99431b00b6)
![frame_0020](https://github.com/user-attachments/assets/fa025b1f-7234-461c-9c66-69a23e891b06)
![frame_0020-](https://github.com/user-attachments/assets/fca80726-27e9-4485-b566-c8ad1ece5b65)

But ,I found that when building the sparse point cloud, the camera pose is not very accurate. For example, the camera shooting on this side will be recognized on the other side. i think:

1. may be because the structure of the tower is somewhat symmetrical , this results in incorrect feature point matching
2. some tower structures are removed when removing the background result in matching error.

**Comment by luocha0107** [comment]
In each of the two images, the top is the rendering and the bottom is the gt.

**Comment by Golbstein** [comment]
When you run sfm, specify low number of connected frames, otherwise it will try to feature match 2 different sides of the tower as you said. Do you have maybe drones sensors information? They can be good hints

**Comment by luocha0107** [comment]
> When you run sfm, specify low number of connected frames, otherwise it will try to feature match 2 different sides of the tower as you said. Do you have maybe drones sensors information? They can be good hints

ok,i will try low number of connected frames. And i don't have drones sensors informations.

**Comment by luocha0107** [comment]
> When you run sfm, specify low number of connected frames, otherwise it will try to feature match 2 different sides of the tower as you said. Do you have maybe drones sensors information? They can be good hints

 I have set mapper --min_num_match 5,but it doesn't work well.It's frustrating, I'm trying something else.
![Weixin Screenshot_20241207203242](https://github.com/user-attachments/assets/75af6c57-11ae-41a7-958d-35d1f4761abc)
