### ISSUE TITLE
Bug in the gradient computation in the backward.cu file!

### ISSUE THREAD

**Issue by Developer-KS** [graphdeco-inria/gaussian-splatting#1096]
It seems there is a bug in the code of computing gradient wrt. conic2D:

`atomicAdd(&dL_dconic2D[global_id].x, -0.5f * gdx * d.x * dL_dG);`
`atomicAdd(&dL_dconic2D[global_id].y, -0.5f * gdx * d.y * dL_dG);`
`atomicAdd(&dL_dconic2D[global_id].w, -0.5f * gdy * d.y * dL_dG);`

the `0.5f` should be removed for the second line, please check!

**Comment by sshiningg** [comment]
Maybe this blog can help. 
https://yindaheng98.github.io/%E5%9B%BE%E5%BD%A2%E5%AD%A6/3D%E9%AB%98%E6%96%AF%E5%8F%8D%E5%90%91%E4%BC%A0%E6%92%AD%E4%BB%A3%E7%A0%81%E8%A7%A3%E6%9E%90.html#%E5%AF%B9%E9%AB%98%E6%96%AF%E7%90%83%E6%8A%95%E5%BD%B1%E5%9C%A8%E6%88%90%E5%83%8F%E5%B9%B3%E9%9D%A2%E4%B8%8A%E7%9A%84%E9%AB%98%E6%96%AF%E5%87%BD%E6%95%B0%E5%8F%82%E6%95%B0%E7%9A%84%E6%A2%AF%E5%BA%A6

**Comment by AsherJingkongChen** [comment]
> Maybe this blog can help.

Well, the blog is correct for me. Great.

**Comment by AsherJingkongChen** [comment]
I believe it is not a bug.
The y scalar will be broadcast to two scalar on the inverse of cov2d.
Please provide your formula if you really think it is a mistake.

**Comment by Developer-KS** [comment]
> I believe it is not a bug. The y scalar will be broadcast to two scalar on the inverse of cov2d. Please provide your formula if you really think it is a mistake.

I see. To clarify, since there is a `2 * ` operation for each `b` in the computeCov2DCUDA function:

`dL_da = denom2inv * (-c * c * dL_dconic.x + 2 * b * c * dL_dconic.y + (denom - a * c) * dL_dconic.z);`
`dL_dc = denom2inv * (-a * a * dL_dconic.z + 2 * a * b * dL_dconic.y + (denom - a * c) * dL_dconic.x);`
`dL_db = denom2inv * 2 * (b * c * dL_dconic.x - (denom + 2 * b * b) * dL_dconic.y + a * b * dL_dconic.z);`

the gradient computation should be correct.

However, in my humble opinion, it will be more intuitive to treat conic2D as three numbers instead of a float4 with one item empty and double the gradient wrt. the middle item. It will also be more consistent with the following `dL_dconv` computation:

`dL_dcov[6 * idx + 1] = 2 * T[0][0] * T[0][1] * dL_da + (T[0][0] * T[1][1] + T[0][1] * T[1][0]) * dL_db + 2 * T[1][0] * T[1][1] * dL_dc;`
`dL_dcov[6 * idx + 2] = 2 * T[0][0] * T[0][2] * dL_da + (T[0][0] * T[1][2] + T[0][2] * T[1][0]) * dL_db + 2 * T[1][0] * T[1][2] * dL_dc;`
`dL_dcov[6 * idx + 4] = 2 * T[0][2] * T[0][1] * dL_da + (T[0][1] * T[1][2] + T[0][2] * T[1][1]) * dL_db + 2 * T[1][1] * T[1][2] * dL_dc;`

where all off-diagonal elements are doubled.

Thanks for clarifying this for me!

**Comment by Chen-Suyi** [comment]
> > I believe it is not a bug. The y scalar will be broadcast to two scalar on the inverse of cov2d. Please provide your formula if you really think it is a mistake.
> 
> I see. To clarify, since there is a `2 * ` operation for each `b` in the computeCov2DCUDA function:
> 
> `dL_da = denom2inv * (-c * c * dL_dconic.x + 2 * b * c * dL_dconic.y + (denom - a * c) * dL_dconic.z);` `dL_dc = denom2inv * (-a * a * dL_dconic.z + 2 * a * b * dL_dconic.y + (denom - a * c) * dL_dconic.x);` `dL_db = denom2inv * 2 * (b * c * dL_dconic.x - (denom + 2 * b * b) * dL_dconic.y + a * b * dL_dconic.z);`

I have a question here. Why do you use `(denom - a * c)` instead of `(-b * b)` directly? Since `denom = a * c - b * b`, they should be equivalent, right?
