### ISSUE TITLE
Error in Training with DepthAnything Depth Images

### ISSUE THREAD

**Issue by Lithinem** [graphdeco-inria/gaussian-splatting#1097]
Hello again,

I tried to train a new model using the README. Sadly there seems to be an error in the script.  I created the depth_param.json-file and the error only occurs, if I'm using `-d <path to depth>`.

![Screenshot_2024-12-05_18-16-43](https://github.com/user-attachments/assets/eaa3360a-c76b-40d6-a69c-97db0d8bce4b)

does anyone know why there is an error ? Any help is highly appreciated. :D

**Comment by Golbstein** [comment]
you can just read the error message and see that cam_info.depth_path has wrong path to image, therefore cv2.imread doesn't read anything .. add print("cam_info.depth_path") and put your depth images in this path

**Comment by Lithinem** [comment]
You are totally right. It was late. I was blind. the -d Parameter appends the depth path to the path given in -s and does not want you to retype it as you need to do for the -m Parameter.

Thank you for your time :D
