### ISSUE TITLE
how to offline render RGB image

### ISSUE THREAD

**Issue by kaixin-bai** [graphdeco-inria/gaussian-splatting#1099]
after training I got ply format 3dgs file, I could give the height, width, and intrinsic or fov of the camera together with the R,t for the camera, how could I render the RGB image online or offline with the ply file and the camera info?

**Comment by AsherJingkongChen** [comment]
Did you try render.py and viewers?

You can move the view by editing the cam rotation and translation.

**Comment by guaMass** [comment]
You can try to use this tool: https://github.com/guaMass/3DGS_PoseRender
