### ISSUE TITLE
number of 3D Gaussians

### ISSUE THREAD

**Issue by Sanctuary345** [graphdeco-inria/gaussian-splatting#1100]
How do I know the number of 3D Gaussians in a point cloud model after training?

**Comment by AsherJingkongChen** [comment]
Open the PLY file and read the number after "element vertex "

**Comment by Sanctuary345** [comment]
I opened the point cloud file using meshlab, do you mean that number of Vertices that I am arrowing to?
![image](https://github.com/user-attachments/assets/7335509b-aecb-4df2-9e56-94966c488378)

**Comment by AsherJingkongChen** [comment]
Yes
