### ISSUE TITLE
SIBR viewer and cfg_args

### ISSUE THREAD

**Issue by leblond14u** [graphdeco-inria/gaussian-splatting#1115]
Hi GS community,

Do you know if there's a way to render the gaussians with SIBR viewer or similar based only on the **ply** file generated by the GS process ? 
To my understanding the SIBR viewer need the **cfg_args** file and the images to be able to render the splats.
Is there a way to still use the SIBR viewer without it ? 

Best,

Hugo

**Comment by jaco001** [comment]
Short answer no and yes. ;)

no - you need those files... but
yes - AFIK you can 'transfer' those files from another model and SIBR 'jumps in'. Only downside that you can get is camera far away ... but at last you can view a model.

**Comment by leblond14u** [comment]
Ok thanks a lot, 
I'll try to do that indeed.

Best,
