### ISSUE TITLE
train on WSL2

### ISSUE THREAD

**Issue by skyeKing** [graphdeco-inria/gaussian-splatting#112]
I don't see real-time effects in the browser, the training code runs on Ubuntu with WSL2 using the conda environment。
The logs for training show that you are connected

**Comment by Snosixtyboo** [comment]
What do you see in the remote viewer? Anything at all?

**Comment by Snosixtyboo** [comment]
Right, that is the output of the training script. What does the remote viewer window show you? Anything at all?

**Comment by johnowhitaker** [comment]
Nothing showing for me. I think it's related to [this WSL issue](https://github.com/microsoft/WSL/issues/5298) (has some suggested fixes to try) and nothing to do with the code here.
