### ISSUE TITLE
Slow Download Speed of the linked pretrained models

### ISSUE THREAD

**Issue by FScociety** [graphdeco-inria/gaussian-splatting#119]
Hi,
I noticed that the download speed of the pretrained models is very slow (50KB/s), which would take 3 days to download. Maybe there is a way to mirror it to google drive? or some other service which has faster download speed.

(I checked my connection, its not the problem)

**Comment by FScociety** [comment]
Never mind. I found the huggingface page where the models can be downloaded. Maybe include them in the github page?

**Comment by Snosixtyboo** [comment]
Done

**Comment by learn01one** [comment]
> Never mind. I found the huggingface page where the models can be downloaded. Maybe include them in the github page?

hello,where is the huggingface page  the models can be downloaded,thank you
