### ISSUE TITLE
Problems about SIBR_Viewer

### ISSUE THREAD

**Issue by hkkkpang** [graphdeco-inria/gaussian-splatting#120]
Hi,

I tried to use 'SIBR_gaussianViewer_app' to visualize my result. It can works well to start, but it fails/breaks when I try to change the camera view or rotate by trackball. I got the error informations:

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/80012295/2df7b531-2971-4030-8da0-d495a440e7e7)

But I can play it very well on another dataset. Do you know how to solve it or what does cause this error?

Thanks in advance.

**Comment by Snosixtyboo** [comment]
Hi,

if it occurs with only your own data sets, we would need them to find out what's up. You can try to send a link with a download to bernhard.kerbl@inria.fr

Best, 
Bernhard

**Comment by hkkkpang** [comment]
Hi,

Thanks for your reply. I have send the data to you.

Best,

**Comment by GotFusion** [comment]
I met the same error before. I reinstall CUDA and CuDNN, turn off V-Sync, set Windows settings, it still happened. I then update the NVIDIA driver, and restart my computer, the error disappeared.

**Comment by hkkkpang** [comment]
> I met the same error: an illegal memery access was encounted. I reinstall CUDA and CuDNN, turn off V-Sync, set Windows settings, it still happened. I then update the NVIDIA driver, and restart my computer, it works.

Thanks for your suggestions. However, it doesn't work for my case.

**Comment by Snosixtyboo** [comment]
Hi, this was explained by the fact that user @hkkkpang changed the type of the trained parameters, so the expected data types don't match. They might want to create a new issue detailing why this was necessary.
