### ISSUE TITLE
Is there reason that point_cloud directory cannot be generated after training?

### ISSUE THREAD

**Issue by XinyueZ** [graphdeco-inria/gaussian-splatting#121]
Hello everyone,

Should I wish to render post-training, I am unable to initiate the render command as the `point_cloud` directory was not produced by the training. Could there be any explanation for this?

Thank you.

**Comment by Snosixtyboo** [comment]
Hi,

can't think of a good reason why this would happen. Everything else is there? The training completed without errors?

**Comment by XinyueZ** [comment]
I think it is bc of oom during training.
