### ISSUE TITLE
Is it possible to preduce point-cloud or mesh?

### ISSUE THREAD

**Issue by XinyueZ** [graphdeco-inria/gaussian-splatting#125]
Hello everyone,

Perhaps I hastened in my judgement. I've found your toolkit such as "`render.py`" quite useful. It reminds me of `nerfStudio`  I believe you are familiar with it as well. Is there a possibility of incorporating additional toolkits that could generate `point-cloud `or `mesh` similar to those produced by `nerfStudio`?

thx

**Comment by Snosixtyboo** [comment]
Hi,

there are currently no plans to directly extend this to produce meshes. But you can get the point clouds quite easily: the final trained model contains a folder ```point_cloud``` with a ```.ply``` file in it. You should be able to load this directly into, e.g., Meshlab and from there you can convert it to any other type you like.

Hth,
Bernhard

**Comment by abenbihi** [comment]
Hi Bernhard,

Thank you for pointing to the generated point cloud. It can indeed be used to generate a mesh using poisson.

I still have a question regarding that point cloud though: in my experiment the resulting point cloud is colorless even though the renders do have color (see attached picture).
According to the other issues, I would have expected the point cloud to have colors.
Could it be that I missed a flag somewhere to generate a colored point cloud?

![colorless_pcl](https://github.com/graphdeco-inria/gaussian-splatting/assets/16404177/29205650-3b36-4433-bed6-78ecc12f8f05)

Thank you very much.
Assia

**Comment by abenbihi** [comment]
Hi again,
I figured it out :)
In case somebody else runs into the problem, the point cloud is colorless by design: only the geometric attributes are stored:
https://github.com/graphdeco-inria/gaussian-splatting/blob/9d977c702bc8819bfec26992f541dc6162074267/scene/gaussian_model.py#L178

**Comment by abenbihi** [comment]
Thank you very much for the explanation and i apologize for my misleading comment, i updated it.
