### ISSUE TITLE
Automated way to remove dynamic object via mask

### ISSUE THREAD

**Issue by smandava98** [graphdeco-inria/gaussian-splatting#127]
Hi. Thanks for the great work. I have a video of an indoor scene with an object bouncing around it but I want to mask away the object. How is this possible?

I have the segmentation masks for it. I saw #101 that mentioned to append an A channel where the 0 means the pixel should not be rendered but I had some questions about that.

Will it still work if in some frames, parts of my scene are blocked by the object but are again visible in future frames if I mask this way?

My goal is the get a fully fleshed 3D representation of the scene minus the object

**Comment by yzslab** [comment]
Hi, looks like the alpha channel mask only simply set the color of the masked pixels to (0, 0, 0) [(scene/cameras.py#L44)](https://github.com/graphdeco-inria/gaussian-splatting/blob/0b3519bca56e0ab38f85d5aa15d8aae7f526a4fe/scene/cameras.py#L44). I don't think it is suitable for the situation that you mentioned.
I have added a dynamic object mask support to gaussian splatting and here is my modification: https://github.com/yzslab/gaussian-splatting/commit/95e7c9282650cac12eb731aa6867d540caa98781. I am still doing experiments on my mask implementation. May be you could try to use my code to train your image set, and tell me whether it work. The mask filename should be `IMAGE_FILENAME.png` (e.g. the mask of `00001.jpg` is `00001.jpg.png`), single channel, and the `0` (black) represents the masked pixel, add `--masks` parameter to `train.py` to specific the mask image directory.

**Comment by smandava98** [comment]
Thanks so much @yzslab I'll test on my end and let you know my results soon

**Comment by smandava98** [comment]
hi @yzslab I don't see any --masks argument in your train.py. Also how is it being read in in train.py? I am not able to get it to read the masks

**Comment by yzslab** [comment]
> hi @yzslab I don't see any --masks argument in your train.py. Also how is it being read in in train.py? I am not able to get it to read the masks

Hi, the `--masks` is defined at [here](https://github.com/yzslab/gaussian-splatting/commit/95e7c9282650cac12eb731aa6867d540caa98781#diff-ce21575d61c78e14ea8203973f7579e9ed141c3be718499aa5f1aec669db72ddR53).
Have you seen the output that tell you how many mask images it read?:
```
$ python train.py ... --masks ...
Output folder: ...
...
Reading camera 177/177
Read 177 masks
...
```

**Comment by smandava98** [comment]
Ah, I forgot to add the args.masks in scene's init.py. It is loading fine now. Will kick off the training on a few videos to see if it is filling up the scene minus the object now.

**Comment by smandava98** [comment]
Tested it on a few videos and I can see it is working well. Thanks @yzslab !

**Comment by yzslab** [comment]
> Tested it on a few videos and I can see it is working well. Thanks @yzslab !

Glad to hear that.

**Comment by yzslab** [comment]
> @yzslab have you made the repo private? I would really need that asap

Hi, here is the new link: https://github.com/yzslab/gaussian-splatting/tree/dynamic_mask

**Comment by mirlansmind** [comment]
@yzslab thank you so much for the prompt reply!

**Comment by smoothumut** [comment]
@yzslab  thank you so much for detailed replies and great solution. 🙇

**Comment by YijunLuo** [comment]
Hi @yzslab , thanks for the repo, it is being helpful to remove the background. However, when I took a closer look at the model, there are ellipsoids in the masked area, some of which are very large in visualization, harming the overal rendering quality. But aftering correcting the mistake in the origianl gs repo as mentioned here https://github.com/graphdeco-inria/gaussian-splatting/issues/283 , there are fewer ellipsoids in the masked area. I wonder if it has something to do with the Gaussian initialization. And is there any way to constrain the gaussians being initialized in the unwanted region? Thanks!

**Comment by Golbstein** [comment]
why this code isn't being merged?

**Comment by gaoyuqiang** [comment]
why this code isn't being merged?

**Comment by applepieiris** [comment]
> Hi, looks like the alpha channel mask only simply set the color of the masked pixels to (0, 0, 0) [(scene/cameras.py#L44)](https://github.com/graphdeco-inria/gaussian-splatting/blob/0b3519bca56e0ab38f85d5aa15d8aae7f526a4fe/scene/cameras.py#L44). I don't think it is suitable for the situation that you mentioned. I have added a dynamic object mask support to gaussian splatting and here is my modification: [yzslab@95e7c92](https://github.com/yzslab/gaussian-splatting/commit/95e7c9282650cac12eb731aa6867d540caa98781). I am still doing experiments on my mask implementation. May be you could try to use my code to train your image set, and tell me whether it work. The mask filename should be `IMAGE_FILENAME.png` (e.g. the mask of `00001.jpg` is `00001.jpg.png`), single channel, and the `0` (black) represents the masked pixel, add `--masks` parameter to `train.py` to specific the mask image directory.

hello, I use your code to realize the mask feature, It looks like having so many artifacts. And If I use the RGBA images as input, It works well, So I think setting the background with 100% opacity is ok for this situation.

**Comment by applepieiris** [comment]
> Hi [@yzslab](https://github.com/yzslab) , thanks for the repo, it is being helpful to remove the background. However, when I took a closer look at the model, there are ellipsoids in the masked area, some of which are very large in visualization, harming the overal rendering quality. But aftering correcting the mistake in the origianl gs repo as mentioned here [#283](https://github.com/graphdeco-inria/gaussian-splatting/issues/283) , there are fewer ellipsoids in the masked area. I wonder if it has something to do with the Gaussian initialization. And is there any way to constrain the gaussians being initialized in the unwanted region? Thanks!

Hi, I have also encounter the same situation, and I think the problem could be the colmap process. We need to mask away the point clouds in the .plt file generated by colmap I think. I use the original plt for train and also using the mask, I obtain the scene with object away but remains a lot of artifacts around the object just like this:

<img width="288" height="240" alt="Image" src="https://github.com/user-attachments/assets/923ef387-3bba-4f0f-b3cb-cf765b894674" />

The comment I refered is here https://github.com/graphdeco-inria/gaussian-splatting/issues/282#issuecomment-1748245974

**Comment by ebhrz** [comment]
I'm also wondering why they don't merge your branch. Anyway, thanks so much for your work, and I'll have a try.

**Comment by farazBhatti** [comment]
Do we need to apply colmap with mask images or only during training? for example, colmap on original images and then use mask while training?
