### ISSUE TITLE
Questions on rendering (SIBR & .ply files)

### ISSUE THREAD

**Issue by smandava98** [graphdeco-inria/gaussian-splatting#130]
Hi. I have a couple questions around rendering.

Firstly, I'm on a cloud GPU that I am ssh-ed into. My machine is a MacBook Pro. I'm a bit confused on how to set this up so I can utilize SIBR locally as my cloud GPU does not have a display? Looking at the SIBR repo it is only available on Windows and Linux so I can't run it on my Macbook.

Secondly, I viewed the image renderings in my output folder and they look fine. But when I view the point_cloud.ply file and import it as a mesh in Meshlab, the output does not resemble a 3D scene representation of those images at all. Is there a better way to get a 3D point cloud representation of my scene alongside with _color_ and _texture_?

One note: The video I took is not particularly centered around an object but an entire scene and the camera moves around slightly (enough to render new views laterally but not enough to where the entire scene can be represented). Please let me know if this is an issue.

**Comment by antithing** [comment]
I have a similar question, i am looking to embed a renderer for these outputs in a realtime engine (c++/ DX12)

Would you be able to outline how the data is stored in the ply file please?

**Comment by yzslab** [comment]
Hi, I implemented gaussian splatting viewer on NeRFStudio, may be you can use this on your Mac OS. Here is the repository: https://github.com/yzslab/nerfstudio/tree/gaussian_splatting

You need to install the nerfstudio denpendices first, then `plyfile==0.8.1`, `submodules/diff-gaussian-rasterization` and `submodules/simple-knn`. By running `python nerfstudio/scripts/gaussian_splatting/run_viewer.py --model-path GAUSSIAN_TRAINING_OUTPUT_DIR`, you can use the web-based viewer of nerfstudio to view your scene.

It has not been well tested yet, and not as fast as SIBR_viewer, and only rendering is support (no training).

Preview:

https://github.com/graphdeco-inria/gaussian-splatting/assets/564361/7e9fa08c-4ea9-4081-a59f-062178c88df2

**Comment by pwais** [comment]
@yzslab very cool!!!!  I just want to give a pointer to the new Nerfstudio Template https://github.com/maturk/nerfstudio-template  which can perhaps provide an affordance for re-using much of Nerfstudio without actually forking the whole repo.  Looking at your diff, it strikes me the template API would be enough for this interop, with perhaps some small `nerfstudio` changes to accommodate the `GaussianSplattingCamera` camera.

**Comment by yzslab** [comment]
> @yzslab very cool!!!! I just want to give a pointer to the new Nerfstudio Template https://github.com/nerfstudio-project/nerfstudio-method-template (edit: link to official repo) which can perhaps provide an affordance for re-using much of Nerfstudio without actually forking the whole repo. Looking at your diff, it strikes me the template API would be enough for this interop, with perhaps some small `nerfstudio` changes to accommodate the `GaussianSplattingCamera` camera.

Thanks for your recommendation. I will try it later.
