### ISSUE TITLE
Does it worked when I use nerfstudio ns-process-data to process?

### ISSUE THREAD

**Issue by XinyueZ** [graphdeco-inria/gaussian-splatting#134]
Hey guys,

my purpose is just to have a single-source to produce a customized dataset. Is it possible to use `ns-process-data ` command of the nerfstudio?

thanks

**Comment by XinyueZ** [comment]
thx

**Comment by jonstephens85** [comment]
@XinyueZ You can re-use your ns-process-data. Here is a tutorial video I made yesterday: https://www.youtube.com/watch?v=wuKhEGCt6ks&t=1s

One caveat, It only works with Nerfstudio projects that you processed using COLMAP.

**Comment by XinyueZ** [comment]
> @XinyueZ You can re-use your ns-process-data. Here is a tutorial video I made yesterday: https://www.youtube.com/watch?v=wuKhEGCt6ks&t=1s
> 
> One caveat, It only works with Nerfstudio projects that you processed using COLMAP.

Indeed, that was my point in the comment on your LinkedIn post, but good job regardless. Now, I can use a single source for data conversion.
