### ISSUE TITLE
train.py - AssertionError: Could not recognize scene type

### ISSUE THREAD

**Issue by Blizaine** [graphdeco-inria/gaussian-splatting#136]
Hello,
Thanks for all the work you do on this project.  I'm having an issue with training my own images.  I initially was using Google Colab tied back to my Windows/Docker (4090), but then recently went ahead and tried the local option.  I extracted about 450 images from drone footage and ran it through COLMAP via convert.py.  

In both colab and local, I get an error: "Could not recognize scene type!" when I run train.py.  I'm pointing it to the directory that has folders for images, sparse, ect., that were a result of convert.py.  Any ideas?  

```
(gaussian_splatting) C:\Users\bliza\conda\gaussian-splatting>python train.py -s /data/DroneFinal
Optimizing
Output folder: ./output/615ddd4f-b [28/08 08:54:59]
Tensorboard not available: not logging progress [28/08 08:54:59]
Traceback (most recent call last):
  File "train.py", line 216, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "C:\Users\bliza\conda\gaussian-splatting\scene\__init__.py", line 49, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!
```

**Comment by Snosixtyboo** [comment]
I guess something is still off about the folder structure. Can you try to compare the folder structure exactly to one of the reference datasets (t&t which we provide or mipnerf360)?

**Comment by Blizaine** [comment]
It was either an issue with ImageMagick or my actual footage.  I shot some fresh footage and didn't use the --resize flag, and it all worked flawlessly.  Thank you!
