### ISSUE TITLE
points3D.ply missing after running "convert.py"

### ISSUE THREAD

**Issue by XinyueZ** [graphdeco-inria/gaussian-splatting#138]
Hello everyone,

Occasionally, I am unable to generate the `points3D.ply` file after executing `convert.py`, while other times it works fine.

Any ideas why this might be happening?

Thanks in advance.

**Comment by Snosixtyboo** [comment]
Hi,

```convert.py``` doesn't create the ```points3D.ply```. That only happens when the optimization (```train.py```) is run for the first time.

Hth,
Bernhard

**Comment by XinyueZ** [comment]
so, correct me if I was wrong.

after training.py there are two `ply`s will be created, right?

1. `<location>/sparse/0/points3D.ply`
2. `model_path/point_cloud/iteration_xxxxxx/point_cloud.ply`

**Comment by XinyueZ** [comment]
thank you
