### ISSUE TITLE
confusion about novel view synthesis

### ISSUE THREAD

**Issue by PengKunPROO** [graphdeco-inria/gaussian-splatting#141]
Hi， I'm new to Nerf-based rendering. In your project and paper, I don't find where the NVS(common Nerf approaches choose MLP to predict the novel view?). Maybe in **./SIBR_viewers/install/bin/SIBR_gaussianViewer_app** you use interpolation to create a novel view? If it's true, could u tell me where can I find it in your code, and Is there something tutorial or open-sourced program to learn your rendering pipeline(It's so hard for me to review your code in the SIBR part, I have no experience in Cuda programming). If it's not, hope u can also tell me how the NVS you implement.
Thanks!

**Comment by Snosixtyboo** [comment]
Hi,

we get a Gaussian mixture (points with extent and view-dependent color) that we can render from any novel view we like using EWA (the forward pass in our differential-rasterization submodule). Therefore we can achieve NVS. There is currently no tutorial on the rendering pipeline other than the paper and the code itself.

Hth,
Bernhard

**Comment by PengKunPROO** [comment]
Thank u for your reply! I'll check the corresponding code you mentioned above!
