### ISSUE TITLE
diff-gaussian-rasterization fails to build

### ISSUE THREAD

**Issue by SvenKratz** [graphdeco-inria/gaussian-splatting#142]
When running python setup.py install, I always get pybind tuple template errors. I tried cuda 116, 117 Python 3.9.7 and Python 3.10.12. Unfortunately I cannot find a solution. Any suggestions?

```
C:\Users\xxx\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\torch\include\pybind11\cast.h(1429): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here

C:\Users\xxx\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\torch\include\pybind11\cast.h(1503): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here

2 errors detected in the compilation of "rasterize_points.cu".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin\\nvcc.exe' failed with exit status 1
```

**Comment by shaysegal-xr** [comment]
I have the same issue

**Comment by Snosixtyboo** [comment]
Hi,

are you running this from within the ```gaussian_splatting``` environment? A step-by-step tutorial for setup is given [here](https://www.youtube.com/watch?v=UXtuigy_wYc), let me know if following it helps!

**Comment by Snosixtyboo** [comment]
Also, at least CUDA 11.6 has known issues, so when its ```nvcc``` is used, there will be problems with C++14.

**Comment by ZachisGit** [comment]
You are missing the submodules. You can run the following in your root repo folder after cloning to get the submodules (including diff-gaussian-rasterization):

`git submodule update --init`

**Comment by dgalor** [comment]
+1

**Comment by Snosixtyboo** [comment]
Closed due to inactivity

**Comment by RyanJFriedrich** [comment]
I have the same issue. I've tried all sorts of versions. I've spent too many hours wrestling with this issue.

After squaring away all the dependencies I kept running in to the same wall. This is done in Windows 11, with VS 2019 and 2022 installed. I have the 2019 and related libraries all pathed. I have tried various Torch/Cuda versions.

It's an issue with pybind11 and the Torch version? Apparently the Torch version MAY interact with pybind11 differently?



---- error below --- 
``
C:\Users\User\miniconda3\envs\testg\lib\site-packages\torch\include\pybind11\cast.h(1429): error: too few arguments for template template parameter "Tuple"
                detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
      (1507): here

      C:\Users\User\miniconda3\envs\testg\lib\site-packages\torch\include\pybind11\cast.h(1503): error: too few arguments for template template parameter "Tuple"
                detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
      (1507): here

      2 errors detected in the compilation of "D:/GausianSplat/gaussian-splatting/submodules/diff-gaussian-rasterization/rasterize_points.cu".
      rasterize_points.cu
      ninja: build stopped: subcommand failed.``
