### ISSUE TITLE
Build fails on Windows 

### ISSUE THREAD

**Issue by xrstack** [graphdeco-inria/gaussian-splatting#148]
Hi, i followed this windows installation guide step by step: https://www.youtube.com/watch?v=UXtuigy_wYc

After looking at multiple issues and reinstalling vscode, anaconda and cuda i'm still getting this error during installation.

Any idea on what's up? Please advise as I see other users with this issue as well: 

----

(base) C:\Users\xrstack\gaussian-splatting>conda env create --file environment.yml
Collecting package metadata (repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 23.7.2
  latest version: 23.7.3

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.7.3

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: - "By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"

done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['C:\\Users\\xrstack\\.conda\\envs\\gaussian_splatting\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\xrstack\\gaussian-splatting\\condaenv.bm7hf9m3.requirements.txt', '--exists-action=b']
Pip subprocess output:
Processing c:\users\xrstack\gaussian-splatting\submodules\diff-gaussian-rasterization
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Processing c:\users\xrstack\gaussian-splatting\submodules\simple-knn
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: diff-gaussian-rasterization, simple-knn
  Building wheel for diff-gaussian-rasterization (setup.py): started
  Building wheel for diff-gaussian-rasterization (setup.py): finished with status 'error'
  Running setup.py clean for diff-gaussian-rasterization
  Building wheel for simple-knn (setup.py): started
  Building wheel for simple-knn (setup.py): finished with status 'error'
  Running setup.py clean for simple-knn
Failed to build diff-gaussian-rasterization simple-knn
Installing collected packages: simple-knn, diff-gaussian-rasterization
  Running setup.py install for simple-knn: started
  Running setup.py install for simple-knn: finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      running bdist_wheel
      C:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-37
      creating build\lib.win-amd64-cpython-37\diff_gaussian_rasterization
      copying diff_gaussian_rasterization\__init__.py -> build\lib.win-amd64-cpython-37\diff_gaussian_rasterization
      running build_ext
      C:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building 'diff_gaussian_rasterization._C' extension
      creating build\temp.win-amd64-cpython-37
      creating build\temp.win-amd64-cpython-37\Release
      creating build\temp.win-amd64-cpython-37\Release\cuda_rasterizer
      "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc" -c cuda_rasterizer/backward.cu -o build\temp.win-amd64-cpython-37\Release\cuda_rasterizer/backward.obj -IC:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\include -IC:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\TH -IC:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\xrstack\.conda\envs\gaussian_splatting\include -IC:\Users\xrstack\.conda\envs\gaussian_splatting\Include -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -IC:\Users\xrstack\gaussian-splatting\submodules\diff-gaussian-rasterization\third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --use-local-env
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_config.h(231): fatal error C1083: Cannot open include file: 'crtdefs.h': No such file or directory
      backward.cu
      error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\bin\\nvcc.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      C:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_ext
      C:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building 'simple_knn._C' extension
      creating build
      creating build\temp.win-amd64-cpython-37
      creating build\temp.win-amd64-cpython-37\Release
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\include -IC:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\TH -IC:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\xrstack\.conda\envs\gaussian_splatting\include -IC:\Users\xrstack\.conda\envs\gaussian_splatting\Include /EHsc /Tpext.cpp /Fobuild\temp.win-amd64-cpython-37\Release\ext.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc /wd4624 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
      ext.cpp
      C:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuda.h(5): fatal error C1083: Cannot open include file: 'cstdint': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple-knn
  error: subprocess-exited-with-error

  × Running setup.py install for simple-knn did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      running install
      C:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      running build
      running build_ext
      C:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      C:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building 'simple_knn._C' extension
      creating build
      creating build\temp.win-amd64-cpython-37
      creating build\temp.win-amd64-cpython-37\Release
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\include -IC:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\TH -IC:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\xrstack\.conda\envs\gaussian_splatting\include -IC:\Users\xrstack\.conda\envs\gaussian_splatting\Include /EHsc /Tpext.cpp /Fobuild\temp.win-amd64-cpython-37\Release\ext.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc /wd4624 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
      ext.cpp
      C:\Users\xrstack\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuda.h(5): fatal error C1083: Cannot open include file: 'cstdint': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> simple-knn

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

failed

CondaEnvException: Pip failed

**Comment by xrstack** [comment]
PS: here's what my VS 2019 installation looks like -- i have the path set yet the compiler still can't find headers like cstdint and crtdefs.h:
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/106619546/2f99bf14-7a3f-46ca-9ecd-3c7b8e9c99de)
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/106619546/8d653a9d-bb63-43f8-97dc-b0492f5bb580)
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/106619546/39176e8b-9d16-475b-ad3e-8c9eb61b65ee)

**Comment by zteffff** [comment]
Same here...

**Comment by jonstephens85** [comment]
Similar to the missing cl.exe file in [issue 146](https://github.com/graphdeco-inria/gaussian-splatting/issues/146), you can add the directory of the missing file to your path as a workaround. It looks like your PC is failing to find crtdefs.h. 

You can try adding the visual studio path to your environment variables (your version number might differ);
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include`

Then make sure you start a new conda prompt and cd to your repo location and try this;

```
conda activate gaussian_splatting
cd C:/gaussian-splatting
pip install submodules\diff-gaussian-rasterization
pip install submodules\simple-knn
```

**Comment by DanielKhiati** [comment]
I was able to install the diff-gaussian-rasterization submodule but not the simple-knn
I'm using the community version of VS2019 so your foldername might vary
What worked for me is the following:

- Make sure you have the build tools installed for VS2019
- Check if you have "vcvarsall.bat" in C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build
- Add this path to your environment variables: 
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build
- Open a new conda prompt and cd to your repo location
- SET DISTUTILS_USE_SDK=1
- vcvarsall x86_amd64

After that i was able to install the simple-knn submodule without errors:
pip install submodules\simple-knn

**Comment by buildmine10** [comment]
A combination of the things shown here solved it for me. I went to the VS installer, and made sure the installed things matched the pictures. Then I did what DanielKhiati said to do.

**Comment by samuelziemian** [comment]
> Similar to the missing cl.exe file in [issue 146](https://github.com/graphdeco-inria/gaussian-splatting/issues/146), you can add the directory of the missing file to your path as a workaround. It looks like your PC is failing to find `crtdefs.h`.
> 
> You can try adding the path to `crtdefs.h` in your environment variables (your version number might differ); `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include`
> 
> Then make sure you start a new conda prompt and cd to your repo location and try this;
> 
> ```
> conda activate gaussian_splatting
> cd C:/gaussian-splatting
> pip install submodules\diff-gaussian-rasterization
> pip install submodules\simple-knn
> ```

had had problems with installing :  ERROR: Failed building wheel for simple_knn
