### ISSUE TITLE
SIBR Viewer

### ISSUE THREAD

**Issue by MichaelYu781** [graphdeco-inria/gaussian-splatting#152]
hi, when building SIBR Viewer, some errors happen when linking executable file.
```
[ 96%] Linking CXX executable SIBR_texturedMesh_app
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_easy_getinfo@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_multi_perform@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_multi_cleanup@CURL_OPENSSL_4'
/usr/bin/ld: /lib/x86_64-linux-gnu/libnetcdf.so.19: undefined reference to `curl_global_init@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_mime_init@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_multi_remove_handle@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_mime_addpart@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_version_info@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_mime_name@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_mime_filename@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_multi_info_read@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_easy_setopt@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_mime_free@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_easy_cleanup@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_mime_data_cb@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_easy_perform@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_easy_init@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_multi_add_handle@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_slist_free_all@CURL_OPENSSL_4'
/usr/bin/ld: /lib/x86_64-linux-gnu/libnetcdf.so.19: undefined reference to `curl_easy_strerror@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_slist_append@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_multi_poll@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_version@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_multi_setopt@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_mime_data@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_multi_init@CURL_OPENSSL_4'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `curl_multi_wait@CURL_OPENSSL_4'
/usr/bin/ld: /lib/x86_64-linux-gnu/libnetcdf.so.19: undefined reference to `curl_global_cleanup@CURL_OPENSSL_4'
collect2: error: ld returned 1 exit status
gmake[2]: *** [src/projects/basic/apps/texturedMesh/CMakeFiles/SIBR_texturedMesh_app.dir/build.make:186: src/projects/basic/apps/texturedMesh/SIBR_texturedMesh_app] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1335: src/projects/basic/apps/texturedMesh/CMakeFiles/SIBR_texturedMesh_app.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```

My environment is  `ubuntu 2204`  `cmake 3.24` `gcc 11.4`.

**Comment by longxiang-ai** [comment]
meeting the same issue, have you got a solution? @MichaelYu781

**Comment by MichaelYu781** [comment]
i turn to use windows and install the viewer directly

**Comment by longxiang-ai** [comment]
@MichaelYu781 Thank you for your reply. This issue seems that some cmake files lack the lib CURL & mislocate the GLIBCXX3.4.30. I finally solved this issue by manually modifying the include of CURL & libstdc++.so.6 in the cmakelist.txt.

**Comment by db-githb** [comment]
Hi @longxiang-ai I am having the same issue.  Can you please share the modified cmakelist.txt? I am having trouble finding where to include CURL and libstdc++.so.6?

**Comment by MichaelYu781** [comment]
I solve this problem by following steps:
1. find the version of `libcurl.so` used by typing the command
```shell
ldd lib/libgdal.so.30 | grep curl
```
2. change the soft link of under the `~/anaconda3/lib`
```shell
cd ~/anaconda3/lib
sudo rm libcurl.so.4
sudo ln -s /usr/lib/x86_64-linux-gnu/libcurl.so.4.x.x libcurl.so.4  # where 4.x.x is the version found above
```
3. As to libstdc++.so.6, install the following package
```shell
conda install -c conda-forge gcc=12.1.0
```

**Comment by db-githb** [comment]
Thank you @MichaelYu781 ! Your solution worked and I got the SIBR viewer installed.  The soft link was pointing at libcurl.so.4.8.0 and after changing it to point to version 4.7 the build worked. Thanks again!

**Comment by yang-code1** [comment]
The libstdc++.so in ~/anaconda/lib may point to ~/anaconda/lib/libstdc++.so.6.0.29. In this case, you also need to change its soft link

**Comment by prathammehta12** [comment]
incase somebody like me was doing it inside their conda environment, deactivate all the way out of base env, and then run the cmake commands. Conda always adds their own soft links to things.

**Comment by hzlbbfrog** [comment]
> incase somebody like me was doing it inside their conda environment, deactivate all the way out of base env, and then run the cmake commands. Conda always adds their own soft links to things.

Yeah!  You are right. I first built it in a conda environment and faced the same problem.
I think the solution here is a little complicated. and then I realize that **it is the Conda's problem**.

So I start a new terminal, **quit any Conda environment**, and rebuild; it works!

![Image](https://github.com/user-attachments/assets/30f00daa-e96d-45a4-b6a2-e24a36ba0b6c)

A key point is that you don't write the default initialization conda env paths in the .bashrc file.  I recommend using an alias to activate Conda so that we can control the open and close of Conda.
