### ISSUE TITLE
Bug? No difference 30000 with 50000, train with --iterations argument

### ISSUE THREAD

**Issue by hecodeit** [graphdeco-inria/gaussian-splatting#156]
Training with:
```
python train.py -s data/bicycle/ --iterations 50000
```

log:
```
Training progress:  14%|██████                                     | 7000/50000 [05:20<47:50, 14.98it/s, Loss=0.0937450]
[ITER 7000] Evaluating train: L1 0.03856598660349846 PSNR 23.824575805664065 [31/08 22:43:31]

[ITER 7000] Saving Gaussians [31/08 22:43:31]
Training progress:  60%|█████████████████████████▏                | 30000/50000 [39:43<29:39, 11.24it/s, Loss=0.0586456]
[ITER 30000] Evaluating train: L1 0.02656959928572178 PSNR 27.107151794433594 [31/08 23:17:54]

[ITER 30000] Saving Gaussians [31/08 23:17:54]
Training progress: 100%|████████████████████████████████████████| 50000/50000 [1:10:02<00:00, 11.90it/s, Loss=0.0540809]

[ITER 50000] Saving Gaussians [31/08 23:48:12]
```

The output folder get iteration_7000, iteration_30000, iteration_50000 three point_cloud.ply files. The iteration_30000 version show same file size with iteration_50000. 

Using SIBR_gaussianViewer_app Real-Time Viewer, Loading 5775269 Gaussian splats, both --iteration 30000 with --iteration 50000

It's a bug?

**Comment by grgkopanas** [comment]
No bug here, after iteration 15k we stop densifying to allow the gradient
descent to converge. So the number of points after iteration 15k is the
same, consequently the file size is the same, but the property values
should have differences though.

**Comment by Snosixtyboo** [comment]
@hecodeit you can control this behavior with the ```--densify_until_iter``` parameter.

**Comment by hecodeit** [comment]
> @hecodeit you can control this behavior with the `--densify_until_iter` parameter.

Thanks @Snosixtyboo, I'll try it later.
