### ISSUE TITLE
 WGL: The driver does not appear to support OpenGL

### ISSUE THREAD

**Issue by narendraadloid** [graphdeco-inria/gaussian-splatting#158]
"[SIBR] ##  ERROR  ##:   FILE C:\Users\narendra\Documents\gaussian-splatting-Windows\SIBR_viewers\src\core\graphics\Window.cpp
LINE 30, FUNC sibr::glfwErrorCallback
WGL: The driver does not appear to support OpenGL"

Got the above error while opening SIBR viewer. Pls help me resolve this

I ran the below command
"./<SIBR install dir>/bin/SIBR_gaussianViewer_app -m <path to trained model>"

exact one: 
(gaussian_splatting2) C:\Users\narendra\Documents\gaussian-splatting-Windows\viewers\bin>SIBR_gaussianViewer_app.exe -m C:\Users\narendra\Documents\gaussian-splatting-Windows\output\55243633-1

**Comment by Snosixtyboo** [comment]
Hi,

from the message, it appears that your driver does not support OpenGL.

I would recommend updating the GPU drivers.

Hth,
Bernhard

**Comment by Snosixtyboo** [comment]
Closed due to inactivity

**Comment by DongniZhu** [comment]
> “[SIBR] ## 错误 ##：文件 c：\Users\narendra\Documents\gaussian-splatting-Windows\SIBR_viewers\src\core\graphics\Window.cpp 第 30 行，FUNC sibr：：glfwErrorCallback WGL：驱动程序似乎不支持 OpenGL”
> 
> 打开 SIBR 查看器时出现上述错误。请帮我解决这个问题
> 
> 我运行了以下命令 “.//bin/SIBR_gaussianViewer_app -m ”
> 
> 确切的一：（gaussian_splatting2） C：\Users\narendra\Documents\gaussian-splatting-Windows\viewers\bin>SIBR_gaussianViewer_app.exe -m C：\Users\narendra\Documents\gaussian-splatting-Windows\output\55243633-1

你好，我遇到了和您相同的问题，请问有解决吗？
