### ISSUE TITLE
How can I get the points' indices which contribute to the pixels?

### ISSUE THREAD

**Issue by Chuan-10** [graphdeco-inria/gaussian-splatting#159]
Hi, thank you for the excellent work!
Now i am trying to know which points in the scene are contributing to the specific pixel, is there any advice about it? I think the CUDA rasterization might need to be modified to record which points are used.
Thank you!

**Comment by ZcsrenlongZ** [comment]
> Hi, thank you for the excellent work! Now i am trying to know which points in the scene are contributing to the specific pixel, is there any advice about it? I think the CUDA rasterization might need to be modified to record which points are used. Thank you!

Hi! Have you solved this problem?
