### ISSUE TITLE
how calculate camera parameter ?

### ISSUE THREAD

**Issue by 1346052851** [graphdeco-inria/gaussian-splatting#162]
-----------  cameras.json	
```
[{"id": 0, "img_name": "first.jpg", "width": 1267, "height": 952, 
  "position": [-1.1116379538112167, -3.6726717783501166, 2.726632000503751], 
  "fy": 1007.2233011429463, "fx": 1012.3493253425622}, 
  
 {"id": 1, "img_name": "last.jpg", "width": 1267, "height": 952, 
  "position": [-1.9806852707163367, -2.349926498357343, 2.9191284564775892], 
  "fy": 1007.2233011429463, "fx": 1012.3493253425622}]
```

**Comment by yzslab** [comment]
Hi, take a look this: https://github.com/Totoro97/f2-nerf/blob/main/scripts/inter_poses.py

**Comment by 1346052851** [comment]
```
how transform  (f2-nerf camera's position)  <->  (gaussian camera's position)

-----------------------------------------
f2-nerf -> inter_poses.py : camera's position
cp.shape == (3, 4)

[[ 0.22728021  0.06116116 -0.9719069  -3.49605881]
 [-0.0644319  -0.99489452 -0.07767513  0.81330172]
 [-0.97169555  0.08027583 -0.2221791   1.78924843]]
-----------------------------------------
gaussian : camera's position
cp["position"].shape == (1, 3)
cp["rotation"].shape == (3, 3)

{"position": [-1.1116379538112167, -3.6726717783501166, 2.726632000503751], 
 "rotation": [[0.2990373833954889, -0.6586733882033187, 0.6904534821439746], 
              [0.13315892331400764, 0.7452870145661082, 0.6533115390539125], 
              [-0.9449049393848218, -0.10342453090006266, 0.3105769179032279]]}
```

> Hi, take a look this: https://github.com/Totoro97/f2-nerf/blob/main/scripts/inter_poses.py

**Comment by ang88myt** [comment]
**# f2-nerf representation**
cp_f2_nerf = np.array([[0.22728021,  0.06116116, -0.9719069,  -3.49605881],
                      [-0.0644319, -0.99489452, -0.07767513, 0.81330172],
                      [-0.97169555, 0.08027583, -0.2221791,  1.78924843]])

# Extract Rotation and Translation
R_f2_nerf = cp_f2_nerf[:, :3]
T_f2_nerf = cp_f2_nerf[:, 3]

# Now these can be used as Gaussian's "rotation" and "position"

**# Gaussian to f2-nerf**
R_gaussian = np.array([[0.29903738, -0.65867339, 0.69045348],
                       [0.13315892,  0.74528701, 0.65331154],
                       [-0.94490494, -0.10342453, 0.31057692]])
T_gaussian = np.array([-1.11163795, -3.67267178, 2.72663200])

# Construct the 3x4 matrix for f2-nerf
cp_f2_nerf = np.hstack((R_gaussian, T_gaussian.reshape(-1, 1)))


Typically, the row and column indices should directly correspond unless one system is transposed relative to the other. Given that both are 3x3 rotation matrices, they should correspond.
