### ISSUE TITLE
Can spatial_lr_scale be dynamic change when training?

### ISSUE THREAD

**Issue by NPU-YanChi** [graphdeco-inria/gaussian-splatting#164]
Thank you for your wonderful work.
When I tried to apply your work to the real scene, I found that self.spatial_lr_scale is created through the scene in advance. Can I dynamically adjust this variable and gradually increase this parameter

**Comment by Snosixtyboo** [comment]
Not ```spatial_lr_scale```, but all it does is act as a multiplier to the position and scaling learning rate. You can take a look at the solution where the position (xyz) learning is adaptively changed over time (each iteration). You can edit it to a different behavior you want and do something similar for scaling.

Hth,
Bernhard
