### ISSUE TITLE
Training on multiple GPUs

### ISSUE THREAD

**Issue by AdityaDhaulakhandi** [graphdeco-inria/gaussian-splatting#165]
Hey, Im trying to train the model on multiple GPUs because I have 12 GB GPU, I tried: 
`CUDA_VISIBLE_DEVICES=0,1 python train.py -s <location>`
but this runs on the first mentioned GPU only, can anyone help me with this? Thanks!

**Comment by why529913** [comment]
Is that solved? Thank you.
