### ISSUE TITLE
Agisoft Metashape support?

### ISSUE THREAD

**Issue by aaronhdgolf** [graphdeco-inria/gaussian-splatting#167]
While colmap is decent, Agisoft Metashape is superior and will bring geophysical accurate camera locations.

Also supporting 360 images would be huge. As Metashape supports it.

Thanks.

**Comment by Snosixtyboo** [comment]
Only if someone else adds it :)

**Comment by PolarNick239** [comment]
Hi, @aaronhdgolf, you can follow [this instruction](https://github.com/PolarNick239/gaussian-splatting-Windows#preparing-images-from-your-own-scenes-agisoft-metashape-pro). It tells how to export cameras alignment/images from Metashape Pro into Colmap format, which can be used as input for Gaussian Splatting.

@Snosixtyboo can you guide me please - is it a good idea to add some kind of information about this possibility into README.MD?
