### ISSUE TITLE
Can point clouds or mesh files with vertex colors be exported.

### ISSUE THREAD

**Issue by Dragonkingpan** [graphdeco-inria/gaussian-splatting#169]
I have tested some scenarios and the results are very good. The point cloud file exported with 10000it also looks very good. I would like to ask if the output point cloud file can contain vertex colors or directly obtain a mesh file.
![poly](https://github.com/graphdeco-inria/gaussian-splatting/assets/33677417/4438e9fb-59ef-4167-a452-0d613f7d919f)

**Comment by ang88myt** [comment]
Yes, point clouds or mesh files with vertex colors can be exported, typically in formats that support such data. The methods for exporting may vary based on the software you're using. Such as blender.
Software: Software like Blender, Houdini, or even custom scripts in C++/Python can be used for exporting. Your choice might depend on the existing tools in your workflow or project requirements.

File Formats: Choose a file format that supports vertex colors. PLY is a straightforward choice for both point clouds and meshes. FBX and OBJ (with MTL) are other options for meshes.

Attributes: Make sure that the vertex colors are appropriately tagged as attributes in the point cloud or mesh before exporting.

Export Settings: Usually, there are options to include vertex colors during the export process. Make sure this is enabled.

Validation: After exporting, it's good to import the file back into another software to validate that the vertex colors have been saved correctly.

**Comment by ang88myt** [comment]
i believe you are using Mesh Room to visualize the data. Right?

**Comment by xiemeilong** [comment]
@ang88myt Please don't respond with ChatGPT , that would be really low.

**Comment by Snosixtyboo** [comment]
Hi,

it should be possible and should be a somewhat easy feature to add. If you are comfortable with a little Python coding, you can do it and then make a pull request:
- Create a function that writes a ```.ply``` similar to the one we have already
- Instead of the SH attributes, just take the ```features_dc``` and convert them with ```SH2RGB``` to get an RGB color
- Write the resulting values into the ```.ply``` attributes where the format expects RGB

That should be it!
