### ISSUE TITLE
cannot find -lembree

### ISSUE THREAD

**Issue by ZcsrenlongZ** [graphdeco-inria/gaussian-splatting#171]

**Comment by Yang-Xijie** [comment]
What do you mean by "lembree"? This word is not found in the paper and the codes. Did you create this issue in a wrong repository?

**Comment by Snosixtyboo** [comment]
no @ZcsrenlongZ is right, embree is used by the SIBR viewers. But the non-existent description does not provide sufficient information to try and address the issue.

**Comment by zeyutt** [comment]
-lembree seems a target link failure, maybe change to link embree3 if you have installed correctly.

**Comment by Snosixtyboo** [comment]
Closed due to inactivity from OP

**Comment by MihneaJurca** [comment]
If you get this error you should change the CMakeList.txt or raycaster in SIBRE repo from embree to embree3 line 34.
