### ISSUE TITLE
Metrics showing NaN

### ISSUE THREAD

**Issue by sauradip** [graphdeco-inria/gaussian-splatting#174]
Hi firstly thanks for making this amazing work public. I want to train this myself and evaluate myself. I observed that i can successfully do the training and rendering step. However i cannot get any value for the metric. 

Here is the rendering script which succesfuly ran
<img width="1251" alt="Screenshot 2023-09-07 at 9 24 36 PM" src="https://github.com/graphdeco-inria/gaussian-splatting/assets/23197350/2a04feac-71ba-40dd-be8a-6d4789ecb7e6">

however, when i run the evaluation it shows nan 
<img width="1255" alt="Screenshot 2023-09-07 at 9 24 56 PM" src="https://github.com/graphdeco-inria/gaussian-splatting/assets/23197350/cd6ab515-aeb8-4b8b-be4b-43e3dfb69100">

Can you let me know what is wrong here ?

**Comment by Snosixtyboo** [comment]
Hi,

without knowing what is being processed, unfortunately no. Are you able to debug the script (e.g. with Visual Studio) and get a clue where the Nans first appear?

**Comment by Snosixtyboo** [comment]
Closed due to inactivity
