### ISSUE TITLE
Mapper failed with no output in sparse folder

### ISSUE THREAD

**Issue by janbro** [graphdeco-inria/gaussian-splatting#177]
When running `python convert.py -s data\playroom\`, the conversion fails at the second Mapper step of undistorting the images. I looked into the distorted image folder and there is no output in the sparse folder, even though that step looks to be completed successfully. Tested using the playroom scene from the paper's website. Also tried with/without the resize flag.
https://github.com/graphdeco-inria/gaussian-splatting/blob/ea68bdf29c3b11d1a7ec2e5a11b1af2c266bd7f2/convert.py#L55-L78
```
Bundle adjustment report
------------------------
    Residuals : 28392
   Parameters : 3731
   Iterations : 3
         Time : 0.0306153 [s]
 Initial cost : 0.477419 [px]
   Final cost : 0.468947 [px]
  Termination : Convergence

  => Merged observations: 0
  => Completed observations: 11
  => Filtered observations: 1
  => Changed observations: 0.000738

==============================================================================
Retriangulation
==============================================================================

  => Completed observations: 19
  => Merged observations: 273
  => Retriangulated observations: 8

==============================================================================
Global bundle adjustment
==============================================================================

iter      cost      cost_change  |gradient|   |step|    tr_ratio  tr_radius  ls_iter  iter_time  total_time
   0  3.923088e+04    0.00e+00    2.36e+04   0.00e+00   0.00e+00  1.00e+04        0    2.78e-02    1.74e-01

CHOLMOD version 3.0.14, Oct 22, 2019: Symbolic Analysis: status: OK
  Architecture: Microsoft Windows
    sizeof(int):      4
    sizeof(SuiteSparse_long):  8
    sizeof(void *):   8
    sizeof(double):   8
    sizeof(Int):      4 (CHOLMOD's basic integer)
    sizeof(BLAS_INT): 4 (integer used in the BLAS)
  Results from most recent analysis:
    Cholesky flop count: 9.7363e+06
    Nonzeros in L:       49230
  memory blocks in use:          11
  memory in use (MB):           0.0
  peak memory usage (MB):       0.2
  maxrank:    update/downdate rank:   8
  supernodal control: 1 40 (supernodal if flops/lnz >= 40)
  nmethods:   number of ordering methods to try: 1
    method 0: natural
        flop count: 9.7363e+06
        nnz(L):     49230
  OK
ERROR:root:Mapper failed with code -1073741819. Exiting.
```

**Comment by Snosixtyboo** [comment]
Hi,

interesting, maybe we can try and reproduce it, but why do you run the conversion script in the first place? We provide the scene ready-to-use, precomputed in our files.

**Comment by janbro** [comment]
I was running into the same issue with my own dataset so I tried the example one provided to see if it was an issue with my images

**Comment by Snosixtyboo** [comment]
Sorry, unfortunately, I have no idea. This appears to be an issue of COLMAP rather than our codebase.

**Comment by TheShoes** [comment]
Is there any luck on this.  I am experiencing it also.  It always gets to around 50 images no matter their resolution before craping out

**Comment by janbro** [comment]
It seemed to be an issue with colmap command line. I ran the bat file for colmap to run the gui and imported the database file and images, and once the processing was done running exported the model to /sparse/0 manually. From there I could run `python convert.py -s data/{folder} —skip_matching` to continue using the data exported from the colmap GUI

**Comment by TheShoes** [comment]
yeah actually i am trying this out now to use the nerf studios colmap command  then the command you talked about 
https://www.youtube.com/watch?v=wuKhEGCt6ks

**Comment by TheShoes** [comment]
Yeah @Snosixtyboo There might be an issue with the the your alls colmap script because when I used the nerf studio to align the images like above everything worked.

**Comment by HungNgoCT** [comment]
> Yeah @Snosixtyboo There might be an issue with the the your alls colmap script because when I used the nerf studio to align the images like above everything worked.

Confirm that using colmap in nerfstudio (ns-process-data) and colmap in instant-ngp gave good results, but convert.py script was failed.

**Comment by tangketan** [comment]
I encountered same issue and it turned out the colmap path I added to system PATH environment was wrong. It should be the path containing COLMAP.bat, not the path of colmap.exe. After changing the path, convert.py works fine.

**Comment by WS517** [comment]
Hi I encounter the same error. Did you fix it?

**Comment by SakuraTau** [comment]
> When running `python convert.py -s data\playroom\`, the conversion fails at the second Mapper step of undistorting the images. I looked into the distorted image folder and there is no output in the sparse folder, even though that step looks to be completed successfully. Tested using the playroom scene from the paper's website. Also tried with/without the resize flag.
> 
> [gaussian-splatting/convert.py](https://github.com/graphdeco-inria/gaussian-splatting/blob/ea68bdf29c3b11d1a7ec2e5a11b1af2c266bd7f2/convert.py#L55-L78)
> 
> Lines 55 to 78 in [ea68bdf](/graphdeco-inria/gaussian-splatting/commit/ea68bdf29c3b11d1a7ec2e5a11b1af2c266bd7f2)
> 
>      ### Bundle adjustment 
>      # The default Mapper tolerance is unnecessarily large, 
>      # decreasing it speeds up bundle adjustment steps. 
>      mapper_cmd = (colmap_command + " mapper \ 
>          --database_path " + args.source_path + "/distorted/database.db \ 
>          --image_path "  + args.source_path + "/input \ 
>          --output_path "  + args.source_path + "/distorted/sparse \ 
>          --Mapper.ba_global_function_tolerance=0.000001") 
>      exit_code = os.system(mapper_cmd) 
>      if exit_code != 0: 
>          logging.error(f"Mapper failed with code {exit_code}. Exiting.") 
>          exit(exit_code) 
>   
>  ### Image undistortion 
>  ## We need to undistort our images into ideal pinhole intrinsics. 
>  img_undist_cmd = (colmap_command + " image_undistorter \ 
>      --image_path " + args.source_path + "/input \ 
>      --input_path " + args.source_path + "/distorted/sparse/0 \ 
>      --output_path " + args.source_path + "\ 
>      --output_type COLMAP") 
>  exit_code = os.system(img_undist_cmd) 
>  if exit_code != 0: 
>      logging.error(f"Mapper failed with code {exit_code}. Exiting.") 
>      exit(exit_code) 
> ```
> Bundle adjustment report
> ------------------------
>     Residuals : 28392
>    Parameters : 3731
>    Iterations : 3
>          Time : 0.0306153 [s]
>  Initial cost : 0.477419 [px]
>    Final cost : 0.468947 [px]
>   Termination : Convergence
> 
>   => Merged observations: 0
>   => Completed observations: 11
>   => Filtered observations: 1
>   => Changed observations: 0.000738
> 
> ==============================================================================
> Retriangulation
> ==============================================================================
> 
>   => Completed observations: 19
>   => Merged observations: 273
>   => Retriangulated observations: 8
> 
> ==============================================================================
> Global bundle adjustment
> ==============================================================================
> 
> iter      cost      cost_change  |gradient|   |step|    tr_ratio  tr_radius  ls_iter  iter_time  total_time
>    0  3.923088e+04    0.00e+00    2.36e+04   0.00e+00   0.00e+00  1.00e+04        0    2.78e-02    1.74e-01
> 
> CHOLMOD version 3.0.14, Oct 22, 2019: Symbolic Analysis: status: OK
>   Architecture: Microsoft Windows
>     sizeof(int):      4
>     sizeof(SuiteSparse_long):  8
>     sizeof(void *):   8
>     sizeof(double):   8
>     sizeof(Int):      4 (CHOLMOD's basic integer)
>     sizeof(BLAS_INT): 4 (integer used in the BLAS)
>   Results from most recent analysis:
>     Cholesky flop count: 9.7363e+06
>     Nonzeros in L:       49230
>   memory blocks in use:          11
>   memory in use (MB):           0.0
>   peak memory usage (MB):       0.2
>   maxrank:    update/downdate rank:   8
>   supernodal control: 1 40 (supernodal if flops/lnz >= 40)
>   nmethods:   number of ordering methods to try: 1
>     method 0: natural
>         flop count: 9.7363e+06
>         nnz(L):     49230
>   OK
> ERROR:root:Mapper failed with code -1073741819. Exiting.
> ```

Hi I encounter the same error. Did you fix it?
