### ISSUE TITLE
Custom point cloud initialization

### ISSUE THREAD

**Issue by VladimirYugay** [graphdeco-inria/gaussian-splatting#178]
Hey there. I want to initialize the method with my point cloud and I'm having issues with the coordinate system.

My initialization works when the translation of the pose is passed to the `Camera` is 0. If it's something other than 0, the rendering is wrong - only a small part of the scene is seen as initialized, but the orientation seems to be correct. 

Therefore, I assume that this error comes from the `Camera` part:

1. I compute my point cloud using the `T_camera_to_world` transformation

2. I create the `Camera` object with the `T_world_to_camera` transformation 

3. In the `Camera` object [here](https://github.com/graphdeco-inria/gaussian-splatting/blob/ea68bdf29c3b11d1a7ec2e5a11b1af2c266bd7f2/scene/cameras.py#L54C24-L54C24), it seems that `self.world_view_transform` consists of `(Rotation_camera_to_word, Translation_world_to_camera)`. Therefore, the `self.camera_center` is something weird consisting of the translation of the inverse of `self.world_view_transform`. 

In one of the comments, @grgkopanas mentioned this [issue](https://github.com/graphdeco-inria/gaussian-splatting/issues/100#issuecomment-1690378854). 

I'm really struggling to understand, why the rotation matrix is rotated when `self.world_view_transform` is Rotated, why rendering works with translation 0, and how to adjust it to my use case.

**Comment by Yang-Xijie** [comment]
A point is a row vector instead of a column vector in this repo... not sure if it is helpful.
