### ISSUE TITLE
Render code? 

### ISSUE THREAD

**Issue by antithing** [graphdeco-inria/gaussian-splatting#18]
Hi, thanks for making this code available, it works very well.

I am looking to port the rendering code into a game engine, can you please explain how the rendering works with your model?

Which parts of SIBR are used?

Thanks!

**Comment by grgkopanas** [comment]
Hi,

I wouldn't be bothered that much with sIBR it is mostly there to handle the
camera the GUI etc. I think you should mostly focus on the cuda rendering
side here:
https://github.com/graphdeco-inria/diff-gaussian-rasterization/tree/c78d81f56cd5da3cf39f6201984570060128c1aa

This is the entry point:
https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/c78d81f56cd5da3cf39f6201984570060128c1aa/rasterize_points.cu#L36

Best,
George

**Comment by antithing** [comment]
Thank you! I will dig into this.

**Comment by Snosixtyboo** [comment]
Actually the rasterizer codebase comes with a torch-agnostic way of building a C++ library, the corresponding CMake is here: https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/c78d81f56cd5da3cf39f6201984570060128c1aa/CMakeLists.txt

That's even a little closer to the pure rendering and avoids the dependency on anything related to torch.

Hth,
Bernhard

**Comment by Snosixtyboo** [comment]
I'll go ahead and close this?
