### ISSUE TITLE
How to use colmap to have images with white background recognized?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [graphdeco-inria/gaussian-splatting#182]
Sample:
![0000000015](https://github.com/graphdeco-inria/gaussian-splatting/assets/18123801/9767337a-4400-469f-bfd9-fe91fe080f01)

**Comment by grgkopanas** [comment]
In that case, depending on your coding skill and your knowledge of pytorch
framework I would suggest that the best solution is an environment map to
be able to model the background correctly.

**Comment by ErfolgreichCharismatisch** [comment]
Can you elaborate in detail?

**Comment by grgkopanas** [comment]
I can try:
1) Your background doesnt seem exactly pure white. So artificially forcing the background to be white while rendering and optimizing the 3DGS model is not really going to do miracles.
2) That is why I suggest you to model the background as an environment map: https://www.reindelsoftware.com/Documents/Mapping/Mapping.html
3) You would need to change the rendering of the 3DGS to use that and blend the final image produced with this environment map and also make sure that you optimize this environment map such that it models your background.
4) There is the other alternative that you can segment your object and make the background pure white or pure black in the images and this could potential be easier to handle, by easier I mean you would need less code.

**Comment by Snosixtyboo** [comment]
Closed due to inactivity
