### ISSUE TITLE
plenoxel experiments with MipNerf-360 dataset

### ISSUE THREAD

**Issue by j93hahn** [graphdeco-inria/gaussian-splatting#183]
Hi, I was wondering how you were able to get the experimental data from Plenoxels on the MipNerf-360 dataset? 

When I tried running plenoxels on the garden scene, for example, it defaulted to the LLFF data loader and failed to converge. I tried to convert it to the NSVF dataset with their provided scripts but the OPENCV camera model is not supported. If you could provide a series of steps on what you did (especially preprocessing if you did any), that would be very helpful.

**Comment by j93hahn** [comment]
I set the number of background layers to 128 and am still only able to achieve a test PSNR of 14 on the bicycle scene while the paper achieved 21.9 - could you share the exact values of the parameters if possible? Thanks!

**Comment by grgkopanas** [comment]
If I remember correctly I converted the colmap format of the original
mipnerf360 it to transforms.json with the ingp script and then used
ingp2nsvf.py
from plenoxels to get a format that works with plenoxels. Finally I
used  config_alt.json
as a configuration file.

I  dont know if I am missing any other details.

Best,
George

**Comment by j93hahn** [comment]
Hi @grgkopanas thank you for the replies! When you say ingp script, are you referring to this file: https://github.com/NVlabs/instant-ngp/blob/master/scripts/colmap2nerf.py?

I tried what you said but still could not match the results from your paper, will continue trying other ways to see how I can reproduce them.

**Comment by MELANCHOLY828** [comment]
python colmap2nerf.py  --images xx/garden/images --text xx/garden/sparse/0/ --out xx/garden/images/transforms.json
python ingp2nsvf.py --data_dir xx/bicycle/images/ --out_data_dir xx/360/bicycle
then use xx/360/bicycle dataset to run plenoxels

**Comment by j93hahn** [comment]
@MELANCHOLY828 thanks!!! Did you use the special `config_alt.json` file? Or you just used the standard NSVF dataloader? If possible, can you copy the actual training command here too?

**Comment by MELANCHOLY828** [comment]
> @MELANCHOLY828 thanks!!! Did you use the special `config_alt.json` file? Or you just used the standard NSVF dataloader? If possible, can you copy the actual training command here too?

yes config_alt.json and NSVF dataloader:
CUDA_VISIBLE_DEVICES={gpu} python opt.py --data_dir {data_dir} --scale {scale} -c /data/liufengyi/MyCode/svox2/opt/configs/custom_alt.json --dataset_type auto --train_dir {output_dir} --expname {scene}
