### ISSUE TITLE
Any way to restrict the camera?

### ISSUE THREAD

**Issue by Brawnee** [graphdeco-inria/gaussian-splatting#185]
Hello, thank's for the code I'm achieving some really promising results during testing.

I was wondering if there is a way to limit the camera's rotation in Orbit mode, preventing the user from, for instance, viewing underneath the object?

**Comment by Snosixtyboo** [comment]
Not unless you go and edit the code of the individual viewers, unfortunately. So getting into some C++ code in the TrackballViewer would be required.
