### ISSUE TITLE
CondaEnvException: Pip failed (Win11)

### ISSUE THREAD

**Issue by bbecausereasonss** [graphdeco-inria/gaussian-splatting#187]
Getting an error during initial env setup as per instructions.

--

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: \ "By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"

done
Installing pip dependencies: / Ran pip subprocess with arguments:
['C:\\Users\\xxxx\\anaconda3\\envs\\gaussian_splatting\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\xxxx\\Deep\\splatting\\condaenv.8i9cbjuw.requirements.txt', '--exists-action=b']
Pip subprocess output:

Pip subprocess error:
ERROR: Directory 'submodules/diff-gaussian-rasterization' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

failed

CondaEnvException: Pip failed

**Comment by iSach** [comment]
How did you solve it?
