### ISSUE TITLE
Handle Distortion when computing metrics

### ISSUE THREAD

**Issue by ThomasParistech** [graphdeco-inria/gaussian-splatting#189]
Thanks for your great work :fire: 

As a pre-processing step we have to undistort our images if the COLMAP model has an OPENCV camera instead of a PINHOLE.

However, when I look at the "full_eval" script it seems like we don't apply the distortion back. In this case, the metrics can't be directly compared against the metrics of another NeRF-like method that renders the actual distorted image.

What's your thoughts on this?
* Should we re-train COLMAP with a PINHOLE model?
* Should we render slightly larger undistorted images and apply the distortion afterwards?

**Comment by grgkopanas** [comment]
The fair way to make a comparison would be to run colmap with pinhole
camera. This is a limitation of the rasterization based pipelines that
cannot handle camera distortion very well.

Best,
George

**Comment by ThomasParistech** [comment]
Ok thanks I'll try that for my datasets with small distortion
And compare with the metrics obtained by "full_eval" on undistorted images as safeguard
