### ISSUE TITLE
convert.py mess up with folders: The system cannot find the path specified: '<location>/sparse'

### ISSUE THREAD

**Issue by emepetres** [graphdeco-inria/gaussian-splatting#19]
After set up folder as <location>/input with images in there (tested with jpg and png files), and running: `python .\convert.py -s <location> --resize`, the script fails with the error stated on the title:

```
Traceback (most recent call last):
  File ".\convert.py", line 63, in <module>
    files = os.listdir(args.source_path + "/sparse")
FileNotFoundError: [WinError 3] The system cannot find the path specified: '<location>/sparse'
```

If I create the folder _'\<location\>/sparse'_ manually, then it creates _images_N_ folders and fails with the following error:

```
Copying and resizing...
Traceback (most recent call last):
  File ".\convert.py", line 81, in <module>
    files = os.listdir(args.source_path + "/images")
FileNotFoundError: [WinError 3] The system cannot find the path specified: '<location>/images'
```

Finally, If again _\<location\>/images_ folder is created, the script doesn't fail but it doesn't do anything as well:
```
Copying and resizing...
Done.
```

Tested on latest main branch, on windows 11.

BTW thank you for the great work, and for sharing the source code, amaizing!

**Comment by Snosixtyboo** [comment]
Hi,

thanks for bringing this up, if at this stage there are neither /sparse nor /images folders, then it seems that COLMAP has just failed. The info it produces should be in those directories. Is there ANY output from colmap with another name, or can you check if maybe the script failed at a much earlier stage already and that's why there's nothing there?

**Comment by emepetres** [comment]
It was indeed a colmap issue. I've sent a PR to improve error handling in the script, so if colmap or imagemagick fails, it shows the proper error and stop the execution.
