### ISSUE TITLE
Why is there a hyperparameter in function 'computeCov2D( )'?

### ISSUE THREAD

**Issue by hjr37** [graphdeco-inria/gaussian-splatting#191]
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/116424970/f7e16d7f-0eef-41bf-9add-104cbd03c5cc)
Thank you for your amazing work, recently, I'm trying to understand CUDA code in this project, while I'm struggled in the reason why you multiplied the 'tan_fovx / tan_fovy' variable by 1.3, as shown in the above image. Thank you in advance.

**Comment by Snosixtyboo** [comment]
Hi,

it's not really a hyperparameter, as in, it's not meant to be tuned. The EWA projection of the Gaussians is an approximation of the real computation, based on the Jacobian at their mean. If the mean falls far outside the view frustum, the projected approximation of Gaussians becomes **very** stretched. This results in very big covariances which were the reason for a lot of popping artifacts. With this limit, we are forcing Gaussians to get stretched no more than they are when their mean falls ~20% of the FOV outside of the frustum.

I realize that this might be a bit tough to parse, but the information is all in the above paragraph, even if it's condensed :P

Hth,
Bernhard

**Comment by hjr37** [comment]
Thank you for your answer!
     I would like to know if there is a math explanation for **‘the mean falls far outside the view frustum, the projected approximation of Gaussians becomes very stretched’**

**Comment by hjr37** [comment]
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/116424970/0f468aab-03b2-4b89-809e-109ba4787c26)
Thank you for your answer!
   I found that **‘0.5’** was added during the **‘SH_to_RGB’** process, as shown in the above image. Can you explain this further?

**Comment by hjr37** [comment]
In addition, if '0.5' is added to the final result, will this result in a value greater than **'1.0',** which is unreasonable for **the normalized RGB value**.

**Comment by nnop** [comment]
Got the same question. Still didn't get what's the relationship between 20% fov and the value 1.3. 
Could you elaborate more?
