### ISSUE TITLE
Request (viewer)

### ISSUE THREAD

**Issue by bbecausereasonss** [graphdeco-inria/gaussian-splatting#193]
Just want to throw this out there, but if we could export, or somehow be able to view these in (VR) this would be game-changing.

**Comment by Hezhexi2002** [comment]
Exactly right,I'd like to see there would have the support  for the model export just like nerfstudio which have the option for the point cloud or mesh export

**Comment by DoctorDiffusion** [comment]
I agree! I hope this is implemented.

**Comment by Snosixtyboo** [comment]
Sorry, that's currently not planned... maybe if we get an engineer to work on it in the future :)
