### ISSUE TITLE
AssertionError: Could not recognize scene type!

### ISSUE THREAD

**Issue by sunhoro** [graphdeco-inria/gaussian-splatting#195]
Any help is appreciated.
Prior to this, the next code worked fine:
(gaussian_splatting) C:\Users\Administrator\gaussian-splatting>Python convert.py -s C:\Users\Administrator\gaussian-splatting\data/max2002_nerfactohudge --skip_matching --resize

============================================================================

(gaussian_splatting) C:\Users\Administrator\gaussian-splatting>python train.py -s :\Users\Administrator\gaussian-splatting\data/max2002_nerfactohudge
Optimizing
Output folder: ./output/eef7a850-5 [13/09 03:58:53]
Tensorboard not available: not logging progress [13/09 03:58:53]
Traceback (most recent call last):
  File "train.py", line 216, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "C:\Users\Administrator\gaussian-splatting\scene\__init__.py", line 49, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!

(gaussian_splatting) C:\Users\Administrator\gaussian-splatting>chat

**Comment by realnihal** [comment]
I am facing the same issue, PLease let me know the solution to this.

**Comment by wimvanhenden-tool** [comment]
Hi guys, me too. Thanks for helping out!

**Comment by realnihal** [comment]
I found the fix, reinstall colmap and run the convert.py file with the directory of images. also I suggest to build using binaries from colmaps website the sudo apt-get installer doesn't work well.

**Comment by sunhoro** [comment]
I tried multiple re-instllation but still the same. 

Could it be the GPU requirement? Because I see that minmal of 24GB VRAM is required but mine is 24GB (NVIDIA A10).

**Comment by sunhoro** [comment]
> I found the fix, reinstall colmap and run the convert.py file with the directory of images. also I suggest to build using binaries from colmaps website the sudo apt-get installer doesn't work well.

What COLMAP version did yo used? Im using 11.7 CUDA FYI.

**Comment by realnihal** [comment]
Cuda version 12.2, colmap version 3.9

**Comment by Snosixtyboo** [comment]
Usually this error occurs when the folder structure is unexpected or files are missing. I recommend downloading one of the pretrained samples and comparing your created folder structure to theirs.

**Comment by Snosixtyboo** [comment]
Closed due to inactivity

**Comment by iwander-all** [comment]
hi， I face the same problem when render your pretained model, could you please offer a help
`(gaussian_splatting) hunkyu@liangliang:~/net/gaussian-splatting$ python render.py -m /home/hunkyu/net/data/testData/gaussianSplat/models/bicycle
Looking for config file in /home/hunkyu/net/data/testData/gaussianSplat/models/bicycle/cfg_args
Config file found: /home/hunkyu/net/data/testData/gaussianSplat/models/bicycle/cfg_args
Rendering /home/hunkyu/net/data/testData/gaussianSplat/models/bicycle
Loading trained model at iteration 30000 [19/12 10:07:22]
Traceback (most recent call last):
  File "render.py", line 66, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test)
  File "render.py", line 40, in render_sets
    scene = Scene(dataset, gaussians, load_iteration=iteration, shuffle=False)
  File "/home/hunkyu/net/gaussian-splatting/scene/__init__.py", line 49, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!
`

**Comment by daiyicheng** [comment]
if you use "conda env create --file environment.yml" install  then face the challenge ,  try "pip reinstall diff-gaussian-rasterization & simple-knn".

**Comment by pranavc2255** [comment]
> hi， I face the same problem when render your pretained model, could you please offer a help `(gaussian_splatting) hunkyu@liangliang:~/net/gaussian-splatting$ python render.py -m /home/hunkyu/net/data/testData/gaussianSplat/models/bicycle Looking for config file in /home/hunkyu/net/data/testData/gaussianSplat/models/bicycle/cfg_args Config file found: /home/hunkyu/net/data/testData/gaussianSplat/models/bicycle/cfg_args Rendering /home/hunkyu/net/data/testData/gaussianSplat/models/bicycle Loading trained model at iteration 30000 [19/12 10:07:22] Traceback (most recent call last): File "render.py", line 66, in <module> render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test) File "render.py", line 40, in render_sets scene = Scene(dataset, gaussians, load_iteration=iteration, shuffle=False) File "/home/hunkyu/net/gaussian-splatting/scene/__init__.py", line 49, in __init__ assert False, "Could not recognize scene type!" AssertionError: Could not recognize scene type! `

Same issue

**Comment by LINHYYY** [comment]
I also encountered this error, but after checking 43-49 in __init__. py and 31-35 in train. py, I can see that I cannot find a separate image collection folder. I need to determine the directory structure and store the images in a separate folder at the same level, for example: \Your data name \ input (your image set) instead of storing images in your data directory can solve this problem

**Comment by ani0075saha** [comment]
> I also encountered this error, but after checking 43-49 in **init**. py and 31-35 in train. py, I can see that I cannot find a separate image collection folder. I need to determine the directory structure and store the images in a separate folder at the same level, for example: \Your data name \ input (your image set) instead of storing images in your data directory can solve this problem

Hi @LINHYYY,

The issue comes from here [https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/__init__.py#L43](https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/__init__.py#L43)

I am trying to render from the pre-trained bicycle model and I have downloaded the bicycle evaluation images. But this piece of code looks for a "sparse" folder or a "transforms_train.json" file which is not present in the evaluation data.

How do I solve this? Any suggestions.

**Comment by LINHYYY** [comment]
> > I also encountered this error, but after checking 43-49 in **init**. py and 31-35 in train. py, I can see that I cannot find a separate image collection folder. I need to determine the directory structure and store the images in a separate folder at the same level, for example: \Your data name \ input (your image set) instead of storing images in your data directory can solve this problem
> 
> Hi @LINHYYY,
> 
> The issue comes from here [https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/**init**.py#L43](https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/__init__.py#L43)
> 
> I am trying to render from the pre-trained bicycle model and I have downloaded the bicycle evaluation images. But this piece of code looks for a "sparse" folder or a "transforms_train.json" file which is not present in the evaluation data.
> 
> How do I solve this? Any suggestions.
> 
> EDIT: This says [you will have to download the corresponding source data sets](https://github.com/graphdeco-inria/gaussian-splatting?tab=readme-ov-file#:~:text=you%20will%20have%20to%20download%20the%20corresponding%20source%20data%20sets). Where do I get the source dataset for bicycle which has the COLMAP data?

Once you've downloaded the data image set you want to train, you should go through the colmap and calculate the camera pose, which is in the author's code, and you'll get the "transforms_train.json" file

**Comment by LINHYYY** [comment]
@

> > I also encountered this error, but after checking 43-49 in **init**. py and 31-35 in train. py, I can see that I cannot find a separate image collection folder. I need to determine the directory structure and store the images in a separate folder at the same level, for example: \Your data name \ input (your image set) instead of storing images in your data directory can solve this problem
> 
> Hi @LINHYYY,
> 
> The issue comes from here [https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/**init**.py#L43](https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/__init__.py#L43)
> 
> I am trying to render from the pre-trained bicycle model and I have downloaded the bicycle evaluation images. But this piece of code looks for a "sparse" folder or a "transforms_train.json" file which is not present in the evaluation data.
> 
> How do I solve this? Any suggestions.
> 
> EDIT: This says [you will have to download the corresponding source data sets](https://github.com/graphdeco-inria/gaussian-splatting?tab=readme-ov-file#:~:text=you%20will%20have%20to%20download%20the%20corresponding%20source%20data%20sets). Where do I get the source dataset for bicycle which has the COLMAP data?

@ani0075saha   Once you've downloaded the data image set you want to train, you should go through the colmap and calculate the camera pose, which is in the author's code, and you'll get the "transforms_train.json" file
