### ISSUE TITLE
Training 300k step worse than 30k steps

### ISSUE THREAD

**Issue by HungNgoCT** [graphdeco-inria/gaussian-splatting#196]
Hi,

Thank you for the great work.

I did experiments, and get not good results with 300k steps. Many lines appear like video below.

https://github.com/graphdeco-inria/gaussian-splatting/assets/110378166/60c519ac-f26c-4357-8a6e-6ac340d3d54a

But when I use only 30k steps, these lines do not occur.

https://github.com/graphdeco-inria/gaussian-splatting/assets/110378166/5f473e56-fa8a-4d08-a0b6-9724f04e3e9e

Can any body guide me how to solve this?

Thank you

**Comment by Khoa-NT** [comment]
I have the same case 

> If you render the training views are these thin elongated gaussians visible?

And I can confirm that after rendering it's still visible.

**Comment by ThomasWarn** [comment]
Can confirm that I had a similar behavior after 1m steps.

**Comment by grgkopanas** [comment]
That's very interesting thank you for letting us know. There is nothing
trivial that we can try here. We will investigate further.

**Comment by jaco001** [comment]
Overtraining don't give you more detail just include noise. Experiment and take your best 'sweet spot'.
