### ISSUE TITLE
Fisheye lens support?

### ISSUE THREAD

**Issue by SizheAn** [graphdeco-inria/gaussian-splatting#199]
In readme it says 

> For rasterization, the camera models must be either a SIMPLE_PINHOLE or PINHOLE camera.

I'm wondering if it is possible to support fisheye lens as well. What are the challenges here? Thanks.

**Comment by henrypearce4D** [comment]
"cameras other than pinhole will likely not be supported due to the fact that our code is rasterization based"

https://github.com/graphdeco-inria/gaussian-splatting/issues/7#issuecomment-1634088524

**Comment by Snosixtyboo** [comment]
That's right, supporting cameras with deformation is easy in ray-based methods, not so much with rasterization, so for now this is not planned.
