### ISSUE TITLE
Module install error

### ISSUE THREAD

**Issue by henrypearce4D** [graphdeco-inria/gaussian-splatting#2]
Error running;
`conda env create --file environment.yml`

message;
```
Installing pip dependencies: - Ran pip subprocess with arguments:
['C:\\Users\\admin\\.conda\\envs\\gaussian_splatting\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\gaussian-splatting\\condaenv.5o1tubvd.requirements.txt', '--exists-action=b']
Pip subprocess output:

Pip subprocess error:
ERROR: Directory 'submodules/diff-gaussian-rasterization' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

failed

CondaEnvException: Pip failed
```

Because these modules are not installed I cannot run train.py

```
(gaussian_splatting) C:\gaussian-splatting>python train.py -s C:\gaussian-splatting\data\dozer
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "C:\gaussian-splatting\gaussian_renderer\__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'
```

These folders are empty, should they contain anything.. any suggestions?

**Comment by yzslab** [comment]
Hi, try again after running below commands:
```
git submodule sync --recursive
git submodule update --init --recursive --force
```

**Comment by Snosixtyboo** [comment]
Hi,

did you pull with --recursive? If not, the submodules are missing and could still be added by running "git submodule update --init".

Hth!

**Comment by henrypearce4D** [comment]
Hi both, thanks for the replies

From your recommendation I ran;
`git submodule update --init --recursive --force`

Then installed the modules by;
```
pip install submodules\diff-gaussian-rasterization
pip install submodules\simple-knn
```
And its working
Thanks for the help

**Comment by DrMemoryFish** [comment]
> Hi both, thanks for the replies
> 
> From your recommendation I ran; `git submodule update --init --recursive --force`
> 
> Then installed the modules by;
> 
> ```
> pip install submodules\diff-gaussian-rasterization
> pip install submodules\simple-knn
> ```
> 
> And its working Thanks for the help

i always get

```
(gaussian-splatting) E:\AI\gaussian-splatting>pip install submodules\diff-gaussian-rasterization
Processing e:\ai\gaussian-splatting\submodules\diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff-gaussian-rasterization
  Building wheel for diff-gaussian-rasterization (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\diff_gaussian_rasterization
      copying diff_gaussian_rasterization\__init__.py -> build\lib.win-amd64-cpython-38\diff_gaussian_rasterization
      running build_ext
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects

(gaussian-splatting) E:\AI\gaussian-splatting>pip install submodules\simple-knn
Processing e:\ai\gaussian-splatting\submodules\simple-knn
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: simple-knn
  Building wheel for simple-knn (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      running bdist_wheel
      running build
      running build_ext
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple-knn
  Running setup.py clean for simple-knn
```

**Comment by guoqiZZ** [comment]
> > 大家好，感谢您的回复
> > 根据你的推荐，我跑了；`git submodule update --init --recursive --force`
> > 然后通过以下方式安装模块：
> > ```
> > pip install submodules\diff-gaussian-rasterization
> > pip install submodules\simple-knn
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 它的工作感谢您的帮助
> 
> 我总是得到
> 
> ```
> (gaussian-splatting) E:\AI\gaussian-splatting>pip install submodules\diff-gaussian-rasterization
> Processing e:\ai\gaussian-splatting\submodules\diff-gaussian-rasterization
>   Preparing metadata (setup.py) ... done
> Building wheels for collected packages: diff-gaussian-rasterization
>   Building wheel for diff-gaussian-rasterization (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [9 lines of output]
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build\lib.win-amd64-cpython-38
>       creating build\lib.win-amd64-cpython-38\diff_gaussian_rasterization
>       copying diff_gaussian_rasterization\__init__.py -> build\lib.win-amd64-cpython-38\diff_gaussian_rasterization
>       running build_ext
>       error: [WinError 2] The system cannot find the file specified
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for diff-gaussian-rasterization
>   Running setup.py clean for diff-gaussian-rasterization
> Failed to build diff-gaussian-rasterization
> ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects
> 
> (gaussian-splatting) E:\AI\gaussian-splatting>pip install submodules\simple-knn
> Processing e:\ai\gaussian-splatting\submodules\simple-knn
>   Preparing metadata (setup.py) ... done
> Building wheels for collected packages: simple-knn
>   Building wheel for simple-knn (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [4 lines of output]
>       running bdist_wheel
>       running build
>       running build_ext
>       error: [WinError 2] The system cannot find the file specified
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for simple-knn
>   Running setup.py clean for simple-knn
> ```

请问你是怎么解决这个问题的
