### ISSUE TITLE
Large scenes are unable to achieve the same effects as small scenes.

### ISSUE THREAD

**Issue by xiemeilong** [graphdeco-inria/gaussian-splatting#200]
I tried a scene with around 8000 images, and used a subset of the images to test a small scene. The small scene used default parameters and achieved good results. However, the large scene still had worse results than the small scene after multiple tests. I noticed that during training of the large scene, the points tended to grow larger instead of splitting. I reduced these two parameters （ `--densify_grad_threshold 0.00008  --percent_dense 0.002 `）to get slightly better results.  While also increasing the number of iterations

```
python train.py -s ../data/gs/xingyuanbian --data_device cpu --position_lr_init 0.000024 --position_lr_final 0.0000008  \
 --scaling_lr 0.005     --densify_until_iter 35000 --iterations 50000 --opacity_reset_interval 4000    --densify_grad_threshold 0.00008 \
 --percent_dense 0.002  --position_lr_max_steps 50000 -w  --test_iterations 2500 5500 8500  11000  15000  20000 25000 30000 35000 40000  45000 50000

```
large scene result:
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/2681638/373ec7db-9e7d-4e6f-b0a7-4e99c8f8fdf2)
small scene result:
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/2681638/b724789b-2531-43bd-b49c-c3a990854cab)

**Comment by gradeeterna** [comment]
I'm also wondering if there are any recommended settings for larger scenes. I've tried reducing the parameters from the driving dataset example and the densify settings, but always get similar results to above. 

The background looks good in this scene, but the foliage near the camera is a blur and the output 30K ply is only 600K points which seems low.

<img width="957" alt="Screenshot 2023-09-16 125630" src="https://github.com/graphdeco-inria/gaussian-splatting/assets/127218272/afd1cf1a-598d-44e7-bdd5-f0bb9c9c641c">

**Comment by Snosixtyboo** [comment]
Hi,

unfortunately the method is not created for very large scenes -- that requires different, specialized methods (e.g., NeRF cannot do something like this, but BlockNeRF or BungeeNeRF can). So for now, the best we can suggest is try reduce the position and scaling learning rates.

**Comment by BitCalSaul** [comment]
will a smaller learning rate help? didn't see the connection here, appreciate any hints.
