### ISSUE TITLE
CUDA Compute Capability Error 'Sorry, need at least compute capability 7.0+!'

### ISSUE THREAD

**Issue by radraddles** [graphdeco-inria/gaussian-splatting#206]
I'm guessing this is due to my GPU being an Nvidia 10 series as I have found that the GTX 1080's CUDA compute capability is up to 6.1. I was receiving this error when attempting to run the 'SIBR_gaussianViewer_app.exe' on a 7k iteration model I had just trained, here's the exact error: 

> [SIBR] --  INFOS  --:   Initialization of GLFW
[SIBR] --  INFOS  --:   OpenGL Version: 4.6.0 NVIDIA 537.13[major: 4, minor: 6]
Number of input Images to read: 162
Number of Cameras set up: 162
LOADSFM: Try to open C:\\Users\\maxim\\gaussian-splatting\\data\\room/sparse/0/points3D.bin
Num 3D pts 20633
[SIBR] --  INFOS  --:   SfM Mesh 'C:\\Users\\maxim\\gaussian-splatting\\data\\room/sparse/0/points3d.bin successfully loaded.  (20633) vertices detected. Init GL ...
[SIBR] --  INFOS  --:   Init GL mesh complete
[SIBR] ##  ERROR  ##:   FILE C:\projects\gauss2\SIBR_viewers\src\projects\gaussianviewer\renderer\GaussianView.cpp
                        LINE 339, FUNC sibr::GaussianView::GaussianView
                        Sorry, need at least compute capability 7.0+!
(gaussian_splatting) C:\Users\maxim\gaussian-splatting\viewers\bin>SIBR_gaussianViewer_app.exe -m C:\Users\maxim\gaussian-splatting\output\b208e399-c
[SIBR] --  INFOS  --:   Initialization of GLFW
[SIBR] --  INFOS  --:   OpenGL Version: 4.6.0 NVIDIA 537.13[major: 4, minor: 6]
Number of input Images to read: 162
Number of Cameras set up: 162
LOADSFM: Try to open C:\\Users\\maxim\\gaussian-splatting\\data\\room/sparse/0/points3D.bin
Num 3D pts 20633
[SIBR] --  INFOS  --:   SfM Mesh 'C:\\Users\\maxim\\gaussian-splatting\\data\\room/sparse/0/points3d.bin successfully loaded.  (20633) vertices detected. Init GL ...
[SIBR] --  INFOS  --:   Init GL mesh complete
[SIBR] ##  ERROR  ##:   FILE C:\projects\gauss2\SIBR_viewers\src\projects\gaussianviewer\renderer\GaussianView.cpp
                        LINE 339, FUNC sibr::GaussianView::GaussianView
                        Sorry, need at least compute capability 7.0+!

the file mentioned in 'C:\projects\... does not exist as far as I am aware so I was not able to look at it directly. Not sure if anyone has ran into this or would know any solutions, just bringing up what I ran into. Really excited for this technology! Let me know if you have any recommendations for me, would love to tinker.

**Comment by LZL-CS** [comment]
I encountered the same question, may I know how do you resolve this issue?
