### ISSUE TITLE
The problems in cov3D in forward.cu.

### ISSUE THREAD

**Issue by cjfcsjt** [graphdeco-inria/gaussian-splatting#208]
I found that the _cov3D_ in _forward.cu_ is calculated based on [here:](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/forward.cu#L143)`glm::mat3 Sigma = glm::transpose(M) * M `
where M is defined as`glm::mat3 M = S * R`

 This is not consistent with the equation 6 in the paper (M = R * S). Will this have any impact on the final outcomes?

**Comment by Snosixtyboo** [comment]
No, the order in which matrices are added to the operators is a question of convention, row-major vs column-major and how the operators themselves are defined. The results you get from the code should be correct.
