### ISSUE TITLE
‘0.5 bias’ in 'SH_to_RGB'

### ISSUE THREAD

**Issue by hjr37** [graphdeco-inria/gaussian-splatting#209]
Thank you for your surprising work.
I found that **‘0.5’** was added during the **‘SH_to_RGB’** process, as shown in the following image. In addition, if the RGB value from SH coefficients is not fed into a **Sigmoid activation function**, will this result in a RGB value greater than **'1.0'**, which is unreasonable for the normalized RGB value.
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/116424970/f883cfa7-9eda-4cfa-b1dc-a661e6811c3f)

**Comment by Snosixtyboo** [comment]
Hi,

we have reused the original Plenoxels implementation for computing RGB from spherical harmonics:

https://github.com/sxyu/svox2/blob/ee80e2c4df8f29a407fda5729a494be94ccf9234/svox2/svox2.py#L777

It is true that an activation on the color would be better to avoid situations that you describe, however we found that they rarely occur, if ever, and that quality is better when we avoid additional activations.

Hth, 
Bernhard
