### ISSUE TITLE
Potential bug or corner case in the forward pass (with code that add depth in pull #20, diff-render repo#2)

### ISSUE THREAD

**Issue by ray8828** [graphdeco-inria/gaussian-splatting#211]
Hi, thanks for sharing this great work, I often encounter wired bugs when I try to use the renderer on other applications, here is an example, for some reason, I can only show this crop of the image, but the error block looks like around size 16x16, i'm using the diff-render pull request #2, (pull reqest #20 in this repo) i.e. this https://github.com/JonathonLuiten/diff-gaussian-rasterization repo with minor depth upgrade. Do you have any idea why this could happen? Thanks!!
<img width="29" alt="image" src="https://github.com/graphdeco-inria/gaussian-splatting/assets/26106300/d7840ae2-5c6d-4469-a626-0e5360d65716">

**Comment by Snosixtyboo** [comment]
Hi,

sorry, we can't provide support for code that we did not develop ourselves. The reason why we did not merge the PR in question is that we did not write it and could not thoroughly test it. Best get in touch with the authors of the PR! If you find that you get the same error with the sources from the main branch of THIS repo, then we can try to provide support!

Best,
Bernhard

**Comment by leblond14u** [comment]
Hi @ray8828,

Can you explain how you solved the nan opacity issue ? 

Best regards,

Hugo
