### ISSUE TITLE
Here's a recommendation to greatly enhance the usefulness of Gaussian Splatting

### ISSUE THREAD

**Issue by Aphexus** [graphdeco-inria/gaussian-splatting#213]
You should be able to use AI image generation on the data to paint the scene to make it even more crystal clear and patch up any missing or inaccurate data.

That is, hypothetically you could plug in to something like stable diffusion to fill in missing data in real time or even modify the scene(e.g., say to add missing parts to "randomize" the data or remove things).

That is, using 3D stable diffusion techniques + Gaussian splatting should allow one to generate 3d worlds in much higher detail using 3D image data. These could be used to build game world. This this obviously can't be done in real time but the option then is to use stable diffusion or other AI techniques to fill in missing Gaussian data before hand.

In fact, maybe a hybrid approach could be used where the training is ran on both simultaneously in a parallel solver. E.g., generate Gaussian data that drives the stable diffusion which then drives the Gaussian training that then drives the stable diffusion etc.

Hypothetically you could also use it to build 3d worlds that use the topological aspects captured from the image set but are "painted" differently according to, say, command prompts like chatGPT. 

E.g., rather than having to have to build a 3D world for a game one can simply use such a technique with some text prompts to generate the world.

One could get quite crazy with the idea and use some type of  hierarchy to define regions in the world which drive changes in the world such as a large Gaussian that defines a category that is put in to the chatGPT prompt. The spatial hierarchy drives the categorical information. This allows, for example, one to then make global changes independently of the local changes.

e.g., "Winter" and "Summer" would be two large scale "Gaussians" that drive the environment generated. One could also then "blend" between the two because one would have Gaussian splattings from both sides(the summer and winter) so one could have smooth transitions.

It may be possible, for example, to use AI image generation to increase the resolution(generating splattings) which can then be used to optimize the scenery to reduce the storage requirements further.

At some point one can then use Gaussian Splattering as models themselves in the same vein as assets are used in 3D programs(of course this is already being done but one doesn't have the ability yet to morph those models using something like stable diffusion).

**Comment by Snosixtyboo** [comment]
Great ideas! But is this really an issue?

**Comment by sunshineatnoon** [comment]
@Snosixtyboo I tried a little bit to incorporate 3D Gaussians with SDS, it does not work well compared to implicit representations. It seems it is really hard to move the points around given gradients from the guidance model. Do you have any thoughts on this point?

**Comment by Aphexus** [comment]
> @Snosixtyboo I tried a little bit to incorporate 3D Gaussians with SDS, it does not work well compared to implicit representations. It seems it is really hard to move the points around given gradients from the guidance model. Do you have any thoughts on this point?

There are a few ways to approach it with varying consequences. The most robust idea is to extend/generalize the 2D NN paradigm to 3D but based on GS. E.g., Some approaches to 3D generation exist but are based on meshes. The mesh approach isn't vastly different from GS(they are related in some way as one could transform one in to another). The other approach is to leverage 2D techniques such as SD to try and modify existing GS. Each of these approaches then have various ways to approach the problem.

The minimal work, which would be a "repainting" of GS in a coherent scene is simply modifying the Gaussian colors and not the geometry. This would be, in some sense, analogous to modifying the color map. By doing so one retains the geometry and so has solved half the problem automatically. The idea is to use more advantaged techniques than simply altering the global color map so one can get something that modifies the unessential characteristics to generate new views.

One way to approach this is to either pre-process the image data with AI image generation such as SD and then push them in to the GS decomposition. This is simply doing them independently. All the work here then comes in to trying to make the input images coherent amongst themselves then pushing that in to GS. The problem is that I do not think modern 2D image generation is stable enough to modify an image set that keeps the underlying 3D geometry stable. Of course maybe the errors would ultimate cancel each other out more or less but it also could cause significant degradation of the 3D scene. With real time video and some of the newer techniques of SD it might be possible to essentially "remap" the video in to another video and then run GS on it. This would be the easiest approach but might be the hardest to get right. I have seen people remap video but there are always spatial distortions across temporal changes. This won't work well for GS except that maybe if those changes are effectively noise they might be integrated out in the GS conversion process. If it worked reasonably well this would be the best approach since it would leverage what already exists. This approach could be scene as Video->Remapped Video->GS (vs Video->GS as the standard way).

A similar method would be to link the two methods above in some way. In this cause the video and the GS training are interleaved with the image generation. Effectively what one would do is create the GS scene then render images and convert those images to new images that are shoved back in to the GS scene. This approach would be Video->GS->Video->Remapped Video->GS->....
The issue with this approach is how to break down the scene(3D->2D) in such a way to get something that can be done practically and still retains spatial coherence. I think one can use the 3D nature of the GS scenery mask out parts of the scene(e.g., to work locally on parts that are close) and maybe with some effort one can get something that is consistent. E.g., for different viewing angles such as from the front and back one would have to have coherence. Maybe with some special techniques one could get something that makes sense. By making sure the geometry is consistently the same will go a long way for it being acceptable. The way I think this would have to be handled is by effectively partitioning the GS scene so that there is some sense of locality and this would be translated in to only local distortions.


The other approach is to essentially build an entire 3D AI system around GS that includes object classification training(e.g., using YOLO for each frame in the video and create some type of spatial coherence classification structure(to say that "this is a car" from all the various 3D positions in the scene). From there one then has to brain a NN on such scenes with their classifications building up a large library to possibilities in the NN which can then be leveraged with something like SD techniques. This is the largest undertaking and effectively is just remapping much of what has been done for images(effectively XYRGB with XY implicit) to GS(effectively XYZRGBMN with the position XYZ being explicit).

But from that the entire theory of AI on images can be transported in to generating GS's with classification generation. E.g., a prompt that can us features from all that the NN was programmed on. From that one can only generate Of course the AI will only generate based on what it was trained so if one wanted some type of artificial worlds it would likely require training it on video of those worlds such video easily exists as most 3D games could be leveraged for such things. Of course such a project would be years of work and probably require an order of magnitude more computation. This ultimately allow quite robust scene generation and with SD and other techniques one would have more control over generating novel and sensible scenes.

**Comment by Snosixtyboo** [comment]
Very interesting discussion! I hope there was some interesting exchange and creative ideas between the participants! I'm gonna close it as an issue at this point :)
