### ISSUE TITLE
Is there a way to just visualize the saved .ply?

### ISSUE THREAD

**Issue by ray8828** [graphdeco-inria/gaussian-splatting#214]
Thanks for sharing this great work! I'm wondering if is there a way to just visualize the saved .ply model? Thanks!

**Comment by lyd405121** [comment]
This maybe what you looking for:
https://github.com/antimatter15/splat

**Comment by Snosixtyboo** [comment]
Hi,

yes, you can load it into e.g. MeshLab. You simply won't see colors, since they are stored in a view-dependent format (they would need to change depending on viewing direction), which 3D editing tools don't usually support.
