### ISSUE TITLE
SIBR Viewer Runtime Error

### ISSUE THREAD

**Issue by db-githb** [graphdeco-inria/gaussian-splatting#220]
When I run the command ./\<SIBR install dir\>/bin/SIBR_gaussianViewer_app -m <path to trained model> from the location <SIBR install dir>/bin the following error occurs:

symbol lookup error: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_log_set_debug_enabled

Any suggestions on how to resolve this?

**Comment by db-githb** [comment]
there was a conflict in the libglib in the anaconda3/lib folder and the installed version under lib/x86_64-linux-gnu/libglib-2.0.so.  The build was using the anaconda3/lib version which did not have the function g_log_set_debug_enabled. 

My quick hack solution was to replace the anaconda3/lib version with the version from lib/x86_64-linux-gnu/libglib-2.0.so via copy+paste.

**Comment by db-githb** [comment]
there was a conflict in the libglib in the anaconda3/lib folder and the installed version under lib/x86_64-linux-gnu/libglib-2.0.so. The build was using the anaconda3/lib version which did not have the function g_log_set_debug_enabled.

My quick hack solution was to replace the anaconda3/lib version with the version from lib/x86_64-linux-gnu/libglib-2.0.so via copy+paste.

**Comment by leblond14u** [comment]
Also possible to use the `https://github.com/graphdeco-inria/gaussian-splatting/issues/152#issuecomment-1726202599` method changing the soft link from conda to linux.
