### ISSUE TITLE
Splatting sequential data

### ISSUE THREAD

**Issue by VladimirYugay** [graphdeco-inria/gaussian-splatting#224]
Do you think splatting will work well with sequential data? If not, what adjustments do you think should be added to that? 

When the new parts of the scene are revealed over time, it will be problematic to initialize those new Gaussians and optimize them without spoiling the old frames. At the same time, optimizing all the previous frames with the current one might become infeasible.

**Comment by Snosixtyboo** [comment]
It might work, but as you mention, there are a lot of things to figure out here: you need to be 100% in control of the state of the optimizer for individual Gaussians, and the system as a whole needs to progress in a way that makes sense. It's a complex topic for sure, and unfortunately, we have no concrete advice for you right now.

**Comment by hariharan1412** [comment]
> Do you think splatting will work well with sequential data? If not, what adjustments do you think should be added to that?
> 
> When the new parts of the scene are revealed over time, it will be problematic to initialize those new Gaussians and optimize them without spoiling the old frames. At the same time, optimizing all the previous frames with the current one might become infeasible.

By any chance, have you experimented with this? If yes, could you please share your experience?

**Comment by VladimirYugay** [comment]
@hariharan1412 you can check our [paper](https://vladimiryugay.github.io/gaussian_slam/index.html) on this, we deal with exactly that problem.

**Comment by hariharan1412** [comment]
> @hariharan1412 you can check our [paper](https://vladimiryugay.github.io/gaussian_slam/index.html) on this, we deal with exactly that problem.

Haha, what a coincidence! I'm currently reading your paper only. Thank you, man. 
but I feel it is very hard to work with my custom dataset. Do I have to get the SLAM model also?

**Comment by VladimirYugay** [comment]
Nice! Yeah, our method needs to be tuned on a specific dataset aggressively... What do you mean under getting the SLAM model?
