### ISSUE TITLE
About the instant-ngp version

### ISSUE THREAD

**Issue by tangyubbb** [graphdeco-inria/gaussian-splatting#228]
Hello, thanks for your great work! And I have a question about the instant-ngp in your paper, since I have use the program of ngp from https://github.com/NVlabs/instant-ngp and I find that it would finish training in less than 3 mins while in your paper the ngp models took more than 6 mins to complete it.

**Comment by Snosixtyboo** [comment]
Hi,

we tried both the default and the "big" configuration with instant ngp. Afaik, we used a version that was pulled sometime last October/November. What config files are you using to launch the scenes in instant ngp? We used custom ```transforms.json``` where we followed the advice of the original authors and set the AABB size to 64. Also, we ran on an A6000: it is certain that performance will vary across different GPU models. 

Hth,
Bernhard



Hth,
Bernhard
