### ISSUE TITLE
Can this be exported or imported to blender?

### ISSUE THREAD

**Issue by CGMikeG** [graphdeco-inria/gaussian-splatting#233]
Sorry I don't where to ask so I will just ask here. Does anybody know if its possible to import this to blender.

**Comment by eivillamuelas** [comment]
I was looking too, and I couldn't find any, but I think there are people working on it

**Comment by codexq123** [comment]
any update please

**Comment by Snosixtyboo** [comment]
Hi,

Blender or Meshlab should happily import the output .ply files and display the position, but not correctly rendering. They can't really, because the rendering pipeline is special to our method.
