### ISSUE TITLE
RuntimeError: numel: integer multiplication overflow

### ISSUE THREAD

**Issue by HrsPythonix** [graphdeco-inria/gaussian-splatting#24]
During Training
```
anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 78, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
RuntimeError: numel: integer multiplication overflow
Training progress:  18%|██████████                                              | 17940/100000 [1:36:57<7:23:31,  3.08it/s, Loss=0.0742834]
```
Any idea how to solve this?

**Comment by HrsPythonix** [comment]
> Would it be possible to provide the dataset that causes this? Could you also tell us
> 
> * the commit you are on
> * number of images, resolution of the images
> * flags you use to run it?

I use 

```
python train.py -s ../gs_dataset/livingroom_ip12_600/ -m ./output/gs_dataset/livingroom_ip12_600_10w/ --port 6008 --eval --resolution 1 --iterations 100000 --position_lr_max_steps 100000 --densify_until_iter 50000 --test_iterations 7000 30000 50000 80000 100000 --save_iterations 7000 30000 50000 80000 100000 --data_device cpu --scaling_lr 0.001 --position_lr_final 0.0000016
```

to train on 600 1920*1080 images using my forked repo https://github.com/HrsPythonix/gaussian-splatting/tree/dev.  

I will first update to mote recent commit and try again

**Comment by Snosixtyboo** [comment]
The fact that it occurs after 90 minutes makes this quite expensive to debug. My plan is to add functionality today that automatically dumps the state when a runtime error is hit. I'll see if I can do this quickly and then let you know, then we could look at the dumped state on our side.

**Comment by Snosixtyboo** [comment]
Hi,

I've added experimental state dumping functionality. You should get it via
```
pip uninstall diff-gaussian-rasterization
cd <gaussian-splatting>/submodules/diff-gaussian-rasterization
git pull
git checkout debug
python setup.py install
```

Then, if the training crashes at some point, it should write BIG state file (>1GB). If this can then be uploaded somewhere and you think it's worth it, we will gladly take a look at it. If this is too bulky, we could think about other ways of finding the bug...

**Comment by GrayMask** [comment]
Hi,
I am also facing the same issue.

```
Something has gone wrong! Inputs to reproduce error have been dumped in 'crash_fw.dump'
Traceback (most recent call last):
  File "/mnt/nfs-mnj-hot-02/tmp/chunyuli/exhibition2022_backup/code/gaussian-splatting/train.py", line 204, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations)
  File "/mnt/nfs-mnj-hot-02/tmp/chunyuli/exhibition2022_backup/code/gaussian-splatting/train.py", line 75, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "/mnt/nfs-mnj-hot-02/tmp/chunyuli/exhibition2022_backup/code/gaussian-splatting/gaussian_renderer/__init__.py", line 84, in render
    rendered_image, radii = rasterizer(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chunyuli/.local/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 198, in forward
    return rasterize_gaussians(
  File "/home/chunyuli/.local/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 29, in rasterize_gaussians
    return _RasterizeGaussians.apply(
  File "/home/chunyuli/.local/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 85, in forward
    raise ex
  File "/home/chunyuli/.local/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 80, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
RuntimeError: numel: integer multiplication overflow
Training progress:  39%|██████████████████████████████████████████████████▊                                                                              | 11810/30000 [53:08<1:21:50,  3.70it/s, Loss=0.0516023]
```

I am training a scene with 254 4K images using:
```
python train.py -s <path> -r 1
```
I use the latest main branch https://github.com/graphdeco-inria/gaussian-splatting/commit/017da305b1ff9c427b617d65c8c83cfb71a41324

Os and environment:
```
os: Ubuntu 22.04.2 LTS
python: 3.10.6
torch: 1.13.1+cu117
torchaudio: 0.13.1+cu117
torchvision: 0.14.1+cu117
```

And I uploaded the `crash_fw.dump` here: https://drive.google.com/file/d/1szqZ6vp9L7u4DLcs_aZHTi7r6zct6ydx/view

**Comment by GrayMask** [comment]
Hi,
I am also facing the same issue.

```
Something has gone wrong! Inputs to reproduce error have been dumped in 'crash_fw.dump'
Traceback (most recent call last):
...
  File "/home/chunyuli/.local/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 80, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
RuntimeError: numel: integer multiplication overflow
Training progress:  39%|██████████████████████████████████████████████████▊                                                                              | 11810/30000 [53:08<1:21:50,  3.70it/s, Loss=0.0516023]
```

I am training a scene with 254 4K images using:
```
python train.py -s <path> -r 1
```
I use the latest main branch https://github.com/graphdeco-inria/gaussian-splatting/commit/017da305b1ff9c427b617d65c8c83cfb71a41324

Os and environment:
```
os: Ubuntu 22.04.2 LTS
python: 3.10.6
torch: 1.13.1+cu117
torchaudio: 0.13.1+cu117
torchvision: 0.14.1+cu117
```

And I uploaded the `crash_fw.dump` here: https://drive.google.com/file/d/1szqZ6vp9L7u4DLcs_aZHTi7r6zct6ydx/view

**Comment by Snosixtyboo** [comment]
> Hi, I am also facing the same issue.
> 
> ```
> Something has gone wrong! Inputs to reproduce error have been dumped in 'crash_fw.dump'
> Traceback (most recent call last):
> ...
>   File "/home/chunyuli/.local/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 80, in forward
>     num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
> RuntimeError: numel: integer multiplication overflow
> Training progress:  39%|██████████████████████████████████████████████████▊                                                                              | 11810/30000 [53:08<1:21:50,  3.70it/s, Loss=0.0516023]
> ```
> 
> I am training a scene with 254 4K images using:
> 
> ```
> python train.py -s <path> -r 1
> ```
> 
> I use the latest main branch [017da30](https://github.com/graphdeco-inria/gaussian-splatting/commit/017da305b1ff9c427b617d65c8c83cfb71a41324)
> 
> Os and environment:
> 
> ```
> os: Ubuntu 22.04.2 LTS
> python: 3.10.6
> torch: 1.13.1+cu117
> torchaudio: 0.13.1+cu117
> torchvision: 0.14.1+cu117
> ```
> 
> And I uploaded the `crash_fw.dump` here: https://drive.google.com/file/d/1szqZ6vp9L7u4DLcs_aZHTi7r6zct6ydx/view

Hi @GrayMask thanks a lot for providing this! I think was able to squash the bug. The dump you sent me works for me now, but it allocates 2GB of VRAM. I should note that the resolution of the images is comparably high. As stated in the documentation, we did most of our testing around 1.6k resolution. With larger images and if you force -r 1, memory consumption can increase a lot. But there is a good chance we can do something about this soon.

To get the fix, you will need to
```
git pull
git submodule update
cd submodules/diff-gaussian-rasterization
python setup.py install
```

Let me know if that works for you!

**Comment by GrayMask** [comment]
Hi, thank you for your prompt response!
It is working after updating `submodules/diff-gaussian-rasterization`.
Thanks for your help!

**Comment by vvuonghn** [comment]
Hello @Snosixtyboo  @GrayMask 

I still have this problem on my side. I tried updating the submodule `submodules/diff-gaussian-rasterization` and re-installing this module. I am working with an image of 1728 × 1152 pixels, and my GPU is a 4090 Ti with 24GB of VRAM.

Case 1: ```python train.py -s data_train -r 1```
```
RuntimeError: CUDA out of memory. Tried to allocate 35.53 GiB (GPU 0; 23.64 GiB total capacity; 16.81 GiB already allocated; 4.44 GiB free; 17.73 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Training progress:   0%|                                           | 0/30000 [00:00<?, ?it/s]
```

Case 2 ```python train.py -s data_train -r 512```
```
(gaussian_splatting) vuonghn@ubuntu:~/research/code/3DV/gaussian-splatting$ python train.py -s /home/vuonghn/research/dataset/3d/data_train -r 512
Optimizing 
Output folder: ./output/380ada20-e [10/09 16:24:11]
Tensorboard not available: not logging progress [10/09 16:24:11]
Reading camera 749/749 [10/09 16:24:11]
Loading Training Cameras [10/09 16:24:11]
Loading Test Cameras [10/09 16:24:25]
Number of points at initialisation :  66290 [10/09 16:24:25]
Training progress:   2%|▎               | 590/30000 [00:00<00:37, 785.01it/s, Loss=0.9339148]Traceback (most recent call last):
  File "/home/vuonghn/research/code/3DV/gaussian-splatting/train.py", line 219, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/home/vuonghn/research/code/3DV/gaussian-splatting/train.py", line 86, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg)
  File "/home/vuonghn/research/code/3DV/gaussian-splatting/gaussian_renderer/__init__.py", line 85, in render
    rendered_image, radii = rasterizer(
  File "/home/vuonghn/Applications/anaconda3/envs/gaussian_splatting/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/vuonghn/Applications/anaconda3/envs/gaussian_splatting/lib/python3.9/site-packages/diff_gaussian_rasterization-0.0.0-py3.9-linux-x86_64.egg/diff_gaussian_rasterization/__init__.py", line 210, in forward
    return rasterize_gaussians(
  File "/home/vuonghn/Applications/anaconda3/envs/gaussian_splatting/lib/python3.9/site-packages/diff_gaussian_rasterization-0.0.0-py3.9-linux-x86_64.egg/diff_gaussian_rasterization/__init__.py", line 32, in rasterize_gaussians
    return _RasterizeGaussians.apply(
  File "/home/vuonghn/Applications/anaconda3/envs/gaussian_splatting/lib/python3.9/site-packages/diff_gaussian_rasterization-0.0.0-py3.9-linux-x86_64.egg/diff_gaussian_rasterization/__init__.py", line 92, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
RuntimeError: numel: integer multiplication overflow
Training progress:   2%|▎               | 600/30000 [00:00<00:38, 760.56it/s, Loss=0.9339148]
```

I assume that if the image size is large, I should set the input resolution to -r 512. It should work.

**Comment by Langwenchong** [comment]
@vvuonghn  hi,have you solved this problem?

**Comment by flow-specter** [comment]
I have same problem on 4090
