### ISSUE TITLE
Multiple GPUs not possible during training process. 

### ISSUE THREAD

**Issue by lumigrade** [graphdeco-inria/gaussian-splatting#241]
Hello,

I got a RTX 4090 and RTX 3090 on my system and during the training process, only the 4090 got fully occupied. Is there any way to activate all available GPUs to jump into this training part?

Thanks,

**Comment by Snosixtyboo** [comment]
Hi,

not easily. It would require to apply your own coding skills and keeping track of you can split data and combine gradients for optimization. This is not currently supported, sorry.
