### ISSUE TITLE
Question on using video as training data

### ISSUE THREAD

**Issue by victorhuzhening** [graphdeco-inria/gaussian-splatting#248]
Hi, I have a question about model training. Is it possible to use a video for training data? If we redirect train.py to use a .mp4 file, and specify the kind of camera, would the model work? If that doesn't work, could we somehow partition the video a sequence of images, and use that for training?

**Comment by jaco001** [comment]
'Normaly' you use command from  FFMPEG Command to extract images from video: 
FFMPEG -i {path to video} -qscale:v 1 -qmin 1 -vf fps={frame extraction rate} %04d.jpg

Select frames (remove blurred, shaked etc). 50-150 is enough. After 500 you just run out of VRAM and things can take days if you lucky. 
But feel free to do it as you like. 
CONS:  
- blurry images
- many images
- very few videos are made for photometry in the mind... so you end usually with one side of object.
PROS:
- many images
