### ISSUE TITLE
How to train from last checkpoint (continue to train) ?

### ISSUE THREAD

**Issue by XinyueZ** [graphdeco-inria/gaussian-splatting#250]

**Comment by XinyueZ** [comment]
ok, just for confirm, will it train from the latest checkpoint **plus**  the value assigned to `--iterations` , right?

**Comment by Snosixtyboo** [comment]
No, the checkpoint stores at which iteration you quit. ```--iterations``` is the total number of iterations to train for. So expected behavior, if you make a checkpoint at 15k, is that it trains for another 15k after restoring.

**Comment by XinyueZ** [comment]
@Snosixtyboo sorry, I dont understand what you mean 😢

**Comment by Snosixtyboo** [comment]
if you make a checkpoint at 15k and launch again with iterations ```--iterations``` (default is 30k), then it will train from the checkpoint for 15k more iterations, not 30k.

**Comment by XinyueZ** [comment]
thanks, much helpful

**Comment by tapowanliwuyun** [comment]
Thank you very much for your questions and responses. I have one more question to ask you: where should the parameters following 'start_checkpoint' point to, and which file in which path should they refer to?
