### ISSUE TITLE
COLMAP.exe error - Missing DLLs when running python convert.py

### ISSUE THREAD

**Issue by trevorroth** [graphdeco-inria/gaussian-splatting#251]
I was following along with Jonathan Stephens tutorial, but when I enter the command:

python convert.py -s <location>
(with location pointing to my dataset of images)

... I get a colmap.exe error stating "The code execution cannot proceed because glew32.dll was not found.  Reinstalling the program may fix this problem."  Followed by another couple errors with other DLLs.

I suspected this may have something to do with setting environment paths, as I see both of those DLLs in the Colmap/lib folder.  But my path seems to be set to the proper top level COLMAP folder.

Any ideas?

**Comment by Snosixtyboo** [comment]
Hi,

try making sure to point the colmap executable param to the ```.bat``` file, not the ```.exe```

**Comment by trevorroth** [comment]
Yep... path environment variable is pointing towards:
C:\Users\myname\COLMAP

And in that folder is the .bat and two subfolders "bin" and "lib"

I can run the .bat from the folder with no error.  Strange.

**Comment by Snosixtyboo** [comment]
Hi,

try to set the colmap executable param to the ```.bat``` file itself. Including the ```.bat```

**Comment by trevorroth** [comment]
So was trying to figure out why it wasn't respecting the environment variables, ended opening up Anaconda Navigator with "Run as Administrator", used the terminal in the gaussian_splatting environment there... and lo and behold, it worked.  

Seems like it was a "Run As Administrator" issue.  Dumb problem, easy fix.  I'll leave this post up just in case others have the issue too if they're working on a company-managed PC.
