### ISSUE TITLE
V-sync for remote viewer

### ISSUE THREAD

**Issue by RohanChacko** [graphdeco-inria/gaussian-splatting#254]
Hi, 

Why does turning off V-Sync have a dramatic effect on fps for the **remote** viewer? I would expect the training to get slower because of the higher fps and hence more compute consumed for rendering. But from my expts, it seems like the training speed remains unaffected.

**Comment by Snosixtyboo** [comment]
Hi,

the remote viewer piggy-backs on the training loop: in every iteration, it may create one additional rendering for the remote viewer. So either you generate 1 rendering (for training) or 2 in the same iteration. It's not asynchronously rendering to provide images to the remote viewer :)
