### ISSUE TITLE
how to reduce floating foggy artifact?

### ISSUE THREAD

**Issue by HrsPythonix** [graphdeco-inria/gaussian-splatting#26]
Can observe many floating foggy artifact training my data with default param, any idea how to reduce them?

![floating](https://github.com/graphdeco-inria/gaussian-splatting/assets/16586180/8fa3dd2c-5d6d-44ed-8019-e934bc875f8f)

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/16586180/a52354fd-4c08-4367-9be3-b62ab9d10ff4)

**Comment by Snosixtyboo** [comment]
You could try running with --white_background and reducing --opacity_reset_interval from 3000 to maybe 1000 or even lower. It would be interesting to see what you can get, but in general, this is what the codebase will produce with the given data. There's several methods to combat floaters out there, but they would require adding functionality and extend the method. Implementing one of the methods for floater removal is interesting, but we can't promise we will have time to do it.

**Comment by Snosixtyboo** [comment]
> You could try running with --white_background and reducing --opacity_reset_interval from 3000 to maybe 1000 or even lower. It would be interesting to see what you can get, but in general, this is what the codebase will produce with the given data. There's several methods to combat floaters out there, but they would require adding functionality and extend the method. Implementing one of the methods for floater removal is interesting, but we can't promise we will have time to do it.

Oh one more thing: I'm about to push a new version of the training script, it might be a good idea to wait for that, should be there in 5 minutes :)
