### ISSUE TITLE
config_args

### ISSUE THREAD

**Issue by fountainbird** [graphdeco-inria/gaussian-splatting#260]
THANK YOU! Got it up and running yesterday. I was able to run the viewer once. I came back this morning to try again but getting an error complaining about a config file. Haven't changed anything since yesterday. Any insight?:
 [SIBR] --  INFOS  --:   Initialization of GLFW
[SIBR] --  INFOS  --:   OpenGL Version: 4.6.0 NVIDIA 536.99[major: 4, minor: 6]
[SIBR] ##  ERROR  ##:   FILE C:\projects\gauss2\SIBR_viewers\src\projects\gaussianviewer\apps\gaussianViewer\main.cpp
                        LINE 140, FUNC main
                        Could not find config file 'cfg_args'

**Comment by mgalvi** [comment]
Nevermind. I just restarted my Anaconda Prompt, activated gaussian-splatting and tried again and it worked just fine

**Comment by fountainbird** [comment]
> Nevermind. I just restarted my Anaconda Prompt, activated gaussian-splatting and tried again and it worked just fine

Glad you got it sorted @mgalvi . My issue was that I was pointing to a wrong output dir.

**Comment by softyoda** [comment]
I have the same issue on some dataset (for example when I train with more images/resolution/iterations).
I have the right environment setup.

Any idea why sometime the file cfg_args isn't recognized by the viewer?
