### ISSUE TITLE
Can I train it with dense model?

### ISSUE THREAD

**Issue by acsgn95** [graphdeco-inria/gaussian-splatting#264]
I used COLMAP and I can take dense model from it. Also, I want to ask that can I train it with dense model?

Thanks in advance...

**Comment by grgkopanas** [comment]
As long as you change the code to load the dense point cloud you should be
fine.

**Comment by acsgn95** [comment]
So, there is no way use of dense currently? I will make a branch and change

**Comment by acsgn95** [comment]
@grgkopanas do you have any suggestion about how can I do this? Because, dense model output and sparse model output are so different!

Thanks in advance!
