### ISSUE TITLE
submodule simple-knn no longer valid

### ISSUE THREAD

**Issue by xnpeter** [graphdeco-inria/gaussian-splatting#265]
the link to simple-knn is no longer valid:https://github.com/graphdeco-inria/gaussian-splatting/blob/main/submodules/simple-knn
I don't know why, but I found this one as a substitute:https://github.com/camenduru/simple-knn

**Comment by kangpeilun** [comment]
you are really a good gay!

**Comment by Snosixtyboo** [comment]
That's not exactly accurate. The link you provided is not entered in the repository: this is just github.com's interpretation of the submodule link, which is wrong. It is a gitlab submodule. If you check out the repository with submodules (e.g., using --recursive), it should fetch it from the correct loaction.

**Comment by back2yes** [comment]
the `knn` module is on gitlab: https://gitlab.inria.fr/bkerbl/simple-knn

just check the [gaussian-splatting](https://github.com/graphdeco-inria/gaussian-splatting/tree/main)
/.gitmodules file
