### ISSUE TITLE
SBR Viewer not Open in Linux

### ISSUE THREAD

**Issue by thiagoholder** [graphdeco-inria/gaussian-splatting#267]
[SIBR] --  INFOS  --:   Initialization of GLFW
[SIBR] ##  ERROR  ##:   FILE /root/gaussian-splatting/SIBR_viewers/src/core/graphics/Window.cpp
                        LINE 30, FUNC glfwErrorCallback
                        GLX: Failed to create context: GLXBadFBConfig
terminate called after throwing an instance of 'std::runtime_error'
  what():  See log for message errors
  
  I connect with X11 server.

**Comment by Snosixtyboo** [comment]
Hi,

via X server, you might face problems with using Native OpenGL 4.3, which we require. You may want to consider using MESA and simulating a GPU with its software interface.

**Comment by maxLWS** [comment]
> [SIBR] -- INFOS --: Initialization of GLFW [SIBR] ## ERROR ##: FILE /root/gaussian-splatting/SIBR_viewers/src/core/graphics/Window.cpp LINE 30, FUNC glfwErrorCallback GLX: Failed to create context: GLXBadFBConfig terminate called after throwing an instance of 'std::runtime_error' what(): See log for message errors
> 
> I connect with X11 server.

Hi, 

I have the same problem. Have you solved it?

**Comment by pooncs** [comment]
For me it was the opengl compatibility profile being a lower version than 4.5
You can check it with
`glxinfo | grep -e "OpenGL version" -e "Core" -e "Compatible"`
I had to update my drivers with the lastest mesa drivers from another apt-repo
`sudo add-apt-repository ppa:oibaf/graphics-drivers
sudo apt update
sudo apt upgrade`

That worked for me.

**Comment by xiazhi1** [comment]
> sudo add-apt-repository ppa:oibaf/graphics-drivers

Same Bug for me? Have you solved it?my OpenGL is 4.5,and test in Ubuntu22.04 @maxLWS @thiagoholder

**Comment by xqdrone** [comment]
Same problem with OpenGL 4.5 and in Ubuntu 20.04.

**Comment by APPZ99** [comment]
> Run "glxinfo| grep OpenGL" command to view OpenGL information on the ubuntu system, if you see that the field of ' OpenGL core profile version string' = 4.5, you can try to add "MESA_GL_VERSION_OVERRIDE=4.5 " before ".//bin/SIBR_remoteGaussian_app". That's useful for me.

Many thanks! That works for me! @ZhouWeikun

**Comment by ERGOWHO** [comment]
> Run "glxinfo| grep OpenGL" command to view OpenGL information on the ubuntu system, if you see that the field of ' OpenGL core profile version string' = 4.5, you can try to add "MESA_GL_VERSION_OVERRIDE=4.5 " before ".//bin/SIBR_remoteGaussian_app". That's useful for me.

Works for me too on Ubuntu 20.04 server. Thanks!

**Comment by lzlcs** [comment]
> For me it seemed to be the opengl compatibility profile being a lower version than 4.5 You can check it with `glxinfo | grep -e "OpenGL version" -e "Core" -e "Compatible"`
> 
> I had to update my drivers with the latest mesa drivers from another apt-repo `sudo add-apt-repository ppa:oibaf/graphics-drivers` `sudo apt update` `sudo apt upgrade`
> 
> That worked for me.

Thanks! That works.

**Comment by oym050922021** [comment]
> Run "glxinfo| grep OpenGL" command to view OpenGL information on the ubuntu system, if you see that the field of ' OpenGL core profile version string' = 4.5, you can try to add "MESA_GL_VERSION_OVERRIDE=4.5 " before ".//bin/SIBR_remoteGaussian_app". That's useful for me.

The method still doesn't work as expected. What could be the reason for this? Thank you!
my error is as follows.
(gaussian_splatting) root@VM-0-13-ubuntu:/home/ubuntu/projects/gaussian-splatting/SIBR_viewers/install/bin# MESA_GL_VERSION_OVERRIDE=4.5 ./SIBR_gaussianViewer_app -m /home/ubuntu/projects/gaussian-splatting/output/c3801597-8/point_cloud/iteration_7000
[SIBR] --  INFOS  --:   Initialization of GLFW
[SIBR] ##  ERROR  ##:   FILE /home/ubuntu/projects/gaussian-splatting/SIBR_viewers/src/core/graphics/Window.cpp
                        LINE 30, FUNC glfwErrorCallback
                        X11: The DISPLAY environment variable is missing
terminate called after throwing an instance of 'std::runtime_error'
  what():  See log for message errors
Aborted (core dumped)

**####opengl information#####**
(gaussian_splatting) root@VM-0-13-ubuntu:/home/ubuntu/projects/gaussian-splatting/SIBR_viewers/install/bin# DISPLAY=:0 glxinfo | grep "OpenGL"
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 12.0.0, 256 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.2.6
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 21.2.6
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

**Comment by zheweijushi** [comment]
1.check the gpu driver in docker
    ldconfig -p | grep libEGL_nvidia
2.if you don't find anything, the docker's driver is not configured properly
you can use this command in host
    docker run --gpus 'all,"capabilities=compute,utility,graphics"' ...
3.then use this command to check 
    ldconfig -p | grep libEGL_nvidia
 and you can find this
![2024-03-01_14-56](https://github.com/graphdeco-inria/gaussian-splatting/assets/148083539/2824a297-e4d3-47c9-96b8-f5552a9a8094)
   if not, the host' gpu driver need install with opengl
4.then, you can check docker in this commond
    glxinfo | grep OpenGL

![2024-03-01_14-58](https://github.com/graphdeco-inria/gaussian-splatting/assets/148083539/9ce8a659-d4f7-4ff8-82e3-271d0d098598)

**Comment by leoShen917** [comment]
> > Run "glxinfo| grep OpenGL" command to view OpenGL information on the ubuntu system, if you see that the field of ' OpenGL core profile version string' = 4.5, you can try to add "MESA_GL_VERSION_OVERRIDE=4.5 " before ".//bin/SIBR_remoteGaussian_app". That's useful for me.
> 
> The method still doesn't work as expected. What could be the reason for this? Thank you! my error is as follows. (gaussian_splatting) root@VM-0-13-ubuntu:/home/ubuntu/projects/gaussian-splatting/SIBR_viewers/install/bin# MESA_GL_VERSION_OVERRIDE=4.5 ./SIBR_gaussianViewer_app -m /home/ubuntu/projects/gaussian-splatting/output/c3801597-8/point_cloud/iteration_7000 [SIBR] -- INFOS --: Initialization of GLFW [SIBR] ## ERROR ##: FILE /home/ubuntu/projects/gaussian-splatting/SIBR_viewers/src/core/graphics/Window.cpp LINE 30, FUNC glfwErrorCallback X11: The DISPLAY environment variable is missing terminate called after throwing an instance of 'std::runtime_error' what(): See log for message errors Aborted (core dumped)
> 
> **####opengl information#####** (gaussian_splatting) root@VM-0-13-ubuntu:/home/ubuntu/projects/gaussian-splatting/SIBR_viewers/install/bin# DISPLAY=:0 glxinfo | grep "OpenGL" OpenGL vendor string: Mesa/X.org OpenGL renderer string: llvmpipe (LLVM 12.0.0, 256 bits) OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.2.6 OpenGL core profile shading language version string: 4.50 OpenGL core profile context flags: (none) OpenGL core profile profile mask: core profile OpenGL core profile extensions: OpenGL version string: 3.1 Mesa 21.2.6 OpenGL shading language version string: 1.40 OpenGL context flags: (none) OpenGL extensions: OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.2.6 OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20 OpenGL ES profile extensions:

Hi, @oym050922021, could you please tell me if you've solved this problem, I'm experiencing the same thing as you are.

**Comment by ZhenWusi** [comment]
> Hi,
> 
> I have the same problem. Have you solved it?

Hi,

I have the same problem. Have you solved it?

**Comment by whu-lyh** [comment]
try to add '--gpus 'all,"capabilities=compute,utility,graphics"' --privileged=true -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY' when you generate a container by docker images

**Comment by tapowanliwuyun** [comment]
> Run "glxinfo| grep OpenGL" command to view OpenGL information on the ubuntu system, if you see that the field of ' OpenGL core profile version string' = 4.5, you can try to add "MESA_GL_VERSION_OVERRIDE=4.5 " before ".//bin/SIBR_remoteGaussian_app". That's useful for me.在ubuntu系统上运行“glxinfo| grep OpenGL”命令查看OpenGL信息，如果看到‘OpenGL core profile version string’字段=4.5，可以尝试在“.//bin”前添加“MESA_GL_VERSION_OVERRIDE=4.5” /SIBR_remoteGaussian_app”。这对我很有用。

Many thanks! That works for me!

**Comment by haaaappy** [comment]
> When I use docker to implement gaussian-splatting, I have same problems.
> 
> I have solved it :
> 
> 1.check the gpu driver in docker ldconfig -p | grep libEGL_nvidia 2.if you don't find anything, the docker's driver is not configured properly you can use this command in host docker run --gpus 'all,"capabilities=compute,utility,graphics"' ... 3.then use this command to check ldconfig -p | grep libEGL_nvidia and you can find this ![2024-03-01_14-56](https://private-user-images.githubusercontent.com/148083539/309173986-2824a297-e4d3-47c9-96b8-f5552a9a8094.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0OTUwMTUsIm5iZiI6MTczNjQ5NDcxNSwicGF0aCI6Ii8xNDgwODM1MzkvMzA5MTczOTg2LTI4MjRhMjk3LWU0ZDMtNDdjOS05NmI4LWY1NTUyYTlhODA5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExMFQwNzM4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjM0OWI3M2U3OTQ5YTEwYTU0ZWMyZGIzNDg4MGM2ZTE3MTQ4ZjVhYjc3YTNkYjU3MzhmMWUxODU4YmM3YjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AcMHwhiOBN3HuQG7b7tClH1OF_42Ny2bB-80mUAqI_M) if not, the host' gpu driver need install with opengl 4.then, you can check docker in this commond glxinfo | grep OpenGL
> 
> ![2024-03-01_14-58](https://private-user-images.githubusercontent.com/148083539/309174464-9ce8a659-d4f7-4ff8-82e3-271d0d098598.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0OTUwMTUsIm5iZiI6MTczNjQ5NDcxNSwicGF0aCI6Ii8xNDgwODM1MzkvMzA5MTc0NDY0LTljZThhNjU5LWQ0ZjctNGZmOC04MmUzLTI3MWQwZDA5ODU5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExMFQwNzM4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODAxNGU0NmUyODRiMjBkM2ExYjFiZDc2NmE1YTZjODRkN2E3YTIyMzIzOTZjODE5YzcwZmY5Mjc5NjMzNDcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7uq7FF2DXmbjY3rjaHo6qp1t40_GCUYBm90DJbIXWcs)

Thanks! I've tried the command "ldconfig -p | grep libEGL_nvidia" and I have only one line output as yours in the red box in the first image, and then I try to use this "glxinfo | grep OpenGL", the output is like that "Error: unable to open display localhost:10.0", have I installed the opengl?

**Comment by liuzhan123** [comment]
> Run "glxinfo| grep OpenGL" command to view OpenGL information on the ubuntu system, if you see that the field of ' OpenGL core profile version string' = 4.5, you can try to add "MESA_GL_VERSION_OVERRIDE=4.5 " before ".//bin/SIBR_remoteGaussian_app". That's useful for me.

Thanks, it works for me! ubuntu20.04 opengl4.5
