### ISSUE TITLE
How do I find the internal coordinate transformation between the input data and the output, like dataparser_transforms.json in NerfStudio 

### ISSUE THREAD

**Issue by cyz2727327** [graphdeco-inria/gaussian-splatting#271]
Hey guys, 

I'm new to Gaussian Splatting but I've been playing with NerfStudio for a while. What I want to achieve is to align the .glb mesh model with the Gaussian NeRF rendering in the web viewer, which are both create from the same data captured with Polycam. 

I understand for training purposed you probably did some coordinate transformation, and I need this information in order to align the Gaussian NeRF rendering with the original mesh model. I can do this already in NerfStudio because they provide a _**dataparser_transforms.json**_ file in the output folder, which contains a transform matrix with the scale factor.

How do I get this in Gaussian Splatting? Thanks a lot in advance !

**Comment by Snosixtyboo** [comment]
Hi,

sorry, we have actually not checked the specifications of Polycam and also have no control over their future conventions. I would recommend to check with them directly for up-to-date info.

**Comment by parodiniccolo** [comment]
> Hey guys,
> 
> I'm new to Gaussian Splatting but I've been playing with NerfStudio for a while. What I want to achieve is to align the .glb mesh model with the Gaussian NeRF rendering in the web viewer, which are both create from the same data captured with Polycam.
> 
> I understand for training purposed you probably did some coordinate transformation, and I need this information in order to align the Gaussian NeRF rendering with the original mesh model. I can do this already in NerfStudio because they provide a _**dataparser_transforms.json**_ file in the output folder, which contains a transform matrix with the scale factor.
> 
> How do I get this in Gaussian Splatting? Thanks a lot in advance !

Can you please explain how you applied the dataparser_transform.json to match the the polycam coordinates?

**Comment by Entongsu** [comment]
Hi, I've encountered the same problems. Do you have any ideas on how to transform the matrix from Nerfstudio to the version applicable for the GS training?
