### ISSUE TITLE
CUDA Memory problem

### ISSUE THREAD

**Issue by acsgn95** [graphdeco-inria/gaussian-splatting#275]
I have 24 GB VRAM in GPU. I created the high quality dense model with COLMAP. It's fulled the GPU memory. I tried low quality, it was fine. But, I need to high quality. Is there any way to train high quality? High quality dense model includes more than 20 million point.

**Comment by jaco001** [comment]
20kk is big even for photogrammetry. Try get under 300k-500k points. If not, last resort is splitting cloud to parts and train it separately.

**Comment by acsgn95** [comment]
How can I seperate them. And, after the training, how can I merge them?

Thanks in advance!!!

**Comment by jaco001** [comment]
1. Separation: 
Before training you got point cloud from COLMAP (and in COLMAP format). If you can edit it ok. If not, start training - script conwert it to input.ply and stop training ^C. Make copy and edit input.ply  in MeshLab. Clear it (floaters) and split 'model' to separate parts. 
Now you can overwrite input.ply in the output directory and back to train with parameter [--model_path / -m] pointing to the output directory.

2. 'Merging'
Apter training you get point_cloud.ply in the binary format. For now there aren't tools to edit those files, but SIBR viewer can 'trim' files and save it, so advanced edition of this .ply is possibly too.
If you using game engines like Unity or Unreal Engine, then there are plugins to import gaussian splatting to the  scene. Just import all parts and rearrange it on the scene. 

I know this is a bit messy, but I hope it helps.

**Comment by acsgn95** [comment]
@jaco001 I noticed that it depends on viewer. I was using webGL, so not SIBR. I installed and I fixed
