### ISSUE TITLE
RuntimeError: Storage size calculation overflowed with sizes=[-2139761793]

### ISSUE THREAD

**Issue by henrypearce4D** [graphdeco-inria/gaussian-splatting#28]
```
traceback (most recent call last):
  File "train.py", line 204, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations)
  File "train.py", line 75, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "C:\gaussian-splatting\gaussian_renderer\__init__.py", line 92, in render
    cov3D_precomp = cov3D_precomp)
  File "C:\Users\admin\.conda\envs\gaussian_splatting\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\admin\.conda\envs\gaussian_splatting\lib\site-packages\diff_gaussian_rasterization\__init__.py", line 194, in forward
    raster_settings,
  File "C:\Users\admin\.conda\envs\gaussian_splatting\lib\site-packages\diff_gaussian_rasterization\__init__.py", line 37, in rasterize_gaussians
    raster_settings,
  File "C:\Users\admin\.conda\envs\gaussian_splatting\lib\site-packages\diff_gaussian_rasterization\__init__.py", line 78, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
RuntimeError: Storage size calculation overflowed with sizes=[-2139761793]
Training progress:  20%|████████                                | 6020/30000 [30:05<1:59:53,  3.33it/s, Loss=0.0507467]
```

Running 56 of 3450 x 5180 images with -r 1.
Using a6000 with 48gb, is there anyway to calculate the limit of whats possible to run to which iteration?

**Comment by Snosixtyboo** [comment]
Hi,

no, we have no mechanics for working with a fixed budget. It's also not 100% clear what is exceeding the limits here, whether it is due to image data or geometry. If it is geometry, then a higher densify_grad_threshold value should help. In general however, 3450 x 5180 is VERY big, I am pretty certain that you won't get much additional detail out of using such a high resolution. If you omit the -r 1 flag, does the problem still occur?

Best,
Bernhard

**Comment by henrypearce4D** [comment]
Hi, I ran it with -r 2 and it went to 30k :)

Super interesting results!

![Screenshot 2023-07-13 165729](https://github.com/graphdeco-inria/gaussian-splatting/assets/106480554/55da98a3-ac1c-4b93-881f-c0457a5b8bea)
![closeup](https://github.com/graphdeco-inria/gaussian-splatting/assets/106480554/437b742c-114c-426a-8577-06757151607c)

With running -r 2 I saved at iteration 15000 and 30000 and the points in the .ply  files are the same - 427,850. But visually it is better at 30000.
The points in the scene I trained with -r 1 at the 6000 iteration were 167,933 so I'm not sure is exceeding the limit.

**Comment by Snosixtyboo** [comment]
Thanks for trying! It seems that very high-resolution images can get us into some corner cases, we'll need to see if those can be fixed. But we don't even have a dataset with this high resolution ourselves 😅

**Comment by grgkopanas** [comment]
Also do you. mind rendering a small path and sending it to me, I am planning to gather some interesting and cool use cases from the community and showcase them in the github README and the project webpage

**Comment by henrypearce4D** [comment]
Thanks I will try that data on cpu flag, although we are running an a6000 48gb and task manager was saying 8% used...

I will render out a path and we will contact you by email, also perhaps to discuss sharing datasets.
(Our systems were recently used for the humanRF paper)

**Comment by Snosixtyboo** [comment]
Update, I think this error should be fixed now, you would need:
```
git pull
git submodule update
cd submodules/diff-gaussian-rasterization
pip uninstall diff-gaussian-rasterization
python setup.py install
```
and then you shouldn't get an error unless you ACTUALLY run out of GPU memory.

Hth,
Bernhard

**Comment by henrypearce4D** [comment]
This time training continued past 6000 and used from what I saw 40/48gb gpu memory!

slight odd thing is that the point_cloud filesize ( points 317,534 ) for my 15000 and 30000 iteration are the same and its less than when I ran with -r 2

**Comment by Snosixtyboo** [comment]
> This time training continued past 6000 and used from what I saw 40/48gb gpu memory!
> 
> slight odd thing is that the point_cloud filesize ( points 317,534 ) for my 15000 and 30000 iteration are the same and its less than when I ran with -r 2

Hi, good to hear! 

The point cloud doesn't density after ```densify_until_iter```, which by default is 15,000. Things work out better if we leave them alone in the second half and just let them optimize, so that's expected. The number of points that one receive is not necessarily associated with the resolution. If you desire more points, consider lowering the --densify_grad_threshold.

I'll go and mark this as closed?
