### ISSUE TITLE
Render Using just the .PLY file

### ISSUE THREAD

**Issue by FatChicken277** [graphdeco-inria/gaussian-splatting#280]
It's possible to render a .ply file generated by luma into the viewer (i only have the .ply file)

**Comment by jaco001** [comment]
Just make proper catalog structure. Like:

catalog_model
-point_cloud
--iteration_30000

Put your file in the last and name it point_cloud.ply . After that start viewer
SIBR_gaussianViewer_app_.exe -m \catalog_model\ --iteration 30000

**Comment by FatChicken277** [comment]
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/60363061/d0df48e0-8cfd-461b-9b33-71e2e56e07dc)

I only have the .ply file

**Comment by jaco001** [comment]
If you have any splat you can copy cfg_args and cameras.json to main folder. If not 
[example.zip](https://github.com/graphdeco-inria/gaussian-splatting/files/12831437/example.zip)

**Comment by Snosixtyboo** [comment]
Hi,

sorry, we can't support files that are produced by third-party software, we we also have no control over Luma's future output conventions.
