### ISSUE TITLE
Ability to mask input images to remove moving or unnecessary objects from the scene

### ISSUE THREAD

**Issue by Sridhar701Pitt** [graphdeco-inria/gaussian-splatting#282]
Is there any way to mask input images to remove moving objects in a scene (like city) reconstruction scenario? For example for images taken from the top of a moving car, it would be desirable to mask the sections of the car that appear in all the images.

**Comment by jaco001** [comment]
Quick hack :)
Look at FAQ COLMAP -> https://colmap.github.io/faq.html#mask-image-regions
Prepare masks and put it in 'mask' subfolder

Add line to convert.py in     ## Feature extraction section
--ImageReader.mask_path  " + args.source_path + "/mask \

Start convert.py

**Comment by Sridhar701Pitt** [comment]
this process only masks the feature point extraction pipeline in colmap. i don't think this has any effect on the gaussian splat renderings. I am interested in ways to mask the splats within the image mask area.

**Comment by jaco001** [comment]
GS are based on point cloud. If you don't have points you don't have GS. So if you mask it before you don't have it in the model.
But if ask about rendering... Change SIBR viewer to you need. For now SIBR viewer can put 'box' around model and trim it. GL

**Comment by yzslab** [comment]
Hi, take a look this issue: https://github.com/graphdeco-inria/gaussian-splatting/issues/127

**Comment by Sridhar701Pitt** [comment]
Thank you. Exactly what i was looking for.
