### ISSUE TITLE
Running `convert.py` headless / without a display

### ISSUE THREAD

**Issue by bmikaili** [graphdeco-inria/gaussian-splatting#284]
How can I run the converter on a machine without a display? I keep getting this error:

```qt.qpa.xcb: could not connect to display

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**Comment by samiragarwala** [comment]
Hi! I was wondering if you could share how you got around this issue? I would appreciate any insight. Thanks!

**Comment by bmikaili** [comment]
Hey! I had originally used colmap from Apt packages and rebuilt it on the server manually, then it worked.
