### ISSUE TITLE
Quality getting worse as iterations increase

### ISSUE THREAD

**Issue by bmikaili** [graphdeco-inria/gaussian-splatting#286]
Hey, so I'm a bit baffled by one of my datasets: It's a very complex chemical processing machine with valves and transparent stuff and a lot of details. What happens is that it's rendered the best at 1000 iterations, but as soon as I increase to 2000 or more the splats get worse and all over the place. Has anyone else encountered similar issues?

**Comment by softyoda** [comment]
Hi, you closed this issue, was it a bug only on your side ? 
Or were there certain datadsets where 3DGS get worst with iterations ?

**Comment by bmikaili** [comment]
It seemed to look like a bug on my side as when I did it on another VPS it was fine.
