### ISSUE TITLE
Error with diff-gaussian-rasterization and simple-knn

### ISSUE THREAD

**Issue by vmendezm** [graphdeco-inria/gaussian-splatting#287]
Hello all,

[error_log.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/12836033/error_log.txt)

I'm working with:
Windows 10
Cuda 11.6
VSCode 2019

I got this error, specially related to Optional.h and spatial.cu.

I couldn't find any more related information.

I hope that at least you can view the log and guide a possible solution

My best regards

**Comment by Snosixtyboo** [comment]
Unfortunately I have no good explanation for why this happens. It seems like a pybind issue. Which pytorch version do you use?

**Comment by vmendezm** [comment]
Hello,

I am using pytorch 1.12.1. 

Finally, I achieve to install the dependencies, using Cuda 11.8 in Windows but with cudatoolkit 11.6 in the environment.yml file. 

I hope this can help to someone..
