### ISSUE TITLE
Restore the training

### ISSUE THREAD

**Issue by hkkkpang** [graphdeco-inria/gaussian-splatting#29]
Hi,

Thanks for your work. I just want to know whether your code support the "restore from specific iteration steps"? For example, I have stored the point clould for 10K stpes. Now, I want to load this point cloud information and restore training from it. Does your code support this?

Thanks in advance.

**Comment by Snosixtyboo** [comment]
> Hi,
> 
> Thanks for your work. I just want to know whether your code support the "restore from specific iteration steps"? For example, I have stored the point clould for 10K stpes. Now, I want to load this point cloud information and restore training from it. Does your code support this?
> 
> Thanks in advance.

Hi, unfortunately not right now. But you could convert the issue into a feature request and then we may look at it at some point in the future. It should not be super hard.

**Comment by Snosixtyboo** [comment]
Hi @hkkkpang ,

we added this functionality now, it works with the ```--checkpoint_iterations``` and ```--start_checkpoint``` parameters. It's experimental for now, so feel free to test it and let us know if it suits your needs.

Best,
Bernhard

**Comment by hkkkpang** [comment]
> Hi @hkkkpang ,
> 
> we added this functionality now, it works with the `--checkpoint_iterations` and `--start_checkpoint` parameters. It's experimental for now, so feel free to test it and let us know if it suits your needs.
> 
> Best, Bernhard

Hi Bernhard,

Thanks a lot for your kind help!

Best,

**Comment by luiscarone** [comment]
> Hi @hkkkpang ,
> 
> we added this functionality now, it works with the `--checkpoint_iterations` and `--start_checkpoint` parameters. It's experimental for now, so feel free to test it and let us know if it suits your needs.
> 
> Best, Bernhard

Hi Bernhard, I woundering how the --start_checkpoint works, Can I use my normally save 7000 interation or do I need to have a ---checkpoint_interations set on the training before hand?
