### ISSUE TITLE
how many graph in the directory images where use colmap Obtain Camera poses?

### ISSUE THREAD

**Issue by daxue2017** [graphdeco-inria/gaussian-splatting#290]
i use the colmap Obtain Camera poses,  the command line is below
python convert.py -s $FOLDER_PATH

when it finished, the images dir have seventeen graphs, is it right?
![imagesgraph](https://github.com/graphdeco-inria/gaussian-splatting/assets/43563918/ccf6bd2c-1912-44f6-8a3b-c99a3d04bc8e)

**Comment by daxue2017** [comment]
found use manual colmap gui  reconstruct, then use 
python convert.py -s $FOLDER_PATH --skip_matching

the images number is 749

**Comment by liuzhao6322** [comment]
I have also encountered the same problem. Have you resolved it

**Comment by qixuanwang-233** [comment]
> 发现使用手动 colmap gui 重建，然后使用 python Convert.py -s $FOLDER_PATH --skip_matching
> 
> 图片数量为 749

Hello, I also encountered the same problem, may I ask how you solved it? Thanks!

**Comment by hariharan1412** [comment]
> > 发现使用手动 colmap gui 重建，然后使用 python Convert.py -s $FOLDER_PATH --skip_matching
> > 图片数量为 749
> 
> Hello, I also encountered the same problem, may I ask how you solved it? Thanks!

The images present in the images directory after convert.py ran are the actual poses or the images registered in the SFM point cloud.
