### ISSUE TITLE
Optimisation: Most gaussian attributes could probably be float16 instead of float32

### ISSUE THREAD

**Issue by expenses** [graphdeco-inria/gaussian-splatting#291]
https://github.com/graphdeco-inria/gaussian-splatting/blob/414b553ef1d3032ea634b7b7a1d121173f36592c/scene/gaussian_model.py#L141-L147

Out of this lot, I think `features_dc`, `features_rest`, `rotation` and `opacity` could definitely be turned into 16-bit floats without much quality loss at all. I'm not sure about `max_radii2D` or `scaling`. Changing `xyz` is probably a bad idea.

**Comment by Snosixtyboo** [comment]
Correct! Our implementation is not optimized for memory consumption. Feel free to experiment!
