### ISSUE TITLE
How important is `distCUDA2`?

### ISSUE THREAD

**Issue by expenses** [graphdeco-inria/gaussian-splatting#292]
As far as I can tell, the only use of `simple-knn` is to import this `distCUDA2` function:

https://github.com/graphdeco-inria/gaussian-splatting/blob/414b553ef1d3032ea634b7b7a1d121173f36592c/scene/gaussian_model.py#L20

This is used presumably to set up sensible initial values for gaussian scales:

https://github.com/graphdeco-inria/gaussian-splatting/blob/414b553ef1d3032ea634b7b7a1d121173f36592c/scene/gaussian_model.py#L134-L135

It'd be great to get rid of `simple-knn` if possible as it would make building a bit easier and be one less thing in the way of a purely pytorch implementation.

A few questions:

1. Could a different KNN or other spatial-data-structure library be used?
2. Is there a simpler way to setting up default values for scales? Could they be initialised to zero like rotations?

**Comment by Snosixtyboo** [comment]
Hi,

it used to be quite important because we did it frequently. Now it is a one-time operation that is done for initialization, as you correctly identified. So really, it could be replaced by anything that offers reasonably quick kNN queries.

Zero for scale is probably a bad idea. You need them to be reasonably visible from the start.

**Comment by xiazhi1** [comment]
@expenses @Snosixtyboo  Hi ! Thanks for this meaningful discussion! I wonder how to replace the distCUDA2 with pure python or pytorch code?  I am looking forward to your suggestions!

**Comment by rfeinman** [comment]
The following replicates it in pure python (with scipy):

```python
from scipy.spatial import KDTree
import torch

def distCUDA2(points):
    points_np = points.detach().cpu().float().numpy()
    dists, inds = KDTree(points_np).query(points_np, k=4)
    meanDists = (dists[:, 1:] ** 2).mean(1)

    return torch.tensor(meanDists, dtype=points.dtype, device=points.device)
```

**Comment by xiazhi1** [comment]
> The following replicates it in pure python (with scipy):
> 
> ```python
> from scipy.spatial import KDTree
> import torch
> 
> def distCUDA2(points):
>     points_np = points.detach().cpu().float().numpy()
>     dists, inds = KDTree(points_np).query(points_np, k=4)
>     meanDists = (dists[:, 1:] ** 2).mean(1)
> 
>     return torch.tensor(meanDists, dtype=points.dtype, device=points.device)
> ```
> 
> @expenses @xiazhi1

Thanks a lot ! have solved it!
