### ISSUE TITLE
Failed to build SIBR Viewer

### ISSUE THREAD

**Issue by lingchen1991** [graphdeco-inria/gaussian-splatting#293]
[ 83%] Built target sibr_imgproc
[ 86%] Built target sibr_basic
[ 87%] Linking CXX executable SIBR_texturedMesh_app
/usr/bin/ld: ../../../../core/video/libsibr_video.so: undefined reference to `cv::optflow::calcOpticalFlowSF(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, int, int, int)'
/usr/bin/ld: ../../../../core/video/libsibr_video.so: undefined reference to `cv::ximgproc::guidedFilter(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, int, double, int)'
/usr/bin/ld: ../../../../core/video/libsibr_video.so: undefined reference to `cv::optflow::createOptFlow_DeepFlow()'
collect2: error: ld returned 1 exit status
make[2]: *** [src/projects/basic/apps/texturedMesh/CMakeFiles/SIBR_texturedMesh_app.dir/build.make:149: src/projects/basic/apps/texturedMesh/SIBR_texturedMesh_app] Error 1
make[1]: *** [CMakeFiles/Makefile2:1189: src/projects/basic/apps/texturedMesh/CMakeFiles/SIBR_texturedMesh_app.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

Sorry I am a fresh to C++. When I followed the instruction to build the SIBR Viewer, the built was failed. May I ask for some suggestion?

**Comment by heavenofpast** [comment]
Have you ever dealt with this question?

**Comment by lingchen1991** [comment]
> Have you ever dealt with this question?

It was solved by building opencv and its contrib before building SIBR Viewer

**Comment by heavenofpast** [comment]
> > Have you ever dealt with this question?
> 
> It was solved by building opencv and its contrib before building SIBR Viewer

Could you tell me the specific opencv version?I have tried some versions but it doesn't work.

**Comment by Au-LiuJY** [comment]
Sorry could you tell me more details about this question?I have the same question. In my server it has opencv, but it has this probelm,could you give me your email for me to ask for the solution?
