### ISSUE TITLE
some questions about the ply model property?

### ISSUE THREAD

**Issue by daxue2017** [graphdeco-inria/gaussian-splatting#298]
use notepad ++ open the ply model, 
the ply format is below:

ply
format binary_little_endian 1.0
element vertex 66290
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float f_dc_0
property float f_dc_1
property float f_dc_2
property float f_rest_0
property float f_rest_1
~~~~~~~~~~~~~
property float f_rest_43
property float f_rest_44
property float opacity
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
end_header


-------------------------------------
the non zero property is 

property float x
property float y
property float z
property float f_dc_0
property float f_dc_1
property float f_dc_2
property float opacity
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
-----------------------------
**then , what is the f_dc_0,f_dc_1,f_dc_2,  rot_0,rot_1,rot_2,rot_3  ?**

**Comment by softyoda** [comment]
Correct me if I'm wrong, but I think it is the following: 

Position : coordinate for point (x, y, z)
  property float x
  property float y
  property float z

Normal : normal vector components (nx, ny, nz)
  property float nx
  property float ny
  property float nz

Color : fundamental color before harmonics (r, g, b) (non-gamma-correct)
  property float f_dc_0
  property float f_dc_1
  property float f_dc_2

Harmonics : Spherical coefficients
  property float f_rest_0
  property float f_rest_1
  property float f_rest_2
  property float f_rest_3
  property float f_rest_4
  property float f_rest_5
  property float f_rest_6
  property float f_rest_7
  property float f_rest_8
  property float f_rest_9
  property float f_rest_10
  property float f_rest_11
  property float f_rest_12
  property float f_rest_13
  property float f_rest_14
  property float f_rest_15
  property float f_rest_16
  property float f_rest_17
  property float f_rest_18
  property float f_rest_19
  property float f_rest_20
  property float f_rest_21
  property float f_rest_22
  property float f_rest_23
  property float f_rest_24
  property float f_rest_25
  property float f_rest_26
  property float f_rest_27
  property float f_rest_28
  property float f_rest_29
  property float f_rest_30
  property float f_rest_31
  property float f_rest_32
  property float f_rest_33
  property float f_rest_34
  property float f_rest_35
  property float f_rest_36
  property float f_rest_37
  property float f_rest_38
  property float f_rest_39
  property float f_rest_40
  property float f_rest_41
  property float f_rest_42
  property float f_rest_43
  property float f_rest_44

Opacity : 
  property float opacity

Scale : (x, y, z)
  property float scale_0
  property float scale_1
  property float scale_2

Rotation : (Quaternions i, j, k, and a scalar component w)
  property float rot_0
  property float rot_1
  property float rot_2
  property float rot_3

**Comment by Snosixtyboo** [comment]
f_dc_0,f_dc_1,f_dc_2,

those are the direct (RGB) coefficients for the spherical harmonics

rot_0,rot_1,rot_2,rot_3 

those are the coefficients of the rotation (quaternion)

**Comment by daxue2017** [comment]
the f_dc_0~f_dc_2 is a negative  decimal , is it the color rgb?

**Comment by hanhantie233** [comment]
sir,I want to konw why are there so many spherical coefficients.

**Comment by softyoda** [comment]
Hi @hanhantie233, an image sometimes worth 1000 words.

![firefox-Photopea__Online_Photo_Editor_—_Mozilla_Firefox-13-14_18-janvier-24_4819-78909_1490-1078](https://github.com/graphdeco-inria/gaussian-splatting/assets/13988751/11c1eb3a-036a-481d-88f2-65f805469f68)


There are 16 coefficient * 3 colors = 48 coefficient (45 of them being only for spherical harmonics and 3 for fundamental color)

**Comment by hanhantie233** [comment]
> Hi @hanhantie233, an image sometimes worth 1000 words.
> 
> ![firefox-Photopea__Online_Photo_Editor_—_Mozilla_Firefox-13-14_18-janvier-24_4819-78909_1490-1078](https://private-user-images.githubusercontent.com/13988751/297736434-11c1eb3a-036a-481d-88f2-65f805469f68.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1OTA0OTgsIm5iZiI6MTcwNTU5MDE5OCwicGF0aCI6Ii8xMzk4ODc1MS8yOTc3MzY0MzQtMTFjMWViM2EtMDM2YS00ODFkLTg4ZjItNjVmODA1NDY5ZjY4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDE1MDMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZDdkZjVkMzFhNjRmNDhhOGE3NTJkMDc0OGQ2OWNkNGQ5MGNhMDgwMzdjOTFhYWU4MjQwMzBhNmE4ODhjNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ojd6na_X2VhmmILa6WzEySgfP5FfyMerKpTMG3AoCFQ)
> 
> There are 16 coefficient * 3 colors = 48 coefficient (45 of them being only for spherical harmonics and 3 for fundamental color)

Thanks for your answering, I observed that these f_res_x variables occupy a significant amount of Cuda memory during training. When I delete them, the training performance severely deteriorates.

**Comment by softyoda** [comment]
You could change the order of spherical harmonics to be used (instead of 3 by default), with the command `--sh_degree 2` or `--sh_degree 1`

**Comment by hanhantie233** [comment]
> You could change the order of spherical harmonics to be used (instead of 3 by default), with the command `--sh_degree 2` or `--sh_degree 1`

Thanks,I will attempt this method.

**Comment by hanhantie233** [comment]
> You could change the order of spherical harmonics to be used (instead of 3 by default), with the command `--sh_degree 2` or `--sh_degree 1`

sir,I try to set the sh_degree=2,but I noticed that the training results, especially the point_cloud, are very poor.
