### ISSUE TITLE
OSError: [Errno 24] Too many open files 

### ISSUE THREAD

**Issue by Ryan-ZL-Lin** [graphdeco-inria/gaussian-splatting#299]
Hello 3DGS fellow
I tried to run `python train.py` for 18866 images on my locallaptop with 12GB VRAM and got the following error, has anyone encounntered the same error before?

> (gaussian_splatting) C:\Users\lzlal\gaussian_splatting>python train.py -s data/BCA_L2_center_R1 --data_device cpu
> Optimizing
> Output folder: ./output/1e1a8541-2 [10/10 15:14:12]
> Tensorboard not available: not logging progress [10/10 15:14:12]
> Reading camera 8190/18866Traceback (most recent call last):
>   File "train.py", line 216, in <module>
>   File "train.py", line 35, in training
>   File "C:\Users\lzlal\gaussian_splatting\scene\__init__.py", line 44, in __init__
>   File "C:\Users\lzlal\gaussian_splatting\scene\dataset_readers.py", line 145, in readColmapSceneInfo
>   File "C:\Users\lzlal\gaussian_splatting\scene\dataset_readers.py", line 99, in readColmapCameras
>   File "C:\Users\lzlal\.conda\envs\gaussian_splatting\lib\site-packages\PIL\Image.py", line 3227, in open
> OSError: [Errno 24] Too many open files: 'C:\\Users\\lzlal\\gaussian_splatting\\data\\BCA_L2_center_R1\\images\\frame_07404.jpg'

**Comment by DRosemei** [comment]
@Ryan-ZL-Lin You can refer https://stackoverflow.com/questions/29234413/too-many-open-files-error-when-opening-and-loading-images-in-pillow

**Comment by Snosixtyboo** [comment]
Sorry, that's far outside the dataset complexity we support with our released code. Arbitrarily-sized scenes is its own research question altogether.

**Comment by JeS24** [comment]
Sorry for replying to a closed thread. Just thought, this might help some people.

@Ryan-ZL-Lin Check your system's open file limit count. For Windows, you can use the following python script:
```py
import win32file
print(win32file._getmaxstdio())
```
To change the limit ([up to a maximum of 8192](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setmaxstdio?view=msvc-170#remarks)), you can do:
```py
win32file._setmaxstdio(8192)
```
Note that this does *not* apply system-wide and has to be included with the main python code, you are trying to run. Of course, in your case, 8192 would not help either. Perhaps, you can try splitting the scene or try it on a *nix-based system.

For *nix, `ulimit -n` shows the current maximum. You can alter this using the same command - `ulimit -n 8192` (this is per session and not system-wide, so you have to run it each time before `train.py`). Or, in python (on *nix):
```py
import resource
print(resource.getrlimit(resource.RLIMIT_NOFILE)) # Shows current soft & hard limits, e.g., [512, 1048576]
resource.setrlimit(resource.RLIMIT_NOFILE, [8192, 1048576]) # Sets new soft limit and keeps the hard limit as-is
```

To see the system's maximum, you can run `cat /proc/sys/fs/file-max`, though editing the system-wide limit is not recommended.
