### ISSUE TITLE
Q about COLMAP Camera Model?

### ISSUE THREAD

**Issue by TwiceMao** [graphdeco-inria/gaussian-splatting#303]
In your dataset_readers.py, the code only handles the camera models SIMPLE_PINHOLE and PINHOLE, but does not handle the SIMPLE_RADIAL type. I would like to ask if there is any rationale for this? The reason I can think of may be that the 3D Gaussian may not perform well after COLMAP processing with the camera model set to SIMPLE_RADIAL. Thank you for your answer~
@Snosixtyboo 
@grgkopanas

**Comment by yzslab** [comment]
Theoretically, I think there won't be any performance problems. Just non-pinhole camera model is more complicated than pinhole. For non-pinhole cameras, you need to add some codes to the rasterization pipeline to calculate the correct coordinates using the distortion coefficients.
Though `dataset_readers.py` can only deal with pinhole, the colmap provides a command `image_undistorter` to convert non-pinhole cameras to pinhole. So only handles pinhole here is enough.

**Comment by Snosixtyboo** [comment]
What @yzslab says is correct. Using radial distortion would result in "Gaussians" that no longer have a Gaussian shape under projection. It might be possible to ignore this distortion factor, but we haven't tested it, and at least for intense distortions it is likely to create issues, so we didn't add official support for this camera model.

Hth

**Comment by scott198510** [comment]
@Snosixtyboo @yzslab
