### ISSUE TITLE
There are only 2 images in the directory "images" after run the "convert.py".

### ISSUE THREAD

**Issue by Relif-me** [graphdeco-inria/gaussian-splatting#304]
I meet a issue when I run "python convert.py -s ./data" to deal with my data.

The directory structure in the data directory is as follows. there are 226 images.
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/124853470/64c1a2a0-6f8b-4ce4-9413-adf95c32e201)
Then I run the following command:

"python convert.py -s ./data"

And then I only get two images in the "data/images" directory.

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/124853470/17760960-8359-434a-b8bf-3dd295790c9d)

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/124853470/c5db8aa2-f750-494e-a2d7-f3ce44a58e6f)

This makes subsequent training impossible.
I want to know what the problem is. It bothers me.
Thanks!

**Comment by ThomasWarn** [comment]
This typically indicates that COLMAP was unable to solve the camera positions.
Additionally the low number of points looks abnormally low.

If possible, can you share an image or two? What type of scene are you showing? There may not be enough overlap in your images, the images may be of poor quality, or auto-focus / auto-exposure may be causing issues.

**Comment by Relif-me** [comment]
@ThomasWarn Thanks for your response.
I tried some datasets. Some were found to produce normal results, while others did not.
Here are some datasets that don't work:
The nerfstudio dataset "poster"
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/124853470/7775fb13-8c1c-4a80-a593-3332764d7d0d)
The nerfstudio dataset "campanelle"
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/124853470/cd51ddf7-4fc8-4e71-941f-8a86a6595187)
And my own sence
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/124853470/996ef1b4-4f0e-440e-bd92-87891270735b)

I'm not sure if there are any special requirements for the scene.
I think the texture of these scenes is also quite rich.
Is it because these scenes have sky or white walls?

**Comment by liuzhao6322** [comment]
I have also encountered the same problem. Have you resolved it

**Comment by Snosixtyboo** [comment]
Hi,

sorry, this appears to be an issue with COLMAP, which we don't maintain. Please consider messaging the original authors. Our approach starts from the assumption that the established calibration via COLMAP is successful.

Hth,
Bernhard

**Comment by Relif-me** [comment]
Specifying "--camera" as "SIMPLE_PINHOLE" or "PINHOLE" when executing the command can solve this problem, assuming that the image data parameters are consistent and free of distortion.

**Comment by NeutrinoLiu** [comment]
colmap 3.8 works fine, but colmap 3.9 fails when derive sfm result.
