### ISSUE TITLE
batchsize = 1?

### ISSUE THREAD

**Issue by Torment123** [graphdeco-inria/gaussian-splatting#307]
Hi, based on the code, I see that the batchsize is 1, i.e. each iteration the optimization is done for one training image; is this for computational efficiency?

**Comment by Snosixtyboo** [comment]
Hi,

it's mainly done for reasons of feasibility: a large scene, when rendered, can already consume a few hundreds of megabytes in rasterizer state. If you want to rasterize N different views simultaneously, you will have to multiply that memory consumption by N, so large batch sizes are not feasible either way. On the other hand, the GPU is usually quite occupied in terms of compute with one image, so batching does not make a ton of sense there. Note that you can still manually batch to get smoother gradients (i.e., do multiple backwards before one optimizer step).

**Comment by Torment123** [comment]
thanks for the fast and detailed reply, that helps alot

**Comment by Tejasdavande07** [comment]
> I see that the batch size is 1,

can we change the batch size while entering the training command?
python convert.py -s data/test  
as above is the plain command please give me any argument is thier for changing the default batch size because large batch size consumes complete GPU memory for this i needed this.

**Comment by kwea123** [comment]
the only way to reduce memory is to use smaller image, or to disable all sh coefs

**Comment by BitCalSaul** [comment]
Hi @Snosixtyboo ,

Thanks again for your previous explanation — it was really helpful.

I’m trying to better understand the memory scaling with respect to batch size. Specifically, could you give a rough sense of how much additional GPU memory is consumed when increasing the batch size by 1 (i.e., rendering one more view in parallel)?

From my understanding, the extra cost likely comes from storing the 2D projected Gaussians for the additional view, as well as their associated gradient buffers. But I’m wondering if there are any other major contributors I might be overlooking.

For reference, with ~10 million Gaussians and batch size = 1, I’m already seeing around 40 GB of GPU memory usage. I'm trying to assess whether a small batch size increase could be viable in my setup.

Appreciate your insights!
