### ISSUE TITLE
.ply to .splat conversion using Python

### ISSUE THREAD

**Issue by lenismerino** [graphdeco-inria/gaussian-splatting#310]
It is my impression that the SIBR viewer can render the contents of the scene without performing this conversion.

Is there a sample code to perform this conversion in Python? are there plans to add this as a feature of this repository? Any help guidance is appreciated.

**Comment by grgkopanas** [comment]
We do not support external formats other than the ones we produce with our
code base

**Comment by lenismerino** [comment]
Got it, thanks for the response. Issue can be closed now
