### ISSUE TITLE
Unable to locate package libembree-dev

### ISSUE THREAD

**Issue by EhabWilson** [graphdeco-inria/gaussian-splatting#314]
When I try to install the viewer on Ubuntu 18.04, it shows that
`E: Unable to locate package libembree-dev`
How can I solve the problem ?

**Comment by EhabWilson** [comment]
I find that there is no released package [libembree-dev] for Ubuntu 18.04.

**Comment by hyoseok1223** [comment]
@EhabWilson Hi, Wilson have you build viewer in Ubuntu 18.04?  Without  [libembree-dev] , viewer is work well? 
Thank you for sharing you experience!

**Comment by EhabWilson** [comment]
I fail to build the viewer without the lib on Ubuntu18. Finally, I change my system to ubuntu 22 and build it successfully.
