### ISSUE TITLE
SIBR viewer closes

### ISSUE THREAD

**Issue by qqrr8** [graphdeco-inria/gaussian-splatting#321]
Hi, please help me with the problem. The SIBR viewer opens for a few seconds and immediately closes when I try to launch it.

(gaussian_splatting) C: \programms\gaussian-splatting\viewers\bin>SIBR_gaussianViewer_app.exe -m C:\programms\gaussian-splatting\output\chair
[SIBR] -- INFOS --: Initialization of GLFW
[SIBR] -- INFOS --: OpenGL Version: 4.6.0 NVIDIA 537.58[major: 4, minor: 6]

That is what i see in cmd, when SIBR closes. I will be glad if you help me with this

P. S. If it helps, this is what happens when I run the SIBR_gaussianViewer_app file in Explorer, it also crashes after a few seconds
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/146338628/62b64a65-1acb-48fa-a5ef-08b3c753e00e)

**Comment by henrypearce4D** [comment]
Can you check your folder;
`C:\programms\gaussian-splatting\output\chair`

In it, can you see;
```
point_cloud (folder)
cameras.json
cfg_args
input.ply
```

**Comment by qqrr8** [comment]
Yes, 
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/146338628/489c6203-c0cc-4bc2-bac4-a8fc7a548142)

**Comment by poomnatt** [comment]
i have the exact same problem here ,the train data is done ( i can open the train scene in blender but very slow) ,but this viewer will opens for a few seconds and immediately close every time 
C:\gaussianspaltviewer\viewers\bin> SIBR_gaussianViewer_app -m C:\Users\Poom\gaussian-splatting\output\ef283843-8
[SIBR] --  INFOS  --:   Initialization of GLFW
[SIBR] --  INFOS  --:   OpenGL Version: 4.6.0 NVIDIA 537.42[major: 4, minor: 6]
i have zero knowledge about coding so i'm not sure which part is broken
I use rtx4090

**Comment by Snosixtyboo** [comment]
> Hi, please help me with the problem. The SIBR viewer opens for a few seconds and immediately closes when I try to launch it.
> 
> (gaussian_splatting) C: \programms\gaussian-splatting\viewers\bin>SIBR_gaussianViewer_app.exe -m C:\programms\gaussian-splatting\output\chair [SIBR] -- INFOS --: Initialization of GLFW [SIBR] -- INFOS --: OpenGL Version: 4.6.0 NVIDIA 537.58[major: 4, minor: 6]
> 
> That is what i see in cmd, when SIBR closes. I will be glad if you help me with this
> 
> P. S. If it helps, this is what happens when I run the SIBR_gaussianViewer_app file in Explorer, it also crashes after a few seconds ![image](https://user-images.githubusercontent.com/146338628/275347942-62b64a65-1acb-48fa-a5ef-08b3c753e00e.png)

Somehow it seems that the parser does not register you "-m" flag with the model path. Could you take a screenshot of you entering the command before the viewer launches, and could you also post the contents of the cfg_args?

**Comment by qqrr8** [comment]
Thank you for your help, but I have already deleted the program and everything related to it

> > Hi, please help me with the problem. The SIBR viewer opens for a few seconds and immediately closes when I try to launch it.
> > (gaussian_splatting) C: \programms\gaussian-splatting\viewers\bin>SIBR_gaussianViewer_app.exe -m C:\programms\gaussian-splatting\output\chair [SIBR] -- INFOS --: Initialization of GLFW [SIBR] -- INFOS --: OpenGL Version: 4.6.0 NVIDIA 537.58[major: 4, minor: 6]
> > That is what i see in cmd, when SIBR closes. I will be glad if you help me with this
> > P. S. If it helps, this is what happens when I run the SIBR_gaussianViewer_app file in Explorer, it also crashes after a few seconds ![image](https://user-images.githubusercontent.com/146338628/275347942-62b64a65-1acb-48fa-a5ef-08b3c753e00e.png)
> 
> Somehow it seems that the parser does not register you "-m" flag with the model path. Could you take a screenshot of you entering the command before the viewer launches, and could you also post the contents of the cfg_args?

**Comment by Snosixtyboo** [comment]
Fair enough :D

**Comment by theshamot** [comment]
I got this same problem with SIBR. Did not try Blender though.
I will continue whe discussion ended.

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/38070601/ea5ed4f3-bbfd-4695-8771-23cc87641437)

cfg_args
`Namespace(data_device='cuda', eval=False, images='images', model_path='./output/d11f11e9-a', resolution=-1, sh_degree=3, source_path='D:\\Projekty\\Gaussian splatting\\gaussian-splatting\\data\\battlestation', white_background=False)`

**Comment by theshamot** [comment]
> I got this same problem with SIBR. Did not try Blender though. I will continue whe discussion ended.
> 
> ![image](https://private-user-images.githubusercontent.com/38070601/297812206-ea5ed4f3-bbfd-4695-8771-23cc87641437.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTE5OTIsIm5iZiI6MTcwNTYxMTY5MiwicGF0aCI6Ii8zODA3MDYwMS8yOTc4MTIyMDYtZWE1ZWQ0ZjMtYmJmZC00Njk1LTg3NzEtMjNjYzg3NjQxNDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDIxMDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNzEwNmQ0YTg0ZTcwMTJmOTk1NWEzYzY2NWExYWIwNDQ1NGJhMzU5ODkwMWMzYmFkNmFhNzQ0ZjEwZGMwNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2f5WiAV0-C8OyJ7AT8YiM1VeM2LTJnejQi8fNfjSNFs)
> 
> cfg_args `Namespace(data_device='cuda', eval=False, images='images', model_path='./output/d11f11e9-a', resolution=-1, sh_degree=3, source_path='D:\\Projekty\\Gaussian splatting\\gaussian-splatting\\data\\battlestation', white_background=False)`

solved my problem by running cmd as Administrator

**Comment by tkbees** [comment]
I want my output in glb format. Can help?
