### ISSUE TITLE
How to export to stl

### ISSUE THREAD

**Issue by carlos-reynoso** [graphdeco-inria/gaussian-splatting#322]
Hi, is there any way to export the model to stl or similar?
Thanks

**Comment by henrypearce4D** [comment]
There is no model, the result is a point cloud with shading attributes. You can open the .ply pointcloud in meshlab and mesh it, but the results are far worse than photogrammetry

**Comment by oUp2Uo** [comment]
Thanks for the reply. 
So is it correct that I could not see the color when using Meshlab?
Or could I check the result without SIBR Viewers?

**Comment by henrypearce4D** [comment]
You can load the file into Cloud compare and assign red green and blue to the correct headers or edit the .ply headers first by adding RED, GREEN, BLUE to these lines;

```
RED_f_dc_0 
GREEN_f_dc_1
BLUE_f_dc_2
```

It should load automatically with the assigned colours, then save the .ply file out and load it into meshlab or mesh it in cloudcompare

https://youtu.be/m43usERF33M?t=62

**Comment by oUp2Uo** [comment]
Thanks for your reply.

I tried to set Red Green Blue when opening the ply file.
![20231016182954](https://github.com/graphdeco-inria/gaussian-splatting/assets/29222415/c0376ee4-ed86-4b02-9a9d-0b6c14ab62ed)
And then change **Colors** in **CC Object** in **Properties** window from **Scalar field** to **RGB**.
Then I could see the color.
Hope this could help someone else.

BTW, when I try to do mesh as the video, error occured.
![20231016183755](https://github.com/graphdeco-inria/gaussian-splatting/assets/29222415/b3cfd3db-efae-4077-a381-74125a6add39)
