### ISSUE TITLE
Feature Extraction failing on Windows 11

### ISSUE THREAD

**Issue by GuiltyPixel** [graphdeco-inria/gaussian-splatting#323]
environment
```
Windows 11 22H2 22621.2361
conda 23.1.0
python 3.7.13
nvcc 11.7.r11.7
imagemagick 7.1.1-20 Q16-HDRI x64 98bb1d4:20231008
colmap 3.8 cuda
ffmpeg 4.2.3
conda environment within powershell  5.1.22621.1778
```

output
```
(gaussian_splatting) PS C:\Applications\gaussian-splatting> python .\convert.py --source_path C:\Applications\gaussian-splatting\data\video_dump_02_clean
[option_manager.cc:815] Check failed: ExistsDir(*image_path)
ERROR: Invalid options provided.
ERROR:root:Feature extraction failed with code 1. Exiting.
```

The folder structure of <source>\distorted and the sparse subfolder are created but neither contains data files. Removing this folder and rerunning repeats the behavior. Running again produces the same output. Other paths and different datasets produce the same result.

All prerequisite applications were tested in this environment and are otherwise working and in the path, I also manually specified the path to no avail.

Any ideas?

**Comment by ishipachev** [comment]
Do you have images at C:\Applications\gaussian-splatting\data\video_dump_02_clean ?

Have you tried to specify path with double slashes and put it in quotes? Also try to put path to images with forward slashes in Linux-like style (in quotes also).

COLMAP didn't see the directory for some reason.

**Comment by GuiltyPixel** [comment]
/input is added inside the script and I didn't catch it. The images were in the literal folder i specified as --source_path not in <source_path>/images

nevermind but thanks

**Comment by Lenubolim** [comment]
> python .\convert.py --source_path C:\Applications\gaussian-splatting\data\video_dump_02_clean
Try putting quotes around the path, and make sure that there is an input folder inside the video_dump_02_clean folder and that there is a photo inside the input.
python .\convert.py --source_path 'C:\Applications\gaussian-splatting\data\video_dump_02_clean'

**Comment by chillbert** [comment]
how did you fix this?

I have my images in this folder:
`C:\Users\chillo\pinokio\api\gaussian-splatting-Windows.git\data\snow\input
`
I run:
`$ python convert.py -s C:/Users/chillo/pinokio/api/gaussian-splatting-Windows.git/data/snow
`
and get this error:

`ERROR:root:Feature extraction failed with code -1073741515. Exiting.`

a distorted/sparse folder is created into the input folder but the error is there.

**Comment by Lenubolim** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你的邮件我已收到。

**Comment by chillbert** [comment]
OK I noticed colmap and ImageMagick were not in the path yet.

**Comment by 27yw** [comment]
hello, I face the same problems now, I have already installed colmap and added into the path on my computer. Can anyone help?

**Comment by Lenubolim** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你的邮件我已收到。

**Comment by hesetone** [comment]
> hello, I face the same problems now, I have already installed colmap and added into the path on my computer. Can anyone help?

Hi, specify the path to you colmap.exe and colmap.bat could be the final solution, ohhhhhh, just remember rename 'COLMAP.bat' to 'colmap.bat'.

**Comment by Lenubolim** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你的邮件我已收到。

**Comment by ZR-AI** [comment]
> > hello, I face the same problems now, I have already installed colmap and added into the path on my computer. Can anyone help?您好，我现在面临同样的问题，我已经安装了 colmap 并添加到我计算机上的路径中。谁能帮忙？
> 
> Hi, specify the path to you colmap.exe and colmap.bat could be the final solution, ohhhhhh, just remember rename 'COLMAP.bat' to 'colmap.bat'.嗨，colmap.exe指定您的路径，colmap.bat可能是最终的解决方案，哦，请记住将“COLMAP.bat”重命名为“colmap.bat”。

I've tried, but the problem hasn't been solved
