### ISSUE TITLE
Recurring Error when trying to train largish datasets - ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Fanie-Visagie** [graphdeco-inria/gaussian-splatting#327]
Good day...

So tired of seeing this error...Anyone have any idea what may be wrong...clearly not smart enough to figure it out...

(gaussian_splatting) C:\Users\perso\gaussian-splatting>python train.py -s data/burner
Optimizing
Output folder: ./output/05a2c4e2-1 [17/10 16:19:36]
Reading camera 212/212 [17/10 16:19:37]
Loading Training Cameras [17/10 16:19:37]
[ INFO ] Encountered quite large input images (>1.6K pixels width), rescaling to 1.6K.
 If this is not desired, please explicitly specify '--resolution/-r' as 1 [17/10 16:19:37]
Loading Test Cameras [17/10 16:22:07]
Number of points at initialisation :  181257 [17/10 16:22:07]
Training progress:   0%|                                                                                                         | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 216, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 83, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "C:\Users\perso\gaussian-splatting\gaussian_renderer\__init__.py", line 93, in render
    cov3D_precomp = cov3D_precomp)
ValueError: too many values to unpack (expected 2)
Training progress:   0%|

Using the standard workflow that works EVERYTIME, until it does not >_<

**Comment by Fanie-Visagie** [comment]
Not sure if related...but tried a different workflow and got the following...Note the EXIF...

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/107527026/2bf5467f-50e3-4095-91ba-254a4f550739)

**Comment by Fanie-Visagie** [comment]
Ah fixed it...make sure you GIT the fork of https://github.com/jonstephens85/gaussian-splatting-Windows...Thanks for the setup yet your code has more bugs than a kings cross girl on christmas day...#everpoint

**Comment by Larthas** [comment]
> Ah fixed it...make sure you GIT the fork of https://github.com/jonstephens85/gaussian-splatting-Windows...Thanks for the setup yet your code has more bugs than a kings cross girl on christmas day...#everpoint

I just clone the project https://github.com/jonstephens85/gaussian-splatting-Windows, but the problem is still there, how I fixed it...

**Comment by Larthas** [comment]
> Good day...
> 
> So tired of seeing this error...Anyone have any idea what may be wrong...clearly not smart enough to figure it out...
> 
> (gaussian_splatting) C:\Users\perso\gaussian-splatting>python train.py -s data/burner Optimizing Output folder: ./output/05a2c4e2-1 [17/10 16:19:36] Reading camera 212/212 [17/10 16:19:37] Loading Training Cameras [17/10 16:19:37] [ INFO ] Encountered quite large input images (>1.6K pixels width), rescaling to 1.6K. If this is not desired, please explicitly specify '--resolution/-r' as 1 [17/10 16:19:37] Loading Test Cameras [17/10 16:22:07] Number of points at initialisation : 181257 [17/10 16:22:07] Training progress: 0%| | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last): File "train.py", line 216, in training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from) File "train.py", line 83, in training render_pkg = render(viewpoint_cam, gaussians, pipe, background) File "C:\Users\perso\gaussian-splatting\gaussian_renderer__init__.py", line 93, in render cov3D_precomp = cov3D_precomp) ValueError: too many values to unpack (expected 2) Training progress: 0%|
> 
> Using the standard workflow that works EVERYTIME, until it does not >_<

Did you solve this problem? If so, could you tell me how you did it?
