### ISSUE TITLE
Did something change in the 'point cloud init' in the last 24 hours?

### ISSUE THREAD

**Issue by JonathonLuiten** [graphdeco-inria/gaussian-splatting#33]
Current render on initialization (without training) (13th 4pm):

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/23000532/3d35b744-7a91-452a-a268-1a1ab8fe500e)

PSNR: 17.6

whereas yesterday (12th) at 4.30pm, the same render at initialization (without training) looked like this:
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/23000532/83a7fa2e-ce96-47ed-a239-ad3a0030b295)
PSNR: 24.6

Did anything change when I repulled things? I don't think I did anything to make this change.. (but maybe I did)?

**Comment by JonathonLuiten** [comment]
I think I found my answer...

This commit:
https://github.com/graphdeco-inria/gaussian-splatting/commit/b1a35bc94bfb1a94c6f8aeca341978b4d32e094b

Changed the initial alpha from 0.5 to 0.1. Makes sense this would cause this change...

Is it better with a lower alpha init? @Snosixtyboo

**Comment by Snosixtyboo** [comment]
> I think I found my answer...
> 
> This commit: [b1a35bc](https://github.com/graphdeco-inria/gaussian-splatting/commit/b1a35bc94bfb1a94c6f8aeca341978b4d32e094b)
> 
> Changed the initial alpha from 0.5 to 0.1. Makes sense this would cause this change...
> 
> Is it better with a lower alpha init? @Snosixtyboo

Hi,

our experiments say yes, especially in larger scenes. Is this an issue for you?

**Comment by Snosixtyboo** [comment]
> > I think I found my answer...
> > This commit: [b1a35bc](https://github.com/graphdeco-inria/gaussian-splatting/commit/b1a35bc94bfb1a94c6f8aeca341978b4d32e094b)
> > Changed the initial alpha from 0.5 to 0.1. Makes sense this would cause this change...
> > Is it better with a lower alpha init? @Snosixtyboo
> 
> Hi,
> 
> our experiments say yes, especially in larger scenes. Is this an issue for you?

If so, we could make it a command line param. But 0.1 works the same or better than 0.5 for everything we evaluated.

**Comment by JonathonLuiten** [comment]
No this should be fine, I just thought it was very strange. Closing now :)
