### ISSUE TITLE
illegal memory access

### ISSUE THREAD

**Issue by MurtazaSFakhry** [graphdeco-inria/gaussian-splatting#331]
I have no idea what this means and how to solve it, someone please help.

thanks in advance. 

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/117734652/51a633e8-b778-40e4-bbdd-a3e64790fb24)

**Comment by Snosixtyboo** [comment]
Hi,

unfortunately this seems like an error that occurs in Colmap, which is not maintained by us. Please consider forwarding this to the creators of COLMAP.

Hth,
Bernhard
