### ISSUE TITLE
'colmap' is not recognized... [solved]

### ISSUE THREAD

**Issue by cNichols0788** [graphdeco-inria/gaussian-splatting#337]
...as an internal or external command, operable program or batch file.
ERROR;root:Feature extraction failed with code 1. Exiting.

This is interesting because I'm sure I set up the correct path in the environment window. But it doesn't see it. So I'm not sure what I might be missing.

I'm at the part where I'm trying to convert my images for training.

**Comment by yuedajiong** [comment]
if linux is ok for you, I can help you.

I used colmap on win a few months ago, no env today.

please fellow me step by step,  in 3 minutes:

@ubuntu-18.04

[0000-cuda11.7_pytorch1.13_tinycudann_colmap.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13030759/0000-cuda11.7_pytorch1.13_tinycudann_colmap.txt)

[superi_colmap.py.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13030766/superi_colmap.py.txt)
[superi_colmap2nerf.py.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13030767/superi_colmap2nerf.py.txt)

my code is very simple, no any garbage.

**Comment by yuedajiong** [comment]
if you use convert.py, --colmap_executable abs_path?

**Comment by cNichols0788** [comment]
> if linux is ok for you, I can help you.
> 
> I used colmap on win a few months ago, no env today.
> 
> please fellow me step by step, in 3 minutes:
> 
> @ubuntu-18.04
> 
> [0000-cuda11.7_pytorch1.13_tinycudann_colmap.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13030759/0000-cuda11.7_pytorch1.13_tinycudann_colmap.txt)
> 
> [superi_colmap.py.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13030766/superi_colmap.py.txt) [superi_colmap2nerf.py.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13030767/superi_colmap2nerf.py.txt)
> 
> my code is very simple, no any garbage.

Ah, I appreciate the quick response, but my work runs Windows on their computers. I'm also a huge beginner with this kind of stuff but nothing seems too confusing so far. Just this one issue where colmap isn't found or recognized.

Thanks for the help though!

**Comment by yuedajiong** [comment]
very easy on win in 5 seconds:

1.  download https://github.com/colmap/colmap/releases/download/3.8/COLMAP-3.8-windows-no-cuda.zip   #cuda or no-cuda  #2 seconds
2.  unzip to c:\ (or anywhere)  #2 seconds
3.  directly click to run c:\COLMAP-3.8-windows-no-cuda\COLMAP.bat      #NOTICE： COLMAP.bat   #1 second

lucky! caffe!

**Comment by cNichols0788** [comment]
> very easy on win in 5 seconds:
> 
> 1. download https://github.com/colmap/colmap/releases/download/3.8/COLMAP-3.8-windows-no-cuda.zip   (cuda or no-cuda) (2 seconds)
> 2. unzip to c:\    (or anywhere)  (2 seconds)
> 3. directly click to run c:\COLMAP-3.8-windows-no-cuda\COLMAP.bat      (NOTICE： COLMAP.bat)   (1 second)
> 
> lucky! caffe!

Oh, I have that. I placed it in a good spot, created the environment path. I can even run the batch file. Opening colmap isn't a problem for me. The conda cmd isn't picking it up or something.

**Comment by cNichols0788** [comment]
Hey, I figured it out.

I did everything right. I just needed to restart the computer.

**Comment by henrypearce4D** [comment]
@cNichols0788 When you edit your environment paths you have to restart any command prompts for the added paths to work correctly, that caught me out at first!

**Comment by leejngmn** [comment]
> > if linux is ok for you, I can help you.
> > I used colmap on win a few months ago, no env today.
> > please fellow me step by step, in 3 minutes:
> > @ubuntu-18.04
> > [0000-cuda11.7_pytorch1.13_tinycudann_colmap.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13030759/0000-cuda11.7_pytorch1.13_tinycudann_colmap.txt)
> > [superi_colmap.py.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13030766/superi_colmap.py.txt) [superi_colmap2nerf.py.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13030767/superi_colmap2nerf.py.txt)
> > my code is very simple, no any garbage.
> 
> Ah, I appreciate the quick response, but my work runs Windows on their computers. I'm also a huge beginner with this kind of stuff but nothing seems too confusing so far. Just this one issue where colmap isn't found or recognized.
> 
> Thanks for the help though!

Thank you very much for sharing your code. Is there any code for custom image data without video?

**Comment by leejngmn** [comment]
> if linux is ok for you, I can help you.
> 
> I used colmap on win a few months ago, no env today.
> 
> please fellow me step by step, in 3 minutes:
> 
> @ubuntu-18.04
> 
> [0000-cuda11.7_pytorch1.13_tinycudann_colmap.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13030759/0000-cuda11.7_pytorch1.13_tinycudann_colmap.txt)
> 
> [superi_colmap.py.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13030766/superi_colmap.py.txt) [superi_colmap2nerf.py.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13030767/superi_colmap2nerf.py.txt)
> 
> my code is very simple, no any garbage.

Thank you very much for sharing your code. Is there any code for custom image data without video?
