### ISSUE TITLE
what is the better viewer?

### ISSUE THREAD

**Issue by yuedajiong** [graphdeco-inria/gaussian-splatting#340]
1. algorithm output and viewer input:  the final result of this algorithm is .ply   (from a small 'input.ply' splat to a bigger output 'point_cloud.ply')
2. view methods:   
    a)modified SIBR, windows-ONLY, CUDA needed !!!
    b)a special gauss-splat branch in NerfStudio
    x)can not directly view by common .ply tool.    (right?)
3. what is the better viewer?
    a) is the max-iteration best? maybe not.
    b) if my understanding to 2.x is right, can we export training PC to a public .ply that can be loaded by common .ply tool，and without information loss.

anyway，continue to learn， rewrite a simpler version.

**Comment by jaco001** [comment]
From my expireience
AD 1. input.ply -> 'normal' .ply file
point_cloud.ply -> 'normal' .ply file + extra data that you loose if open in 'normal tools'
AD 2.  You can use Blender plugins, Unity or Unreal Engine (game engine plugins)
For viewing it is ok, but there is conversion to internal engine particles (eg. UE Niagara)
AD 3 a)  max-iteration vs quality depends of dataset.  Usually 30000 is OK. Over training give bigger files and extra noise. So experiment 

Tip: 
1. You can edit .ply before training to remove some points with normal tools (eg. MeshLab)
2. SIBR to some degree allow to crop model and save it. It helps if you want to focus on one part of scene.

**Comment by yuedajiong** [comment]
not an issue

**Comment by hepeixin123** [comment]
> 从我的到期 AD 1.input.ply -> 'normal' .ply 文件 point_cloud.ply -> 'normal' .ply 文件 + 如果在“普通工具”中打开，您将丢失的额外数据 AD 2.您可以使用 Blender 插件、Unity 或 Unreal Engine（游戏引擎插件）来查看它是可以的，但可以转换为内部引擎粒子（例如。UE Niagara） AD 3 a） 最大迭代与质量取决于数据集。通常 30000 就可以了。过度训练会产生更大的文件和额外的噪音。所以实验
> 
> 提示：
> 
> 1. 您可以在训练前编辑 .ply 以使用普通工具删除一些点（例如。MeshLab）
> 2. SIBR 在某种程度上允许裁剪和保存模型。如果您想专注于场景的某一部分，它会有所帮助。

why I use the meshlab to .ply,it have not color?
