### ISSUE TITLE
why the export .ply file has no faces,and how to export an .obj file

### ISSUE THREAD

**Issue by ilovebing** [graphdeco-inria/gaussian-splatting#341]
hi ,i impressed your work. But when i export model file , it just has .ply type. when i open it by using blender or meshlab and want to transfer it to obj , the softwares told me that there has no faces. 
can you tell me how to fix it , my coding ablitity is poor. thank you very much

**Comment by grgkopanas** [comment]
Hi,

The models that come out from our method are an augmented point cloud with
extra properties such that each point represents a semi transparent
ellipsoid in 3D space.

This means that it is not trivial to be exported in any way as a
traditional assets. There are some tools to import those in unreal engine
and unity but these are done by the community and we do not support them so
you have to search on the web for more info.

Best,
Geoge

**Comment by yuedajiong** [comment]
1.  this .ply just named .ply, not a standard .ply.
2. you can refer to DreamGauss, that includes mesh exporter (the .ply  ~=  mesh .ojb, I guess).   (please cite this paper too :-) )
3. I am rewriting this code, and I think I can find a proper way to show the .ply++ format.
