### ISSUE TITLE
LLFF Dataset

### ISSUE THREAD

**Issue by aiyb1314** [graphdeco-inria/gaussian-splatting#342]
The model does not support the camera format of the LLFF dataset, is there any way to convert it to a supported format?

**Comment by ricshaw** [comment]
Any update on this?

**Comment by grgkopanas** [comment]
It's not in our plans, front-facing scenes was not our goal

**Comment by rdzhao** [comment]
https://github.com/graphdeco-inria/gaussian-splatting/assets/25854909/c5970ccb-27df-4ef0-b693-506ad624efde

LLFF dataset, Room has floater issues at textureless region.

**Comment by mldemox** [comment]
May I ask how you are doing the reading of the LLFF data? Can you provide a code example?

**Comment by YunSeok-Kang** [comment]
First, run the COLMAP image undistorter with the following command:
`colmap image_undistorter --image_path datasets/nerf_llff_data/fern/images --input_path datasets/nerf_llff_data/fern/sparse/0 --output_path datasets/nerf_llff_data/processed/fern --output_type COLMAP
`
This command is an example of how to process the ‘fern’ dataset.

After running the image undistorter, navigate to the processed/fern directory and create a new directory named ‘0’ inside the ‘sparse’ directory.

Finally, move the cameras.bin, images.bin, and points3D.bin files into the newly created ‘0’ directory.

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/16894765/e085bc15-0059-4631-9da7-1ea6a99ba494)
