### ISSUE TITLE
How can I measure the FPS as reported in the paper?

### ISSUE THREAD

**Issue by askmgk** [graphdeco-inria/gaussian-splatting#349]
I wanted to measure the FPS (Frames Per Second) of the Tanks & Temples dataset using the 'render.py' script. I used the 30K-pretrained model provided in the source code. As described in the paper, I performed the measurements on a single A6000 GPU, but I obtained an FPS of around 3.

The paper reports an FPS of 154  (in Table 1) on the a6000 GPU, and I'd like to know how to measure it correctly. If there are any modifications needed in the code, I'd like to know about them.

**Comment by grgkopanas** [comment]
Make sure you don't save anything on the disk and you only measure the
render function.

**Comment by askmgk** [comment]
Thanks for the response. I commented out the image saving codes and it was fixed!
