### ISSUE TITLE
After executing" Python convert. py - s data \mp4", only half of the images folder in the input folder is obtained? How to solve the missing part of PLY after training

### ISSUE THREAD

**Issue by liuzhao6322** [graphdeco-inria/gaussian-splatting#354]

**Comment by liuzhao6322** [comment]
After executing" Python convert. py - s data \mp4" ，Fewer images in the images folder ，For example, if there are 300 images in the input, only 200 images will be generated? How to solve it

**Comment by Snosixtyboo** [comment]
Hi,

sorry, this appears to be an issue with COLMAP, which we don't maintain. Please consider messaging the original authors. Our approach starts from the assumption that the established calibration via COLMAP is successful.

Hth,
Bernhard
