### ISSUE TITLE
Python convert. py - s failed. I shot it using 300 ，1280 * 720 building image sequences and a drone

### ISSUE THREAD

**Issue by liuzhao6322** [graphdeco-inria/gaussian-splatting#355]
Registering image #122 (3)
==============================================================================

  => Image sees 1712 / 7033 points
  => Could not register, trying another image.

==============================================================================
Registering image #182 (3)
==============================================================================

  => Image sees 1285 / 6986 points
  => Could not register, trying another image.

==============================================================================
Registering image #121 (3)
==============================================================================

  => Image sees 1667 / 6985 points
  => Could not register, trying another image.

==============================================================================
Registering image #120 (3)
==============================================================================

  => Image sees 1649 / 7098 points
  => Could not register, trying another image.

==============================================================================
Registering image #183 (3)
==============================================================================

  => Image sees 1254 / 7050 points
  => Could not register, trying another image.

==============================================================================
Finding good initial image pair
==============================================================================

  => No good initial image pair found.

Elapsed time: 42.711 [minutes]
ERROR: failed to create sparse model
ERROR:root:Mapper failed with code 1. Exiting.
(gaussian_splatting) PS E:\gaussian-splatting>

**Comment by Snosixtyboo** [comment]
Hi,

sorry, this appears to be an issue with COLMAP, which we don't maintain. Please consider messaging the original authors. Our approach starts from the assumption that the established calibration via COLMAP is successful.

Hth,
Bernhard

**Comment by QY0911** [comment]
Hi @liuzhao6322,
I encountered the same issue, could you tell me how you solved it? Many thanks!

**Comment by pyl122516** [comment]
> 的问题，我们不维护

pls,you have fix it? i have same problem
