### ISSUE TITLE
Point Cloud Seems super noisy

### ISSUE THREAD

**Issue by yytang220** [graphdeco-inria/gaussian-splatting#36]
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/99238776/acb515dd-13e3-4172-b627-3f29d7fbfa1a)

the red part is the only valid part, the rest seems out side of camera. In my opinion, your method shoud produce a more valid pointcloud since using splatting as rendering method?

Any idea how to generate a more valid point cloud in future work?

**Comment by Snosixtyboo** [comment]
Hi,

generating a geometrically correct model is not in the scope of this work, it is about matching the appearance of the target images from the desired views. Spatial discrepancies are very much expected, just like with the density samples of NeRFs. I am not sure which type of data set it is, the distant objects could very well be modeling distant background? But yes, we are definitely working towards how the reconstructed point clouds could be used as the BASIS for proper geometry reconstruction :)

Best,
Bernhard

**Comment by yytang220** [comment]
Thanks for your reply, it is a cellphone-colllected llff-style data. Look forward to your future work. This approach is pretty efficient.
