### ISSUE TITLE
Question regarding deep blending dataset preparation

### ISSUE THREAD

**Issue by ywyue** [graphdeco-inria/gaussian-splatting#371]
Dear authors, thanks for this amazing work! It is great that you provided the processed two scenes (DrJohnson and Playroom) from the Deep Blending dataset. I am trying to convert other scenes in the dataset to the required format by 3D-GS. I wonder could you please provide an instruction on how to preprocess the raw data from Deep Blending? Thanks in advance!

**Comment by grgkopanas** [comment]
Using the highest resolution images provided in the datasets and then
following the instructions of the readme is your best bet.

**Comment by ywyue** [comment]
Oh, sorry, I missed the [Processing your own Scenes](https://github.com/graphdeco-inria/gaussian-splatting#processing-your-own-scenes) part in the readme. Closed the issue for now.
