### ISSUE TITLE
simple-knn link broken?

### ISSUE THREAD

**Issue by henrypearce4D** [graphdeco-inria/gaussian-splatting#372]
Is the link for the submodule simple-knn broken?
It would explain this issue https://github.com/graphdeco-inria/gaussian-splatting/issues/346

https://github.com/graphdeco-inria/gaussian-splatting/blob/main/submodules/simple-knn

camenduru's fork is available 
https://github.com/camenduru/simple-knn

**Comment by henrypearce4D** [comment]
I see actually in .gitmodules the url is different;
https://github.com/graphdeco-inria/gaussian-splatting/blob/main/.gitmodules

url = https://gitlab.inria.fr/bkerbl/simple-knn.git


So should the link isn the submodules folder be disregarded?


And does running this overcome the url change?
```
git submodule sync --recursive
git submodule update --init --recursive --force
```

**Comment by Snosixtyboo** [comment]
Hi,

I believe this is an issue only with github.com's website, which automatically interprets submodules as something that must come from github.com, even if that is not true. As you pointed out, the .gitmodules points to gitlab, there never was a github version. So you should only run into that problem if you try to manually click the submodules link from the github.com page, if you clone with submodules there should not be an issue.

If I'm wrong and you have other info, please let me know :)

Hth,
Bernhard
