### ISSUE TITLE
Issues when using WSL2

### ISSUE THREAD

**Issue by Xzzit** [graphdeco-inria/gaussian-splatting#378]
I'm using WSL2 with Ubuntu 22.04.2 on Windows 11 platform.
`glxinfo | grep "OpenGL version"` shows: `OpenGL version string: 4.2 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1`

* **What has been done successfully:**
1. Running `python train.py path_to_my_data_file` successfully trains the model and generates the following directory structure:
```
<scene_name>
|---point_cloud
|   |---<iteration_7000>
|       |---point_cloud.ply
|   |---<iteration_30000>
|       |---point_cloud.ply
|---cameras.json
|---cfg_args
|---input.ply
```
2. SIBR_viewer has been successfully installed. Both `SIBR_remoteGaussian_app` and `SIBR_gaussianViewer_app` can be found in `SIBE_viewer/install/bin` directory.

* **What can not be done successfully:**
1. During training, I cannot view or interact with the scene in my browser.
```
(gnerf) xzz@xzzit:~/project/gaussian-splatting$ python train.py -s /mnt/d/tandt_db/tandt/train/ -m ./output/train
Optimizing ./output/train
Output folder: ./output/train [24/10 02:44:06]
Tensorboard not available: not logging progress [24/10 02:44:06]
Reading camera 301/301 [24/10 02:44:09]
Converting point3d.bin to .ply, will happen only the first time you open the scene. [24/10 02:44:09]
Loading Training Cameras [24/10 02:44:11]
Loading Test Cameras [24/10 02:44:18]
Number of points at initialisation :  182686 [24/10 02:44:18]
Training progress:   0%|                                                                                                                         | 0/30000 [00:00<?, ?it/s]
Connected by ('127.0.0.1', 56528) [24/10 02:44:18]

Connected by ('127.0.0.1', 56536) [24/10 02:44:18]

Connected by ('127.0.0.1', 55106) [24/10 02:44:19]
Training progress:   1%|▋                                                                                              | 200/30000 [00:05<10:53, 45.60it/s, Loss=0.2207987]
Connected by ('127.0.0.1', 48646) [24/10 02:44:24]
Training progress:   1%|▋                                                                                              | 210/30000 [00:06<10:52, 45.63it/s, Loss=0.2001045]
Connected by ('127.0.0.1', 48654) [24/10 02:44:24]
```
and in my browser, it displays the error message: `This page isn’t working. 127.0.0.1 didn’t send any data. ERR_EMPTY_RESPONSE.`

2. I can not use gaussianViewer for a pre-trained model
```
(gnerf) xzz@xzzit:~/project/gaussian-splatting$ ./SIBR_viewers/install/bin/SIBR_gaussianViewer_app -m output/train/
[SIBR] --  INFOS  --:   Initialization of GLFW
[SIBR] ##  ERROR  ##:   FILE /home/xzz/project/gaussian-splatting/SIBR_viewers/src/core/graphics/Window.cpp
                        LINE 30, FUNC glfwErrorCallback
                        GLX: Failed to create context: GLXBadFBConfig
terminate called after throwing an instance of 'std::runtime_error'
  what():  See log for message errors
Aborted
```

**Comment by AdvancedHe** [comment]
How to solve this problem?

**Comment by hh0525** [comment]
I meet the same problem in WSL2.

**Comment by xuyanging** [comment]
I think i might be the version of opengl, I successfully run it with opengl 4.5, but meet the same problem when it comes to v4.3 in wsl2

**Comment by Xzzit** [comment]
> I think i might be the version of opengl, I successfully run it with opengl 4.5, but meet the same problem when it comes to v4.3 in wsl2

Thank you so much for your reply! I updated my OpenGL in WSL2 from version 4.2 to 4.5, and it worked! However, I noticed that running `SIBR_remoteGaussian_app` during training significantly slows down the process.

Here's how I did it:
```
sudo add-apt-repository ppa:kisak/kisak-mesa
sudo apt update
sudo apt upgrade
```
