### ISSUE TITLE
how to save video by the sibr_viewer?

### ISSUE THREAD

**Issue by daxue2017** [graphdeco-inria/gaussian-splatting#380]
if click the checkbox  save video (from playing),  and set the save path, there is no video file in the path. so how to save video by the sibr_viewer?
![savevideo](https://github.com/graphdeco-inria/gaussian-splatting/assets/43563918/8b9a139f-96e5-44bb-8a3a-bb86e91b5e9d)

**Comment by henrypearce4D** [comment]
This comment should help, if it does, report back and then close the issue :)

https://github.com/graphdeco-inria/gaussian-splatting/issues/59#issuecomment-1650099134
