### ISSUE TITLE
[Ubuntu20.04] SIBR Viewer build error

### ISSUE THREAD

**Issue by APPZ99** [graphdeco-inria/gaussian-splatting#383]
Hello authors! Thank you very much for such an excellent project!

I encountered the following error message when installing SIRB Viewer on Ubuntu 20.04 system.

`cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release`

`-- Populating library imgui...
CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.

CMake Error at /usr/local/share/cmake-3.22/Modules/FetchContent.cmake:1075 (message):
  CMake step for imgui failed: 1
Call Stack (most recent call first):
  /usr/local/share/cmake-3.22/Modules/FetchContent.cmake:1111 (__FetchContent_directPopulate)
  cmake/linux/sibr_library.cmake:143 (FetchContent_Populate)
  cmake/linux/dependencies.cmake:286 (sibr_gitlibrary)
  cmake/linux/include_once.cmake:20 (include)
  src/CMakeLists.txt:46 (include_once)

-- Configuring incomplete, errors occurred!
`

This problem seems to be caused by imgui, but I couldn't find a corresponding solution. I'd be very grateful if you could help.

**Comment by poet77** [comment]
I had the same problem. And the above method does not work for me. Can anybody help me?

**Comment by APPZ99** [comment]
After I deleted the entire build file, I re-ran the following command:

`cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release -G Ninja`

and then compiled successfully.

**Comment by hg111** [comment]
@APPZ99  Good to hear you got SIBR Viewer to work on Ubuntu 20.04. I am still trying and no luck so far on Aarch64, What architecture is your machine?  Wouuld you mind sharing your enviornment and steps?
