### ISSUE TITLE
about the projection matrix

### ISSUE THREAD

**Issue by willer94** [graphdeco-inria/gaussian-splatting#388]
Hi, I think there is a small bug about the projection matrix at     
[P[2, 2] = z_sign * zfar / (zfar - znear))](https://github.com/graphdeco-inria/gaussian-splatting/blob/f11001b46c5c73a0a7d553353c898efd68412abe/utils/graphics_utils.py#L69)

It should be P[2, 2] = z_sign *(zfar + znear) / (zfar - znear)).

When zfar is larger enough than zfar, the both computation results can be very close.

Please refer to http://www.songho.ca/opengl/gl_projectionmatrix.html

**Comment by grgkopanas** [comment]
Hi thank you for noticing, I think that we do not really use the normalized depth anywhere. But thanks for noticing.

Best,
George

**Comment by willer94** [comment]
What's more, are you going to support more camera models? such as the opencv model.

**Comment by willer94** [comment]
Ok,  I am going to implement it in this weekend.
Thanks for your outstanding work!

**Comment by ZhouCX117** [comment]
@willer94 Hi, sorry to bother you. Could you please share your code for the open CV model? I realized one but the results seem incorrect.
