### ISSUE TITLE
Random Point Initialization

### ISSUE THREAD

**Issue by muskie82** [graphdeco-inria/gaussian-splatting#39]
Thank you very much for sharing the amazing work.

Is there any easy way to try random point initialization instead of SfM points as shown in Table 3 in the paper?
I don't find the argument options in train.py.

Sincerely,

**Comment by grgkopanas** [comment]
Hi,

I think I hacked it myself just for the shake of the experiment and never
actually made a proper way to control it for scenes other than nerf
synthetic.

Should not be super hard to replacing the point cloud with a random one
here:

https://github.com/graphdeco-inria/gaussian-splatting/blob/5c04e3574315ff9f4df1a8d5d34795bb90d7b986/scene/dataset_readers.py#L160

If you have time, feel free to try to make it properly controllable with a
flag and we will happily accept this pull request.

Best,
George

**Comment by Snosixtyboo** [comment]
@muskie82 If you are interested in doing it for the Blender data set, for those (and those only) we have included automatic random initialization.

**Comment by muskie82** [comment]
@grgkopanas  @Snosixtyboo 
Thank you very much for your prompt reply. I will try it.
