### ISSUE TITLE
I think '--ImageReader.single_camera' in convert.py should be 0 instead of 1. 

### ISSUE THREAD

**Issue by gwxxx** [graphdeco-inria/gaussian-splatting#390]
If use 1, the number of undistorted images is not same as input images.

**Comment by gwxxx** [comment]
sorry, is a mistake.

**Comment by grgkopanas** [comment]
Indeed 1 would not be a bad choice but we decided to go with 0 such that we
are compatible with other nerf implementations that do not implement
different intrinsics for different views.
