### ISSUE TITLE
The Gaussian-Splatting create a brand-new era for stereo vision, likes CNN, Transformer!!!     and has anybody plan to develop a powerful Gauss-Point based editor, not only differentable-render and viewer.

### ISSUE THREAD

**Issue by yuedajiong** [graphdeco-inria/gaussian-splatting#398]
as title

**Comment by Fanie-Visagie** [comment]
In progress...

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: yuedajiong ***@***.***>
Sent: Friday, October 27, 2023 12:04:26 PM
To: graphdeco-inria/gaussian-splatting ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [graphdeco-inria/gaussian-splatting] The Gaussian-Splatting create a brand-new era for stereo vision, likes CNN, Transformer!!! and has anybody plan to develop a powerful Gauss-Point based editor, not only differentable-render and viewer. (Issue #398)


as title
