### ISSUE TITLE
Can you explain more about binning in rasterizer?

### ISSUE THREAD

**Issue by wanmeihuali** [graphdeco-inria/gaussian-splatting#40]
Hi, the work is great! I'm trying to migrate the Algorithm to some other platform. 
During reading your code, I notice that you implement a GPU memory pool in your rasterizer and use an alignment of 128. I'm curious about the idea behind this design decision. I'm wondering if the GPU memory pool help. Is there any data point/experiment result comparing using/not using the GPU memory pool?

Thanks!

**Comment by Snosixtyboo** [comment]
Hi,

thanks a lot for your interest!

The reason for this memory pool is to make the rasterizer compatible with complex pytorch pipelines (e.g., running multiple forwards and preserving the context before one backup is run). To do this, we need to keep the internal state of the rasterizer around. Our internal state consists of multiple buffers. We were wary of how pytorch would handle 20+ resize operations of large buffers, that is why we compressed it into 3 memory pools and then deconstruct them into the buffers ourselves. It might very well be overkill, we never tried without it.

Hth,
Bernhard

**Comment by wanmeihuali** [comment]
Thanks for the information!
