### ISSUE TITLE
Question on Densification

### ISSUE THREAD

**Issue by ljjTYJR** [graphdeco-inria/gaussian-splatting#404]
Hi,
Thanks for open-sourcing the excellent work.

I am doing some experiments on the code: If I want to disable the _Densification_ module, do I only need to comment on the following lines?

```python
    def densify_and_prune(self, max_grad, min_opacity, extent, max_screen_size):
        grads = self.xyz_gradient_accum / self.denom
        grads[grads.isnan()] = 0.0

        # self.densify_and_clone(grads, max_grad, extent)
        # self.densify_and_split(grads, max_grad, extent)

        prune_mask = (self.get_opacity < min_opacity).squeeze()
        # if max_screen_size:
        #     big_points_vs = self.max_radii2D > max_screen_size
        #     big_points_ws = self.get_scaling.max(dim=1).values > 0.1 * extent
        #     prune_mask = torch.logical_or(torch.logical_or(prune_mask, big_points_vs), big_points_ws)
        self.prune_points(prune_mask)

        torch.cuda.empty_cache()
```

I also commented on the _pruning_ lines because I noticed that If not, nearly all points will be pruned eventually.

**Comment by Snosixtyboo** [comment]
Hi,

you could just set the ```--densify_from_iter``` to e.g. ```0```, then neither densification nor pruning should happen

**Comment by ljjTYJR** [comment]
OK, thanks.

**Comment by HungNgoCT** [comment]
> Hi,
> 
> you could just set the `--densify_from_iter` to e.g. `0`, then neither densification nor pruning should happen

Hi @Snosixtyboo ,

I think `--densify_from_iter` to a value that is greater than iterations, not 0 as you indicated right?

**Comment by Gurutva** [comment]
Is it that if i've 5000 iterations, so to disable densification, i'll add flag --densify_from_iter=5001 or so? please clarify !!
@Snosixtyboo @HungNgoCT 
> > Hi,
> > you could just set the `--densify_from_iter` to e.g. `0`, then neither densification nor pruning should happen
> 
> Hi @Snosixtyboo ,
> 
> I think `--densify_from_iter` to a value that is greater than iterations, not 0 as you indicated right?

**Comment by HungNgoCT** [comment]
> Is it that if i've 5000 iterations, so to disable densification, i'll add flag --densify_from_iter=5001 or so? please clarify !! @Snosixtyboo @HungNgoCT
> 
> > > Hi,
> > > you could just set the `--densify_from_iter` to e.g. `0`, then neither densification nor pruning should happen
> > 
> > 
> > Hi @Snosixtyboo ,
> > I think `--densify_from_iter` to a value that is greater than iterations, not 0 as you indicated right?

Hi @Gurutva ,

I understood like you did. But don't sure if I was wrong.
