### ISSUE TITLE
"warm-up" the computation in lower resolution.

### ISSUE THREAD

**Issue by ywyue** [graphdeco-inria/gaussian-splatting#412]
Hi authors, it was mentioned in the paper 7.1 Implementation - Optimization Details: "For stability, we "warm-up" the computation in lower resolution. Specifically, we start the optimization using 4 times smaller image resolution and we upsample twice after 250 and 500 iterations." 

However, I didn't find the corresponding code - Could you please point it out to me? 

Thanks in advance!

**Comment by grgkopanas** [comment]
The warm phase in low resolution seemed to helped in some experiment we
originally did. Later on after fixing a few initialization issues here and
there we tried to ablate it again and showed no impact so we removed it for
the shake of simplicity.

**Comment by ywyue** [comment]
Thank you for the reply! A quick follow-up question: I noticed that if the input image is larger than 1600px, it will be automatically resized to 1600px. However, the FovX and FovY still come from the original camera info ([here](https://github.com/graphdeco-inria/gaussian-splatting/blob/f11001b46c5c73a0a7d553353c898efd68412abe/utils/camera_utils.py#L49)) calculated from the original image width/height. I wonder is there any motivation behind this?

**Comment by jb-ye** [comment]
@grgkopanas What if I train the image on 4k+ images without downscaling to 1600, can coarser-to-fine warm-up help for high resolution input images?

**Comment by grgkopanas** [comment]
Potentially, many of these tricks are hand wavy and experimentally based so
you can only be sure if you try

**Comment by kwea123** [comment]
@ywyue fov doesn't change if you maintain the image aspect ratio while resizing

**Comment by chenqi13814529300** [comment]
> @grgkopanas What if I train the image on 4k+ images without downscaling to 1600, can coarser-to-fine warm-up help for high resolution input images?

Have you tried this please, I suddenly see this problem?
