### ISSUE TITLE
Training on sub-clip of a large scene results in weired (blurry and cropped) result

### ISSUE THREAD

**Issue by HrsPythonix** [graphdeco-inria/gaussian-splatting#414]
Hello, I captured a whole park with around 15000 images and succeed in using colmap to reconstruct the camera pose and sparse point cloud.

during training, I manually added clip operation in dataset_reader.py to take cameras only in a sub-region for training, but use the whole sparse cloud as initialization, each clip has around 1000-2000, after training the clip, the preview result looks weird, the pixels near the camera is very blurry and seems to be cropped. Any idea about this behavior?
 
video attached below:
https://github.com/graphdeco-inria/gaussian-splatting/assets/16586180/775496c6-a1dc-44c6-8f95-c14241f1e38f

**Comment by jb-ye** [comment]
It looks like a near-plane clipping effect. If you rescale the entire scene by 10x (for translation component of pose), it may be less?

**Comment by HrsPythonix** [comment]
> It looks like a near-plane clipping effect. If you rescale the entire scene by 10x (for translation component of pose), it may be less?

Thanks! sounds like a reasonable advice, I will give it a try and comment back.

**Comment by HrsPythonix** [comment]
> It looks like a near-plane clipping effect. If you rescale the entire scene by 10x (for translation component of pose), it may be less?

worked out fine, Thank you again

**Comment by entracte-arlo** [comment]
Hi HrsPythonix
I'm interested in testing your solution to create sub-regions for training
How do you add a clip operation? Do you modify the source code of the original repository? Or you prepare the sub-regions during the colmap alignment?

**Comment by HrsPythonix** [comment]
> Hi HrsPythonix I'm interested in testing your solution to create sub-regions for training How do you add a clip operation? Do you modify the source code of the original repository? Or you prepare the sub-regions during the colmap alignment?

Hi, you can simply create sub-regions by first dividing the input cameras into different clips, eg. by clustering, and then for each clip train a separate gaussian splatting model. I do the clipping after the colmap alignment because I need to bring them together after training each clip.

**Comment by entracte-arlo** [comment]
Hi, I also need to bring the gaussian splatting models together after training each clip

I'm trying to make some tests, processing very large areas. My solution was to proces the sfm using RealityCapture. I have all the cameras aligned in RC. I divide the areas into differnt sub-regions, export the alignmernt in a colmap compatible format, train, and bring together the gaussian splatting models.

However, if there was a way to do the clipping after the alignment, that would be much better

If we use the original repo, the method is not created for very large scenes:
https://github.com/graphdeco-inria/gaussian-splatting/issues/200

I've tried to adjust the learning rates  (--position_lr_init, --position_lr_final, --scaling_lr), but in my tests, if I divide the area into sub-regions, the quality is always much better

**Comment by HungNgoCT** [comment]
> > It looks like a near-plane clipping effect. If you rescale the entire scene by 10x (for translation component of pose), it may be less?
> 
> worked out fine, Thank you again

Hi @HrsPythonix , @jb-ye ,

Could you please share with me how to and where to rescale the entire scene? I meant where I can scale up in the Gaussian-splatting codebase? Or scale up from Colmap?

Thank you in advance for your advice
