### ISSUE TITLE
Where is the culling ?

### ISSUE THREAD

**Issue by YoannSo** [graphdeco-inria/gaussian-splatting#42]
Hi ! Your work is truly amazing. 
I have one question about the renderer, i would like to know where do you cull the 3D Gaussian on the tiles.
Thanks

**Comment by Snosixtyboo** [comment]
Hi,

this happens in the ```submodules/diff-gaussian-rasterization/rasterizer_impl.cu```

We have the functions
```
preprocess
InclusiveSum
duplicateWithKeys
SortPairs
identifyTileRanges
```
- The first identifies for each Gaussians how many tiles it overlaps (by checking against their bounding rectangle)
```tiles_touched[idx] = (rect_max.y - rect_min.y) * (rect_max.x - rect_min.x);```
- The second computes the offsets where each Gaussian write its (tile ID | depth) keys
- The last one then write the actual (tile ID | depth) keys
- Then we sort them by their key
- And lastly we find where the sorted list of keys goes from tile ID X to tile ID Y, giving us the start and end of sublists of Gaussians overlapping with each individual tile.

**Comment by YoannSo** [comment]
ok thanks for the clarification

**Comment by JiatengLiu** [comment]
Hi, @Snosixtyboo @YoannSo 
I have a problem with the process of sorting gs. After sorting we get the `collected_id` and use it in forward, if I want to sort gs in my own way and get the `collected_id` of a pixel and use it in foward and backward, what should I do?
