### ISSUE TITLE
Some part of the renderings are cropped.

### ISSUE THREAD

**Issue by DevikalyanDas** [graphdeco-inria/gaussian-splatting#429]
Thanks for your great contribution. I am trying to render this point cloud using gaussian splatting,  
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/14145901/cd9f294e-dab0-4036-b4d6-e496a7481c50)

But, the renderings appear to be cropped 
![00070](https://github.com/graphdeco-inria/gaussian-splatting/assets/14145901/343a7f62-83a8-4e1a-a8c7-fb566cfb60b7)

I don't understand why it happens. For other poses, I am able to get full renderings, but for certain poses, I am getting similar cropped ones. Can anyone tell where the issue can be?

**Comment by jaco001** [comment]
As I thinking about GS:
In short color/alpha/size of GS depend if  it was present at camera input. If not you get approximation. 
This way you get almost perfect camera views and rest is 'cloudy'. This give you illusion that you have more data then you got.
If you move too far away from the camera positions you will see more noise.

**Comment by DevikalyanDas** [comment]
Hello, this is just a training view. Also, from the beginning of the training, this part is not visible. This happens for certain views, for all other views this part is visible.

**Comment by DevikalyanDas** [comment]
Solved: Changed the p_view.z parameter in the auxiliary.h file in diff-gaussain_rasterizer to allow gaussians that are closer to the camera

**Comment by DevikalyanDas** [comment]
Solved: Changed the p_view.z parameter in the auxiliary.h file in diff-gaussain_rasterizer to allow gaussians that are closer to the camera

**Comment by Reed-yang** [comment]
same issue and `Changed the p_view.z parameter in the auxiliary.h` did work, even change to 0.0f, still cropped
