### ISSUE TITLE
Real time viewer all black when the trained model doesn't use the default sh degree

### ISSUE THREAD

**Issue by aoliao12138** [graphdeco-inria/gaussian-splatting#43]
Great work! When I train the model using different sh degrees like 1 or 2 and use the viewer to visualize the result. It seems that the screen all turns black. When the sh degree of the training model is 3, it works well. Did I mix up something?  Or is the viewer only supporting the sh degree at 3? Thank you very much!

**Comment by Snosixtyboo** [comment]
Hi,

thanks for noticing, another user has brought this to our attention and we will be adding support for scenes with less than 3 SH degrees, hopefully by tomorrow.

Best,
Bernhard
