### ISSUE TITLE
config file 'cfg_args' not found at C:

### ISSUE THREAD

**Issue by JackySlo** [graphdeco-inria/gaussian-splatting#431]
I'm on the last step before opening the viewer and this pops up in cmd
![image_2023-11-05_194555858](https://github.com/graphdeco-inria/gaussian-splatting/assets/51710304/1501d755-f386-4743-9c30-ccad012d5967)
I have the file, or at least I believe that's the one
![image_2023-11-05_194648976](https://github.com/graphdeco-inria/gaussian-splatting/assets/51710304/23ed140e-f62b-45ee-8ae3-047bca3778a0)
Am I doing anything wrong?
Should the config file be anywhere else?
Thanks in advance and cheers

**Comment by jaco001** [comment]
If you have path with spaces or exotic chars is better use " ". Small windows tip.

**Comment by JackySlo** [comment]
Thank you very much, everything works normally now. I guess cmd really doesn't like spaces :)
