### ISSUE TITLE
How to transform point_cloud.ply to depth map?

### ISSUE THREAD

**Issue by gwxxx** [graphdeco-inria/gaussian-splatting#436]

**Comment by gwxxx** [comment]
During rendering, depth map can be directly outputted.

**Comment by ThePassedWind** [comment]
hello, could you please explain how to output depth map?

**Comment by uuu686** [comment]
hello, can you tell me how to get the depth?

**Comment by johnren-code** [comment]
same question, can you tell the details?

**Comment by gwxxx** [comment]
use z-buffer, and render the depth map just the same as RGB rendering.

**Comment by jingyuzhao1010** [comment]
> use z-buffer, and render the depth map just the same as RGB rendering.

hi,
Could you please show the relevant code?I've been struggling with this problem lately
