### ISSUE TITLE
Any great-master tell me why the author split sh-color-feature into features_dc[-1,1] and features_rest[-1,15]? just have different learning-rate.

### ISSUE THREAD

**Issue by yuedajiong** [graphdeco-inria/gaussian-splatting#438]

**Comment by Snosixtyboo** [comment]
Yes, we do it just to be able to give them different learning rates for Adam, that's all. Too high learning rates for the higher bands lead to too strong view-dependent overfitting.

Hth,
Bernhard

**Comment by yuedajiong** [comment]
thanks great-master.   @Snosixtyboo 
you are so kindly.
