### ISSUE TITLE
Render.py require a lot more VRAM than the SIBR viewer

### ISSUE THREAD

**Issue by HrsPythonix** [graphdeco-inria/gaussian-splatting#44]
Using the same model, it cost 6GB-16GB VRAM when use render.py to render on my A10 card. But on my 2080 card with only 8GB it can run the viewer smoothly. How could that happen?

Any idea to reduce the VRAM requirment when use  render.py

**Comment by HrsPythonix** [comment]
I am training on my own data, around 700-800 1920*1080 images, and I use the --data_device cpu so there should be no data loaded on GPU using render.py.

I observe that, the rendering starts at around 4-5GB VRAM, as the rendering goes on, the VRAM gradually grow to 14.5GB.

I tried to add a line as below to constrain the VRAM usage in render.py, as A10 has 24GB VRAM, 24*0.3 limit the max VRAM to 7.2GB, but the expected CUDA OOM is not appeared.

```
torch.cuda.set_per_process_memory_fraction(0.3, 0)
```

But reducing the 0.3 to 0.2 (4.8G) can lead to CUDA OOM after rendering 50 images.

So how

**Comment by Snosixtyboo** [comment]
PyTorch is very liberal with memory if it believes it can reuse it later (caches). I can check if clearing them more frequently might help there.
