### ISSUE TITLE
maybe a bug to load images

### ISSUE THREAD

**Issue by zhao-yiqun** [graphdeco-inria/gaussian-splatting#442]
Hi contributors,

Thanks for your amazing work. When I try to use the rgba image,  I found that the code in this line may not be correct [loaded_mask](https://github.com/graphdeco-inria/gaussian-splatting/blob/main/utils/camera_utils.py#L46). where the code should be 
`if resized_image_rgb.shape[0] == 4:`, since the loaded rgba image in your code is (C, H, W) rather than (H, C, W).

Bests.

**Comment by yuedajiong** [comment]
maybe you are right!

PIL Image.open ->  HWC & C:RGB
no batch, permuted,  so C is 0.  


def PILtoTorch(pil_image, resolution):
    resized_image_PIL = pil_image.resize(resolution)
    resized_image = torch.from_numpy(np.array(resized_image_PIL)) / 255.0
    if len(resized_image.shape) == 3:
        return resized_image.permute(2, 0, 1)
    else:
        return resized_image.unsqueeze(dim=-1).permute(2, 0, 1)
