### ISSUE TITLE
No module named 'diff_gaussian_rasterization'

### ISSUE THREAD

**Issue by Aniruddhqp** [graphdeco-inria/gaussian-splatting#444]
I'm getting the following error, can anyone help beyond this point

(gaussian_splatting) C:\Windows\System32\gaussian-splatting>python train.py -s data/MetalContainer
Traceback (most recent call last):
File "train.py", line 16, in
from gaussian_renderer import render, network_gui
File "C:\Windows\System32\gaussian-splatting\gaussian_renderer_init_.py", line 14, in
from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

**Comment by SebastianWebster** [comment]
Hi, you need to install the submodules

in cli navigate to the root folder of this repo.
`pip install submodules\diff-gaussian-rasterization
pip install submodules\simple-knn`

If running these produces an error then you might need to re-clone the repo with the --recursive flag
Then re-install

**Comment by Aniruddhqp** [comment]
This is the error I'm getting while processing pip install submodules\diff-gaussian-rasterization

(gaussian_splatting) C:\Windows\System32\gaussian-splatting>pip install submodules\diff-gaussian-rasterization
Processing c:\windows\system32\gaussian-splatting\submodules\diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff-gaussian-rasterization
  Building wheel for diff-gaussian-rasterization (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running bdist_wheel
      C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      running build_ext
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
Installing collected packages: diff-gaussian-rasterization
  Running setup.py install for diff-gaussian-rasterization ... error
  error: subprocess-exited-with-error

  × Running setup.py install for diff-gaussian-rasterization did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      running install
      C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-37
      creating build\lib.win-amd64-cpython-37\diff_gaussian_rasterization
      copying diff_gaussian_rasterization\__init__.py -> build\lib.win-amd64-cpython-37\diff_gaussian_rasterization
      running build_ext
      C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> diff-gaussian-rasterization

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Aniruddhqp** [comment]
This is the error I'm getting while processing pip install submodules\simple-knn

(gaussian_splatting) C:\Windows\System32\gaussian-splatting>pip install submodules\simple-knn
Processing c:\windows\system32\gaussian-splatting\submodules\simple-knn
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: simple-knn
  Building wheel for simple-knn (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      running bdist_wheel
      C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_ext
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple-knn
  Running setup.py clean for simple-knn
Failed to build simple-knn
Installing collected packages: simple-knn
  Running setup.py install for simple-knn ... error
  error: subprocess-exited-with-error

  × Running setup.py install for simple-knn did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      running install
      C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      running build
      running build_ext
      C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> simple-knn

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

(gaussian_splatting) C:\Windows\System32\gaussian-splatting>

**Comment by ShaYito** [comment]
I have the same issue, tried `pip install submodules\simple-knn` and re-clone the repo with the --recursive flag Then re-install, but still failed to install simple-knn.

**Comment by SpaceCowboy850** [comment]
Same issue.  I'm on Windows 11.  I've tried with Cuda 11.6, 11.8, 12.1, 12.3 and pytorch 1.13.1 and pytorch 2.1.  I've tried VS2019 and VS2022 command prompts.  Tried python 3.7, 3.9, 3.10.  Nothing seems to work.

My steps (started by using the environment.yaml, but switched to individual to see if some step was causing dependency conflict)

mkdir gaussian_splatting_windows

cd gaussian_splatting_windows
git clone https://github.com/jonstephens85/gaussian-splatting-Windows.git ./
git submodule update --init --recursive 

conda create -n gaussian_splatting python=3.10
conda activate gaussian_splatting
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
conda install -c pytorch -c nvidia plyfile
conda install -c pytorch -c nvidia tqdm
set DISTUTILS_USE_SDK=1
pip install submodules\diff-gaussian-rasterization

[install_diff_gaussian_rasterization.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13444596/install_diff_gaussian_rasterization.txt)

pip install submodules\simple-knn
[install_simple_knn.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13444605/install_simple_knn.txt)

**Comment by maxolib** [comment]
Can you try this solution https://github.com/graphdeco-inria/gaussian-splatting/issues/535#issuecomment-1866575358, solved my issue

**Comment by giscap** [comment]
had the same issue, probably beacause of cuda toolkit 12+ istalled.
1. reinstalled cuda toolkit 11.8
2. ran the two pip install commands 

now everything works fine for me

**Comment by catalpa-bungei** [comment]
I meet the same problem. I'm on Ubuntu 22.04.

**Comment by BlazeGuard111111** [comment]
> I'm getting the following error, can anyone help beyond this point
> 
> (gaussian_splatting) C:\Windows\System32\gaussian-splatting>python train.py -s data/MetalContainer Traceback (most recent call last): File "train.py", line 16, in from gaussian_renderer import render, network_gui File "C:\Windows\System32\gaussian-splatting\gaussian_renderer_init_.py", line 14, in from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

I have successfully solved the problem. Although I am not sure how to implement it, I recommend trying the following methods: 1. Open Visual Studio Installer. 2. Ensure that there are C++components (usually present, can be ignored). 3. Try clicking the repair button, and it will automatically reinstall all components. 4. Allow the code to be rediscovered
!4.I don't think it has anything to do with the cuda version

**Comment by Shashank-Vyas** [comment]
I was having the same problem, so I saw the documentation for the same where it was written "We used **CUDA 11.8** and know **problems in CUDA 11.6**" and I was **using CUDA 11.6**.
So, the steps I followed to solve this issue are:

1. I downloaded **CUDA 11.8** successfully  [.](https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local)

2. `pip install submodules\diff-gaussian-rasterization` run in cmd.

3. `pip install submodules\simple-knn` run in cmd.

This solved my problem.

**Comment by GanLinJackie** [comment]
> I'm getting the following error, can anyone help beyond this point
> 
> (gaussian_splatting) C:\Windows\System32\gaussian-splatting>python train.py -s data/MetalContainer Traceback (most recent call last): File "train.py", line 16, in from gaussian_renderer import render, network_gui File "C:\Windows\System32\gaussian-splatting\gaussian_renderer_init_.py", line 14, in from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

I downloaded the lib from git but still get this error. I just can't understand why pip did't work. My cuda is 11.8 and torch is 2.0.0 as the project recommand. Maybe there are something wrong?

**Comment by wangwenqiao666** [comment]
if you don't have pyproject.toml file, you can touch a pyproject.toml file, then copy under word to pyproject.toml file:
`[build-system]
requires = ["setuptools", "wheel", "torch"]
build-backend = "setuptools.build_meta"`
then run pip install .
