### ISSUE TITLE
'simple-knn' missing

### ISSUE THREAD

**Issue by bnBarr** [graphdeco-inria/gaussian-splatting#446]
the submodel 'simple-knn' is missing, i cant find it in this repo

**Comment by bnBarr** [comment]
when i click on the link to simple-knn in this repo, it says page not found

**Comment by jaco001** [comment]
This is extra repo. 
Try this
https://github.com/graphdeco-inria/gaussian-splatting/issues/444#issuecomment-1801983046

**Comment by bnBarr** [comment]
thank u for this❤. but i wonder why this link cant work
<img width="823" alt="image" src="https://github.com/graphdeco-inria/gaussian-splatting/assets/134189180/fe805e1f-eafd-42e3-9e22-8df78e31754f">

**Comment by kenton0607** [comment]
I faced same situation and I couldn't clone the simple-knn submodule recursively.
