### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by uuu686** [graphdeco-inria/gaussian-splatting#447]
hello, 
   thank you for the great work. When I run the train.py, I meet a error.

![111111](https://github.com/graphdeco-inria/gaussian-splatting/assets/39000973/1e3d7ab5-eef2-41fc-b629-2879486ac63c)

However, if I don't set the `--position_lr_init 0.000016 --scaling_lr 00001`, train process will be right.

I don't know the reason of the problem and I hope you can give me some guidance

**Comment by Snosixtyboo** [comment]
Hi,

you are effectively setting the scaling learning rate to "1", this just might be too high. Is that intentional or a typo?

**Comment by uuu686** [comment]
I'm really sorry that I made a mistake and didn't notice it. Thank you very much. I'll keep trying
