### ISSUE TITLE
how to render four view with fov angle=90 to cover whole scene and has no overlap

### ISSUE THREAD

**Issue by ansj11** [graphdeco-inria/gaussian-splatting#453]
Hi, I trained gaussian splatting, and render four image in left, right, front and behind view with fov angle=90, but the images has some overlap and shift. I am sure that four poses T are same and R can cover 360 angle , what is the reason?
<img width="1272" alt="截屏2023-11-10 14 38 12" src="https://github.com/graphdeco-inria/gaussian-splatting/assets/24786133/149557cc-32c8-487f-9941-1b39c6f95e62">

**Comment by yuedajiong** [comment]
有QQ邮件的大神哈，那是中国人咯，中文了哈。
我是外行，我按照我的理解，解释一下，可能不对。

先说结论，哪怕就是绕目标对象精准的平移，绝大部分时候4视图/90都是不够的。

我们假设一个标准的正方体，每个面有不同的纹理，甚至为了COLMAP定位和后面的GS算法，来构造最容易重构的纹理，比如色块交错的棋盘格子。

当你在一定距离观察（用相机拍照），高度就在四方体中间。得到四张照片。

你可以想想，从四方体的转角方向看过来，两个面怎么可能没有一点点定位和重构的误差？ SfM有误差，后面GS的高斯球有误差，具体是把你所谓的接缝处：搞多了，或者搞掉了，一看SfM定位怎么误差的，二看那个高斯球如何偏，体积多大。
就算SfM是完美的，连数值误差都可以忽略不计； 你可以想象，6个面上有完全不同的纯色，在接头处某个位置是一个大高斯球，没有尖锐的直角切面啊，颜色是按照球谐函数给渲染出来的也不是两面一红一绿啊。
毕竟，这是用高斯球组合，形态和纹理上，在2D投影上给你近似。  你这个few view就恰好卡在这些丢失精度的地方了。


最有效的，还是：多采集一些照片，水平更多角度，elevation上也有一些起伏。

如果你就要硬拼算法：1）SfM定位部分，看如何搞得更准，一旦大偏差就一定引起后面对不齐       2）根据你的场景设计一些保持一致性得损失，不过不太好搞得样子   3）通过生成方向的算法带一些先验过来，比如人体重构把两侧耳朵建没了，先验找补回来。

**Comment by ansj11** [comment]
我理解SfM给定了一个稀疏的重建结果，那么四个视角即使有偏差，也是可以容忍的，毕竟要在投影的物理机制上保证和采集时的真实视图一致，可能会有一些扭曲、模糊。现在是有比较明显的错位和重叠，所以我认为高斯球的误差会更大一些，或许是因为训练和渲染阶段内参不一致导致高斯球没有适配90度fov的内参。只是不知道怎么缓解这个误差？

**Comment by ansj11** [comment]
I find a bug in my four pose generation, the reason is the rotation vector is not y axis in cameras coordinate!
