### ISSUE TITLE
SIBR and WebGL and WebGPU

### ISSUE THREAD

**Issue by OlegSV1** [graphdeco-inria/gaussian-splatting#455]
Hi, There is a deference in rendering results in SIBR viewer and any other viewer that I tried. Is there any way to get results like in SIBR in web based viewer??

![Screenshot 2023-11-10 112334](https://github.com/graphdeco-inria/gaussian-splatting/assets/150429949/95d67efa-4e33-4759-9d24-bc8f78b73c19)

**Comment by yuedajiong** [comment]
a lesson to me: "use official viewer", some unofficial viewers have diffent rendering qualities.
@ https://github.com/graphdeco-inria/gaussian-splatting/issues/424

1. the training uses the official GS renderer, and the loss is computed between original inputs and GS outputs, so, the best renderer should be developed on official renderer, or equivalents.
2. maybe, there are some little differences in low-level API between official CUDA renderer and other renderers, such as openGL, webGL.
3. there is not lighting in GS, I can not make sure whether other unofficial ones used different lighting.
4. does any other one use other rendering steps: interpolation, anti-aliasing, ...

in a world, if you care that little diffenece, please use official viewer, of develop you own viewer based on GS renderer/diff-gaussian-rasterization.

This is unofficial answer, maybe wrong.  :-(

**Comment by OlegSV1** [comment]
Unfachanatly I am base user not a developer thats whi i am serching for ready solution. My thots that the ploblem is somewhere in gamma or bitrate of individual splat before final render (maybe wrong). Did you know if there is GS web viewer in development or ready? I think that Polycam uses proper viewer but there now control ower generation or any settings....

**Comment by yzslab** [comment]
You can try to train with [sh_degree=0](https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/arguments/__init__.py#L49).
Some browser based implementations will discard the view dependent effects, which may bring some inconsistency.
