### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by JunyongPark97** [graphdeco-inria/gaussian-splatting#456]
I have multiple GPUs, and I want to run multiple training processes simultaneously using the CUDA_VISIBLE_DEVICES option. However, when I try to run one train.py on CUDA_VISIBLE_DEVICES=0 and another train.py on CUDA_VISIBLE_DEVICES=1, I encounter the following error. How can I resolve this issue?

> Traceback (most recent call last):
  File "train.py", line 214, in <module>
    network_gui.init(args.ip, args.port)
  File "/research/gaussian-splatting/gaussian_renderer/network_gui.py", line 30, in init
    listener.bind((host, port))
OSError: [Errno 98] Address already in use

**Comment by yuedajiong** [comment]
This is not a 3d-reconstruction issue.

you can expose the TCP listening port to command-line, and different process use differnet port. 

so easy!
