### ISSUE TITLE
Load pretrained model for training

### ISSUE THREAD

**Issue by HungNgoCT** [graphdeco-inria/gaussian-splatting#459]
Hi,

I checked and tried with options in help, but did not meet.
Could you guide me how to load a trained model for training? For example, I trained 30k steps, and now I want to load and continue train.

Thank you.

**Comment by yuedajiong** [comment]
Oh my god, lazier than me.   :-(

python ****.py  --start_checkpoint <your-checkpoint-file>


   
parser.add_argument("--start_checkpoint", type=str, default = None)


 if checkpoint:
        (model_params, first_iter) = torch.load(checkpoint)
        gaussians.restore(model_params, opt)

**Comment by HungNgoCT** [comment]
> Oh my god, lazier than me. :-(
> 
> python ****.py --start_checkpoint your-checkpoint-file
> 
> parser.add_argument("--start_checkpoint", type=str, default = None)
> 
> if checkpoint: (model_params, first_iter) = torch.load(checkpoint) gaussians.restore(model_params, opt)

Where is the checkpoint file? After training, I got iterations_xxx\point_cloud.ply. Then, how to load this to continue training? NO checkpoint file I can see.

**Comment by shewangmu** [comment]
> > Oh my god, lazier than me. :-(
> > python ****.py --start_checkpoint your-checkpoint-file
> > parser.add_argument("--start_checkpoint", type=str, default = None)
> > if checkpoint: (model_params, first_iter) = torch.load(checkpoint) gaussians.restore(model_params, opt)
> 
> Where is the checkpoint file? After training, I got iterations_xxx\point_cloud.ply. Then, how to load this to continue training? NO checkpoint file I can see.

checkpoint file is saved only if you set --checkpoint_iterations while training.

**Comment by HungNgoCT** [comment]
> > > Oh my god, lazier than me. :-(
> > > python ****.py --start_checkpoint your-checkpoint-file
> > > parser.add_argument("--start_checkpoint", type=str, default = None)
> > > if checkpoint: (model_params, first_iter) = torch.load(checkpoint) gaussians.restore(model_params, opt)
> > 
> > 
> > Where is the checkpoint file? After training, I got iterations_xxx\point_cloud.ply. Then, how to load this to continue training? NO checkpoint file I can see.
> 
> checkpoint file is saved only if you set --checkpoint_iterations while training.

Hi @shewangmu 

I set option --checkpoint_iterations 60000. I could get chkpnt60000.pth file. Then, I loaded to continue train from 60k steps. However, it trains from the beginning, the initial number of points is not the number of points when I trained 60k steps.

Could you please guide me more? The CLI I use like this:
(gaussian-splatting_1) D:\Tests\gaussian-splatting_1\gaussian-splatting>python train.py -s <path to image folder> --data_device cpu  --position_lr_init 0.000016 --scaling_lr 0.016 --start_checkpoint "<path to checkpoint>\chkpnt60000.pth" --iterations 90000

Optimizing
Output folder: ./output/1ce3e9e9-f [27/11 10:51:31]
Tensorboard not available: not logging progress [27/11 10:51:31]
Reading camera 2518/2518 [27/11 10:51:39]
Loading Training Cameras [27/11 10:51:40]
Loading Test Cameras [27/11 10:55:34]
Number of points at initialisation :  485196 [27/11 10:55:35]
Training progress:   1%|▊
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/110378166/ef520eb8-4b78-423e-a5d5-6488f987b132)

Thank you in advance

**Comment by shewangmu** [comment]
> > > > Oh my god, lazier than me. :-(
> > > > python ****.py --start_checkpoint your-checkpoint-file
> > > > parser.add_argument("--start_checkpoint", type=str, default = None)
> > > > if checkpoint: (model_params, first_iter) = torch.load(checkpoint) gaussians.restore(model_params, opt)
> > > 
> > > 
> > > Where is the checkpoint file? After training, I got iterations_xxx\point_cloud.ply. Then, how to load this to continue training? NO checkpoint file I can see.
> > 
> > 
> > checkpoint file is saved only if you set --checkpoint_iterations while training.
> 
> Hi @shewangmu
> 
> Thank for the guidance
> 
> I set option --checkpoint_iterations 60000. I could get chkpnt60000.pth file. Then, I loaded to continue train from 60k steps. However, it trains from the beginning, the initial number of points is not the number of points when I trained 60k steps.
> 
> Could you please guide me more? The CLI I use like this: (gaussian-splatting_1) D:\Tests\gaussian-splatting_1\gaussian-splatting>python train.py -s --data_device cpu --position_lr_init 0.000016 --scaling_lr 0.016 --start_checkpoint "\chkpnt60000.pth" --iterations 90000
> 
> Optimizing Output folder: ./output/1ce3e9e9-f [27/11 10:51:31] Tensorboard not available: not logging progress [27/11 10:51:31] Reading camera 2518/2518 [27/11 10:51:39] Loading Training Cameras [27/11 10:51:40] Loading Test Cameras [27/11 10:55:34] Number of points at initialisation : 485196 [27/11 10:55:35] Training progress: 1%|▊ ![image](https://private-user-images.githubusercontent.com/110378166/285709832-ef520eb8-4b78-423e-a5d5-6488f987b132.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDYzNjAsIm5iZiI6MTcwMTg0NjA2MCwicGF0aCI6Ii8xMTAzNzgxNjYvMjg1NzA5ODMyLWVmNTIwZWI4LTRiNzgtNDIzZS1hNWQ1LTY0ODhmOTg3YjEzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwNzAxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDBiYjRmMmJkNjExMDI4NzdiYzU5MjgxMjRlNzJlNTRjYmU1OWFhMjU4NjcyN2IzMTU2MTdhYjUyNjJhNWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0Q3LEtzmpEWsfRLHhgFQ83ukQJ3qaJZUxu3ux4lEOLQ)
> 
> Thank you in advance

you set iterations to 90000, but the total iteration of the training progress  is 30000. This means you load 60000 iterations from your checkpoint. In other words, you are not training from the beginning but from the checkpoint.

**Comment by HungNgoCT** [comment]
> > > > > Oh my god, lazier than me. :-(
> > > > > python ****.py --start_checkpoint your-checkpoint-file
> > > > > parser.add_argument("--start_checkpoint", type=str, default = None)
> > > > > if checkpoint: (model_params, first_iter) = torch.load(checkpoint) gaussians.restore(model_params, opt)
> > > > 
> > > > 
> > > > Where is the checkpoint file? After training, I got iterations_xxx\point_cloud.ply. Then, how to load this to continue training? NO checkpoint file I can see.
> > > 
> > > 
> > > checkpoint file is saved only if you set --checkpoint_iterations while training.
> > 
> > 
> > Hi @shewangmu
> > Thank for the guidance
> > I set option --checkpoint_iterations 60000. I could get chkpnt60000.pth file. Then, I loaded to continue train from 60k steps. However, it trains from the beginning, the initial number of points is not the number of points when I trained 60k steps.
> > Could you please guide me more? The CLI I use like this: (gaussian-splatting_1) D:\Tests\gaussian-splatting_1\gaussian-splatting>python train.py -s --data_device cpu --position_lr_init 0.000016 --scaling_lr 0.016 --start_checkpoint "\chkpnt60000.pth" --iterations 90000
> > Optimizing Output folder: ./output/1ce3e9e9-f [27/11 10:51:31] Tensorboard not available: not logging progress [27/11 10:51:31] Reading camera 2518/2518 [27/11 10:51:39] Loading Training Cameras [27/11 10:51:40] Loading Test Cameras [27/11 10:55:34] Number of points at initialisation : 485196 [27/11 10:55:35] Training progress: 1%|▊ ![image](https://private-user-images.githubusercontent.com/110378166/285709832-ef520eb8-4b78-423e-a5d5-6488f987b132.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDYzNjAsIm5iZiI6MTcwMTg0NjA2MCwicGF0aCI6Ii8xMTAzNzgxNjYvMjg1NzA5ODMyLWVmNTIwZWI4LTRiNzgtNDIzZS1hNWQ1LTY0ODhmOTg3YjEzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwNzAxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDBiYjRmMmJkNjExMDI4NzdiYzU5MjgxMjRlNzJlNTRjYmU1OWFhMjU4NjcyN2IzMTU2MTdhYjUyNjJhNWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0Q3LEtzmpEWsfRLHhgFQ83ukQJ3qaJZUxu3ux4lEOLQ)
> > Thank you in advance
> 
> you set iterations to 90000, but the total iteration of the training progress is 30000. This means you load 60000 iterations from your checkpoint. In other words, you are not training from the beginning but from the checkpoint.

Thank you very much @shewangmu .

So now I understood. The problem solved, please let me close here.
