### ISSUE TITLE
from GS to GS++,  FROM relative-free-Gaussian-points forming a cloud for 2D-visual-realistic TO regular-flat-Gaussian-points point-center-surface-approximation for 3D-physical-precise

### ISSUE THREAD

**Issue by yuedajiong** [graphdeco-inria/gaussian-splatting#463]
I added some logics, compute the normals-like data, 1) to regular the GS points to flater, 2) force the points close to 'local implicit surface'.

tested on a flat-grid.

initilized:  (xyz-only here)
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/52232153/85a3f659-e379-4061-bf27-bc77a388ec4d)

optimized:  (xyz-only here)
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/52232153/1ef8232d-a40d-452d-a7d4-d4ebf04bf144)

**Comment by Snosixtyboo** [comment]
Cool, did you see any measurable improvement in image quality?

**Comment by yuedajiong** [comment]
Hi, @Snosixtyboo great-master:

totally, I think the biggest advantage of GS is 'FAST', including train and infer/render-only.
but, it do optimization on 2D space, that means: 1) if the 2D loss is very small, it still may have big gap in 3D:  a) points dislocation, b) too-big gauss point.

so, I implemented the GS++:   flatten every GS point,  force the GS points to around the real surface(need not as label), I just regular the points to a thin layer.


this is my real test-case.

the green points is input, and the red points is output and thiner.  (screen captuered)
similar with points, the big single-gauss-point is thiner, from ellipsoid to ellipse.

I can append these logies as postprecess of GS.

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/52232153/6ef9a13b-8f7b-42de-a709-c27f1fcb6afa)
