### ISSUE TITLE
SIBR_gaussianViewer got crash

### ISSUE THREAD

**Issue by ryudokid** [graphdeco-inria/gaussian-splatting#464]
I got crash when using this viewer. Anybody help pleas. Thank you so much

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/68176850/b4b85485-9b25-4081-bd44-19e6e8c63aef)

**Comment by jaco001** [comment]
1. path must be at your example to few dir up
2. file must be point_cloud.ply
Like
SIBR_gaussianViewer_app.exe -m "C:\Users\Po Nguyen\gasussian-splatting\output\exciter 3D\" --iteration 30000

Also you need original cfg_args.
Handy tip: make separate dir inside like iteration_10 and put your changed point_cloud.ply  there,
and start SIBR_gaussianViewer_app.exe -m "C:\Users\Po Nguyen\gasussian-splatting\output\exciter 3D\" --iteration 10

GL

**Comment by ryudokid** [comment]
> 1. path must be at your example to few dir up
> 2. file must be point_cloud.ply
>    Like
>    SIBR_gaussianViewer_app.exe -m "C:\Users\Po Nguyen\gasussian-splatting\output\exciter 3D" --iteration 30000
> 
> Also you need original cfg_args. Handy tip: make separate dir inside like iteration_10 and put your changed point_cloud.ply there, and start SIBR_gaussianViewer_app.exe -m "C:\Users\Po Nguyen\gasussian-splatting\output\exciter 3D" --iteration 10
> 
> GL

i change the folder name back to previous one (form the original cfg_args file), and  use the original point_cloud.ply but i still get this error. Btw i tried your handy tip but it still not working. 
i m using Rtx4090 
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/68176850/9b90365f-5adf-4e29-a56f-f11a5bb2e83e)

**Comment by Snosixtyboo** [comment]
Hi, 

typo: gaussian vs. gasussian in your command line.

**Comment by ryudokid** [comment]
You save me now, thank you so much 
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/68176850/79820ed2-3ace-4ef3-8799-0c624147d5ff)
