### ISSUE TITLE
About the rendering a point with large alpha

### ISSUE THREAD

**Issue by YutingXiao** [graphdeco-inria/gaussian-splatting#466]
Hi, thanks for this excellent work. I feel very strange about this cuda code in forward.cu(line 343):

			float alpha = min(0.99f, con_o.w * exp(power));
			if (alpha < 1.0f / 255.0f)
				continue;
			float test_T = T * (1 - alpha);
			if (test_T < 0.0001f)
			{
				done = true;
				continue;
			}

			// Eq. (3) from 3D Gaussian splatting paper.
			for (int ch = 0; ch < CHANNELS; ch++)
				C[ch] += features[collected_id[j] * CHANNELS + ch] * alpha * T;

			T = test_T;

			// Keep track of last range entry to update this
			// pixel.
			last_contributor = contributor;

What if I have a point list with alpha[0.05, 0.05, 0.05, 0.9999]. The last point has a very alpha value. I think the last point should be rendered, but in this code, it would get a very small "test_T"(0.95*0.95*0.95*0.0001<0.0001) and the for loop is stopped (done=True) here. Specifically, If a point has a very large alpha value in a point list of a pixel, the rendering processing would be stopped here with this large alpha value point ignored. But I think this point still need to be rendered.

Can you explain why?

**Comment by yuedajiong** [comment]
上海的朋友是吧，感觉你对这段代码推算有误？ （我也是靠脑袋推算的，没有调试打印，也可能理解有错。）

按照你给的0.05  0.05  0.05  0.999这组alpha“不透明度”数据，也就实现下面第一行依次这几个值。
显然，在第二行判断，这几个值，都认为大于0.02，就是不是几乎透明，要继续后面的C/color计算。 
T是一个递增的，初始T时1.0，这前三轮下来，还是远远大于0.0001，不会don也不会continue，表示要继续后面的C累加。
1*0.95
0.95*0.95
0.95*0.95*0.95
0.95*0.95*0.95*0.001 = 0.000857375
累加了0.999后，test_T都还大于0.0001f的门限啊。   test_T我估计是：累积并测试透明度是否足够低了。反过来也就是不透明opccity累的足够了。
			float alpha = min(0.99f, con_o.w * exp(power));
			if (alpha < 1.0f / 255.0f)
				continue;
			float test_T = T * (1 - alpha);
			if (test_T < 0.0001f)
			{
				done = true;
				continue;
			}

			// Eq. (3) from 3D Gaussian splatting paper.
			for (int ch = 0; ch < CHANNELS; ch++)
				C[ch] += features[collected_id[j] * CHANNELS + ch] * alpha * T;

			T = test_T;

**Comment by YutingXiao** [comment]
> this is NOT official answer.
> 
> 上海的朋友是吧，感觉你对这段代码推算有误？ （我也是靠脑袋推算的，没有调试打印，也可能理解有错。）
> 
> 按照你给的0.05 0.05 0.05 0.999这组alpha“不透明度”数据，也就下面第一行依次这几个值。 显然，在第二行判断，这几个值，都认为大于0.02，就是不是几乎透明，要继续后面的C/color计算。 T是一个递进的，初始T时1.0，这前三轮下来，还是远远大于0.0001，不会done也不会continue，表示要继续后面的C/color累加。 1_0.95 0.95_0.95 0.95_0.95_0.95 0.95_0.95_0.95*0.001 = 0.000857375 累加了0.999后，test_T都还大于0.0001f的门限啊。 test_T我估计是：累积并"测试透明度"是否足够低了。反过来也就是不透明opccity累的足够了。
> 
> ```
> 		float alpha = min(0.99f, con_o.w * exp(power));
> 		if (alpha < 1.0f / 255.0f)
> 			continue;
> 		float test_T = T * (1 - alpha);
> 		if (test_T < 0.0001f)
> 		{
> 			done = true;
> 			continue;
> 		}
> 
> 		// Eq. (3) from 3D Gaussian splatting paper.
> 		for (int ch = 0; ch < CHANNELS; ch++)
> 			C[ch] += features[collected_id[j] * CHANNELS + ch] * alpha * T;
> 
> 		T = test_T;
> ```



> this is NOT official answer.
> 
> 上海的朋友是吧，感觉你对这段代码推算有误？ （我也是靠脑袋推算的，没有调试打印，也可能理解有错。）
> 
> 按照你给的0.05 0.05 0.05 0.999这组alpha“不透明度”数据，也就下面第一行依次这几个值。 显然，在第二行判断，这几个值，都认为大于0.02，就是不是几乎透明，要继续后面的C/color计算。 T是一个递进的，初始T时1.0，这前三轮下来，还是远远大于0.0001，不会done也不会continue，表示要继续后面的C/color累加。 1_0.95 0.95_0.95 0.95_0.95_0.95 0.95_0.95_0.95*0.001 = 0.000857375 累加了0.999后，test_T都还大于0.0001f的门限啊。 test_T我估计是：累积并"测试透明度"是否足够低了。反过来也就是不透明opccity累的足够了。
> 
> ```
> 		float alpha = min(0.99f, con_o.w * exp(power));
> 		if (alpha < 1.0f / 255.0f)
> 			continue;
> 		float test_T = T * (1 - alpha);
> 		if (test_T < 0.0001f)
> 		{
> 			done = true;
> 			continue;
> 		}
> 
> 		// Eq. (3) from 3D Gaussian splatting paper.
> 		for (int ch = 0; ch < CHANNELS; ch++)
> 			C[ch] += features[collected_id[j] * CHANNELS + ch] * alpha * T;
> 
> 		T = test_T;
> ```

你最后一步算的不对，应该是0.95*0.95*0.95*0.0001，我最后的alpha=0.9999而不是0.999

**Comment by yuedajiong** [comment]
我抄写错了你的数据。

opacity整个算法开始也是有意义的初始化。  (就是过程中无论如何都给别的点意思光亮？防止开始就被阻断。)

alpha是min过的，小于0.99。这一点你考虑到了没？影响你的结论吗？
