### ISSUE TITLE
garbage code in in_frustum() ?

### ISSUE THREAD

**Issue by yuedajiong** [graphdeco-inria/gaussian-splatting#470]
__forceinline__ __device__ bool in_frustum(int idx,      //John: per-thread, per-gauss-point
	const float* orig_points,
	const float* viewmatrix,
	const float* projmatrix,
	bool prefiltered,
	float3& p_view)
{
	float3 p_orig = { orig_points[3 * idx], orig_points[3 * idx + 1], orig_points[3 * idx + 2] };

	// Bring points to screen space
	float4 p_hom = transformPoint4x4(p_orig, projmatrix);                    //here: garbage?
	float p_w = 1.0f / (p_hom.w + 0.0000001f);                                      //here: garbage?
	float3 p_proj = { p_hom.x * p_w, p_hom.y * p_w, p_hom.z * p_w };   //here: garbage?
	p_view = transformPoint4x3(p_orig, viewmatrix);

	if (p_view.z <= 0.2f)// || ((p_proj.x < -1.3 || p_proj.x > 1.3 || p_proj.y < -1.3 || p_proj.y > 1.3)))
	{
		if (prefiltered)
		{
			printf("Point is filtered although prefiltered is set. This shouldn't happen!");
			__trap();
		}
		return false;
	}
	return true;
}

**Comment by windkiss5** [comment]
I am also wondering about this code. Do you have any ideas now?

**Comment by mashiroyuki02** [comment]
hi, I am also confused by this code. since projmatrix has project world coordinates to ndc in [-1,1], what's the meaning of do a world view transform again? and why use 0.2 to clip the frustum?
