### ISSUE TITLE
Zooming out the splats become large and blocky

### ISSUE THREAD

**Issue by henrypearce4D** [graphdeco-inria/gaussian-splatting#471]
If I zoom out in SIBR the splats become large and blocky, they don't seem to visibly scale with distance. Is there a way to correct this?
https://github.com/graphdeco-inria/gaussian-splatting/assets/106480554/4ceef97f-c577-4dee-9cea-3d6a1752569d

**Comment by grgkopanas** [comment]
Not a simple one I am afraid, this might be related to some issues that
have been discussed before related to AA, we are working on a fix

**Comment by henrypearce4D** [comment]
Ok thanks, fingers crossed - I will leave the issue open for now
