### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by cfchi** [graphdeco-inria/gaussian-splatting#473]
I got an error when run train.py. It seems to occur in the GaussianRasterizer.
Optimizing
Output folder: ./output/92694154-4 [16/11 10:11:53]
Tensorboard not available: not logging progress [16/11 10:11:53]
Reading camera 2/2 [16/11 10:11:53]
Loading Training Cameras [16/11 10:11:53]
Loading Test Cameras [16/11 10:11:54]
Number of points at initialisation :  823 [16/11 10:11:54]
Training progress:   0%|                                                                                             | 0/30000 [00:00<?, ?it/s]                                      Traceback (most recent call last):
  File "train.py", line 219, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args                                      .start_checkpoint, args.debug_from)
  File "train.py", line 86, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg)
  File "/Desktop/CodeFolder/gaussian-splatting/gaussian_renderer/__init__.py", line 85, in render
    rendered_image, radii = rasterizer(
ValueError: too many values to unpack (expected 2)
Training progress:   0%|                                                                                             | 0/30000 [00:00<?, ?it/s]

How can I fix this issue?

**Comment by cfchi** [comment]
I fix this problem by re-install GaussianRasterizer again.
If you have same error, you can try this. 
pip install plyfile tqdm
pip install submodules/diff-gaussian-rasterization
pip install submodules/simple-knn

**Comment by CloudyBuaaer** [comment]
> I fix this problem by re-install GaussianRasterizer again. If you have same error, you can try this. pip install plyfile tqdm pip install submodules/diff-gaussian-rasterization pip install submodules/simple-knn

Your solution is pretty useful！Thanks！

**Comment by mapoto** [comment]
Thank you!

**Comment by xiao10ma** [comment]
'''
rendered_image, radii, _ = rasterizer
'''
I add an additional _ to the return, and third one is depth_map. Probably the author didn't use it.

**Comment by dwz138831** [comment]
trank you
