### ISSUE TITLE
Convert Error

### ISSUE THREAD

**Issue by 2668342956** [graphdeco-inria/gaussian-splatting#476]
Hi, thanks for your great job. When I prepared the data, I used "python convert.py -s data/train", but it seemed encounterd error that was 
"
Elapsed time: 0.003 [minutes]
ERROR: Failed to parse options - unrecognised option '--mapper.ba_global_function_tolerance=0.000001'.
ERROR:root:Mapper failed with code 256. Exiting.
"
how can I fix it. Thanks again for your effort.

**Comment by yuedajiong** [comment]
Oh my god, look, another guy who can not run the GS correctlly.

In a word, please install 'proper colmap version'.

I uploaded my 'step by step' installlation scipt, you can find the colmap installation steps, even you can just copy and paste, simplest.

[0000-cuda11.7_pytorch1.13_tinycudann_colmap.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13387436/0000-cuda11.7_pytorch1.13_tinycudann_colmap.txt)

**Comment by 2668342956** [comment]
oh, thanks a lot. I will try it next time when I need to install colmap in linux. By the way, I solved this problem yesterday by converting the data in colmap_windows.

**Comment by 2668342956** [comment]
Copy that!
