### ISSUE TITLE
Mapper failed

### ISSUE THREAD

**Issue by ZiBrianQian** [graphdeco-inria/gaussian-splatting#480]
Hi guys. I'm a newbie. But I keep getting this error while trying to convert my images:

ERROR:root:Mapper failed with code -1073741819. Exiting.
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/129299515/a1b2935a-c4d5-4311-b084-7b83df916fa6)

**Comment by ZiBrianQian** [comment]
But with NerfStudio everything works fine. Is it COLMAP problem?

**Comment by theAdityaRamesh** [comment]
Try using point_triangulator instead of mapper, the mapper did not work well in my case too.
Ref : https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses

**Comment by ZiBrianQian** [comment]
Thanks. But I fixed the issue by reinstalling COLMAP and cleaning environment variables

**Comment by An-u-rag** [comment]
For people that come here later, please recheck your CUDA version using
```
nvcc --version
```

In my case, I constantly change CUDA versions and forgot to switch it back to CUDA 11.8 (which is what this repository recommends) and consequently current COLMAP version also works with this one. I was using CUDA 11.1 which caused this issue in my case. 

To change your CUDA version, go to system environment variable -> PATH -> Reorder the 11.8 one at the top of all other cuda version -> reopen Anaconda prompt / terminal.

**Comment by pyl122516** [comment]
> Thanks. But I fixed the issue by reinstalling COLMAP and cleaning environment variables谢谢。但是我通过重新安装 COLMAP 和清理环境变量解决了这个问题

i have same problem,how to fix it?

**Comment by Songxinlei** [comment]
> Thanks. But I fixed the issue by reinstalling COLMAP and cleaning environment variables

I do these works,but not work for this.still have same problem.how to reinstall and clean path?

**Comment by ENGFCC** [comment]
> Thanks. But I fixed the issue by reinstalling COLMAP and cleaning environment variables感谢。但我通过重新安装 COLMAP 并清理环境变量解决了问题

请问您是如何安装colmap的，我在ubuntu 20.04 环境下，安装 colmap 好麻烦，正在尝试用 conda 安装 colmap。想请问您是怎么安装的？
