### ISSUE TITLE
How to apply transformation and scaling to a 3D Gaussian-trained point cloud?

### ISSUE THREAD

**Issue by 834810269** [graphdeco-inria/gaussian-splatting#492]
I want to apply rotation, translation, and scaling to a 3D Gaussian-trained point cloud. How do I handle attributes other than the XYZ coordinates of the point cloud?
I see that the point cloud has the following content:

> ply
format binary_little_endian 1.0
element vertex 270583
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float f_dc_0
property float f_dc_1
property float f_dc_2
property float f_rest_0
property float f_rest_1
property float f_rest_2
property float f_rest_3
property float f_rest_4
property float f_rest_5
property float f_rest_6
property float f_rest_7
property float f_rest_8
property float f_rest_9
property float f_rest_10
property float f_rest_11
property float f_rest_12
property float f_rest_13
property float f_rest_14
property float f_rest_15
property float f_rest_16
property float f_rest_17
property float f_rest_18
property float f_rest_19
property float f_rest_20
property float f_rest_21
property float f_rest_22
property float f_rest_23
property float f_rest_24
property float f_rest_25
property float f_rest_26
property float f_rest_27
property float f_rest_28
property float f_rest_29
property float f_rest_30
property float f_rest_31
property float f_rest_32
property float f_rest_33
property float f_rest_34
property float f_rest_35
property float f_rest_36
property float f_rest_37
property float f_rest_38
property float f_rest_39
property float f_rest_40
property float f_rest_41
property float f_rest_42
property float f_rest_43
property float f_rest_44
property float opacity
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
end_header

Do I need to perform operations on the properties:
`property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3`
If so, how should I proceed with these operations?

**Comment by yzslab** [comment]
Hi, you can take a look this file about how to transform gaussians: https://github.com/yzslab/gaussian-splatting-lightning/blob/73acf406f6346f2f4241f1deb2ad6c5031258b7e/gaussian_transform.py#L171-L173
But the spherical harmonics transformation (the `f_rest_*`) has not been implemented yet. Without it will cause a little bit quality drop (not too much, acceptable).
This issue discussed how to rotate the SHs: https://github.com/graphdeco-inria/gaussian-splatting/issues/176

**Comment by 834810269** [comment]
> Hi, you can take a look this file about how to transform gaussians: https://github.com/yzslab/gaussian-splatting-lightning/blob/73acf406f6346f2f4241f1deb2ad6c5031258b7e/gaussian_transform.py#L171-L173 But the spherical harmonics transformation (the `f_rest_*`) has not been implemented yet. Without it will cause a little bit quality drop (not too much, acceptable). This issue discussed how to rotate the SHs: #176

Thanks a lot!

**Comment by ygtxr1997** [comment]
> Hi, you can take a look this file about how to transform gaussians: https://github.com/yzslab/gaussian-splatting-lightning/blob/73acf406f6346f2f4241f1deb2ad6c5031258b7e/gaussian_transform.py#L171-L173 But the spherical harmonics transformation (the `f_rest_*`) has not been implemented yet. Without it will cause a little bit quality drop (not too much, acceptable). This issue discussed how to rotate the SHs: #176

Thank you very much! But I have a question: why the "scaling" operation needs to use a `log` function like this?
```python
self.scales += np.log(scale)
```
I tried `self.scales *= scale`, but the results seemed very incorrect.
Could you show me the mathematical princinple of this `self.scales += np.log(scale)` code?

**Comment by yzslab** [comment]
> Could you show me the mathematical princinple of this `self.scales += np.log(scale)` code?

The scale value is logarithmic: 
https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L33-L34
https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L95-L97
https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L135
