### ISSUE TITLE
An installation advice for those using RTX 4090 GPU and 'no cuda runtime is found' error. 

### ISSUE THREAD

**Issue by Maftej** [graphdeco-inria/gaussian-splatting#493]
I have been struggling with the installation of this repository using RTX 4090.
Some developers have said that CUDA 11.8 is not compatible with RTX 4090, but eventually I have successfully installed all the requirements using CUDA 11.8 on RTX 4090. I would like to share my experience and findings. 

1. HW  and SW specifications
OS: Window 11
Installed: visual studio community 2019 and visual studio build tools 2019 (both may be not necessary)
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/58000288/2b7e7a24-d0f9-4681-9551-003b218ff3bb)
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/58000288/32e937fb-1cf8-47ca-8e05-e37f9391f6ce)
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/58000288/948af202-1234-49d3-a154-980a028a17de)

2. Environment variables:
System variables:
CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
Path
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include (It has to be added because the CUDA does not recognize the path for <crt.defs.h>)

4.  Anaconda prompt commands:
nvcc --version (11.8)
cd C:\...\3d_gaussian_splatting\gaussian-splatting
conda create -n gs python=3.10 (MY CONDA ENVIRONMENT HAS SPECIFIC PYTHON VERSION 3.10 -> PYTORCH+CUDA do not have to be compatible with different python version as 3.12)
conda activate gs
python --version (OUTPUT IS 3.10.13 for date 22.11.2023)
python -m pip install --upgrade pip --user (OPTIONAL)
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 (YOU HAVE TO HAVE INSTALLED PYTOHON 3.10 not newer as 3.12 in CONDA ENVIRONMENT otherwise there is an error that cannot be installed torch; installing pytorch+cuda using conda does not work!!)
pip install plyfile
pip3 install tqdm
cd submodules
cd diff-gaussian-rasterization
pip install .
cd ..
cd simple-knn
pip install .
cd ..
cd ..
python train.py -s data/carla_dataset (whether we do not install submodules, then the error is 'ModuleNotFoundError: No module named 'diff_gaussian_rasterization'')

AFTER TRAINING (VIEW or RENDERING the results)
cd viewers/bin (from root project folder to viewers/bin)
SIBR_gaussianViewer_app.exe -m C:\...\3d_gaussian_splatting\gaussian-splatting\output\fdsada32dc1-4 (IT IS IMPORTANT TO DOWNLOAD ZIP FILE viewer.zip, then unzip it and add to root gaussian-splatting project, the link is https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/binaries/viewers.zip)

After these steps, I am able to train and view the results of 3D Gaussian Splatting. I hope, it will help the community.

**Comment by DevepNoName** [comment]
@Maftej Thank you a lottt for putting this here
after many hours was the only installation that worked for me (was always getting errors when training)
i have a rtx 3090 / driver 546.29

just a note, in the path also have to add this:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64
because wasnt finding cl.exe

**Comment by codeBoyLxc** [comment]
I have the same configuration with yours，but it not work！Do you have other configurations did not metioned above？

**Comment by Maftej** [comment]
@codeBoyLxc  No. :/

**Comment by TommasoLabieni** [comment]
Hello @Maftej, I noticed from the training path that you were using a "carla dataset". I'm currently planning to use 3DGS with such setup, did you get any interesting result so far that could be publicly shared? Thanks!

**Comment by Maftej** [comment]
@TommasoLabieni, we have recently published the paper about using radiance fields with CARLA simulator for video compression:
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10595661

**Comment by TommasoLabieni** [comment]
That's great! I will definitely give it a look. Thanks a lot for the effort!

**Comment by Maftej** [comment]
Thank you! If you would like to share your results or experience, feel free to message me :)
