### ISSUE TITLE
A little question in simple-knn

### ISSUE THREAD

**Issue by jiawei151** [graphdeco-inria/gaussian-splatting#498]
Hi authors. Thank you for your great work and wonderful code! I have a question in `submodule/simple-knn`. In the line 163-166 of simple_knn.cu, the `best` array is re-initialized by:

	float reject = best[2];
	best[0] = FLT_MAX;
	best[1] = FLT_MAX;
	best[2] = FLT_MAX;

I am wondering what if there is no update in the following For loop,

 	for (int b = 0; b < (P + BOX_SIZE - 1) / BOX_SIZE; b++)
	{
		MinMax box = boxes[b];
		float dist = distBoxPoint(box, point);
		if (dist > reject || dist > best[2])
			continue;

		for (int i = b * BOX_SIZE; i < min(P, (b + 1) * BOX_SIZE); i++)
		{
			if (i == idx)
				continue;
			updateKBest<3>(point, points[indices[i]], best);
		}
	}
the final `meanDict` will be equal to `FLT_MAX` if I didn't misunderstand it.

	dists[indices[idx]] = (best[0] + best[1] + best[2]) / 3.0f;
So would this be an unexpected feature? Thank you.

**Comment by Snosixtyboo** [comment]
Yes, if there are fewer than 3 Gaussians in the scene, this would indeed be a problem, but it would also be a very non-standard input.
