### ISSUE TITLE
Python-based rasterization code

### ISSUE THREAD

**Issue by zhshi0816** [graphdeco-inria/gaussian-splatting#50]
Hi,

Thanks for making a great contribution to the area. I am wondering do you have Python rasterization code, which is easier to read and redevelop. Thank you.

**Comment by Snosixtyboo** [comment]
Hi,

sorry, we don't. We wouldn't even know how PyTorch would be able to keep track of an arbitrary number of Gaussian blending steps for the backward, so we never considered this.

Best,
Bernhard
