### ISSUE TITLE
Render with custom cameras?

### ISSUE THREAD

**Issue by gregogalante** [graphdeco-inria/gaussian-splatting#506]
Is there a way to use the 'render.py' command with custom cameras instead of those related to the images used in training?

**Comment by Ph03n1xdust** [comment]
I don't think "render.py" could be directly used for that, but you can define custom camera poses and make a custom camera object having all the needed info for rendering.

What I did was:
```
from utils.graphics_utils import getWorld2View2, getProjectionMatrix

class DummyCamera:
    def __init__(self, R, T, FoVx, FoVy, W, H):
        self.projection_matrix = getProjectionMatrix(znear=0.01, zfar=100.0, fovX=FoVx, fovY=FoVy).transpose(0,1).cuda()
        self.R = R
        self.T = T
        self.world_view_transform = torch.tensor(getWorld2View2(R, T, np.array([0,0,0]), 1.0)).transpose(0, 1).cuda()
        self.full_proj_transform = (self.world_view_transform.unsqueeze(0).bmm(self.projection_matrix.unsqueeze(0))).squeeze(0)
        self.camera_center = self.world_view_transform.inverse()[3, :3]
        self.image_width = W
        self.image_height = H
        self.FoVx = FoVx
        self.FoVy = FoVy

class DummyPipeline:
    convert_SHs_python = False
    compute_cov3D_python = False
    debug = False
```

Fill an instance of the Dummycam with the info you want to render from and call the `render` of `gaussian_renderer` like this:
```
result = render(mycam, gaussians, DummyPipeline(), background)["render"]
```

**Comment by gregogalante** [comment]
@Ph03n1xdust Ok the solution is working great. I have another question. How can we change the width and height of images generated by render? We have tried to change the values on image_width and image_height but we get the output streched.

**Comment by gregogalante** [comment]
I answer myself, it can be solved by setting the correct value for FoVx and FovY:

```python

def calculate_fov(output_width, output_height, focal_length, aspect_ratio=1.0, invert_y=False):
    fovx = 2 * math.atan((output_width / (2 * focal_length)))
    fovy = 2 * math.atan((output_height / aspect_ratio) / (2 * focal_length))
    
    if invert_y:
        fovy = -fovy
    
    # Convert angles from radians to degrees if necessary
    fovx_deg = math.degrees(fovx)
    fovy_deg = math.degrees(fovy)
    
    return fovx_deg, fovy_deg

# Example usage
output_width = 1920  # Replace with your actual output width
output_height = 1080  # Replace with your actual output height
focal_length = 50.0  # Replace with your actual focal length
aspect_ratio = 16 / 9  # Replace with your desired aspect ratio
invert_y = True  # Set to True if y-axis is inverted

fovx, fovy = calculate_fov(output_width, output_height, focal_length, aspect_ratio, invert_y)
```

**Comment by xytjc** [comment]
@gregogalante Hello,i am doing the same work too,i wanna input the new camera pose(different from my training step) and output the correspond image,how should i do for this?there are my codes:
`import open3d as o3d
import numpy as np
import json
import matplotlib.pyplot as plt

# 加载点云
point_cloud = o3d.io.read_point_cloud('/home/chengkang/project/3D-Gaussian-Splatting/gaussian-splatting/output/garden/point_cloud/iteration_30000/point_cloud.ply')

# 加载相机参数
with open('/home/chengkang/project/3D-Gaussian-Splatting/gaussian-splatting/output/garden/cameras.json', 'r') as f:
    cameras = json.load(f)

# 定义相机内参矩阵
def get_intrinsic_matrix(fx, fy, width, height):
    cx, cy = width / 2 - 0.5, height / 2 - 0.5
    intrinsic = o3d.camera.PinholeCameraIntrinsic(width, height, fx, fy, cx, cy)
    return intrinsic

# 获取相机的变换矩阵
def get_extrinsic_matrix(R, T):
    extrinsic = np.hstack((R, np.array(T).reshape((3, 1))))
    extrinsic = np.vstack((extrinsic, [0, 0, 0, 1]))
    return extrinsic

# 定义新的旋转矩阵R和平移向量T
R_new = np.array([[20, 100, -100],
                  [10, 30, 0],
                  [0, 0, 1]])  # 示例旋转矩阵
T_new = [100, 20, -3]  # 示例平移向量

# 使用一个相机的内参矩阵
fx = cameras[0]['fx']
fy = cameras[0]['fy']
width = cameras[0]['width']
height = cameras[0]['height']

# 生成新的相机内参矩阵和外参矩阵
intrinsic = get_intrinsic_matrix(fx, fy, width, height)
extrinsic = get_extrinsic_matrix(R_new, T_new)

# 创建 PinholeCameraParameters 对象
camera_params = o3d.camera.PinholeCameraParameters()
camera_params.intrinsic = intrinsic
camera_params.extrinsic = extrinsic

# 创建渲染器
vis = o3d.visualization.Visualizer()
vis.create_window(visible=False, width=width, height=height)
vis.add_geometry(point_cloud)

# 设置相机参数
ctr = vis.get_view_control()
if not ctr.convert_from_pinhole_camera_parameters(camera_params):
    print("Failed to convert from pinhole camera parameters. Check the width and height.")
    vis.destroy_window()
    exit()

# 渲染并保存图像
vis.poll_events()
vis.update_renderer()
image = vis.capture_screen_float_buffer(do_render=True)
image = np.asarray(image)
vis.destroy_window()

# 保存图像
plt.imsave('/home/chengkang/project/3D-Gaussian-Splatting/gaussian-splatting/new_camera_pose_images/rendered_image4.png', image)`
this is my output,and my R_new,T_new seems dont work!
![rendered_image](https://github.com/graphdeco-inria/gaussian-splatting/assets/150337812/aa6cf471-2dea-4d27-ac5e-68269c4624c9)
i am looking forward for your replay!thank you!

**Comment by lhbing-alt** [comment]
> I don't think "render.py" could be directly used for that, but you can define custom camera poses and make a custom camera object having all the needed info for rendering.
> 
> What I did was:
> 
> ```
> from utils.graphics_utils import getWorld2View2, getProjectionMatrix
> 
> class DummyCamera:
>     def __init__(self, R, T, FoVx, FoVy, W, H):
>         self.projection_matrix = getProjectionMatrix(znear=0.01, zfar=100.0, fovX=FoVx, fovY=FoVy).transpose(0,1).cuda()
>         self.R = R
>         self.T = T
>         self.world_view_transform = torch.tensor(getWorld2View2(R, T, np.array([0,0,0]), 1.0)).transpose(0, 1).cuda()
>         self.full_proj_transform = (self.world_view_transform.unsqueeze(0).bmm(self.projection_matrix.unsqueeze(0))).squeeze(0)
>         self.camera_center = self.world_view_transform.inverse()[3, :3]
>         self.image_width = W
>         self.image_height = H
>         self.FoVx = FoVx
>         self.FoVy = FoVy
> 
> class DummyPipeline:
>     convert_SHs_python = False
>     compute_cov3D_python = False
>     debug = False
> ```
> 
> Fill an instance of the Dummycam with the info you want to render from and call the `render` of `gaussian_renderer` like this:
> 
> ```
> result = render(mycam, gaussians, DummyPipeline(), background)["render"]
> ```

Can you share the full code with me, since I'm new to 3DGS, I don't understand a lot of it, thanks!

**Comment by lhbing-alt** [comment]
> @Ph03n1xdust Ok the solution is working great. I have another question. How can we change the width and height of images generated by render? We have tried to change the values on image_width and image_height but we get the output streched.

Can you share the full code with me, since I'm new to 3DGS, I don't understand a lot of it, thanks!

**Comment by guaMass** [comment]
Try to use [this](https://github.com/guaMass/3DGS_PoseRender) if you waht to render new images from new camera paramaters.

**Comment by i-nkrumah** [comment]
Can you share the full code with me, since I'm new to 3DGS, I don't understand a lot of it, thanks!

**Comment by guaMass** [comment]
This tool maybe helpful: https://github.com/guaMass/3DGS_PoseRender

**Comment by Elaine10** [comment]
> I answer myself, it can be solved by setting the correct value for FoVx and FovY:
> 
> ```python
> def calculate_fov(output_width, output_height, focal_length, aspect_ratio=1.0, invert_y=False):
>     fovx = 2 * math.atan((output_width / (2 * focal_length)))
>     fovy = 2 * math.atan((output_height / aspect_ratio) / (2 * focal_length))
>     
>     if invert_y:
>         fovy = -fovy
>     
>     # Convert angles from radians to degrees if necessary
>     fovx_deg = math.degrees(fovx)
>     fovy_deg = math.degrees(fovy)
>     
>     return fovx_deg, fovy_deg
> 
> # Example usage
> output_width = 1920  # Replace with your actual output width
> output_height = 1080  # Replace with your actual output height
> focal_length = 50.0  # Replace with your actual focal length
> aspect_ratio = 16 / 9  # Replace with your desired aspect ratio
> invert_y = True  # Set to True if y-axis is inverted
> 
> fovx, fovy = calculate_fov(output_width, output_height, focal_length, aspect_ratio, invert_y)
> ```

thanks for your reply.
But, I just confused about  "fovy = 2 * math.atan((output_height / aspect_ratio) / (2 * focal_length))"
Why here use (output_height / aspect_ratio) instead of output_height ?

**Comment by jiahanyue-del** [comment]
How do I know the position of the virtual camera so that the object I need to render is in the middle of the rendered image
