### ISSUE TITLE
libembree problem/ build SIBR on Ubuntu22.04

### ISSUE THREAD

**Issue by dawnJiang** [graphdeco-inria/gaussian-splatting#507]
I noticed that when building SIBR_viewer on Ubuntu22.04, it report a mistake about -lembree
It's because of the name problem on Ubuntu, when I try ```sudo apt-get install -y libembree-dev```, I found that it's name is 'lib/x86_64-linux-gnu/libembree3.so', so I have to make a symbolic link by ```sudo ln -s /lib/x86_64-linux-gnu/libembree3.so /lib/x86_64-linux-gnu/libembree.so``` it worked

**Comment by elenacliu** [comment]
In fact on Ubuntu22.04, we can also modify the cmake file directly.

We can modify the line 34 of`/SIBR_viewers/src/core/raycaster/CMakeLists.txt` from `embree` to `embree3`.

Then it will work.

**Comment by yanqswhu** [comment]
> In fact on Ubuntu22.04, we can also modify the cmake file directly.
> 
> We can modify the line 34 of`/SIBR_viewers/src/core/raycaster/CMakeLists.txt` from `embree` to `embree3`.
> 
> Then it will work.

works for me. thanks
