### ISSUE TITLE
running problem/ it seems that some file in SIBR_viewers is missing

### ISSUE THREAD

**Issue by dawnJiang** [graphdeco-inria/gaussian-splatting#508]
[SIBR] ##  ERROR  ##:   FILE /home/j/project/gaussian-splatting/SIBR_viewers/src/core/system/Utils.cpp
                        LINE 82, FUNC loadFile
                        File not found: uv_mesh.vert
I build SIBR on Ubuntu22.04 and it's confused that the SIBR_remoteGaussian_app worked, but SIBR_gaussianViewer_app got this problem, any help can be useful.

**Comment by TossgirlF91** [comment]
> I have the same problem. May I ask if you have resolved it？
according to:
https://github.com/graphdeco-inria/gaussian-splatting/issues/27#issuecomment-1637030743

just run the SIBR_viewers with work directory path './SIBR_viewers/install/shaders/core' will be fine.

**Comment by pangchenglin** [comment]
> > I have the same problem. May I ask if you have resolved it？
> > according to:
> > [#27 (comment)](https://github.com/graphdeco-inria/gaussian-splatting/issues/27#issuecomment-1637030743)
> 
> just run the SIBR_viewers with work directory path './SIBR_viewers/install/shaders/core' will be fine.

This is effective. Thanks!

**Comment by feihuafuyou** [comment]
This works well! Thank you!@TossgirlF91
