### ISSUE TITLE
How to save the rendered 3D smoothing file

### ISSUE THREAD

**Issue by haung-hangdian** [graphdeco-inria/gaussian-splatting#51]

**Comment by grgkopanas** [comment]
Can you elaborate i dont know what a 3d smoothing file is

**Comment by haung-hangdian** [comment]
就是带有点面纹理的obj文件

**Comment by haung-hangdian** [comment]
OBJ file with point surface texture

**Comment by grgkopanas** [comment]
This is a different representation than the one discussed in the paper,
converting this representation to a traditional point cloud is not trivial
but could be considered feasible.

**Comment by grgkopanas** [comment]
This is a different representation than the one discussed in the paper, converting this representation to a traditional point cloud is not trivial but could be considered feasible.
