### ISSUE TITLE
SIBR install

### ISSUE THREAD

**Issue by Daviddddl** [graphdeco-inria/gaussian-splatting#516]
you may need to specify the nvcc path when cmake Bbuild, delete the build directory and rerun:

cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release -DCMAKE_CUDA_COMPILER="/usr/local/cuda-11.8/bin/nvcc"

**Comment by ivashmak** [comment]
That worked for me as well, probably it's worth mentioning on the main page.
