### ISSUE TITLE
Tank and Temple dataset

### ISSUE THREAD

**Issue by amoazeni75** [graphdeco-inria/gaussian-splatting#52]
Hi,

Thanks for providing the source code;
As I can see inside the `scene` class, you can only load Blender and Colmap datasets. Do you have any code for loading the Tank and Temple dataset?

Thanks.

**Comment by grgkopanas** [comment]
Unfortunately, Tanks and Temples are often being preprocessed by different
papers in many different ways. What we did is that we run out own colmap
pipeline exactly as described in the README and also provide some of the
colmap out for some scenes.

What exactly do you struggle with?

**Comment by amoazeni75** [comment]
Thanks for your quick reply.
I'm using Tank and Temples dataset provided here: 
[PointNeRF](https://github.com/Xharlie/pointnerf)

I'm not sure their poses have the same format as NeRF synthetic datasets to modify your `readCamerasFromTransforms` function to load the images and get R and T matrices.

It would make more sense to install Colmap and use your preprocessing pipeline. What do you think?

**Comment by Snosixtyboo** [comment]
> It would make more sense to install Colmap and use your preprocessing pipeline. What do you think?

Yes definitely, the transforms loader is only meant to load the NeRF Synthetic dataset. Loading general scenes with it will **not** work well (I tried at some point).

Hth,
Bernhard
