### ISSUE TITLE
Without sfm initialization.

### ISSUE THREAD

**Issue by Lwy-1998** [graphdeco-inria/gaussian-splatting#529]
Hi, thanks for your work.
I used colmap for reconstruct point cloud for my own dataset( shot on iphone).
but the colmap result produce only 2 photos in images folder.So I think colmap failed on my dataset.

I want to train without sfm initialization.
How can I do it?

**Comment by yuedajiong** [comment]
withOUT sfm, if no spar point-cloud only, not a big problem, just not very good on quality.

pls take more photos form different views and process it by colmap.
