### ISSUE TITLE
why stop at Populating library imgui when i run cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release on ubuntu 20.04?

### ISSUE THREAD

**Issue by 999love999** [graphdeco-inria/gaussian-splatting#531]
<img width="632" alt="屏幕截图 2023-12-07 232420" src="https://github.com/graphdeco-inria/gaussian-splatting/assets/150641118/269499ed-fb53-4857-a46d-17880f9971f5">
<img width="644" alt="屏幕截图 2023-12-07 232901" src="https://github.com/graphdeco-inria/gaussian-splatting/assets/150641118/2db49bc4-4aae-413b-9d97-7885f1e88bd4">

**Comment by 999love999** [comment]
![Uploading 屏幕截图 2023-12-07 232500.png…]()

**Comment by NeakNero** [comment]
It just takes a long time.

**Comment by xiaokezhou** [comment]
> It just takes a long time.

How long?  The building thread shows 0% CPU and MEM occupation, weird

**Comment by lovelyyoshino** [comment]
about 20min, you can use ethstatus to check eth0 network speed
