### ISSUE TITLE
how to run SIBR?

### ISSUE THREAD

**Issue by 999love999** [graphdeco-inria/gaussian-splatting#532]
when I run that viewers happen that bash: .viewersbinSIBR_gaussianViewer_app.exe: command not found.Due to the absence of a GPU on my computer, I am running on a remote server with Ubuntu 20.04 using VSCode, connected via SSH.

**Comment by Snosixtyboo** [comment]
An Ubuntu installation of the code will not produce an exe, but simply an executable without a particular extension
