### ISSUE TITLE
Question about the variable

### ISSUE THREAD

**Issue by tuning12** [graphdeco-inria/gaussian-splatting#536]
First thank you for your excellent work.

The method "create_from_pcd" of class "GaussianModel" in "./scene
/gaussian_model.py" defines the properties called "self._features_dc" and "self._features_rest" in line 142 and 143. I don't know what they correspond to in the article and how to use them. Could you please explain it?

**Comment by xiaoc57** [comment]
i thought it is color and sh.
in paper, section 5 mentions it that they said In addition to positions 𝑝, 𝛼, and covariance Σ, we also optimize SH coefficients representing color 𝑐 of each Gaussian to correctly capture the view-dependent appearance of the scene. 
this is my opponion.
in Chinese： 我认为它是同时优化颜色和sh系数。

**Comment by yuedajiong** [comment]
标准答案：
作者用SH来给高斯球着色。
本来直接用个feature，2^level即可；但大神们研究发现，把这个分成两部分，用不同的学习率来优化更好。 （我在issue中问过，作者也这么回答的。）（我还没有推敲，如果不用SfM的初始化，是不是也分两部分更好。）
前面DC，我不肯定，是不是direct-color?  还是其他缩写。
如何在render中使用SH，代码在cuda的.cu中，那个函数很简单，搞CG的人可能看都不用看就知道。
computeColorFromSH @ forward.cu

额外赠送一个理解： 这里其实用了16个float，相比坐标才3个，有点浪费啊。 有些沿GS继续发展的大神，也在想优化这个大小，包括训练渲染和文件存储的时候。  这里有各种优化，不展开了。

**Comment by tuning12** [comment]
感谢各位的回复和解释，我的问题解决了

**Comment by tuning12** [comment]
感谢各位的回复和解释，我的问题解决了

**Comment by tuning12** [comment]
感谢各位的回复和解释，我的问题解决了
The issue has been solved
