### ISSUE TITLE
not issue, info to GS-er:  how to reconstruct 'clean' object without 'float'.

### ISSUE THREAD

**Issue by yuedajiong** [graphdeco-inria/gaussian-splatting#541]
1.  segment 2D image to generate focus-object and background-mask.
2.  make the best of the ‘background’ parameter in GS.
--- it is ok. ---
[ 3.  I am trying other way(s), still on the way:  use the mask in optimization and cuda-render.  (don't  generate gauss-point(s) and render the pixels for bg-mask pixels.) ] 

very CLEAN for me now:

[ply_029900_o.zip](https://github.com/graphdeco-inria/gaussian-splatting/files/13637324/ply_029900_o.zip)

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/52232153/b6352803-8a06-4483-9f02-516abf8c127b)

你就说，beautiful 不 beautiful？

**Comment by HungNgoCT** [comment]
> 1. segment 2D image to generate focus-object and background-mask.
> 2. make the best of the ‘background’ parameter in GS.
>    --- it is ok. ---
>    [ 3.  I am trying other way(s), still on the way:  use the mask in optimization and cuda-render.  (don't  generate gauss-point(s) and render the pixels for bg-mask pixels.) ]
> 
> very CLEAN for me now:
> 
> [ply_029900_o.zip](https://github.com/graphdeco-inria/gaussian-splatting/files/13637324/ply_029900_o.zip)
> 
> ![image](https://private-user-images.githubusercontent.com/52232153/289579202-b6352803-8a06-4483-9f02-516abf8c127b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjkzMjAsIm5iZiI6MTcwMjM2OTAyMCwicGF0aCI6Ii81MjIzMjE1My8yODk1NzkyMDItYjYzNTI4MDMtOGEwNi00NDgzLTlmMDItNTE2YWJmOGMxMjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA4MTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5Y2U1NDE0ZDdkODZkN2E5OWZmNmVlMmVlYjA4OWNjNmE0OTY4NWU0OGM4MjgwNzlkN2I5YzFmNzQwYmRjMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.atQauBV-m1ktdfTcOuha-zZSyEeZBScwZquBsQyrnqE)
> 
> 你就说，beautiful 不 beautiful？

@yuedajiong Can you try with large scene? For example, capture a street 500m, then try. This is problem many people facing.

**Comment by bmikaili** [comment]
I also tried this on images of complex industrial machinery, unfortunately segmenting them (I used rembg) did not work as too many internal parts were erroneously detected as background. But maybe for simpler objects it's a good approach!

**Comment by yuedajiong** [comment]
yes, proper for individual /standalone objects.
my case is for individual object reconstruction for VR and Game, such as resin toy.

**Comment by bmikaili** [comment]
Then it's a good fit! I can also recommend you to check out this https://github.com/francescofugazzi/3dgsconverter it does density based pruning and filtering of floaters.

**Comment by yuedajiong** [comment]
@bmikaili    Thanks great-master.  You are so kindly.
