### ISSUE TITLE
Is it possible to use SIBR_gaussianViewer_app without GPU in Windows?

### ISSUE THREAD

**Issue by AnimatableDreamer** [graphdeco-inria/gaussian-splatting#545]
I have a Radeon 6800H CPU. Is it possible to use SIBR_gaussianViewer_app without GPU in Windows?

**Comment by yuedajiong** [comment]
技术上可行：
    1. 用CPU多线程模式重写
    2. 用Windows上的非CUDA的GPU来实现 （肯定有GPU啊，哪怕集成的），OPENGL之类的

实际上：
    1.  上面的方案，成本太高了，没必要。 纯CPU的跑起来也最终用户也慢得没法用。
    2.   你可以选择一个WebGL之类的用一下，现在实现的有不少了。
    3.   你可以在Linux GPU上渲染，把窗口重定向到windows显示， Xserver之类的。
    4.   如果你连SIBR viewer都不想装，也挺麻烦的，我给你一个我写的最简单的。
          我的GS代码修改过，你需要把数据和模型那几行稍微修改一下。
          按照训练数据集，单击一步一步显示，双击直接全部动画完毕。
          如果有用，你说个谢谢啊。
         
[superi.zip](https://github.com/graphdeco-inria/gaussian-splatting/files/13690917/superi.zip)

**Comment by Snosixtyboo** [comment]
Sorry, we only support CUDA-capable GPUs.
