### ISSUE TITLE
The problem of the boxMinMax function

### ISSUE THREAD

**Issue by SYSUykLin** [graphdeco-inria/gaussian-splatting#547]
I read the boxMinMax function in simple_knn.cu. And I think there are some problem in the code:
`	for (int off = BOX_SIZE / 2; off >= 1; off /= 2)
	{
		if (threadIdx.x < 2 * off)
			redResult[threadIdx.x] = me;

		__syncthreads();
		if (threadIdx.x < off)
		{
			MinMax other = redResult[threadIdx.x + off];
			me.minn.x = min(me.minn.x, other.minn.x);
			me.minn.y = min(me.minn.y, other.minn.y);
			me.minn.z = min(me.minn.z, other.minn.z);
			me.maxx.x = max(me.maxx.x, other.maxx.x);
			me.maxx.y = max(me.maxx.y, other.maxx.y);
			me.maxx.z = max(me.maxx.z, other.maxx.z);
		}
		__syncthreads();
	}`

When the P can not divisible by BOX_SIZE，the number of the valid elements in the last block might not be BOX_SIZE. 
`MinMax other = redResult[threadIdx.x + off];`
redResult[threadIdx.x + off] is invalid.

Is that right?

**Comment by Snosixtyboo** [comment]
This should be fine, because in the lines just above the ones that you posted, threads that would read boxes with an index >= P will just write boxes into ```me``` that cannot cause an update to either min or max, so it results in no changes being made.
