### ISSUE TITLE
GS-er, look here:  COLMAP-Free 3D Gaussian Splatting.     

### ISSUE THREAD

**Issue by yuedajiong** [graphdeco-inria/gaussian-splatting#549]

**Comment by elenacliu** [comment]
Sry, but what do you mean?

**Comment by yuedajiong** [comment]
搞立体重构或生成，最理想的效果什么？

我用五个关键字概括（不同的场景需求不一定非常完全，但这几个很有代表性）：
立体+交互+逼真+影级+世界
1）立体：就不用解释了；
2）交互：是如果我们要构造上帝之梦般的场景，立体游戏，元宇宙，实时交互式电影（在影院用app，观众给主角换衣服，换装备...；踩一踩地板电影里也风沙四起<下一代弹幕深入电影里面>，敌人一脚把足球踢出屏幕观众一拳砸回去皮球变形...），那么需要立体模型是mesh这种可以交互的。
3）逼真：有两层意思，一是比如构造人，这个人很逼真于人类，比UE5-MetaHuman还逼真，还有非人类物体的逼真问题，比如流体例子等，在SpacetimeGaussians中demo里那个火焰枪其实可见GS对这种很适应，水波我还没有看到有人show demo，不过从原理上也适合用GS做的很逼真；二是逼真于某个具体的对象，比如human之苏菲玛索。比如科幻世界，有人喜欢二次元动画，但更多大片还是真人现实风格，表现力还是不一样。 
4）影级：就是分辨率，细节丰富等，现在论文这中resin-toy肯定不够，得UE-5那种效果。
5）世界：多对象，复杂的场景，包含互作。

我们搞立体重构或生成，最理想的技术是什么？
1）能不能一张几张苏菲玛索的照片，就把她重构的很逼真？  //few-shot / priori /  generation-proiblem   (me: 立体问题，最终一定是个生成问题，一定利用先验，而不是一个重构问题。 就算给你足够多照片。)
2)  能不能不要那么精确的camera pose esitmation?  甚至不要这一步？  就算不考虑算力/实时，很多场景由于输入数据质量，环境变化ei，特征点不充分，ColMap SfM的输出不好不准导致后面的重构不好，RobustLoc,  Lean等就算较好的算法，也有挑战 。   //camera-free至少是理想化的，完全不要cam-pos至少joint-opt.     (HERE: 这里是直接回答你的challange)
3)  观察现在立体游戏和电影。 远景用静态动态的2D，都足以欺骗观众的眼睛，中景用GS这种2.5D的在观察者有限移动下也足以以假乱真，近景不仅观察者远近变化大，角度变化大导致对视角很敏感（多移动一度就模糊了），除了看还有可能互动。   //suface/mesh,   interactive
4)  类似的，还有动态化:  4D/dynamic/temp-spat/, ... 
5)  类似的，还有......    (太多要做的技术点，才能达到第一节所述的理想效果，不一一列举)
0）其实，立体的表示，以及表示之后的构造算法，为了满足上面第一节的需求，GS除了是2.5D在深度上不是那么强的约束，是比较好的一种表示。  有没有更好的表示呢？也是问题。


SO:   我没有啥意思，我只是把我心目中为了达到理想效果需要的技术，发现有比较好的文章，在GS的大本营这里给分享一下。

**Comment by elenacliu** [comment]
I see, thank you!
