### ISSUE TITLE
Edit/clean a trained .ply file ?

### ISSUE THREAD

**Issue by henrypearce4D** [graphdeco-inria/gaussian-splatting#55]
Hi, is it possible to edit the noise and floaters from the trained .ply file?

I have opened the file in CloudCompare and can see that there are many headers with layers of information. Is there a way to edit the clouds in one go, crop them to a bounding box and save them back to the trained file type?

The subject in the bounding box is what I would like to crop to, as you can see there are a lot of floaters way out of the main scene area.

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/106480554/c4c85550-8306-4c8e-a61c-2975f5e6f699)

Alternatively, is there a way to constrain the splatting much closer to the input point cloud? I have tried swapping out the input cloud to one that has been edited so that just the subject is isolated but training still creates noise and floaters outside of this area, is this expected? We would also prefer to avoid masking.

And finally, is there an aabb_crop in the viewer it self, so the noise is still in the file but not rendered?

**Comment by grgkopanas** [comment]
> Hi, is it possible to edit the noise and floaters from the trained .ply file?
> 
> I have opened the file in CloudCompare and can see that there are many headers with layers of information. Is there a way to edit the clouds in one go, crop them to a bounding box and save them back to the trained file type?

If you can write a bit of python code and you know the coordinates of your aabb it should be fairly trivial to create a new point cloud with only the points that are inside the bounding box.

In a post-process setting with 3rd party tools I think it should work as long as they respect the .ply format correctly. I think a lot of tools are cutting corners in this regard and they assume that a point cloud has only xyz, normals, and rgb and assume that the properties in the ply file have a specific name which is a bit sad.


> 
> The subject in the bounding box is what I would like to crop to, as you can see there are a lot of floaters way out of the main scene area.
> 
> ![image](https://user-images.githubusercontent.com/106480554/255667011-384d46a6-f15c-4987-920a-1a75f98eb25e.png) ![image](https://user-images.githubusercontent.com/106480554/255666970-e82131a9-7fec-41c7-bac5-94f0cab4e7d5.png) ![image](https://user-images.githubusercontent.com/106480554/255666749-c4c85550-8306-4c8e-a61c-2975f5e6f699.png)
> 
> Alternatively, is there a way to constrain the splatting much closer to the input point cloud? I have tried swapping out the input cloud to one that has been edited so that just the subject is isolated but training still creates noise and floaters outside of this area, is this expected? We would also prefer to avoid masking.
> 

I can think of multiple ways to do that most of them include tweaking the optimisation, maybe one way is to add a regularisation term in the loss forcing anything outside of the aabb box to be transparent.

> And finally, is there an aabb_crop in the viewer it self, so the noise is still in the file but not rendered?

There is only zfar/znear I think @Snosixtyboo maybe has more info on that.

**Comment by henrypearce4D** [comment]
Hi thankyou for the suggestions. 
I have attempted to use open3d and plyfile python modules to read, crop and save but unfortunately I these don't seem to support extended headers and only save the xzy and normals info.

I read PCL could support extended format but its C++ and doesn't have an official python binding.

I also have tried converting the file from binary to ascii to then perform a crop but getting errors due to non-ascii characters so I'm a bit stuck here.


Interested to hear the follow ups on your other ideas also.

Henry

**Comment by Snosixtyboo** [comment]
Heyo,

because you have done some great things with our method I went ahead and added in the crop box feature (mostly self-explanatory, see below).

|![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/40643808/3195f25e-bf5d-419b-bd80-ac1affbb6931)|![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/40643808/2a79f60a-bdbc-42e7-b647-2987f5372ddd)|
|---|---|

The box may not align with your scene rotation-wise (this depends on your calibration). Also if you want to load the cropped version in our viewer after saving, you will have to make a custom iteration directory and put it in there. Also note that the cropped and saved point cloud always uses 3 SH bands, so if your trained scene uses fewer you will need a new ```cfg_args```

Looking forward to see you do cool stuff,
best,
Bernhard

**Comment by henrypearce4D** [comment]
Hey this is fantastic! thankyou so much for adding this, its really cleaned up our scenes, the toolset you created is great to test with.

We would also be interested to run something via the python method mention above to batch crop, not sure how to get started with loading the scenes that way so will have to investigate, are there any links that could help me in the right direction?

Again thanks for this addition of cropping in the viewer! hopefully we can share some more things soon.

**Comment by HrsPythonix** [comment]
Hello, I am also trying to clean the point cloud trained with this method, actually open3d support point cloud with custom labels, by using the `o3d.t.geometry.PointCloud` instead of `o3d.geometry.PointCloud` it can read the custom property defined in the ply file.

An example is shown below:
```
PointCloud on CPU:0 [1195326 points (Float32)].
Attributes: f_rest_42 (dtype = Float32, shape = {1195326, 1}), f_rest_33 (dtype = Float32, shape = {1195326, 1}), normals (dtype = Float32, shape = {1195326, 3}), f_dc_0 (dtype = Float32, shape = {1195326, 1}), f_rest_21 (dtype = Float32, shape = {1195326, 1}), f_rest_1 (dtype = Float32, shape = {1195326, 1}), f_rest_0 (dtype = Float32, shape = {1195326, 1}), f_rest_20 (dtype = Float32, shape = {1195326, 1}), f_dc_1 (dtype = Float32, shape = {1195326, 1}), f_dc_2 (dtype = Float32, shape = {1195326, 1}), f_rest_2 (dtype = Float32, shape = {1195326, 1}), f_rest_22 (dtype = Float32, shape = {1195326, 1}), f_rest_3 (dtype = Float32, shape = {1195326, 1}), f_rest_23 (dtype = Float32, shape = {1195326, 1}), f_rest_4 (dtype = Float32, shape = {1195326, 1}), f_rest_24 (dtype = Float32, shape = {1195326, 1}), f_rest_5 (dtype = Float32, shape = {1195326, 1}), f_rest_25 (dtype = Float32, shape = {1195326, 1}), f_rest_6 (dtype = Float32, shape = {1195326, 1}), f_rest_26 (dtype = Float32, shape = {1195326, 1}), f_rest_7 (dtype = Float32, shape = {1195326, 1}), f_rest_27 (dtype = Float32, shape = {1195326, 1}), f_rest_8 (dtype = Float32, shape = {1195326, 1}), f_rest_28 (dtype = Float32, shape = {1195326, 1}), f_rest_9 (dtype = Float32, shape = {1195326, 1}), f_rest_29 (dtype = Float32, shape = {1195326, 1}), f_rest_10 (dtype = Float32, shape = {1195326, 1}), f_rest_11 (dtype = Float32, shape = {1195326, 1}), f_rest_12 (dtype = Float32, shape = {1195326, 1}), f_rest_13 (dtype = Float32, shape = {1195326, 1}), f_rest_14 (dtype = Float32, shape = {1195326, 1}), rot_3 (dtype = Float32, shape = {1195326, 1}), f_rest_15 (dtype = Float32, shape = {1195326, 1}), rot_2 (dtype = Float32, shape = {1195326, 1}), f_rest_16 (dtype = Float32, shape = {1195326, 1}), rot_1 (dtype = Float32, shape = {1195326, 1}), f_rest_17 (dtype = Float32, shape = {1195326, 1}), rot_0 (dtype = Float32, shape = {1195326, 1}), f_rest_18 (dtype = Float32, shape = {1195326, 1}), f_rest_19 (dtype = Float32, shape = {1195326, 1}), f_rest_30 (dtype = Float32, shape = {1195326, 1}), f_rest_41 (dtype = Float32, shape = {1195326, 1}), scale_0 (dtype = Float32, shape = {1195326, 1}), f_rest_31 (dtype = Float32, shape = {1195326, 1}), f_rest_40 (dtype = Float32, shape = {1195326, 1}), scale_1 (dtype = Float32, shape = {1195326, 1}), f_rest_32 (dtype = Float32, shape = {1195326, 1}), f_rest_43 (dtype = Float32, shape = {1195326, 1}), scale_2 (dtype = Float32, shape = {1195326, 1}), f_rest_34 (dtype = Float32, shape = {1195326, 1}), f_rest_35 (dtype = Float32, shape = {1195326, 1}), f_rest_44 (dtype = Float32, shape = {1195326, 1}), f_rest_36 (dtype = Float32, shape = {1195326, 1}), f_rest_37 (dtype = Float32, shape = {1195326, 1}), f_rest_38 (dtype = Float32, shape = {1195326, 1}), f_rest_39 (dtype = Float32, shape = {1195326, 1}), opacity (dtype = Float32, shape = {1195326, 1}).
```

But when the open3d tries to write an point cloud ply with such labels, it will mess up the order of these properties, which will result the render viewer and python file fail to load the ply processed by open3d. 

I had a glance at the reading implementation in viewer code and python code, I found that they must support a specific order to store the properties, but it seems that open3d cannot support to specify that kind of order.

@grgkopanas @Snosixtyboo Wonder if there could be any help to read ply with any order of these properties

in SIBR_viewers\src\projects\gaussianviewer\renderer\GaussianView.cpp, it use Aos to read all value to a predefined structure
```
	// Read all Gaussians at once (AoS)
	std::vector<RichPoint<D>> points(count);
	infile.read((char*)points.data(), count * sizeof(RichPoint<D>));

	// Resize our SoA data
	pos.resize(count);
	shs.resize(count);
	scales.resize(count);
	rot.resize(count);
	opacities.resize(count);

```

in scene\gaussian_model.py
```
def load_ply(self, path):
        plydata = PlyData.read(path)

        xyz = np.stack((np.asarray(plydata.elements[0]["x"]),
                        np.asarray(plydata.elements[0]["y"]),
                        np.asarray(plydata.elements[0]["z"])),  axis=1)
        opacities = np.asarray(plydata.elements[0]["opacity"])[..., np.newaxis]

        features_dc = np.zeros((xyz.shape[0], 3, 1))
        features_dc[:, 0, 0] = np.asarray(plydata.elements[0]["f_dc_0"])
        features_dc[:, 1, 0] = np.asarray(plydata.elements[0]["f_dc_1"])
        features_dc[:, 2, 0] = np.asarray(plydata.elements[0]["f_dc_2"])

        extra_f_names = [p.name for p in plydata.elements[0].properties if p.name.startswith("f_rest_")]
        assert len(extra_f_names)==3*(self.max_sh_degree + 1) ** 2 - 3
        features_extra = np.zeros((xyz.shape[0], len(extra_f_names)))
        for idx, attr_name in enumerate(extra_f_names):
            features_extra[:, idx] = np.asarray(plydata.elements[0][attr_name])
        # Reshape (P,F*SH_coeffs) to (P, F, SH_coeffs except DC)
        features_extra = features_extra.reshape((features_extra.shape[0], 3, (self.max_sh_degree + 1) ** 2 - 1))

        scale_names = [p.name for p in plydata.elements[0].properties if p.name.startswith("scale_")]
        scales = np.zeros((xyz.shape[0], len(scale_names)))
        for idx, attr_name in enumerate(scale_names):
            scales[:, idx] = np.asarray(plydata.elements[0][attr_name])

        rot_names = [p.name for p in plydata.elements[0].properties if p.name.startswith("rot")]
        rots = np.zeros((xyz.shape[0], len(rot_names)))
        for idx, attr_name in enumerate(rot_names):
            rots[:, idx] = np.asarray(plydata.elements[0][attr_name])
```

**Comment by grgkopanas** [comment]
To me it seems that the python side should be ok, `plydata.elements[0][**blah_name**] but the viewer side could take an improvement.

Does it fail loading on python too?

**Comment by HrsPythonix** [comment]
> extra_f_names

In Python, it does not fail, but the features_extra constructed here depends on the order of the property name. So if the order is messed up, the result will be messed up too

Eg, In this line, it read the f_rest_xxx as the order provided by the ply, the original ply follows the f_rest_1, f_rest_2,... , f_rest_N, but after being messed up by open3d, the order bnecome random, so the `features_extra ` constructed here is also random.
```
extra_f_names = [p.name for p in plydata.elements[0].properties if p.name.startswith("f_rest_")]
...
features_extra[:, idx] = np.asarray(plydata.elements[0][attr_name])
```


Wrong messed up result eg:
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/16586180/b256add6-8b61-4f80-a610-e2faba9b533c)


original right result:
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/16586180/1ae2812f-86dc-405f-ae07-3469a22d62a1)


Maybe for the Python code part I can help improve the implementation here and make a PR after testing it.

**Comment by HrsPythonix** [comment]
> To me it seems that the python side should be ok, `plydata.elements[0][**blah_name**] but the viewer side could take an improvement.
> 
> Does it fail loading on python too?

**Comment by grgkopanas** [comment]
yes, feel free :)

**Comment by henrypearce4D** [comment]
@HrsPythonix could you expand on your method of how you are loading the points and what you are doing?
Are you filtering floating points in the scene in the scene? would that it be possible?

**Comment by henrypearce4D** [comment]
> https://github.com/graphdeco-inria/gaussian-splatting/issues/55#issuecomment-1650286864

@Snosixtyboo just to check, for the values in the cropping box you added, are these the values in scene units? 
If I want to scale my scene and camera poses before training, what units would be best, does it matter? mm / cm / m ?

**Comment by Snosixtyboo** [comment]
Hi @henrypearce4D 

yes, the cropping is in scene units. But the ranges of the slider will adapt to go from the minimum xyz point coordinate in the scene to the maximum, so it shouldn't matter what you throw at it, cropping should just work.

Hth,
Bernhard

**Comment by henrypearce4D** [comment]
Thanks, and I presume using mm or m scale shouldn't effect calculations or quality?

**Comment by Snosixtyboo** [comment]
It SHOULD not. We have scaled scenes 10x up and down for testing and things worked the same. If you find that it creates issues, let us know and we can see what we can do.

**Comment by henrypearce4D** [comment]
3dgs convertor;
https://github.com/francescofugazzi/3dgsconverter

**Comment by chambbj** [comment]
If any PDAL users come along, I wanted to leave this here. PDAL can be used to edit/clean the PLY with a few "tricks". The `translate` command provided below will crop the X dimension in scene coordinates to the range (-5, 5), and setup the PLY writer in such a way that the SIBR viewer can visualize the results...almost. More on that below.

```
pdal translate original\point_cloud.ply edited\point_cloud.ply expression \
    --filters.expression.expression "X>-5 && X<5" \
    --writers.ply.storage_mode "little endian" \
    --writers.ply.dims "x=float, y=float, z=float, nx, ny, nz, f_dc_0, f_dc_1, f_dc_2, f_rest_0, f_rest_1, f_rest_2, f_rest_3, f_rest_4, f_rest_5, f_rest_6, f_rest_7, f_rest_8, f_rest_9, f_rest_10, f_rest_11, f_rest_12, f_rest_13, f_rest_14, f_rest_15, f_rest_16, f_rest_17, f_rest_18, f_rest_19, f_rest_20, f_rest_21, f_rest_22, f_rest_23, f_rest_24, f_rest_25, f_rest_26, f_rest_27, f_rest_28, f_rest_29, f_rest_30, f_rest_31, f_rest_32, f_rest_33, f_rest_34, f_rest_35, f_rest_36, f_rest_37, f_rest_38, f_rest_39, f_rest_40, f_rest_41, f_rest_42, f_rest_43, f_rest_44, opacity, scale_0, scale_1, scale_2, rot_0, rot_1, rot_2, rot_3"
```

Some things to note in this invocation.

1. `filters.expression` is used to limit the range of X values
2. `writers.ply.storage_mode` is used to specify binary output in little endian (default is ASCII)
3. `writers.ply.dims` is used to change the XYZ dimension type from doubles (PDAL's default for XYZ) to float. Sadly, all other dimensions must be listed to include them in the output, but the type is not required for these.

The final step is to remove the comment line from PDAL's PLY, which seems to trip up the SIBR viewer. In bash, I can use

```
sed -i '3d' /path/to/point_cloud.ply
```

I've just started to employ some additional PDAL filtering methods as well, for example outlier removal, with some success.
