### ISSUE TITLE
Question about the gaussian's opacity

### ISSUE THREAD

**Issue by leblond14u** [graphdeco-inria/gaussian-splatting#555]
Dear authors, 

Thank you for this great work. 
My question is about the gaussians opacity values :
In the code when looking at the opacity of each gaussians (`gaussians._opacity` tensor) during training I observed that the values could be negatives and were not bounded between 0 and 1 as I originally thought looking at your paper. 
Is there something I am missing or misinterpreting ? 

Thank you in advance for your answer,
Best regards

**Comment by yuedajiong** [comment]
Ha-ha-ha, I caught someone who doesn't read code.

@property
    def get_opacity(self):   #our great-master GS authors, used sigmoid in @property.   not directly use _opacity.
        return self.opacity_activation(self._opacity)  #sigmoid [0~1]

**Comment by leblond14u** [comment]
Aha, 
Yes indeed I missed it ! 

Thanks :+1:
