### ISSUE TITLE
Question about `reset_opacity()`

### ISSUE THREAD

**Issue by KosukeFukazawa** [graphdeco-inria/gaussian-splatting#556]
Hi, I couldn't find any of explanation of `reset_opacity()` in the paper.
In this repositry, the function appears to be called during optimization to force an opacity greater than 0.01 to 0.01.
https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/train.py#L123
https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L210
What effect does this function have in optimization?

**Comment by grgkopanas** [comment]
Here is where we discuss the reset of alpha in the paper.

Best,
George

**Comment by grgkopanas** [comment]
Here is where we discuss the alpha reset in the paper.

![Uploading IMG_20231216_115949.jpg…]()

**Comment by KosukeFukazawa** [comment]
Thank you for your reply!
However, I can't see the image...
It shows up as `Uploading IMG_20231216_115949.jpg…` on my screen. Could you upload it again?

**Comment by xiazhi1** [comment]
> Thank you for your reply! However, I can't see the image... It shows up as `Uploading IMG_20231216_115949.jpg…` on my screen. Could you upload it again?

@KosukeFukazawa  Same question for me. Have you solved it? when I run the code with debug , I find type error because I adjust the --opacity_reset_interval to 1 to see the function of reset_opacity and it may caused by stored_state is None? https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L262
I wonder why there do not use the same style like https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L277  to have a classification discussion on stored_state

**Comment by KosukeFukazawa** [comment]
I found that on page 5 to 6.
Thank you.

> In the first case we detect and treat the need for increasing both the total volume of the system and the number of Gaussians, while in the second case we conserve total volume but increase the number of Gaussians. Similar to other volumetric representations, our optimization can get stuck with floaters close to the input cameras;
in our case this may result in an unjustified increase in the Gaussian density. An effective way to moderate the increase in the number of Gaussians is to set the α value close to zero every α = 3000 iterations. The optimization then increases the α for the Gaussians where this is needed while allowing our culling approach to remove Gaussians with α  less than εα  as described above. Gaussians may shrink or grow and considerably overlap with others, but we periodically remove Gaussians that are very large in worldspace and those that have a big footprint in viewspace. This strategy results in overall good control over the total number of Gaussians. The Gaussians in our model remain primitives in Euclidean space at all times; unlike other methods [Barron et al. 2022; Fridovich-Keil and Yu et al. 2022], we do not require space compaction, warping or projection strategies for distant or large Gaussians.

**Comment by ZiqianHuan9** [comment]
Thank you for your question and the reply. I still don't quit understand the purpose of the opacity reset. Do you have any idea and new thoughts about it? Thank you!
