### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Le0m1** [graphdeco-inria/gaussian-splatting#558]
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 24.00 GiB total capacity; 53.19 GiB already allocated; 0 bytes free; 53.57 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I use rtx3090 24gb

**Comment by Tejasdavande07** [comment]
i also facing same issue with my 4090.please suggest how we can avoid this issue and is it any command or argument for reducing number of data-sets input

**Comment by Le0m1** [comment]
> i also facing same issue with my 4090.please suggest how we can avoid this issue and is it any command or argument for reducing number of data-sets input

As far as I know, Guasian is not adaptive for large number of photos. In my case, I had to train the whole building with all the rooms, I left this idea for an unknown period.
