### ISSUE TITLE
Prebuilt Windows viewer did not work after updating to the latest version

### ISSUE THREAD

**Issue by HrsPythonix** [graphdeco-inria/gaussian-splatting#56]
I used viewer downloaded in 07/12, I all worked fine. After downloading the latest version of viewer yesterday, the viewer just could not open the scene (a blank viewer pop out and disappear after a while). The logs are pasted below, I am using RTX2080, any idea what could cause this?

CMD:
```
.\bin\SIBR_gaussianViewer_app.exe -m .\gaussian-splatting\output\shop\ -s .\gs_dataset\dataset\shop\ --rendering-size 1920 1080
```

latest:
```
[SIBR] --  INFOS  --:   Initialization of GLFW
[SIBR] --  INFOS  --:   OpenGL Version: 4.6.0 NVIDIA 516.59[major: 4, minor: 6]
```

previous:
```
[SIBR] --  INFOS  --:   Initialization of GLFW
[SIBR] --  INFOS  --:   OpenGL Version: 4.6.0 NVIDIA 516.59[major: 4, minor: 6]
Number of input Images to read: 802
Number of Cameras set up: 802
LOADSFM: Try to open D:\workspace\SotaNeRFs\gs_dataset\dataset\shop_800\/sparse/0/points3D.bin
Num 3D pts 99869
[SIBR] --  INFOS  --:   SfM Mesh 'D:\workspace\SotaNeRFs\gs_dataset\dataset\shop_800\/sparse/0/points3d.bin successfully loaded.  (99869) vertices detected. Init GL ...
[SIBR] --  INFOS  --:   Init GL mesh complete
[SIBR] --  INFOS  --:   Loading 1193241 Gaussian splats
[SIBR] --  INFOS  --:   Initializing Raycaster
[SIBR] --  INFOS  --:   Interactive camera using (0.009,1100) near/far planes.
Switched to trackball mode.
[SIBR] --  INFOS  --:   Deinitialization of GLFW
```

**Comment by Snosixtyboo** [comment]
Hi,

thanks for letting us know, should now be fixed.

**Comment by Tao-617** [comment]
> I used viewer downloaded in 07/12, I all worked fine. After downloading the latest version of viewer yesterday, the viewer just could not open the scene (a blank viewer pop out and disappear after a while). The logs are pasted below, I am using RTX2080, any idea what could cause this?
> 
> CMD:
> 
> ```
> .\bin\SIBR_gaussianViewer_app.exe -m .\gaussian-splatting\output\shop\ -s .\gs_dataset\dataset\shop\ --rendering-size 1920 1080
> ```
> 
> latest:
> 
> ```
> [SIBR] --  INFOS  --:   Initialization of GLFW
> [SIBR] --  INFOS  --:   OpenGL Version: 4.6.0 NVIDIA 516.59[major: 4, minor: 6]
> ```
> 
> previous:
> 
> ```
> [SIBR] --  INFOS  --:   Initialization of GLFW
> [SIBR] --  INFOS  --:   OpenGL Version: 4.6.0 NVIDIA 516.59[major: 4, minor: 6]
> Number of input Images to read: 802
> Number of Cameras set up: 802
> LOADSFM: Try to open D:\workspace\SotaNeRFs\gs_dataset\dataset\shop_800\/sparse/0/points3D.bin
> Num 3D pts 99869
> [SIBR] --  INFOS  --:   SfM Mesh 'D:\workspace\SotaNeRFs\gs_dataset\dataset\shop_800\/sparse/0/points3d.bin successfully loaded.  (99869) vertices detected. Init GL ...
> [SIBR] --  INFOS  --:   Init GL mesh complete
> [SIBR] --  INFOS  --:   Loading 1193241 Gaussian splats
> [SIBR] --  INFOS  --:   Initializing Raycaster
> [SIBR] --  INFOS  --:   Interactive camera using (0.009,1100) near/far planes.
> Switched to trackball mode.
> [SIBR] --  INFOS  --:   Deinitialization of GLFW
> ```

I also meet this problem by now, could do you tell me how to fix it?
