### ISSUE TITLE
DataParallel or DistributeDataParallel for training

### ISSUE THREAD

**Issue by XuPengJian** [graphdeco-inria/gaussian-splatting#560]
When I use a large number of high-resolution images for training, when the number of initialized points exceeds a certain number, I find it easy to get "cuda out of memory". I am currently using a 3090 series 24GB graphics card, but it is still not enough. I would like to know if there is a way to train through DataParallel or DistributeDataParallel.

**Comment by BeauDing** [comment]
I have got the same problem with a RTX 3090. The error message is as follows.
`  RuntimeError: CUDA out of memory. Tried to allocate 8.04 GiB (GPU 0; 23.70 GiB total capacity; 12.18 GiB already allocated; 5.89 GiB free; 16.21 GiB reserved in total by PyTorch)`

**Comment by Snosixtyboo** [comment]
Hi, for the images, I recommend to set the data-device to 'cpu', this should help!

**Comment by smart4654154** [comment]
> Hi, for the images, I recommend to set the data-device to 'cpu', this should help!

hi,Can you explain in detail how to do it? Thank you very much
