### ISSUE TITLE
[question] the difference between the paper and the code

### ISSUE THREAD

**Issue by democheng** [graphdeco-inria/gaussian-splatting#562]
Thank you for your excellent paper and open source code.
I find the difference between the paper and the code: 
as shown in alg1, fist, 𝐿 ← 𝐿𝑜𝑠𝑠 (𝐼, 𝐼 ˆ ), next, 𝑀, 𝑆, 𝐶, 𝐴 ← Adam(∇𝐿), then, SplitGaussian or CloneGaussian.
but the code, fist 𝐿 ← 𝐿𝑜𝑠𝑠 (𝐼, 𝐼 ˆ ), next, SplitGaussian or CloneGaussian, the 𝑀, 𝑆, 𝐶, 𝐴 ← Adam(∇𝐿).

I think the paper is right, the Loss is computed on the current 3D-gaussians(before split or clone), and the  Parameters  should be optimized by these observations(before split or clone).

![alg1](https://github.com/graphdeco-inria/gaussian-splatting/assets/13517019/fb05ff26-bf88-476f-a9e9-fbd7cfdc0e9f)

**Comment by elenacliu** [comment]
same question here.

**Comment by elenacliu** [comment]
maybe change the order in the code and see what happens?

**Comment by democheng** [comment]
I have done the experiments, Considering the randomness involved in training, this order has almost no impact on the final result.
