### ISSUE TITLE
Question about backward: Is there any error in the calculation of dL_dconic2D.z?

### ISSUE THREAD

**Issue by will-zzy** [graphdeco-inria/gaussian-splatting#567]
Thanks for your excellent jobs!
I have a question about your backward process. In `backward.cu` line 551, why `dL_dconic2D.w` is updated? Should it be `dL_dconic2D.z`? And should dL_dconic2D.y be `-1.0f * gdx * d.y * dL_dG` Here is my calculation:
![question_github_3dgs](https://github.com/graphdeco-inria/gaussian-splatting/assets/54033655/59e0e3ba-0fbb-42fe-a401-d45151b865ad)

If I make any mistakes, please point them out. Thanks for a lot !

**Comment by KeKsBoTer** [comment]
I think this is the same issue as in https://github.com/graphdeco-inria/gaussian-splatting/issues/551

**Comment by will-zzy** [comment]
> I think this is the same issue as in #551

Thank you for your reply! I believe the issue with dL_dconic.y is resolved but I still have a question about dL_dconic.z, why is dL_dconic.w updated in line 551?

**Comment by kwea123** [comment]
@will-zzy because they use `.w` to save it, and they read it to `dL_dconic` by this https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/backward.cu#L165
whose `z` is actually the `w` of `dL_dconics`. This is extremely confusing.

**Comment by will-zzy** [comment]
@kwea123 @KeKsBoTer 
Thank you very much! This helps me a lot!

**Comment by Chen-Suyi** [comment]
> [@kwea123](https://github.com/kwea123) [@KeKsBoTer](https://github.com/KeKsBoTer) Thank you very much! This helps me a lot!

So, what is the conclusion?
Is dL_dconics.z redundant or meaningless? I cannot find any places where it is used.

**Comment by Chen-Suyi** [comment]
> I think this is the same issue as in [#551](https://github.com/graphdeco-inria/gaussian-splatting/issues/551)

It should be `atomicAdd(&dL_dconic2D[global_id].y, -gdx * d.y * dL_dG);`, right? Because the gradient of conic2D.y comes from 2 entries of the inverse covariance matrix, they need to be summed up.
