### ISSUE TITLE
Shourd the matrix "transformPoint4x4" transform from viewing (camera) space to the clipping space?

### ISSUE THREAD

**Issue by Dehaoq** [graphdeco-inria/gaussian-splatting#576]
Hello,

I was checking the Cuda code part. But some space transformation confused me.
Based on the function getProjectionMatrix(znear, zfar, fovX, fovY) from graphics_utils.py, the input projection matrix for "transformPoint4x4" should be a perspective projection matrix. It means that "transformPoint4x4" will transform a point in camera space to clipping space.
However, in your code (forward.cu, and function bool in_frustum), it seems that you directly transform the world space point through "transformPoint4x4". May I kindly know the reason for that? (example code is bleow)

float3 p_orig = { orig_points[3 * idx], orig_points[3 * idx + 1], orig_points[3 * idx + 2] };
float4 p_hom = transformPoint4x4(p_orig, projmatrix);

By the way, for "transformPoint4x3" , it transforms the point from world space to camera space, which follows my assumption. (example code is below.)
p_view = transformPoint4x3(p_orig, viewmatrix);

**Comment by Dehaoq** [comment]
solved

**Comment by FeiiYin** [comment]
Hi, I have the same questions also, Can you provide some detailed explaination of why he did this? :-(

It seems that they first transformed the world point via a full_projection matrix (including view matrix already). Then they transform the point again with a 4*3 view matrix.

Thanks in advance.

**Comment by Dehaoq** [comment]
In their python code, they deliver the 'full_projection matrix' and 'view matrix' to the cuda part. View matrix transforms the point coordination from world space to camera space. Meanwhile, 'full_projection matrix'  is calculated by view matrix * perspective projection matrix (camera space to screen clipping space (NDC)). Thus, 'full_projection matrix' transforms the point from world space to clipping space. Did I solve your problem?

**Comment by FeiiYin** [comment]
Well, Thanks! It solved my problem. Currently I have another problem, hope you can give me some inspiration.

Currently, I want to project some image point `(x_i, y_i)` back to the world space, i.e. find the corresponding world point of the image point. I have obtained the depth `z_d` after the `in_frustum` function. How to obtain the world point? I perform the below operation but always get wrong results.

```
# Calculate the left bound and right bound from fovy and znear
tanHalfFovY = math.tan((FoVy / 2))
bound = tanHalfFovY * znear

# norm the point according to the fovy and znear
x_i = -bound + (x_i / resolution * (bound + bound))
y_i = -bound + (y_i / resolution * (bound + bound))

# Then get the camera point? Does this operation requries to scale the x_i?
x_i = x_i * z_d / z_near
y_i = y_i * z_d / z_near
(x_i, y_i, z_d)

# Then multiply the inverse matrix of full_projection matrix
world_point = bmm(full_projection.inverse(), (x_i, y_i, z_d, 1))
```
Can you provide some insights? If you are willing to provide some more help, I would like to inquire about the possibility of adding your wechat or something to take further communication!

**Comment by Dehaoq** [comment]
> Well, Thanks! It solved my problem. Currently I have another problem, hope you can give me some inspiration.
> 
> Currently, I want to project some image point `(x_i, y_i)` back to the world space, i.e. find the corresponding world point of the image point. I have obtained the depth `z_d` after the `in_frustum` function. How to obtain the world point? I perform the below operation but always get wrong results.
> 
> ```
> # Calculate the left bound and right bound from fovy and znear
> tanHalfFovY = math.tan((FoVy / 2))
> bound = tanHalfFovY * znear
> 
> # norm the point according to the fovy and znear
> x_i = -bound + (x_i / resolution * (bound + bound))
> y_i = -bound + (y_i / resolution * (bound + bound))
> 
> # Then get the camera point? Does this operation requries to scale the x_i?
> x_i = x_i * z_d / z_near
> y_i = y_i * z_d / z_near
> (x_i, y_i, z_d)
> 
> # Then multiply the inverse matrix of full_projection matrix
> world_point = bmm(full_projection.inverse(), (x_i, y_i, z_d, 1))
> ```
> 
> Can you provide some insights? If you are willing to provide some more help, I would like to inquire about the possibility of adding your wechat or something to take further communication!

The full_projection matrix may not be invertiable. And calculating the inverse of a matrix is not that accurate (some small error) and time-consuming. You can get the inverse matrix by the physical definition of the projection matrix or view matrix.

**Comment by Dehaoq** [comment]
The full_projection matrix may not be invertiable. And calculating the inverse of a matrix is not that accurate (some small error) and time-consuming. You can get the inverse matrix by the physical definition of the projection matrix or view matrix.

**Comment by Dehaoq** [comment]
> Well, Thanks! It solved my problem. Currently I have another problem, hope you can give me some inspiration.
> 
> Currently, I want to project some image point `(x_i, y_i)` back to the world space, i.e. find the corresponding world point of the image point. I have obtained the depth `z_d` after the `in_frustum` function. How to obtain the world point? I perform the below operation but always get wrong results.
> 
> ```
> # Calculate the left bound and right bound from fovy and znear
> tanHalfFovY = math.tan((FoVy / 2))
> bound = tanHalfFovY * znear
> 
> # norm the point according to the fovy and znear
> x_i = -bound + (x_i / resolution * (bound + bound))
> y_i = -bound + (y_i / resolution * (bound + bound))
> 
> # Then get the camera point? Does this operation requries to scale the x_i?
> x_i = x_i * z_d / z_near
> y_i = y_i * z_d / z_near
> (x_i, y_i, z_d)
> 
> # Then multiply the inverse matrix of full_projection matrix
> world_point = bmm(full_projection.inverse(), (x_i, y_i, z_d, 1))
> ```
> 
> Can you provide some insights? If you are willing to provide some more help, I would like to inquire about the possibility of adding your wechat or something to take further communication!

You could send an email to me. dehaoq@g.clemson.edu

**Comment by FeiiYin** [comment]
Thanks. That really helps me. I will follow your advice to perform some experiments then report the results to you! :-)

**Comment by BitCalSaul** [comment]
> In their python code, they deliver the 'full_projection matrix' and 'view matrix' to the cuda part. View matrix transforms the point coordination from world space to camera space. Meanwhile, 'full_projection matrix' is calculated by view matrix * perspective projection matrix (camera space to screen clipping space (NDC)). Thus, 'full_projection matrix' transforms the point from world space to clipping space. Did I solve your problem?

Interestingly, the [original code](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/auxiliary.h#L154) seems not use the result by full_projection matrix to prefilter the points in the frustum. I am confused by this act.
