### ISSUE TITLE
videos requirements

### ISSUE THREAD

**Issue by oym050922021** [graphdeco-inria/gaussian-splatting#577]
hello, thank you for the source code. When training the model, are there any requirements for the video, such as image resolution, shooting speed, shooting Angle, shooting trajectory, minimum and maximum number of video frames, whether the first frame and the last frame should be consistent, etc. Thank you !

**Comment by jaco001** [comment]
1. Full HD should be ok
2. Frame rate don't have much to do - cus you output 1-2 frame per sec. (after 500 pic you have VRAM problems)
3. NO MOTTION BLUR - every blured images you can delete at start. So no fast turns.
4. Sharp images is your go to.
5. At last try to move camera to the places where ppl will be look.

Bonus: wide view

**Comment by oym050922021** [comment]
@jaco001  thank you very much for your reply.
