### ISSUE TITLE
The result without opening the viewer

### ISSUE THREAD

**Issue by Le0m1** [graphdeco-inria/gaussian-splatting#579]
Is there some way for me to download a screenshot, or even a couple, without opening the viewer. I am making a program that processes many models one at a time, and it would be very problematic for me to open each model to see the output.

**Comment by jaco001** [comment]
1. Viewing gs model start from first image/camera that you put to train.
2. You can use first model.ply too create automatic thumbnail.

**Comment by Snosixtyboo** [comment]
You can use ```render.py```. It should be fairly easy to modify it so that it renders only a few images (say, the first 5 training images) that you can then download.

**Comment by MilesMena** [comment]
> You can use `render.py`. It should be fairly easy to modify it so that it renders only a few images (say, the first 5 training images) that you can then download.

I am trying to generate novel views with render.py. It seems like render.py can only render images that we already have views of

**Comment by cta5425** [comment]
@MilesMena This should help I think: https://github.com/graphdeco-inria/gaussian-splatting/issues/506
I am going to try it out

**Comment by MilesMena** [comment]
@cta5425 Yes I tried that and it worked for me! I had opened another issue and completed it there. For my task there was some issues with how the scene was rendered and the orientation of the axis, but that was easy enough to solve.

**Comment by cta5425** [comment]
@MilesMena I am glad to hear you could solve your problem! 
I am currently trying to do something similar, but I am facing some issues initializing the 3dgs model I had previously created to make custom renders afterwards. 

How did you pass the path of the gaussian model and later initialize gaussians = GaussianModel()? 
Many thanks in advance!

**Comment by MilesMena** [comment]
the gaussians are initialized in the Scene() init, but that isn't what I needed so I wrote this:
`def get_gaussians(dataset: ModelParams, iteration: int):
    '''
    '''
    gaussians = GaussianModel(dataset.sh_degree)
    if iteration:
            if iteration == -1:
                loaded_iter = searchForMaxIteration(os.path.join(dataset.model_path, "point_cloud"))
            else:
                loaded_iter = iteration
            print("Loading trained model at iteration {}".format(loaded_iter))

    gaussians.load_ply(os.path.join(dataset.model_path,"point_cloud","iteration_" + str(loaded_iter),"point_cloud.ply"), args.train_test_exp)
    
    return gaussians`
 and call it with 
`gaussians = get_gaussians(dataset, iteration)`

I lifted most of it from how the authors load the gaussians.

**Comment by isso313** [comment]
@MilesMena Thank you a lot! I managed to do the same and it worked!

**Comment by i-nkrumah** [comment]
Can you share the full code with me, since I'm new to 3DGS, I don't understand a lot of it, thanks!
