### ISSUE TITLE
Rendering remotely

### ISSUE THREAD

**Issue by resurgo97** [graphdeco-inria/gaussian-splatting#580]
Hi.
I am working on my local computer, connected to the high-end remote server.
When I execute the SIBR viewer on my local using X11, rendering is extremely slow. (FPS lower than 1)
Is it even possible to perform real-time rendering when rendering remotely?

**Comment by yifanlu0227** [comment]
I can run the SIBR_viewer on the remote server and display it on my local PC with X11 forwarding now. However, the FPS is very low as well.

**Comment by Snosixtyboo** [comment]
Hi,

remote rendering with the remote viewer requires a good connection and a fluent X11 server. For real-time rendering we use the gaussianViewer app, which does NOT support remote rendering.

**Comment by LChen-99** [comment]
> I can run the SIBR_viewer on the remote server and display it on my local PC with X11 forwarding now. However, the FPS is very low as well.

Is there a solution now? O.O

**Comment by UpsilonYHZ** [comment]
> > I can run the SIBR_viewer on the remote server and display it on my local PC with X11 forwarding now. However, the FPS is very low as well.
> 
> Is there a solution now? O.O

maybe you can download the result and view it locally?
