### ISSUE TITLE
Training flat square object (specular painting on metal plate with view dependent colors) 

### ISSUE THREAD

**Issue by pknmax** [graphdeco-inria/gaussian-splatting#581]
How to train flat square object (specular painting on metal plate) whose rear side I can no capture?
As I can not capture back side, the gaussians tends to scale more in z directions, 
Which hyper parameters should I use? 
Any other suggestions? 
@grgkopanas

**Comment by jaco001** [comment]
In short: capture it with the entire wall around it.

Shinny/glossy items need some 3D room to make illusions of reflection. If you don't have eg. game engine to render GS with mask to cover this 3D noise behind flat surface, all you can do is make something behind paint (like wall) that visualy prevent spectator to go behind.

**Comment by pknmax** [comment]
is there way to limit the spread of the gaussians at back?

**Comment by Snosixtyboo** [comment]
You could try to introduce depth regularization, but in the published approach, no, there is no built-in way to limit the spread in the depth! But if you know the plane on which you want to render, you could add some Python code to force all Gaussians back onto this plane (or into a given z range) in every iteration.

**Comment by pknmax** [comment]
@Snosixtyboo can you please elaborate how to do this:

"if you know the plane on which you want to render, you could add some Python code to force all Gaussians back onto this plane (or into a given z range) in every iteration."

Like how to add depth map Loss supervision during training given we have depths?
