### ISSUE TITLE
What is the meaning of `add_densification_stats `?

### ISSUE THREAD

**Issue by elenacliu** [graphdeco-inria/gaussian-splatting#582]
https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L405-L407

A little confused about the `xyz_gradient_accum` and `viewspace_point_tensor` variable. What's the meaning of `xyz_gradient_accum`? And I think `xyz` is in world space, but viewspace_point is in 2D screen space, so what's the relation of the two?

**Comment by jh27kim** [comment]
Adaptive Gaussian control uses partial derivative (dL/du) to determine which Gaussian to be split/cloned. 
The function precomputes the gradient to every Gaussian in the visible frustum.

**Comment by Snosixtyboo** [comment]
> Adaptive Gaussian control uses partial derivative (dL/du) to determine which Gaussian to be split/cloned.
> The function precomputes the gradient to every Gaussian in the visible frustum.

**accumulates** the gradient to every Gaussian in the visible frustum, but other than this, correct.

**Comment by xuyanging** [comment]
Why can the gradient be used to determine split/clone gaussian, I mean what is the physical meaning of the gradient

> Adaptive Gaussian control uses partial derivative (dL/du) to determine which Gaussian to be split/cloned. The function precomputes the gradient to every Gaussian in the visible frustum.
