### ISSUE TITLE
Rendering a camera path in the pre-built viewer options not working

### ISSUE THREAD

**Issue by henrypearce4D** [graphdeco-inria/gaussian-splatting#59]
The tools for adding cameras to make a camera path and rendering it doesn't seem to work in the pre-built viewer, am I missing something?

**Comment by Snosixtyboo** [comment]
Hi,

how did you do it? I just tried, it works for me. Here is one possible workflow i used:
1) Click Record
2) Start moving
3) Click Stop
4) Click Play to check the path. You can rerecord it if you don't like it. 
5) When happy, tick "Save video (from playing)"
6) Click "Play"
7) When it's over, click "Capture" -> "Export video"

Hth,
Bernhard

**Comment by henrypearce4D** [comment]
Thankyou, I was expecting controls such as a camera creation and path editor to appear, now I understand its recording the mouse movements.

**Comment by leo-frank** [comment]
Hi, could you share with me what's the diff between <Play> and <Play(No Interp)>?  @Snosixtyboo

**Comment by whu-lyh** [comment]
Such a genius design

**Comment by ZahraRezaee11** [comment]
hi 
Thanks Snosixtyboo! I tried this method, but manually moving the mouse results in uneven speed and pauses, making it difficult to create a smooth, repeatable video for comparison. I also tried the "key camera" method, but after adding multiple keys, the camera doesn’t move when I click Play.

Would you happen to know a way to define a smooth camera orbit programmatically, save it as a path, and load it into the viewer for consistent motion? I’d really appreciate any suggestions. Thanks in advance!

**Comment by ZahraRezaee11** [comment]
> Hi,
> 
> how did you do it? I just tried, it works for me. Here is one possible workflow i used:
> 
> 1. Click Record
> 2. Start moving
> 3. Click Stop
> 4. Click Play to check the path. You can rerecord it if you don't like it.
> 5. When happy, tick "Save video (from playing)"
> 6. Click "Play"
> 7. When it's over, click "Capture" -> "Export video"
> 
> Hth, Bernhard



hi
Thanks Snosixtyboo! I tried this method, but manually moving the mouse results in uneven speed and pauses, making it difficult to create a smooth, repeatable video for comparison. I also tried the "key camera" method, but after adding multiple keys, the camera doesn’t move when I click Play.

Would you happen to know a way to define a smooth camera orbit programmatically, save it as a path, and load it into the viewer for consistent motion? I’d really appreciate any suggestions. Thanks in advance!

**Comment by henrypearce4D** [comment]
Create a camera path in blender and convert it to a .lookat or .bundler using ChatGPT

You can use the points3d.ply and the blender photogrammetry addon to import the cloud with colours to plan your path

**Comment by ZahraRezaee11** [comment]
> Create a camera path in blender and convert it to a .lookat or .bundler using ChatGPT
> 
> You can use the points3d.ply and the blender photogrammetry addon to import the cloud with colours to plan your path

Hi henry, thanks for your help,
I’ve been trying to set up the Photogrammetry Importer in Blender but ran into some issues.

What I’ve done so far:
-Installed the Photogrammetry Importer Addon successfully.
-Installed all required dependencies (pillow, lazrs, laspy, pyntcloud) inside a virtual environment (blender_env).
-Verified that Blender is using the correct Python environment.
-Manually added the correct Python path inside Blender’s sys.path.
-Removed & reinstalled the addon, but it doesn’t appear in Blender’s Add-ons list or in File → Import.

so when i use import -.ply file i see this picture 

![Image](https://github.com/user-attachments/assets/42eab1a8-57f5-4f08-bca6-e3be3221eafc)

but with sibr i see this 

![Image](https://github.com/user-attachments/assets/9bd7ebc3-2360-4fd7-967c-20e04457b81e)

Any suggestions on how to fix this? 
so i can't see my model correctly to create a path



Thanks in advance for your help!

**Comment by henrypearce4D** [comment]
The dependency to view points is Pyntcloud, the others dont matter too much

![Image](https://github.com/user-attachments/assets/fdc5c8a2-092a-4071-b4f2-b9f5c567f1c7)

Toggle the Update Importers and the option to import should be there

![Image](https://github.com/user-attachments/assets/15150dc9-d10e-4d0b-b93a-4755334b8c67)

Import Point Data
![Image](https://github.com/user-attachments/assets/a726d84d-56ad-46f0-bbbb-602b4f21d309)

Remember though the points3d is the sparse cloud so wont look very detailed.


The Kiri Addon is another option to view your trained splats .ply but rendering is heavy

https://github.com/Kiri-Innovation/3dgs-render-blender-addon

**Comment by ZahraRezaee11** [comment]
> The dependency to view points is Pyntcloud, the others dont matter too much
> 
> ![Image](https://github.com/user-attachments/assets/fdc5c8a2-092a-4071-b4f2-b9f5c567f1c7)
> 
> Toggle the Update Importers and the option to import should be there
> 
> ![Image](https://github.com/user-attachments/assets/15150dc9-d10e-4d0b-b93a-4755334b8c67)
> 
> Import Point Data ![Image](https://github.com/user-attachments/assets/a726d84d-56ad-46f0-bbbb-602b4f21d309)
> 
> Remember though the points3d is the sparse cloud so wont look very detailed.
> 
> The Kiri Addon is another option to view your trained splats .ply but rendering is heavy
> 
> https://github.com/Kiri-Innovation/3dgs-render-blender-addon


I do have PyntCloud installed, and I’ve toggled the Update Importers so that “Point Data” shows up exactly like in your screenshot. I was able to import the .ply output from my Gaussian Splatting pipeline, but it still looks sparse


I also tried the Kiri add-on you mentioned (3DGS Render for Blender), but the result is look like this 

![Image](https://github.com/user-attachments/assets/05d3a6c8-c64a-41d4-897c-861e2d1ca977)

. Is there a step I’m missing to make the splats more visible or to improve the appearance?

thanks again!

**Comment by henrypearce4D** [comment]
Change to viewport shading, Enable Camera Updates and Start Camera Update

![Image](https://github.com/user-attachments/assets/c84a0ee5-069b-4c28-b44b-a28a8acd248c)

**Comment by ZahraRezaee11** [comment]
> Change to viewport shading, Enable Camera Updates and Start Camera Update

Thanks for the tip. I switched the viewport shading and enabled camera updates as you suggested , but it still appears blurry. Any advice on making it clearer? Thanks again!

![Image](https://github.com/user-attachments/assets/79eafc39-3f5c-4bf1-9b04-683df1c97f2b)

![Image](https://github.com/user-attachments/assets/1fa88b1d-d513-43e9-a1b6-c4ed59fec58c)
