### ISSUE TITLE
Just single Pixel rendering

### ISSUE THREAD

**Issue by pknmax** [graphdeco-inria/gaussian-splatting#597]
Hi @grgkopanas @kwea123 @Snosixtyboo 
Is it possible to render just single pixel which returns the color of each single ray from different colmap camera positions using diff-gaussian-rasterization?

I am interested in getting final color at particular location for different view directions, by providing 3DGS pointcloud, location of target pixel for tracking in first fully rasterized image using first colmap camera pose from colmap pose sequence or 3D location in scene (how to find it?), and colmap camera poses.
Can you please guide me to achieve this?

**Comment by Snosixtyboo** [comment]
Hi, unfortunately, the pipeline is not designed to do this efficiently. What you describe should be possible if you just render the image and then discard all other pixels except for one. If you are interested in rendering a single pixel, a rasterization-based approach is really a wasteful idea: something that is ray-based, like NeRF, would be way, WAY smarter for this.

**Comment by xiaoc57** [comment]
@Snosixtyboo Although you are correct, some tasks still want to render a pixel rather than a tile patch. I think more research is needed.
