### ISSUE TITLE
Seeking for clarification in calculating dL_dmeans

### ISSUE THREAD

**Issue by QitaoZhao** [graphdeco-inria/gaussian-splatting#598]
Hi, thanks for your work! I am looking into your code for back-propagation. I found the last line (https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/backward.cu#L387) confusing for me in

```
// Compute loss gradient w.r.t. 3D means due to gradients of 2D means
// from rendering procedure
// ... some part
dL_dmean.x = (proj[0] * m_w - proj[3] * mul1) * dL_dmean2D[idx].x + (proj[1] * m_w - proj[3] * mul2) * dL_dmean2D[idx].y;
dL_dmean.y = (proj[4] * m_w - proj[7] * mul1) * dL_dmean2D[idx].x + (proj[5] * m_w - proj[7] * mul2) * dL_dmean2D[idx].y;
dL_dmean.z = (proj[8] * m_w - proj[11] * mul1) * dL_dmean2D[idx].x + (proj[9] * m_w - proj[11] * mul2) * dL_dmean2D[idx].y;

// That's the second part of the mean gradient. Previous computation
// of cov2D and following SH conversion also affects it.
dL_dmeans[idx] += dL_dmean;
```
It seems that `dL_dmean.x (.y, and .z)` is the gradient w.r.t. the 2D gaussian mean in the camera space (before perspective projection) and `dL_dmean2D` is the gradient in NDC coordinate system. If that's the case, why is the 2D mean gradient `dL_dmean` directly added to the 3D mean gradient `dL_dmeans`? Should we deal with the `view_matrix` before doing that to account for the w2c transform, or do I misunderstand something? Any explanation is appreciated!

**Comment by Chen-Suyi** [comment]
Have you figured it out? I have the same question about why they did not deal with view_matrix here.
