### ISSUE TITLE
Just Help

### ISSUE THREAD

**Issue by habeascorpse** [graphdeco-inria/gaussian-splatting#6]
HI, i'm trying to run the provided trained images that has been available.
but isn't clear to me what commands to run it. It's possible to just writes the steps to run the available on images.zip file?

**Comment by henrypearce4D** [comment]
The images you mention are evaluation images to see the quality differences between methods as far as I know. There are prepared datasets in the pinhole colmap format here [T&T+DB Datasets (650MB)](https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/datasets/input/tandt_db.zip)

I extracted them to a folder in my gaussian-splatting directory to a folder called 'data' then ran the training script;

`python train.py -s C:\gaussian-splatting\data\tandt\truck -m C:\gaussian-splatting\output\truck`

I then downloaded the [Pre-built Windows Binaries](https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/binaries/viewers.zip) to a folder in my gaussian-splatting directory to a folder called 'SIBR_viewers_win' then ran this command to launch the gui
`start C:/gaussian-splatting/SIBR_viewers_win/bin/SIBR_gaussianViewer_app.exe  -m C:\gaussian-splatting\output\truck`

**Comment by habeascorpse** [comment]
Thank you!
works very well on my RTX 3050 on Linux!
Amazing job, ~100 FPS
