### ISSUE TITLE
`do_shs_python` related to `convert_SHs_python`?

### ISSUE THREAD

**Issue by penguinflys** [graphdeco-inria/gaussian-splatting#60]
Hallo, Thanks for the great work!

I saw the remote Gaussian visualizer return the message `do_shs_python`, and the assigned params is not used anywhere.

https://github.com/graphdeco-inria/gaussian-splatting/blob/add0ada0e47493cda91f743019f99e39bdeb0657/train.py#L57

and the param is assigned to `pipe` the config for pipeline, and there has been a param `convert_SHs_python`. 

https://github.com/graphdeco-inria/gaussian-splatting/blob/add0ada0e47493cda91f743019f99e39bdeb0657/arguments/__init__.py#L64-L69

Is there any relation between the 2 params? what is the logic behind it?

**Comment by Snosixtyboo** [comment]
Hi,

great catch! They should be the same so that one can control these settings with the remote viewer. I fixed it and pushed.

Best,
Bernhard

**Comment by penguinflys** [comment]
Thanks for quick action! Issue closed
