### ISSUE TITLE
Can 3D gaussian splatting used for generate depth maps for image?

### ISSUE THREAD

**Issue by Ice-bear-go** [graphdeco-inria/gaussian-splatting#603]

**Comment by jaco001** [comment]
You can use just coordinates from point cloud and render it on image with gradient depend how far it is from camera.
So short answer: yes.

**Comment by myc634** [comment]
so do I need to modify CUDA code if I want to generate depth map for image?

**Comment by Ph03n1xdust** [comment]
Take a look at the merge requests, some of those deal with depth rendering, probably you can find a solution there.

**Comment by Snosixtyboo** [comment]
In theory it could, but the resulting depth maps from the published code are not great. Check out some follow-up publications, they are specifically targeting the extraction of good depth from 3DGS!

**Comment by leo-frank** [comment]
Based on original rasterization module, I make two contributions: Depth forward and backward, and I have verified its correctness on real datasets. Anyone can check the code for convenience. [Differential Gaussian Rasterization with Depth Forward and Backward Functionality](https://github.com/leo-frank/diff-gaussian-rasterization-depth)

**Comment by cs-mshah** [comment]
You may want to check these:
https://github.com/JonathonLuiten/diff-gaussian-rasterization-w-depth  
https://github.com/pointrix-project/msplat
