### ISSUE TITLE
To GSer:   huge 4D (stereo+motion) dataset

### ISSUE THREAD

**Issue by yuedajiong** [graphdeco-inria/gaussian-splatting#604]
1.  human + motion
   Characters: 200+  x  Motions:2500+  x  Cameras:108(36<360/10>*3<high-mid-low>)   x  Frames<Animations>:128  x  lights: 4(sun, pooint, ...)
   samples:  (supprted format: fbx, obj(s), mp4, images)
   ![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/52232153/12e36542-f2b5-4937-8f3e-5f61789e62c8)

2.  object  + motion
   2K+ objects (eg. dog<run, sit, ...>, pig<run, eat,...>, bird<fly,...>, ...)  
    (supprted format: fbx, obj(s), mp4, images)

3.  object + no-motion

**Comment by jaco001** [comment]
Nice... price? licence? link?

**Comment by yuedajiong** [comment]
@jaco001 
if not all data, if just for research, free, share to you.

**Comment by Fiiiiifi** [comment]
> 1. human + motion
>    Characters: 200+  x  Motions:2500+  x  Cameras:108(36<360/10>*3)   x  Frames:128  x  lights: 4(sun, pooint, ...)
>    samples:  (supprted format: fbx, obj(s), mp4, images)
>    ![image](https://private-user-images.githubusercontent.com/52232153/295225633-12e36542-f2b5-4937-8f3e-5f61789e62c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTE5ODQsIm5iZiI6MTcxNTI1MTY4NCwicGF0aCI6Ii81MjIzMjE1My8yOTUyMjU2MzMtMTJlMzY1NDItZjJiNS00OTM3LThmM2UtNWY2MTc4OWU2MmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEwNDgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNzE5MjMxMWQzMDIwOGM0Y2VjMjczY2NlMmMwMzRhOWUzY2IzNjUwOGZlZjYzYTIzYTdiOTY2Mzg2M2FiZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IZbZZFZq7qLs7xwKE7Tk9Aq1WhleowuW4ZbfINkJBSc)
> 2. object  + motion
>    2K+ objects (eg. dog<run, sit, ...>, pig<run, eat,...>, bird<fly,...>, ...)
>    (supprted format: fbx, obj(s), mp4, images)
> 3. object + no-motion

nice！would you like to share the dataset with me? Thanks a lot!

**Comment by yuedajiong** [comment]
@Fiiiiifi    
I have shared even code for dataset #1.   
Please checkout my code [super-ai-vision-stereo-object-mixamo](https://github.com/yuedajiong/super-ai-vision-stereo-object-mixamo).   And you can generarte more.   
Any running problem, you can call me.
