### ISSUE TITLE
3Dmodels

### ISSUE THREAD

**Issue by jiangyixing** [graphdeco-inria/gaussian-splatting#610]
Dear author, hello. Regarding your Gaussian pasting, I would like to ask, actually, I want to use it to export 3D models. Yes, I see that the generated effect is very realistic, and I want to export the characters or objects in the scene separately to 3D formats such as OBJ for my own use. Can I do this?

**Comment by yuedajiong** [comment]
读issue，太多人讨论这个了。
SuGaR是我折腾过的中间比较好的（感觉是最好），除了有点慢。

**Comment by jiangyixing** [comment]
> 读issue，太多人讨论这个了。 SuGaR是我折腾过的中间比较好的（感觉是最好），除了有点慢。

Okay, thank you for your suggestion
