### ISSUE TITLE
Is it unfair for learning parameters for all training images?

### ISSUE THREAD

**Issue by HungNgoCT** [graphdeco-inria/gaussian-splatting#613]
Hi.,

Thank you for your work.
I have question from your code: Each training iteration use a random training image with a learning parameters generated by update_learning_rate() function. Because iteration index of each image is different, learning parameters should be different too. Does this cause unfair training parameters for all the images? With a small dataset, this is not a problem. But with a large dataset, say thoundsands of images, this may cause an large unfairness.

Could you help me understand this, or I had a miss-understanding?

Thank you

**Comment by ljjTYJR** [comment]
why not you modify the iteration threshold according to your dataset size?

**Comment by HungNgoCT** [comment]
> why not you modify the iteration threshold according to your dataset size?

Thank you. Yes, I know. I just would like to understand the idea of Authors or algorithm here, or I have a mis-understanding when reading code.

**Comment by Snosixtyboo** [comment]
The published solution is definitely designed for a target problem size, i.e., common NeRF datasets. In the case that you mention, with thousands of images, if they are truly randomized, then we should still get "fair" behavior with respect to the features in the scene. But there are definitely scalability issues, which would be the subject of future followup work.
