### ISSUE TITLE
Is it possible to render features(with 16 channels) instead of RGB(with 3 channels) using "override_color"?

### ISSUE THREAD

**Issue by zz7379** [graphdeco-inria/gaussian-splatting#615]
Is it possible to render features(with 16 channels) instead of RGB(with 3 channels) using "override_color"? I find that if override_color=features, then i can only get a 3 channels image, but not 16 channels

**Comment by LoickCh** [comment]
You have to change the number of NUM_CHANNELS in config.h I guess

**Comment by johnren-code** [comment]
Hello, have you solved this?

**Comment by Snosixtyboo** [comment]
Yes, it should be. Change the NUM_CHANNELS, rebuild diff-gaussian-rasterization package, pass colors_precomp instead of shs, and then it should work.
