### ISSUE TITLE
Question about using COLMAP for dividing train/test.

### ISSUE THREAD

**Issue by YJ-142150** [graphdeco-inria/gaussian-splatting#617]
Firstly, thank you for your great work.
I have a question about utilizing the COLMAP.
We usually extract point clouds and camera poses from the images by COLMAP.
To get camera pose, we usually run COLMAP simultaneously with both train & test dataset.
However, it seems to get point clouds from test dataset.

How did you manage this problem?
Is there a way to get rid of test datasets' point clouds?

**Comment by jaco001** [comment]
When you start train.py code check if exist 'input.ply'. If not code import it from colmap and create file in training folder. At this moment you can change it/delete and replace/edit.

**Comment by YJ-142150** [comment]
So, does that mean I have to delete input.ply and let it make point cloud from only train set?

**Comment by Snosixtyboo** [comment]
There is currently no clean solution for what you are suggesting. Doing it in a two-step procedure is not easy, since COLMAP is free to choose different coordinate systems for the same scene. Sorry, this is currently not planned.

**Comment by YJ-142150** [comment]
Okay. Thank you for the answer.

**Comment by LiuJF1226** [comment]
@Snosixtyboo  @YJ-142150  This could be realized following https://colmap.github.io/faq.html#register-localize-new-images-into-an-existing-reconstruction or https://github.com/colmap/colmap/issues/1873#issuecomment-1504901277. First, use colmap to process the training images. Then, register the test images into existing model reconstructed by training images. This can ensure the same coordinate system and lead to point clound from only train set. But actually, the performance difference is negligible.
