### ISSUE TITLE
Does the input image sizes have to be all same?

### ISSUE THREAD

**Issue by YJ-142150** [graphdeco-inria/gaussian-splatting#621]
I can't run COLMAP with different image sizes.
Should image sizes have to be all same to run 3DGS?

**Comment by jaco001** [comment]
Yes and No ;)

Script from GS (convert.ply) accept images from one camera and with one size (even if it is rotated by 90 deg it is out)
So you can prep images, resize it and rotate before... but keep in mind that keep same FOV of cameras and image proportions.

Colmap can proced more - try colmap forum/documentation.

**Comment by YJ-142150** [comment]
Does the GS itself can run with various input image sizes or only single size? I think there might be other way to get point clouds from different input image sizes.

**Comment by yifanlu0227** [comment]
Just do the COLMAP sparse reconstruction yourself using multiple camera models for data preparation. 

3DGS supports multiple camera models in one scene.

**Comment by YJ-142150** [comment]
Okay, I'll try it.

**Comment by HungNgoCT** [comment]
> Just do the COLMAP sparse reconstruction yourself using multiple camera models for data preparation.
> 
> 3DGS supports multiple camera models in one scene.

Hi @yifanlu0227 ,

It seem that 3DGS-code base does not support multiple camera model? When I capture with different zooms (lens) from Iphone, I could not get good results. I am wondering I was wrong somethings? Please correct and advice if you have.

**Comment by yifanlu0227** [comment]
@HungNgoCT. Suppose you have 5 camera models, then you should create 5 subfolders under `images` which store corresponding images. When performing `colmap feature_extractor`, remember to set `--ImageReader.single_camera_per_folder 1`. This allows you to estimate 5 cameras for each subfolder. 

After the sparse reconstruction, `cameras.bin` and `images.bin` naturally save the 5-camera configuration and image-to-camera correspondence. You can seamlessly use them in 3DGS's code with little modification:

You need to modify `readColmapCameras` function in `gaussian_splatting/scene/dataset_readers.py` since your 'images' have subfolders. Origin `image_path = os.path.join(images_folder, os.path.basename(extr.name))` does not point to your image.

My code
```
        image_path = os.path.join(images_folder, os.path.basename(extr.name))
        image_name = os.path.basename(image_path).split(".")[0]
        try:
            image = Image.open(image_path)
        except FileNotFoundError: 
            # multiple camera models, 'images' have subfolders
            # For my example, extr.name: 'camera_model_1/1512860037922281.jpg'
            image_path = os.path.join(images_folder, extr.name)
            image_name = extr.name.split(".")[0] 
            image = Image.open(image_path)

```

**Comment by HungNgoCT** [comment]
> @HungNgoCT. Suppose you have 5 camera models, then you should create 5 subfolders under `images` which store corresponding images. When performing `colmap feature_extractor`, remember to set `--ImageReader.single_camera_per_folder 1`. This allows you to estimate 5 cameras for each subfolder.
> 
> After the sparse reconstruction, `cameras.bin` and `images.bin` naturally save the 5-camera configuration and image-to-camera correspondence. You can seamlessly use them in 3DGS's code with little modification:
> 
> You need to modify `readColmapCameras` function in `gaussian_splatting/scene/dataset_readers.py` since your 'images' have subfolders. Origin `image_path = os.path.join(images_folder, os.path.basename(extr.name))` does not point to your image.
> 
> My code
> 
> ```
>         image_path = os.path.join(images_folder, os.path.basename(extr.name))
>         image_name = os.path.basename(image_path).split(".")[0]
>         try:
>             image = Image.open(image_path)
>         except FileNotFoundError: 
>             # multiple camera models, 'images' have subfolders
>             # For my example, extr.name: 'camera_model_1/1512860037922281.jpg'
>             image_path = os.path.join(images_folder, extr.name)
>             image_name = extr.name.split(".")[0] 
>             image = Image.open(image_path)
> ```

Thank you so much @yifanlu0227 .

I really want to do this. I will try to follow your guidance, then update my results later.

Thanks again.
