### ISSUE TITLE
How do I render data for more channels

### ISSUE THREAD

**Issue by wangyuanbiubiubiu** [graphdeco-inria/gaussian-splatting#622]
I set shs to none before render, and colors_precomp concate became the dimension I needed, and I also changed #define NUM_CHANNELS 6
But the result of render is wrong, may I ask which step I may have done wrong?

**Comment by jh27kim** [comment]
i also face this issue any updates ?

**Comment by QitaoZhao** [comment]
Same issue here.

**Comment by johnren-code** [comment]
hello, have you solved this?

**Comment by jh27kim** [comment]
Yes please change the channel size specified in the config.cu and re-build the library. 
Also pass the precomputed colors during rendering since SH expects 3-ch output.

**Comment by Snosixtyboo** [comment]
> Yes please change the channel size specified in the config.cu and re-build the library. Also pass the precomputed colors during rendering since SH expects 3-ch output.

That is the correct answer, it should work like this. The important part is to rebuild the diff-gaussian-rasterization!

**Comment by johnren-code** [comment]
Hi, can I refer to the code you modified?

**Comment by z-mahmud22** [comment]
I think @jh27kim referred to this [line](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/config.h#L15C22-L15C23) from `config.h`.

**Comment by wangyuanbiubiubiu** [comment]
Sorry, forgot to reply. My changes are fine and need to be re-build: delete the build/ and diff_gaussian_rasterization.egg-info/ files and then pip install
