### ISSUE TITLE
No Good Initial Image Pair Found.

### ISSUE THREAD

**Issue by Yuhan291** [graphdeco-inria/gaussian-splatting#625]
Sometimes when I put in an image and run it I get a result like this: => No good initial image pair found.
What is the reason for this problem? Which piece of code will feedback such a problem?

Thank you.

**Comment by HungNgoCT** [comment]
> Sometimes when I put in an image and run it I get a result like this: => No good initial image pair found. What is the reason for this problem? Which piece of code will feedback such a problem?
> 
> Thank you.

It seems the error occurred when you run convert.py due to less images. Try to increase the number of images, say 50 or 100.

**Comment by jaco001** [comment]
This is Colmap telling you that you have "bad" photos and your work will be poor.
Generally, larger size and sharp photos are better. Single-color "walls" are difficult if you can't see the patterns on them.

If you really know what you do: 
- add more pictures (if you have)
- remove blurred ones
- sharpen pictures

**Comment by Snosixtyboo** [comment]
Hi, this is an issue related to COLMAP, which is not maintained by us. Please kindly refer to the original authors and their code solutions.
