### ISSUE TITLE
Better result for driving scenes?

### ISSUE THREAD

**Issue by killer2-1** [graphdeco-inria/gaussian-splatting#626]
I am dealing driving scenes with 3D gaussian splatting, and I found the description for improving the rendering result for larger datasets in FAQ: https://github.com/graphdeco-inria/gaussian-splatting/blob/main/assets/better.png, and I wonder if anyone can tell me which dataset this picture belongs to.
Thank you.

**Comment by killer2-1** [comment]
I googled this picture and didn't find any matched result except the pic itself. Wonder if anyone has any idea?

**Comment by Snosixtyboo** [comment]
Hi, sorry this is an unpublished dataset. It may be released at some point, but right now it is not openly available.

**Comment by killer2-1** [comment]
Thank you for your kind reply, and we hope the dataset may come soon. Happy Chinese New Year!







---- Replied Message ----
| From | ***@***.***> |
| Date | 2/10/2024 06:42 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [graphdeco-inria/gaussian-splatting] Better result for driving scenes? (Issue #626) |

Hi, sorry this is an unpublished dataset. It may be released at some point, but right now it is not openly available.
