### ISSUE TITLE
Some bugs in getProjectionMatrix()

### ISSUE THREAD

**Issue by chenguolin** [graphdeco-inria/gaussian-splatting#628]
It seems that there are some bugs in `getProjectionMatrix()` according to http://www.songho.ca/opengl/gl_projectionmatrix.html.

I understand that we never use the normalized z value anywhere, but it would be better to learn from the source code if these bugs could be fixed.

https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/utils/graphics_utils.py#L51-L70

As far as I understand, the last 2 lines should be:
```python
P[2, 2] = z_sign * (z_far + z_near) / (z_far - z_near)
P[2, 3] = -(2 * z_far * z_near) / (z_far - z_near)
```

Please let me know if I am wrong. Thanks!

**Comment by Snosixtyboo** [comment]
Hi,

there are different ways of computing the projection matrix. We follow the one given by 
https://www.scratchapixel.com/lessons/3d-basic-rendering/perspective-and-orthographic-projection-matrix/building-basic-perspective-projection-matrix.html
Note that we are not setting the entry of the matrix you think we are! In contrast to your reference, the row/column indices of the second, non-trivial entry are switched.
