### ISSUE TITLE
Does the 3DGS use point-cloud collected from both train/test dataset?

### ISSUE THREAD

**Issue by YJ-142150** [graphdeco-inria/gaussian-splatting#630]
We usually run COLMAP on whole dataset(train & test) and get camera pose. 
Is it possible to get rid of point cloud from test dataset?

**Comment by Snosixtyboo** [comment]
There is currently no clean solution for what you are suggesting. Doing it in a two-step procedure is not easy, since COLMAP is free to choose different coordinate systems for the same scene. Sorry, this is currently not planned.
