### ISSUE TITLE
Access Denied WinError 5 while building submodules

### ISSUE THREAD

**Issue by Type-Here** [graphdeco-inria/gaussian-splatting#634]
Hi, I'm trying to setting up Gaussian Splatting following the tutorial in this repo and Stephens' one.
I'm on a Windows 11 Machine using Anaconda with Python 3.7. This PC is shared among other users in lab so I can't change some settings but I've got Admin Privileges.

I'm stuck while building the submodules (diff-gaussian-rasterization and simple-knn). I know the order is important but I think I followed instruction quite correctly.
CUDA v11.7 is installed and all c++/python/conda packages should be compatible.

What I've already tried following suggestions among issues here and internet researches:

Commands run:
- Tried Anaconda  Prompt -> Open as Admin -> pip install / conda update env with environment.yml didn't work.
- `pip install submodules\diff-guassian-rasterization --user` gives same error
- `pip wheel . -w dist` (inside appropriate subdirectory) same error

What I also did:
- `pip install cmake wheel setuptools`
- `conda install vs2019_win-x64`
- `conda install cudatoolkit=11.7`
- `pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 -f  https://download.pytorch.org/whl/torch_stable.html` (for me, this solved 'No CUDA runtime found 'Error before)
- Setup several env variables (for CUDA ecc.) on Path among which:
    - C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64 
    - C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\
    - Added also env CUDA_PATH with same path as value as above.

- VS Studio 2019 is already installed (also 2022 but 2019 should be used)
- Added VS Tools and Optional Components for C/C++
- Already checked for Privileges in Properties -> Securitiy
- Already removed Read-Only to all repo directory and subdirectories.
- Restarted several times.
- Completely reinstalled the environment.
- Other things I don't recall.

I keep getting this error of Access Denied (WinError 5).
Any ideas?

```
Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff-gaussian-rasterization
  Building wheel for diff-gaussian-rasterization (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      error: [WinError 5] Accesso negato
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
Installing collected packages: diff-gaussian-rasterization
  Running setup.py install for diff-gaussian-rasterization ... error
  error: subprocess-exited-with-error

  × Running setup.py install for diff-gaussian-rasterization did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      running install
      C:\Users\CasaLabDell2\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-37
      creating build\lib.win-amd64-cpython-37\diff_gaussian_rasterization
      copying diff_gaussian_rasterization\__init__.py -> build\lib.win-amd64-cpython-37\diff_gaussian_rasterization
      running build_ext
      error: [WinError 5] Accesso negato
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> diff-gaussian-rasterization

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by DeepDream1128** [comment]
"git clone + url + **--recursive**" is all you need

**Comment by Type-Here** [comment]
Hi @DeepDream1128, thank you for your answer.
Do you mean something like git clone https://github.com/graphdeco-inria/gaussian-splatting --recursive ?
Because I'm pretty sure it was the first thing I did while trying to install gaussian splatting. I tried again to be sure and then I tried most of the passages above but unfortunately I didn't resolve the issue.

**Comment by Type-Here** [comment]
## Solved
I tried to use CUDA v12.1 in a new environment and initially it didn't work but the solution should be CUDA-version independent. 
The problem originated from some permissions not correctly set on our machine; since it's shared with other people, privileges were a bit messed up.

What worked for me:
- Set Full Control in Properties->Security for Users for:
    -   `"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc.exe"`
    -  `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\Hostx64\x64\cl.exe"`
    (NB Absolute Path may vary based on installation directories and versions)
- Open Anaconda Prompt with Admin (NB Important, I didn't solve without this passage. Maybe someone could use --user flag with pip install instead)
- Open the created env: `conda activate gaussian_splatting`
- Go to the working directory for gaussian_splatting (where you cloned the repo) 
- Make sure to set or have already set environment variables `DISTUTILS_USE_SDK=1` as the guide suggests and 
  `CUDA_PATH=<path/to/cuda>`
- Run `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64`
- Run `pip install submodule\diff-gaussian-rasteritazion`
- Run `pip install submodule\simple-knn`

What I DIDN'T use in the new solving environment:
- `pip install cmake wheel setuptools` (they're still required but they were installed as requirements while creating the env)
- `conda install vs2019_win-x64` (in my experience this messes up a bit the env, it is better to run vcvarsall.bat instead)
- `conda install cudatoolkit=11.7` (replace with own correct version)
- `pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 -f  
  https://download.pytorch.org/whl/torch_stable.html` (replace with own correct versions)

However, especially the last 2 could be very useful for other problems related to older CUDA versions (i.e. 11.7-11.8)
