### ISSUE TITLE
Error reported for Build of SIBR Viewers in ubuntu 20.04.

### ISSUE THREAD

**Issue by vamWu** [graphdeco-inria/gaussian-splatting#636]
Thank you for your outstanding work and open source contributions.

My system is ubuntu 20.04 and I have installed embree-3.8.0 with the following command.
sudo apt install -y libglew-dev libassimp-dev libboost-all-dev libgtk-3-dev libopencv-dev libglfw3-dev libavdevice-dev libavcodec-dev libeigen3-dev libxxf86vm-dev libembree-dev
the result is
Reading state information... Done
libavcodec-dev is already the newest version (7:4.2.7-0ubuntu0.1).
libavdevice-dev is already the newest version (7:4.2.7-0ubuntu0.1).
libxxf86vm-dev is already the newest version (1:1.1.4-1build1).
libassimp-dev is already the newest version (5.0.1~ds0-1build1).
libboost-all-dev is already the newest version (1.71.0.0ubuntu2).
libeigen3-dev is already the newest version (3.3.7-2).
libembree-dev is already the newest version (3.8.0+dfsg-1).
libglew-dev is already the newest version (2.1.0-4).
libglfw3-dev is already the newest version (3.3.2-1).
libopencv-dev is already the newest version (4.2.0+dfsg-5).
libgtk-3-dev is already the newest version (3.24.20-0ubuntu1.1).

But it always reports WARNING when building against SIBR Viewers:
"
ASSIMP DIR ASSIMP_DIR
-- Found ASSIMP: /usr/include
-- Found FFMPEG: /usr/include/x86_64-linux-gnu
CMake Warning at cmake/linux/dependencies.cmake:127 (find_package):
By not providing "Findembree.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "embree", but
CMake did not find one.

Could not find a package configuration file provided by "embree" (requested
version 3.0) with any of the following names:

embreeConfig.cmake
embree-config.cmake
Add the installation prefix of "embree" to CMAKE_PREFIX_PATH or set
"embree_DIR" to a directory containing one of the above files. If "embree"
provides a separate development package or SDK, be sure it has been
installed.
Call Stack (most recent call first):
cmake/linux/include_once.cmake:20 (include)
src/CMakeLists.txt:46 (include_once)

"

Can you please tell me how to modify the dependencies.cmake as I have observed that embree is defined here. Or any other to modify. Thanks for your time and help!

**Comment by oym050922021** [comment]
@vamWu hi, I encountered a similar problem. Has the problem been solved?

**Comment by Snosixtyboo** [comment]
Hi, feel free to ignore WARNINGS, they may be harmless. Can you compile it successfully afterward?

**Comment by vamWu** [comment]
> Hi, feel free to ignore WARNINGS, they may be harmless. Can you compile it successfully afterward?

I tried to ignore the warning and run cmake --build build -j24 --target install,  it can't build. 
But I've solved it by specifying the precompiled version of Embree. Thanks for your reply.

**Comment by 18128381510** [comment]
下载[embree-3.13.5.x86_64.linux.tar.gz](https://github.com/RenderKit/embree/releases/download/v3.13.5/embree-3.13.5.x86_64.linux.tar.gz)，修改SIBR_viewers/cmake/linux/dependencies.cmake第127行，将find_package(embree 3.0 )改为find_package(embree 3.0 REQUIRED PATHS "你的embree解压路径/lib/cmake" )，然后重新执行cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release即可

**Comment by Mingqj** [comment]
> 下载[embree-3.13.5.x86_64.linux.tar.gz](https://github.com/RenderKit/embree/releases/download/v3.13.5/embree-3.13.5.x86_64.linux.tar.gz)，修改SIBR_viewers/cmake/linux/dependencies.cmake第127行，将find_package(embree 3.0 )改为find_package(embree 3.0 REQUIRED PATHS "你的embree解压路径/lib/cmake" )，然后重新执行cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release即可

By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "TBB", but
  CMake did not find one.

  Could not find a package configuration file provided by "TBB" with any of
  the following names:

    TBBConfig.cmake
    tbb-config.cmake

  Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR"
  to a directory containing one of the above files.  If "TBB" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  cmake/linux/dependencies.cmake:132 (find_package)
  cmake/linux/include_once.cmake:20 (include)
  src/CMakeLists.txt:48 (include_once)
报错啦

**Comment by boxw987** [comment]
> 下载[embree-3.13.5.x86_64.linux.tar.gz](https://github.com/RenderKit/embree/releases/download/v3.13.5/embree-3.13.5.x86_64.linux.tar.gz)，修改SIBR_viewers/cmake/linux/dependencies.cmake第127行，将find_package(embree 3.0 )改为find_package(embree 3.0 REQUIRED PATHS "你的embree解压路径/lib/cmake" )，然后重新执行cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release即可

It works! Thank you!

**Comment by ZefuLin** [comment]
> 下载[embree-3.13.5.x86_64.linux.tar.gz](https://github.com/RenderKit/embree/releases/download/v3.13.5/embree-3.13.5.x86_64.linux.tar.gz)，修改SIBR_viewers/cmake/linux/dependencies.cmake第127行，将find_package(embree 3.0 )改为find_package(embree 3.0 REQUIRED PATHS "你的embree解压路径/lib/cmake" )，然后重新执行cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release即可

thank you！

**Comment by chenhongjin811** [comment]
> 下载[embree-3.13.5.x86_64.linux.tar.gz](https://github.com/RenderKit/embree/releases/download/v3.13.5/embree-3.13.5.x86_64.linux.tar.gz)，修改SIBR_viewers/cmake/linux/dependencies.cmake第127行，将find_package(embree 3.0 )改为find_package(embree 3.0 REQUIRED PATHS "你的embree解压路径/lib/cmake" )，然后重新执行cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release即可下载 embree-3.13.5.x86_64.linux.tar.gz，修改 SIBR_viewers/cmake/linux/dependencies.cmake 第 127 行，将 find_package(embree 3.0 )改为 find_package(embree 3.0 REQUIRED PATHS "你的 embree 解压路径/lib/cmake" )，然后重新执行 cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release 即可

thanks bro, it finally works! really helpful!
