### ISSUE TITLE
disable culling after certain iterations 

### ISSUE THREAD

**Issue by pknmax** [graphdeco-inria/gaussian-splatting#638]
where in code and how to disable culling after certain iterations?
what is size threshold (size_threshold = 20)?
what is densify_grad_threshold?

**Comment by Snosixtyboo** [comment]
Pruning and densification are both disabled after ```densify_until_iter``` iterations, you can pass this as a parameter.
You can ignore size threshold, it is not used in practice.
If the magnitude of accumulated 2D position gradient for a Gaussian exceeds densify_grad_threshold, this Gaussian will be densified.
