### ISSUE TITLE
Bug or feature? culling gaussians with large footprint in viewspace

### ISSUE THREAD

**Issue by hanyanghyhyhy** [graphdeco-inria/gaussian-splatting#643]
one interesting thing I found is that trying to cull gaussians with large footprint in viewspace does not work, since in function `densify_and_split` and `densify_and_clone`, the  `densification_postfix` will be called and thus `max_radii2D` will be set to all zero before the culling precedure.

**Comment by Snosixtyboo** [comment]
That is correct, we found after the release that this code part effectively does nothing. We still have the world-space size culling active and it suffices to do the job. Feel free to experiment if view-space size culling would improve things.
