### ISSUE TITLE
Train with a batch size

### ISSUE THREAD

**Issue by LoickCh** [graphdeco-inria/gaussian-splatting#646]
Hey,

If I've understood the code and the method correctly, the images are processed one by one and the Gaussian optimisations are processed iteratively. Is it conceptually possible to perform gaussian splatting with a batch of images and gaussians?
If so, would a lot of code have to be changed?

I imagine that the merging/splitting part of the gaussians has to be synchronised between GPUs, but are there any other constraints?

Thank you in advance

**Comment by johnren-code** [comment]
Same question, can 3DGS render on multiple GPUs?

**Comment by Snosixtyboo** [comment]
Hi, you understood correctly, we don't have a batched implementation, unfortunately. If you search through some of the already closed issues, you will probably find hints how one could change the code to make it work, but this is not planned as a feature.
