### ISSUE TITLE
Can the viewer see the 3D rendering converge (during train) in real time? like instant ngp

### ISSUE THREAD

**Issue by hanjoonwon** [graphdeco-inria/gaussian-splatting#647]
i ran ./gaussian_splatting/SIBR_viewers/viewers/bin/SIBR_gaussianViewer_app.exe  -m  ./owl_van/ --rendering-size 1500

However, they all come out already rendered. I would like to see them converge in real time like instant ngp, is that possible?

**Comment by Snosixtyboo** [comment]
Yes, sure. Just use the **remote viewer** instead of the gaussianViewer. Consider the instructions in the readme on how to do it, then you will see it converge in real-time, like Instant ngp.
