### ISSUE TITLE
Is the original viewer this small?

### ISSUE THREAD

**Issue by hanjoonwon** [graphdeco-inria/gaussian-splatting#648]
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/125524043/4fbeeaf4-2369-429e-ba3a-044246740cf0)

my viewer look like this...  how can i make viewer bigger??
My laptop is asus gx550lxs

**Comment by jaco001** [comment]
You got 2 parameters
--rendering-size 1920 1080 
--fulscreen

First give you window size inside client (in this example 1920x1080), second overal client size set at fulscreen.

**Comment by hanjoonwon** [comment]
> You got 2 parameters --rendering-size 1920 1080 --fulscreen
> 
> First give you window size inside client (in this example 1920x1080), second overal client size set at fulscreen.

thank you!
