### ISSUE TITLE
pip install submoudels failed

### ISSUE THREAD

**Issue by hanjoonwon** [graphdeco-inria/gaussian-splatting#649]
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/125524043/53582efb-3be6-40af-b4cc-124b40955f31)

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/125524043/456565d0-371b-4fc7-b67c-978a0e09ab22)
how can i solve this error?
wsl2 ubuntu 22.04 anaconda.   
torch cuda available is true

**Comment by jaco001** [comment]
You have CUDA 11.5 at system and pytorch compiled with 11.8 (from first pic). Update cuda to 11.8

**Comment by hanjoonwon** [comment]
> You have CUDA 11.5 at system and pytorch compiled with 11.8 (from first pic). Update cuda to 11.8

Thanks :)
