### ISSUE TITLE
Licensing violation

### ISSUE THREAD

**Issue by pierotofy** [graphdeco-inria/gaussian-splatting#654]
This module https://github.com/graphdeco-inria/gaussian-splatting/blob/main/utils/loss_utils.py is not properly crediting https://github.com/Po-Hsun-Su/pytorch-ssim/blob/master/pytorch_ssim/__init__.py from which it is clearly taken/adapted (MIT licensed).

**Comment by Snosixtyboo** [comment]
Hi,

thanks for noticing and letting us know! We take this oversight seriously and have updated the LICENSE file accordingly. We hope that with this change, we are now duly crediting the original authors. 

Best and thanks,
Bernhard
