### ISSUE TITLE
Calrification on derivative variable names

### ISSUE THREAD

**Issue by VladimirYugay** [graphdeco-inria/gaussian-splatting#670]
Hey there,

1. In `backward.cu` `dL_dtx, dL_dty, dL_dtz` are derivatives w.r.t. Gaussian means in the camera space?
2. In `backward.cu` when I run `glm::mat3 T = W * J;` with the debugger, it gives me the same result if I'd do `T = J @ W` in numpy. I read that in opengl matrices I column-major, but still it's a bit unclear.
3. In `backward.cu` `dL_dTij` are derivatives w.r.t. `T = W * J` or `T = J * W` in "mathematical"/"theoretical" sense?

**Comment by yyzzyy78** [comment]
Hi, have you figured it out? I found the same result about: 
glm::mat3 T = W * J;
In fact, I have the result of T=J@W, corresponding to the matmul.

**Comment by VladimirYugay** [comment]
@yyzzyy78 check out this [repo](https://github.com/muskie82/MonoGS), they actually implemented it if the gaussians are frozen!
