### ISSUE TITLE
Can we train from an edited GS .ply file?

### ISSUE THREAD

**Issue by oUp2Uo** [graphdeco-inria/gaussian-splatting#674]
Hi, the result GS ply file usually have some error "fog", and we could delete them by tools like `SuperSplat`.
But after deleting, there will be "holes" on the object.
(I think this "fog" error some comes from the init sparse point cloud.)

So can we train again from the edited GS `.ply` file in order to fill the holes?

Just like a checkpoint, but the checkpoint is a '.pth' file, which do not include a `.ply` file.

Thanks.

**Comment by jaco001** [comment]
Both floaters ('fog') and holes come from bad image coverage. You can put any .ply at start of trainning but that don't help much if your image dataset is the same. (with bad coverage) . Dense model .ply will be reduced too.

So at first try to get better images ;)

**Comment by oUp2Uo** [comment]
> Both floaters ('fog') and holes come from bad image coverage. You can put any .ply at start of trainning but that don't help much if your image dataset is the same. (with bad coverage) . Dense model .ply will be reduced too.
> 
> So at first try to get better images ;)

Thanks for the reply.
I have done several tests using **original/edited sparse `.ply` file** with **the same image dataset** using **same iteration times**,
and the edited one (delete wrong points) leaded to a obviously better result.

So I thought the algorithm now do now have a good mechanism to analyze and delete wrong points.
And if we manually delete points during the iteration, the result could be better.

I will try to start training with GS `.ply` file.

**Comment by jaco001** [comment]
Try to reduce GS .py  to just 3D coordinates and RGB color. 
All you need is header like that:
ply
format binary_little_endian 1.0
element vertex 374890
property float x
property float y
property float z
property float nx
property float ny
property float nz
property uchar red
property uchar green
property uchar blue
end_header

Meshlab can extract normals, but you still inicialize RGB color (even random is ok)

**Comment by oUp2Uo** [comment]
Thanks for the reply.

I tried to use CloudCompare to process the GS `.ply` file and it could run well.

1. Open an edited GS `.ply` file.
![cloudcompare_ply_open](https://github.com/graphdeco-inria/gaussian-splatting/assets/29222415/d9f843d3-5a60-46cf-9faf-b097c106433c)
In `Ply File Open` dialog, setting RGB using `f_dc_0`/`f_dc_1`/`f_dc_2`.
2. (Optional) Do clean. (Tools-Clean-...)
3. Save a new `.ply` file. (File-Save-Binary)
4. Copy the output file to `sparse/0` and rename to `points3D.ply`.
Then can do training again from this `.ply` file.

And this time training result is better than the last one.

**Comment by hepeixin123** [comment]
为什么我将生成的ply文件用meshlab或者 CloudCompare 打开是没有颜色的？能告诉我吗？
