### ISSUE TITLE
Information on coordinate system

### ISSUE THREAD

**Issue by mohitm1994** [graphdeco-inria/gaussian-splatting#69]
Hi, 
great work! can you tell me what is the default coordinate system?? is it similar to instant-ngp??
Best,
Mohit

**Comment by grgkopanas** [comment]
Hi, what exactly do you need it for? just so I understand what exact information you need.

**Comment by jaeseok4104** [comment]
if you want coordinate system, you can check using top view in SIBR viewer

**Comment by Bin-ze** [comment]
def readCamerasFromTransforms(path, transformsfile, white_background, extension=".png"):
    cam_infos = []

    with open(os.path.join(path, transformsfile)) as json_file:
        contents = json.load(json_file)
        try:
            fovx = contents["camera_angle_x"]
        except:
            fovx = math.atan(contents["w"] / (contents["fl_x"] * 2)) * 2
        frames = contents["frames"]
        for idx, frame in enumerate(frames):
            cam_name = os.path.join(path, frame["file_path"] + extension)

            matrix = np.linalg.inv(np.array(frame["transform_matrix"]))
            R = -np.transpose(matrix[:3,:3])
            R[:,0] = -R[:,0]
            T = -matrix[:3, 3]

            image_path = os.path.join(path, cam_name)
            image_name = Path(cam_name).stem
            image = Image.open(image_path)

            im_data = np.array(image.convert("RGBA"))

            bg = np.array([1,1,1]) if white_background else np.array([0, 0, 0])

            norm_data = im_data / 255.0
            arr = norm_data[:,:,:3] * norm_data[:, :, 3:4] + bg * (1 - norm_data[:, :, 3:4])
            image = Image.fromarray(np.array(arr*255.0, dtype=np.byte), "RGB")

            fovy = focal2fov(fov2focal(fovx, image.size[0]), image.size[1])
            FovY = fovy 
            FovX = fovx

            cam_infos.append(CameraInfo(uid=idx, R=R, T=T, FovY=FovY, FovX=FovX, image=image,
                            image_path=image_path, image_name=image_name, width=image.size[0], height=image.size[1]))
            
    return cam_infos

I want to know why the transformation is done like this：
            matrix = np.linalg.inv(np.array(frame["transform_matrix"]))
            R = -np.transpose(matrix[:3,:3])
            R[:,0] = -R[:,0]
            T = -matrix[:3, 3]
If frame["transform_matrix"] represents c2w, R, T represents the transformation matrix of the world coordinate system, what is the basis for such transformation? Are there any corresponding references?

**Comment by mohitm1994** [comment]
Hey, I found the answer. Its the same as COLMAP.
