### ISSUE TITLE
Help to use ground-truth poses with COLMAP

### ISSUE THREAD

**Issue by leblond14u** [graphdeco-inria/gaussian-splatting#706]
check this to use your own camera settings https://colmap.github.io/faq.html. I think we need to adjust the point3d.txt file so that we can upload our own point cloud data, but it seems that here https://github.com/graphdeco-inria/gaussian-splatting/issues/118 it uploads them directly to the transforms.json file.

_Originally posted by @meriemjabri in https://github.com/graphdeco-inria/gaussian-splatting/issues/205#issuecomment-1722250758_

**Comment by kangy11** [comment]
Hello, I have encountered a similar issue. May I ask if you have resolved this problem now?

**Comment by leblond14u** [comment]
Yes solved it yesterday, 

There's no need to recompute anything with COLMAP. 
The documentation is missleading. 
If you are already able to populate your `image.txt ` and `camera.txt` file and you have your ground truth `txt or ply pointcloud`, just run the 3DGS with those files in your `sparse/0` folder.
The colmap dataloader will simply take the `camera.txt` intrinsics and camera poses from `image.txt`.

**Comment by kangy11** [comment]
Thank you for your reply. It seems my situation is a bit different from yours. I want to use an existing camera to obtain the initial point cloud, rather than using a ground truth point cloud.

**Comment by leblond14u** [comment]
I you also possess depth images a simple reprojection of the depth from the ground truth camera poses will give you a point-cloud.
If you dont and still want to get a point-cloud maybe consider depth estimation networks.

**Comment by leblond14u** [comment]
You can check the data format for the `image.txt` file [here ](https://colmap.github.io/format.html).

**Comment by Pacifica-H** [comment]
> You can check the data format for the `image.txt` file [here ](https://colmap.github.io/format.html).

Should I change my pose file into image.txt format or change the R T loading code of 3dgs https://github.com/graphdeco-inria/gaussian-splatting/blob/b17ded92b56ba02b6b7eaba2e66a2b0510f27764/scene/dataset_readers.py#L82

**Comment by leblond14u** [comment]
The easiest thing to do in my opinion is to convert your data format into the COLMAP one to avoid messing with the dataloading sequence. But you could very well code your own, I've done it too. It boils down to personal preferences at this point.

**Comment by pattgene** [comment]
> Yes solved it yesterday,
> 
> There's no need to recompute anything with COLMAP. The documentation is missleading. If you are already able to populate your `image.txt ` and `camera.txt` file and you have your ground truth `txt or ply pointcloud`, just run the 3DGS with those files in your `sparse/0` folder. The colmap dataloader will simply take the `camera.txt` intrinsics and camera poses from `image.txt`.

Thank you for your great guiding here. I am working similar thing, I want to use my own point cloud and pose to train 3dgs.
I am a little bit confuse, it seem you modified sparse/0 folder with your own
1. image.txt(cam pose)
2. camera.txt (cam intrinsic)
3. pointcloud.ply 
Is this correct? Then just run 3dgs and the fuction ''readColmapSceneInfo'' will then be able to process your modified data?

You get these 3 from: [http://redwood-data.org/indoor/dataset.html](ICL NUM) right? May I see how you structure image.txt, camera.txt, pointcloud.txt please. I am confuse by the COLMAP documentation on how to format those.

**Comment by leblond14u** [comment]
Hi @pattgene,

Sorry for my late answer.
Yes it is correct you just need to make sure that you respect the COLMAP format as described [here](https://colmap.github.io/format.html ) when you write you txt files. 
For the origin data yes you can get Images, depth and gt camera poses on a variety of datasets like ICL or TUM-RGBD for instance. 

Hope this can help you,

Best
