### ISSUE TITLE
Questions about the ablation study in the paper

### ISSUE THREAD

**Issue by JIANG-CX** [graphdeco-inria/gaussian-splatting#73]
Nice work ！
I have a question regarding the ablation study of the Spherical Harmonics. If the Spherical Harmonics representation for color is not used, what alternative method did you choose to describe the color?
Thank you.

**Comment by Snosixtyboo** [comment]
Hi,
the 0th band is a constant color for all directions. Effectively we set the band to 0 for the ablation, so we just optimized an RGB color value.

Hth,
Bernhard

**Comment by JIANG-CX** [comment]
Thanks for your reply.
