### ISSUE TITLE
Questions about the SIBR_remoteGaussian_app

### ISSUE THREAD

**Issue by JIANG-CX** [graphdeco-inria/gaussian-splatting#74]
Hi, I have some questions about the SIBR_remoteGaussian_app:
1、What are the functions of the "SHs Python" and "Rot-Scale Python" in the "Remote Viewer Settings"? I selected them but found nothing changed.
2、What's the meaning of the "Scaling Mod" in the "Remote Viewer Settings"? It seems like the range of influence of each gaussian? And how can I visualize the ellipsoids like in the "SIBR_gaussianViewer_app".
Thanks.

**Comment by Snosixtyboo** [comment]
Hi,

1) You should not see a difference, it simply defines whether the gradient computation (forward and backward) for SHs and Rotation/Scaling to Covariance Matrix are done by our CUDA implementation or PyTorch, e.g., if you want to test or modify these parts of the pipeline.
2) The scaling modifier will scale all Gaussians from 0 to their full extent so you can get an idea of how many Gaussians are where in the scene during training. The remote viewer does not support displaying the ellipsoids unfortunately, it only shows the images that Python renders.

Hth,
Bernhard

**Comment by JIANG-CX** [comment]
> Hi,
> 
> 1. You should not see a difference, it simply defines whether the gradient computation (forward and backward) for SHs and Rotation/Scaling to Covariance Matrix are done by our CUDA implementation or PyTorch, e.g., if you want to test or modify these parts of the pipeline.
> 2. The scaling modifier will scale all Gaussians from 0 to their full extent so you can get an idea of how many Gaussians are where in the scene during training. The remote viewer does not support displaying the ellipsoids unfortunately, it only shows the images that Python renders.
> 
> Hth, Bernhard

OK, thanks for your reply.
