### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by Gynjn** [graphdeco-inria/gaussian-splatting#746]
First, thanks for sharing great work.

I have a question about a code in "densify_and_split"

`new_scaling = self.scaling_inverse_activation(self.get_scaling[selected_pts_mask].repeat(N,1) / (0.8*N))`

Why we need self.scaling_inverse_activation when split and initialization?

Thanks.

**Comment by PanagiotisP** [comment]
Some parameters have an unactivated, raw form/space, which is the one parameters are optimised and stored in and an activated one, which is the useful-interpretable one. The reason optimisation doesn't happen in the activated space (that would remove the need of the two spaces) is mostly for better convergence/optimisation.

In this case, the `new_scaling` values need to be the original ones divided by $`0.8N`$ in the **activated space**. So, the activated scaling values are gathered by `get_scaling`, divided and then transformed back to the unactivated space to be stored.
