### ISSUE TITLE
Missing pointclouds

### ISSUE THREAD

**Issue by runningneverstop** [graphdeco-inria/gaussian-splatting#754]
I want to use TankandTemples dataset to run guassian.But when I use the viewer, I find points within a certain z are missing and the initial point clouds seems ok. I don't know how to fix the bug
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/86957090/0d6d1bde-062b-4d1e-8d9e-6420deac3581)
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/86957090/23f49627-472d-464c-9477-a8e14f2b12c6)
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/86957090/634752d7-1db5-4530-bd12-decd3148630f)

**Comment by jaco001** [comment]
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/67650086/d57eb7ea-4258-4594-bf2d-4d5dc031b6fe)
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/67650086/ec335222-2d37-48b2-9916-93d9096daa79)

Check if you don't select crop box

**Comment by runningneverstop** [comment]
it seems the same? And it may not be missing, when I see the ellipsoids, they have outline but are all white.@
jaco001 ![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/86957090/8912e036-382f-499b-a420-82449d576cf8)
