### ISSUE TITLE
Release of Reducing the Memory Footprint of 3D Gaussian Splatting

### ISSUE THREAD

**Issue by erenovic** [graphdeco-inria/gaussian-splatting#755]
Hello,

Thank you for the great work on 3D Gaussian splatting and the follow-up work on reducing the memory footprint. I was wondering if you have a timeline in mind for the release of the code for "Reducing the Memory Footprint of 3D Gaussian Splatting"?

**Comment by FelixMoeller3** [comment]
In case anyone stumbles across this issue, the code has been released here: https://github.com/graphdeco-inria/reduced-3dgs
