### ISSUE TITLE
GSplat Point Cloud Only Trained from 3 images

### ISSUE THREAD

**Issue by yoponchik** [graphdeco-inria/gaussian-splatting#757]
I used FFMPEG to extract images (649 in total) from the video like the image below.

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/57009810/e6b8458b-7bdf-4ea5-b481-abbb25dcbacb)

But after having executed `convert.py` and `train.py` for more than an hour, the viewer had a very low quality point cloud. 

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/57009810/309cb0b5-1e9b-4ca6-919a-f18009dcc6d8)

After some digging around, the generated point cloud looked very much like the images in the `image` folder, which only had 3 in total.   

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/57009810/b0e8533b-c081-4351-88d7-351eedb781ea)

I am using the default settings. Am I doing something wrong here?

**Comment by jaco001** [comment]
Try to dig deeper and actually help colmap/gs to get good quality dataset. ;)
Look at topics like https://github.com/graphdeco-inria/gaussian-splatting/issues/732#issuecomment-2028106293

In general frames from video are usually blures. You need sharp images for colmap with wide angle and good coverage.
