### ISSUE TITLE
Training with mask

### ISSUE THREAD

**Issue by nuko7055** [graphdeco-inria/gaussian-splatting#761]
I would like to know if it is possible to train with the mask of the target object. I just want to get the gs model of the target object.

ex:

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/145477948/21e6dfde-070e-4891-a293-137f16a504da)

**Comment by jaco001** [comment]
There is a GS fork that uses masks for training.
https://github.com/graphdeco-inria/gaussian-splatting/issues/127


In practice you have 2 sets of mask
- one for colmap (convert.py part)
Check original colmap github for more details.
- second for training
Masks can be similar but colmap usually alter images in 'images' folder so your masks arent 1:1 (image resize and perspective correction). So second mask set is needed.

**Comment by gaoyuqiang** [comment]
@jaco001 I followed your steps to generate the masks and did the cropping, but the 3D model still doesn’t look very clean. As you can see in the image, there’s still some extra background left—especially at the bottom, with a lot of colorful oval shapes.

Do you know what might be causing this？

<img width="799" height="563" alt="Image" src="https://github.com/user-attachments/assets/048b8760-7131-406e-ad97-535387c209f5" />

**Comment by jaco001** [comment]
Today I will recomend you: Reality Scan 2.0 with automatic mask + Postshot workflow. 

Colorful artefacts comes from noise at your pictures, if you too much 'enhance' them. (usually too much sharpening)
