### ISSUE TITLE
Processing my own Scenes with ground truth camera poses

### ISSUE THREAD

**Issue by Siming-He** [graphdeco-inria/gaussian-splatting#77]
Hi,

Thank you for this great work and detailed instructions. I'm processing my own data using 
`python convert.py -s <location> --resize`
which runs sfm from the beginning.

Since I have ground truth camera poses for all the frames, I wonder whether there is an easy way to use these poses during the processing?

Thanks for any help and advise.

**Comment by grgkopanas** [comment]
You would need to run colmap on your own without using our script. I think
this link might help you

https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses

**Comment by Siming-He** [comment]
Thank you! I'll try to run colmap on my own!
