### ISSUE TITLE
Question about dL_dmean in backward.cu

### ISSUE THREAD

**Issue by huiqiang-sun** [graphdeco-inria/gaussian-splatting#776]
Hi,
It seems that there is no consideration of ndc2Pix in the forward process when computing dL_dmean in backward.cu. Is this on purpose or am I misunderstanding something?
![1714121854670](https://github.com/graphdeco-inria/gaussian-splatting/assets/137331394/41238af7-10c8-462d-85d4-259685adc87c)

**Comment by PanagiotisP** [comment]
That's right, but this has already been taken care of by [these factors](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/backward.cu#L460-L461), that are multiplied by the derivatives.

**Comment by huiqiang-sun** [comment]
Thank you very much for solving my confusion!

**Comment by Chen-Suyi** [comment]
I have another question for this part.

Why did they not deal with the view_matrix before adding dL_dmean back to dL_dmeans?

**Comment by Chengbo-Wang** [comment]
> That's right, but this has already been taken care of by [these factors](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/backward.cu#L460-L461), that are multiplied by the derivatives.

Hi. Thank you for your explanation! This indeed takes into account the derivative contribution of `ndc2Pix`.
But it seems to have created another issue. `W/2` and `H/2` should not exist in the derivative chain of `dL_dmean2D`. For details, please check #1160.
