### ISSUE TITLE
Training doesn't bring good results

### ISSUE THREAD

**Issue by frenchtouchXR** [graphdeco-inria/gaussian-splatting#779]
Hello, 

I installed Gaussian Splatting on windows following the getting started guide. 
I managed to use the "Convert" module and the result seems to be a good sparse point cloud in cloud compare. It also generates the asked structure with distorted, images, sparse and stereo directories.

![sparse](https://github.com/graphdeco-inria/gaussian-splatting/assets/40068776/1c5e9cb7-bbe1-4d3f-861f-1a4719db9f47)
![result](https://github.com/graphdeco-inria/gaussian-splatting/assets/40068776/53499f5a-96d5-4d1b-a0e8-e3f8f10d0bfe)

When I use the "Train" module the result is around 14mo for 7000 iterations and 5mo for 30000 iterations. It seems really low. Moreover when I look at the result in cloud compare I just see a noisy eliptic balloon point cloud. 

Do you have any idea how I could solve the problem ? 

Best

**Comment by hariharan1412** [comment]
You have to tune the hyperparameters based on your requirements; once you find the specific set of parameters, it'll work for all the other similar scenarios.

**Comment by jaco001** [comment]
I see many 'clones' on point cloud, so I guess yours cameras aren't aligned well.
Post image from colmap gui how it was aligned (open gui and import \sparse\0 folder)

GS after getting so much noise cameras generate only noise GS.

**Comment by frenchtouchXR** [comment]
Hello, 

Those are not clones. Those are tables in the same room. The registration looks really good. 

![registrationfromgui](https://github.com/graphdeco-inria/gaussian-splatting/assets/40068776/3a803b9f-f1d9-43fa-9cfa-27e6cb67f487)

**Comment by jaco001** [comment]
ok ok :)  you are sure ^^
Then take this a little experiment with me :)
Take ONLY pictures that are sdignet to this 'loop'
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/67650086/5b28cb87-ee23-4642-98e2-5bafa054dda8)

Train it - and check resolut
Add some more and train it. Check if this don't lose alignment.
Doing this few times you can select pictures that 'break' your dataset.

Those almost the same pictures are very hard - trust me ;)

**Comment by frenchtouchXR** [comment]
OK it makes sense. I'll do that.

**Comment by frenchtouchXR** [comment]
Hello, it now work with a reduced set of photos. I'll try to add more and see when it breaks as you adviced. Could we deduce the training can only be done when the scene has a main point of interest or is centered where we have more points of view ? Something like that ?

**Comment by jaco001** [comment]
No - training can be done at anything. :) One POI is easier for camera positioning (you can break it too), but with some work you can do anything. Ppl make drone shots (just  lines) or very big outdoors shots. Big scenes tend be less detailed, but you can always put more pictures where you care more.

This is topic more for photogrametry forums - how to make datasets of large room. GS try the best with data that you put in.
