### ISSUE TITLE
error: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by xgh127** [graphdeco-inria/gaussian-splatting#790]
when I try this，it fails：
C:\AI\gaussian-splatting\submodules\diff-gaussian-rasterization-main>python setup.py install
running install
C:\Users\xgh\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Users\xgh\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing diff_gaussian_rasterization.egg-info\PKG-INFO
writing dependency_links to diff_gaussian_rasterization.egg-info\dependency_links.txt
writing top-level names to diff_gaussian_rasterization.egg-info\top_level.txt
reading manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
adding license file 'LICENSE.md'
writing manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
error: [WinError 2] 系统找不到指定的文件。
I wonder how to fix this issue。

**Comment by zf1531** [comment]
Maybe you didn't copy all of this file

**Comment by xgh127** [comment]
It's beacuse there is cuda11.6 on my path variable. when I delete it,then everything works well.

**Comment by yonadance** [comment]
同样问题，使用cuda11.8 python 3.10，修改对应的vs版本为2019后（并安装build tool）并重启（非常重要）可以正常运行
