### ISSUE TITLE
ffmpeg and colmap not recognised

### ISSUE THREAD

**Issue by malamutes** [graphdeco-inria/gaussian-splatting#795]
![12121](https://github.com/graphdeco-inria/gaussian-splatting/assets/130812373/df2593a2-dc9c-4525-8a90-1be9357f9ac8)
I can run them both as executables from terminal in their respective local files and have placed them in system variables, but they are still not recognised i
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/130812373/99ec6440-97f9-4866-9b36-96c40b7763bc)
f i run "colmap" or "ffmpeg"
For colmap I have system variables pointing to folder which contains bin, lib and bat file
for ffmpeg i have the variable pointing to where ffmpeg.exe lives (i.e. the bin file)
I've tried restarting my pc many times but was no help.

**Comment by jaco001** [comment]
Maybe 'onedrive' isn't good place? Try put it in not user folder , but main drive folder like eg c:\tools\colmap.

**Comment by malamutes** [comment]
Yea i moved it into program files and restarted but still not recognised.
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/130812373/0c38fe9a-2797-4e2b-b99f-82dd7d270f72)

**Comment by jaco001** [comment]
ok ok - now you must add those paths not to system variables like colmap or ffmpeg but to system or user 'path'
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/67650086/9183351e-543f-4d0c-af27-649187ee69fb)

**Comment by malamutes** [comment]
How do I do that aside from setting path in environment variables?

**Comment by jaco001** [comment]
https://www.howtogeek.com/787217/how-to-edit-environment-variables-on-windows-10-or-11/

I take screens from there
Select 'path' from there and click edit
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/67650086/30ab901d-705b-4fdd-8dbc-9e0f589522b7)

add your variables
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/67650086/cfce6ffc-2318-4c1e-836e-e1c24a6a8820)

Accept

**Comment by malamutes** [comment]
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/130812373/ccb2995b-2bbe-4a2c-b7a1-6321e469b777)
If I click on the path, I get this rather than the tab you have shown me. By selecting path I'm assuming I'm selecting one of the system variables but I don't know how how to get a tab with "edit environment variable" as header, and the website did not say either.
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/130812373/9dd1cc7e-b845-4288-9aef-dcaf85eacdba)

**Comment by malamutes** [comment]
Yep that worked! Thanks a lot jaco001. For anyone in the future, to get tab with "edit environment variable" you click on the system variable with name "Path"
