### ISSUE TITLE
How to change Iterations?

### ISSUE THREAD

**Issue by DuVogel87** [graphdeco-inria/gaussian-splatting#796]
Solved! 

Sorry, can not delete the Issue.

**Comment by jaco001** [comment]
Post solution (even it is easy) and mark as solved.

**Comment by DuVogel87** [comment]
here is the solution:

you must add --iterations and the number. for example: --iterations 8000

so the hole trainings command could look like this: 

python train.py -s (here path to COLMAP or NeRF Synthetic dataset) --iterations 8000

**Comment by DuVogel87** [comment]
here is the solution:

you must add --iterations and the number. for example: --iterations 8000

so the hole trainings command could look like this:

python train.py -s (here path to COLMAP or NeRF Synthetic dataset) --iterations 8000
