### ISSUE TITLE
simple-knn build failure

### ISSUE THREAD

**Issue by dllu** [graphdeco-inria/gaussian-splatting#8]
With CUDA 12.0 and pytorch 2.0, it seems that simple-knn has the following build failure:

```
/home/dllu/builds/gaussian-splatting/submodules/simple-knn/simple_knn.cu(196): error: namespace "thrust" has no member "sequence"
```

It seems it is likely that will fail on other versions of CUDA as well but I haven't tried...

This is fixed with the following change:
```diff
diff --git a/simple_knn.cu b/simple_knn.cu
index 4828d2b..f99fee4 100644
--- a/simple_knn.cu
+++ b/simple_knn.cu
@@ -8,6 +8,7 @@
 #include <vector>
 #include <cuda_runtime_api.h>
 #include <thrust/device_vector.h>
+#include <thrust/sequence.h>

 #define __CUDACC__
 #include <cooperative_groups.h>
@@ -207,4 +208,4 @@ void SimpleKNN::knn(int P, float3* points, float* meanDists)
        boxMeanDist << <num_boxes, BOX_SIZE >> > (P, points, indices_sorted.data().get(), boxes.data().get(), meanDists);

        cudaFree(result);
-}
\ No newline at end of file
+}
```

(malheureusement je ne sais pas comment créer un PR sur https://gitlab.inria.fr/bkerbl/simple-knn)

**Comment by Snosixtyboo** [comment]
Thx, should be fixed now! To see it, people will have to **git pull** and **git submodule update**. 

Please note that we did no testing with CUDA 12 and limited testing with PyTorch 2. We would be happy to learn if it works for you.
