### ISSUE TITLE
SIBR_Viewers fossa_compatibility errors

### ISSUE THREAD

**Issue by soeroesg** [graphdeco-inria/gaussian-splatting#80]
Ubuntu 20 comes with GCC9 and the following errors happen with it even if C++17 standard is enabled:

# 1 error: ‘is_same_v’ is not a member of ‘std’
at multiple places:
 - src/core/graphics/Image.hpp
 - src/core/graphics/Types.hpp
 - src/core/video/MultipleVideoDecoder.hpp
 - src/core/video/VideoUtils.hpp

See [https://en.cppreference.com/w/cpp/types/is_same](is_same)
The solution is to change `is_same_v<T,U>` to `is_same<T, U>::value` everywhere

# 2 error: use of deleted function ‘std::atomic<bool>::atomic(const std::atomic<bool>&)’
in /src/./projects/remote/renderer/RemotePointView.hpp:95:36:
std::atomic<bool> keep_running = true;

The solution is to change the line to 
std::atomic<bool> keep_running{true};

As the SIBR code is not on github, I am unable to submit a patch. Please change these few lines.

**Comment by Snosixtyboo** [comment]
Done
