### ISSUE TITLE
Why is training progress stuck at 23%?

### ISSUE THREAD

**Issue by malamutes** [graphdeco-inria/gaussian-splatting#801]
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/130812373/50f27214-8c65-430c-9c00-53bf0da5b8a0)

**Comment by jaco001** [comment]
At 23% (7000 iteration) as default setup GS save first model. Seccon (main) at 30000 iterations. 
If you have many, many images consider to increase -iterations for your optimal result.
