### ISSUE TITLE
only 4 images selected by COLMAP as view directions optimized by 3dGS 

### ISSUE THREAD

**Issue by Furkathertaha** [graphdeco-inria/gaussian-splatting#806]
Hi everyone,
I recently tried to use 3dGS reconstructing objects from 2d images rendered by blender. I have taken around 90 pictures orbitting as a sphere (maybe in a bad way for colmap). 
<img src="https://github.com/graphdeco-inria/gaussian-splatting/assets/84897537/bf510382-3990-4d99-b4de-c85feafe91ad" width = 40%>
Taking certain latitude, the incremental angle varys from 22.5 to 45 degree. I guess this is even too large for colmap?
Because the convert.py only select 4 images from these 90, and only  such narrow view is optimized by 3dGS, which results vey poor reconstruction. 
<img src="https://github.com/graphdeco-inria/gaussian-splatting/assets/84897537/c1460859-fa2a-406e-80c9-e3ced897c423" width = 70%>
[log.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/15283237/log.txt) As seen from the log, only 4 iamges are chosen to reconstruct.
I'm wondering if there's a standard for image selection, is it essential to have very continous viewport transfer?

**Comment by LiuJF1226** [comment]
@Furkathertaha  I have met the same issue. COLMAP only recognized 4 out of 35 images when using ```convert.py```. However, it works well when I directly use the COLMAP GUI to process the 35 images. 
1. File->New project
2. Processing->Feature extraction
3. Processing->Feature matching
4. Reconstruction->Start reconstruction
Maybe you can also have a try!

**Comment by LiuJF1226** [comment]
> @Furkathertaha I have met the same issue. COLMAP only recognized 4 out of 35 images when using `convert.py`. However, it works well when I directly use the COLMAP GUI to process the 35 images.
> 
> 1. File->New project
> 2. Processing->Feature extraction
> 3. Processing->Feature matching
> 4. Reconstruction->Start reconstruction
>    Maybe you can also have a try!

@Furkathertaha   Hi, I just tried to downgrade colmap3.9 to colmap3.8 following https://github.com/graphdeco-inria/gaussian-splatting/issues/631#issuecomment-1971648542. Now it can work well with ```convert.py```.

**Comment by LiuJF1226** [comment]
@Furkathertaha  Hi, I have met the same issue. Colmap only recognized 4 out of 35 images. Then I tried to downgrade colmap3.9 to colmap3.8 following https://github.com/graphdeco-inria/gaussian-splatting/issues/631#issuecomment-1971648542. Now it can work well with ```convert.py```.

**Comment by Furkathertaha** [comment]
> @Furkathertaha Hi, I have met the same issue. Colmap only recognized 4 out of 35 images. Then I tried to downgrade colmap3.9 to colmap3.8 following [#631 (comment)](https://github.com/graphdeco-inria/gaussian-splatting/issues/631#issuecomment-1971648542). Now it can work well with `convert.py`.

Thanks so much for your reply! I forgot to update my solution on this page. Indeed as mentioned, downgrading to 3.8 helps a bit. In my case, however, the selected number only increased to 38 out of 90. I checked the COLMAP doc, and found a robust solution.
I worked it out with v3.8, not sure about the latest version.

**Increase number of matches / sparse 3D points**

<b>To increase the number of matches, you should use the more discriminative DSP-SIFT features instead of plain SIFT
and also estimate the affine feature shape using the options:</b>
```
--SiftExtraction.estimate_affine_shape=true and --SiftExtraction.domain_size_pooling=true.
```
<b>In addition, you should enable guided feature matching using:</b>
```
--SiftMatching.guided_matching=true.
```

**Comment by LiuJF1226** [comment]
@Furkathertaha  Thank you for the robust solution! BTW, I just found that it also worked fine when directly using the GUI of colmap3.9 instead of ```convert.py``` to process my images.

**Comment by Furkathertaha** [comment]
@LiuJF1226 
Thanks for your trial~ 
It looks like some preservation ability is sacrificed for computation acceleration in 3dGS with COLMAP.

**Comment by NIZAHO** [comment]
> @LiuJF1226 Thanks for your trial~ It looks like some preservation ability is sacrificed for computation acceleration in 3dGS with COLMAP.



> > @Furkathertaha Hi, I have met the same issue. Colmap only recognized 4 out of 35 images. Then I tried to downgrade colmap3.9 to colmap3.8 following [#631 (comment)](https://github.com/graphdeco-inria/gaussian-splatting/issues/631#issuecomment-1971648542). Now it can work well with `convert.py`.
> 
> Thanks so much for your reply! I forgot to update my solution on this page. Indeed as mentioned, downgrading to 3.8 helps a bit. In my case, however, the selected number only increased to 38 out of 90. I checked the COLMAP doc, and found a robust solution. I worked it out with v3.8, not sure about the latest version.
> 
> **Increase number of matches / sparse 3D points**
> 
> To increase the number of matches, you should use the more discriminative DSP-SIFT features instead of plain SIFT and also estimate the affine feature shape using the options:
> 
> ```
> --SiftExtraction.estimate_affine_shape=true and --SiftExtraction.domain_size_pooling=true.
> ```
> 
> In addition, you should enable guided feature matching using:
> 
> ```
> --SiftMatching.guided_matching=true.
> ```

Hello! how to enable these parameters in convert.py

**Comment by Furkathertaha** [comment]
> > @LiuJF1226 Thanks for your trial~ It looks like some preservation ability is sacrificed for computation acceleration in 3dGS with COLMAP.
> 
> > > @Furkathertaha Hi, I have met the same issue. Colmap only recognized 4 out of 35 images. Then I tried to downgrade colmap3.9 to colmap3.8 following [#631 (comment)](https://github.com/graphdeco-inria/gaussian-splatting/issues/631#issuecomment-1971648542). Now it can work well with `convert.py`.
> > 
> > 
> > Thanks so much for your reply! I forgot to update my solution on this page. Indeed as mentioned, downgrading to 3.8 helps a bit. In my case, however, the selected number only increased to 38 out of 90. I checked the COLMAP doc, and found a robust solution. I worked it out with v3.8, not sure about the latest version.
> > **Increase number of matches / sparse 3D points**
> > To increase the number of matches, you should use the more discriminative DSP-SIFT features instead of plain SIFT and also estimate the affine feature shape using the options:
> > ```
> > --SiftExtraction.estimate_affine_shape=true and --SiftExtraction.domain_size_pooling=true.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In addition, you should enable guided feature matching using:
> > ```
> > --SiftMatching.guided_matching=true.
> > ```
> 
> Hello! how to enable these parameters in convert.py

Hi there~ You could try replacing corresponding snippet with this:
```
    ## Feature extraction
    feat_extracton_cmd = colmap_command + " feature_extractor "\
        +"--database_path " + args.source_path + "/distorted/database.db \
        --image_path " + args.source_path + "/input \
        --ImageReader.single_camera 1 \
        --ImageReader.camera_model " + args.camera + " \
        --SiftExtraction.use_gpu " + str(use_gpu)\
        +" --SiftExtraction.estimate_affine_shape=true  --SiftExtraction.domain_size_pooling=true"
    exit_code = os.system(feat_extracton_cmd)
    if exit_code != 0:
        logging.error(f"Feature extraction failed with code {exit_code}. Exiting.")
        exit(exit_code)

    ## Feature matching
    #feat_matching_cmd = colmap_command + " vocab_tree_matcher " \
    #feat_matching_cmd = colmap_command + " sequential_matcher " \
    feat_matching_cmd = colmap_command + " exhaustive_matcher \
        --database_path " + args.source_path + "/distorted/database.db \
        --SiftMatching.use_gpu " + str(use_gpu)\
        +" --SiftMatching.guided_matching=true"
        #+" --SequentialMatching.overlap 10"
    exit_code = os.system(feat_matching_cmd)
    if exit_code != 0:
        logging.error(f"Feature matching failed with code {exit_code}. Exiting.")
        exit(exit_code)
```
