### ISSUE TITLE
Training demonstration error: all gaussians have same sizes and shapes

### ISSUE THREAD

**Issue by ghangminyun** [graphdeco-inria/gaussian-splatting#819]
I trained a model and rendered it using WebGL, following guidance from [this repository](https://github.com/camenduru/splat). However, the rendered scene is incorrect, indicating that the model may not have trained successfully. Upon closer inspection, I noticed that all the Gaussian shapes are identical. They are positioned at the same angle, have the same sizes, and the only difference is their colors.

I followed all the steps outlined in [this tutorial](https://medium.com/@sharmamayank990/implementation-of-gaussian-splats-in-ubuntu-3fdcdf5ee872).

And I got this result. [(Youtube)](https://youtu.be/2ppT0Q068Ys?si=12BXL0WtIgSjUEij)

Is this problem caused by poor training or, just rendering environment?

=======================================================================

Below is what I did for training.

at gaussian-splatting directory,
1. `python convert.py data/train/input`
2. `python train.py -s data/train/input/`
3. Output:
```
Training progress: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 300                                                 00/30000 [12:22<00:00, 40.39it/s, Loss=0.0625064]

[ITER 30000] Evaluating train: L1 0.04122012779116631 PSNR 24.076174926757815 [16/05 14:07:44]

[ITER 30000] Saving Gaussians [16/05 14:07:44]

Training complete. [16/05 14:07:48]
```
4. Drag & dropped `home/user/gaussian-splatting/output/340fbdc5-3/input.ply` on WebGl

**Comment by jaco001** [comment]
This is wrong ply file (sparse start model). Your 'end' file is in /point_cloud/iteration_30000/point_cloud.ply

**Comment by ghangminyun** [comment]
> This is wrong ply file (sparse start model). Your 'end' file is in /point_cloud/iteration_30000/point_cloud.ply

Thank you so much!! It worked
