### ISSUE TITLE
Issue with environment - simple-knn

### ISSUE THREAD

**Issue by niconielsen32** [graphdeco-inria/gaussian-splatting#83]
I get the following error when i try to create a conda environment with the provided file:

  × Running setup.py install for simple-knn did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      running install
      C:\Users\USER\miniconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

 note: This error originates from a subprocess, and is likely not a problem with pip.

error: legacy-install-failure

× Encountered error while trying to install package.
╰─> simple-knn

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

failed

CondaEnvException: Pip failed

**Comment by Snosixtyboo** [comment]
Hi,

can you run ```python setup.py install``` from ```submodules/simple-knn``` and see what that gives?

**Comment by niconielsen32** [comment]
(gaussian_splatting) C:\Users\USER\gaussian-splatting\submodules\simple-knn>python setup.py install
running install
C:\Users\USER\miniconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
C:\Users\USER\miniconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
  
  
  building 'simple_knn._C' extension
cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\USER\miniconda3\envs\gaussian_splatting\lib\site-packages\torch\include -IC:\Users\USER\miniconda3\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\USER\miniconda3\envs\gaussian_splatting\lib\site-packages\torch\include\TH -IC:\Users\USER\miniconda3\envs\gaussian_splatting\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\USER\miniconda3\envs\gaussian_splatting\include -IC:\Users\USER\miniconda3\envs\gaussian_splatting\Include /EHsc /Tpext.cpp /Fobuild\temp.win-amd64-cpython-37\Release\ext.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc /wd4624 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
error: command 'cl.exe' failed: None

**Comment by niconielsen32** [comment]
Ended up updating everything to newest versions and used pip install .
Now it builds fine

**Comment by TheCell** [comment]
Here is how to fix it:
The problem is, that the anaconda command prompt does not know cl.exe
- I've installed the C++ build tools (see https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed)
- opened "x64 Native Tools Command Prompt" and entered "path" > get all added variables. The first one was C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64 and that path contains the cl.exe
- Add that path to the system variable PATH. Restart (Ana)conda
- verify that cl.exe is available now by entering "cl" in the conda prompt.
- restart the "conda env create --file environment.yml" after removing the failed environment
