### ISSUE TITLE
Install submodules diff-gaussian-rasterization and simple-knn

### ISSUE THREAD

**Issue by jackyhuuuu** [graphdeco-inria/gaussian-splatting#831]
(LangSplat) PS D:\project\Langsplat> echo $env:CUDA_HOME
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA

(LangSplat) PS D:\project\Langsplat>  pip install submodules/langsplat-rasterization                      
Processing d:\project\langsplat\submodules\langsplat-rasterization
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\project\Langsplat\submodules\langsplat-rasterization\setup.py", line 22, in <module>
          CUDAExtension(
        File "C:\Users\***\anaconda3\envs\LangSplat\lib\site-packages\torch\utils\cpp_extension.py", line 1077, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "C:\Users\***\anaconda3\envs\LangSplat\lib\site-packages\torch\utils\cpp_extension.py", line 1211, in library_paths
          paths.append(_join_cuda_home(lib_dir))
        File "C:\Users\***\anaconda3\envs\LangSplat\lib\site-packages\torch\utils\cpp_extension.py", line 2419, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I have already set my cuda environment but still fail to install submodules. The error is: CUDA_HOME environment variable is not set.
Someone has same issue???

**Comment by hsmmoj** [comment]
I do have the same issue while trying to run the code in docker env.

**Comment by jaswin90** [comment]
I am also facing the same issue. Is there any way to solve ?

**Comment by jackyhuuuu** [comment]
just maek sure you cuda version same as your pytorch version.
for me I use cuda 11.8 and i use the following command to install pytorch in my environment and it works
"pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118"
