### ISSUE TITLE
strange training result

### ISSUE THREAD

**Issue by jiangroubao** [graphdeco-inria/gaussian-splatting#832]
the colmap result looks ok and the spase point cloud also looks great, but the training result is terrible when the training completed and I visualized the  trained point cloud via cloudcompare. I don't know what's the possible reason. I'd be grateful if anyone could give me any advice.
![48a7ce84e0991809e53da4baba9f27e](https://github.com/graphdeco-inria/gaussian-splatting/assets/147974187/e41f1342-9a30-4207-98d9-eb5d0d63572e)
![58164e9b73ca753a83a74389f9825da](https://github.com/graphdeco-inria/gaussian-splatting/assets/147974187/313c5da8-ed1a-4a40-a6c0-d30268ad7403)
![283a4e45b1c216f27f5eae004a77e35](https://github.com/graphdeco-inria/gaussian-splatting/assets/147974187/cafb9759-fd47-4afe-b8be-6223f4a1da9a)
![d5ccc8f1db48f5d477d870c93ed1a57](https://github.com/graphdeco-inria/gaussian-splatting/assets/147974187/1ef5e26c-19a4-4fc6-8706-9a0349c9013a)

**Comment by jaco001** [comment]
Usually training speed at 100 pic is like 18-22 it/s on 3080Ti. 50-60 suggest me that you don't put any data to train at all .. or you have VERY beefy GPU ;)
Try train just with -s parameter and path.

**Comment by jiangroubao** [comment]
> Usually training speed at 100 pic is like 18-22 it/s on 3080Ti. 50-60 suggest me that you don't put any data to train at all .. or you have VERY beefy GPU ;) Try train just with -s parameter and path.

Thanks for your kind reply. I think you are right and  I tried just with -s but get the same bad result. I don't know why it happens and when I tried to add the -w flag (means white background),  the trained point cloud result become good! But..when I use the SIBR Viewers, the color of the final result looks strange again. Do you have any idea? (by the way, the gpu I use is 4090 and when I add the -w ,the training speed is 40-50 but when I try train just with -s, the speed increases to about 100 even more)

![$D2VWO8EO`UY5V5@08WU}46_tmb](https://github.com/graphdeco-inria/gaussian-splatting/assets/147974187/99a93d18-ffbb-4d27-9d38-1a5cec996a3e)
![TSYOVBTI@Z8)5P10H`2%$JN](https://github.com/graphdeco-inria/gaussian-splatting/assets/147974187/b65e46c0-5326-402e-b9d4-3b26b468e3d0)
![TGFLP~)7R_D VKE0`B)T0HW_tmb](https://github.com/graphdeco-inria/gaussian-splatting/assets/147974187/7b49773f-00c2-4d94-8344-feff7dedc360)

![8K~{59Z6}U{(NGCA65YBNK3_tmb](https://github.com/graphdeco-inria/gaussian-splatting/assets/147974187/f5e1fee8-fd59-4ef7-b92a-ea11d140b332)

**Comment by jiangroubao** [comment]
and this is the log I trained just with -s
![$D2VWO8EO`UY5V5@08WU}46_tmb](https://github.com/graphdeco-inria/gaussian-splatting/assets/147974187/b7facc5a-2885-4ef7-a1c8-10e9ae4f1ff9)

**Comment by jaco001** [comment]
If this isn't a problem share your dataset and I can try train it.

**Comment by jiangroubao** [comment]
> If this isn't a problem share your dataset and I can try train it.
thank you. But I'm afriad it's not the dataset's problem
link：https://pan.baidu.com/s/1sqgNZNOjArvwdtbKbQv6qw 
passwd：pv2q

**Comment by jaco001** [comment]
I'm from Central Europe... with no way to use legally Baidu ;) Any other way?

**Comment by jiangroubao** [comment]
> I'm from Central Europe... with no way to use legally Baidu ;) Any other way?

aha,thank you for your reminding and help ! I have solved this problem. It is possibly the docker that caused this bad result and I reproduced this project on my host--everthing goes well. Sorry to bother you for a long time. Thanks again
![9FIS40XWGSZV~D8S}010QCC_tmb](https://github.com/graphdeco-inria/gaussian-splatting/assets/147974187/5f69ce4a-af9d-450d-b221-c48e6f4d65f1)

![SQRXZ@AA91OBB)95EDHNYO7_tmb](https://github.com/graphdeco-inria/gaussian-splatting/assets/147974187/4f91ce0f-07e6-497e-b7f8-ea0fa448578c)

**Comment by adajdioadhwoadh** [comment]
I use virtual environment and the same problem happens

**Comment by jiangroubao** [comment]
> I use virtual environment and the same problem happens

you can just use conda environment to reproduce
