### ISSUE TITLE
Latest Visual Studio 2022 (17.10) not compatiable with CUDA

### ISSUE THREAD

**Issue by potatwei** [graphdeco-inria/gaussian-splatting#833]
I was getting this error when trying to compile simple-knn and diff-guassian-rasterization when using the lastest Visual Studio 2022.

> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\include\crt/host_config.h(164): fatal error C1189: #error: – unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag ‘-allow-unsupported-compiler’ can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.

Apparently it is a known [issue](https://forums.developer.nvidia.com/t/problems-with-latest-vs2022-update/294150), but I was not able to find the official download for Visual Studio 2022 Community version anywhere.\
I solved this issue by downloading the professional version [here](https://learn.microsoft.com/en-us/visualstudio/releases/2019/history#release-dates-and-build-numbers) and reboot the computer, then follows this [comment](https://github.com/graphdeco-inria/gaussian-splatting/issues/146#issuecomment-1697780349).

**Comment by yuzhong12** [comment]
Hi,brother.Do you solve this problem?

**Comment by potatwei** [comment]
You have to install Visual Studio 2019 or earlier versions of Visual Studio 2022. I didn't find the Community version of it, but the professional version can be downloaded in the link I provided up there. You don't need to activate Visual Studio to compile this code. 
After you download it and everything, if you still have issues follow the comment I quoted in the issue description.

**Comment by yuzhong12** [comment]
Thank you very much! Everything started working successfully after I downloaded the Visual Studio 2019 Professional version (without activation). I already have the Visual Studio 2022 Community version.

**Comment by DebbyX3** [comment]
> I was getting this error when trying to compile simple-knn and diff-guassian-rasterization when using the lastest Visual Studio 2022.
> 
> > C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\include\crt/host_config.h(164): fatal error C1189: #error: – unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag ‘-allow-unsupported-compiler’ can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
> 
> Apparently it is a known [issue](https://forums.developer.nvidia.com/t/problems-with-latest-vs2022-update/294150), but I was not able to find the official download for Visual Studio 2019 Community version anywhere. I solved this issue by downloading the professional version [here](https://learn.microsoft.com/en-us/visualstudio/releases/2019/history#release-dates-and-build-numbers) and reboot the computer, then follows this [comment](https://github.com/graphdeco-inria/gaussian-splatting/issues/146#issuecomment-1697780349).

I followed your advice and, with some tweaking, I was able to install the submodules (even the new one in `submodules/fused-ssim`)!

My Win 11 PC already had Visual Studio 2022 installed, I did **not** have to uninstall it to make everything work.

Here are my steps:

- Download and run just the Visual Studio 2019 Build Tools from [your link](https://learn.microsoft.com/en-us/visualstudio/releases/2019/history#release-dates-and-build-numbers) (last version is fine). You don't actually need to download the Professional version, build tools are enough.
- In the VS19 installer, install the "Desktop development with C++" package and make sure that MSVC v142 is checked in the right panel
- Not sure if this step is necessary, but add the following path to your Windows system env PATH:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64` (or a similar version/path in case of a different version)
- Close all your Anaconda prompts, and open a fresh one. 
- `cd` to your gaussian splatting repository 
(`cd <path to repo>/gaussian-splatting`)
- Activate the environment 
(`conda activate gaussian_splatting`)
- As [this comment](https://github.com/graphdeco-inria/gaussian-splatting/issues/146#issuecomment-1718015437) suggested, I had to add this package to the env: 
`conda install -c anaconda vs2019_win-64`. 
It probably sets up all the correct env paths.
- Similarly to [this comment](https://github.com/graphdeco-inria/gaussian-splatting/issues/146#issuecomment-1697780349), make sure to exec 
`git submodule update --init --recursive`
- Install submodules:
`pip install submodules\diff-gaussian-rasterization`
`pip install submodules\simple-knn`
`pip install submodules\fused-ssim`

Done!

**Comment by jlartois** [comment]
For those who want the VS2019 Community version, check out the Power Shell method of the answer by Christopher here: https://stackoverflow.com/questions/63297596/is-there-a-way-to-download-a-specific-version-of-visual-studio-2019

For example (in Windows PowerShell):
```
Invoke-WebRequest -Uri "https://aka.ms/vs/16/release/vs_community.exe" -OutFile "C:\Users\<username>\Downloads\vs_community.exe"
```
