### ISSUE TITLE
submodules installation: error: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by nguyenhuykhang** [graphdeco-inria/gaussian-splatting#841]
Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff_gaussian_rasterization
  Building wheel for diff_gaussian_rasterization (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\diff_gaussian_rasterization
      copying diff_gaussian_rasterization\__init__.py -> build\lib.win-amd64-cpython-310\diff_gaussian_rasterization
      running build_ext
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gaussian_rasterization
  Running setup.py clean for diff_gaussian_rasterization
Failed to build diff_gaussian_rasterization
ERROR: Could not build wheels for diff_gaussian_rasterization, which is required to install pyproject.toml-based projects

**Comment by nguyenhuykhang** [comment]
I have 2 different CUDA paths in Environment variable paths, I delete and keep only 1 CUDA path to solve this problem

**Comment by lxcug** [comment]
Thanks a lot. I just find i have setted CUDA_HOME in my path, even if the CUDA_HOME is an empty directory, it causes the same problem.
