### ISSUE TITLE
how can i use several image for training?

### ISSUE THREAD

**Issue by jaeseok4104** [graphdeco-inria/gaussian-splatting#90]
when i check this code, this project did use only one image for batch dataset.

i want to use more image for batch dataset. how can i this?

**Comment by jaeseok4104** [comment]
i already fixed this code about my system.

**Comment by Snosixtyboo** [comment]
Ok it seems you fixed it yourself, so i will close this issue?

**Comment by jaeseok4104** [comment]
yes. you will close this issue. but i have one question. why didn't use cpp optimizer for this system? just question
