### ISSUE TITLE
Question about convert.py

### ISSUE THREAD

**Issue by justinyeah** [graphdeco-inria/gaussian-splatting#903]
==============================================================================
Initializing with image pair #1 and #202
==============================================================================

  => Initialization failed - possible solutions:
     - try to relax the initialization constraints
     - manually select an initial image pair
  => Relaxing the initialization constraints.
Pose file path undefined.

[pcl::PLYReader::read] File () not found!
Error reading point cloud.

==============================================================================
Finding good initial image pair
==============================================================================

==============================================================================
Initializing with image pair #1 and #202
==============================================================================

  => Initialization failed - possible solutions:
     - try to relax the initialization constraints
     - manually select an initial image pair
  => Relaxing the initialization constraints.
Pose file path undefined.

[pcl::PLYReader::read] File () not found!
Error reading point cloud.

==============================================================================
Finding good initial image pair
==============================================================================

==============================================================================
Initializing with image pair #1 and #9
==============================================================================

  => Initialization failed - possible solutions:
     - try to relax the initialization constraints
     - manually select an initial image pair
  => Relaxing the initialization constraints.
Pose file path undefined.

[pcl::PLYReader::read] File () not found!
Error reading point cloud.

==============================================================================
Finding good initial image pair
==============================================================================

==============================================================================
Initializing with image pair #1 and #9
==============================================================================

  => Initialization failed - possible solutions:
     - try to relax the initialization constraints
     - manually select an initial image pair
  => Relaxing the initialization constraints.
Pose file path undefined.

[pcl::PLYReader::read] File () not found!
Error reading point cloud.

==============================================================================
Finding good initial image pair
==============================================================================

==============================================================================
Initializing with image pair #1 and #7
==============================================================================

  => Initialization failed - possible solutions:
     - try to relax the initialization constraints
     - manually select an initial image pair
Elapsed time: 0.016 [minutes]
ERROR: failed to create sparse model
ERROR:root:Mapper failed with code 256. Exiting.

**Comment by XYLiu69** [comment]
I have the same problem. How can I solve it
