### ISSUE TITLE
Some rendering optimization ideas

### ISSUE THREAD

**Issue by dedoubleyou1** [graphdeco-inria/gaussian-splatting#91]
I've been briefly reading through the code and I had some thoughts on potential optimizations when rendering the final scenes. If you chunk ahead of time, into something like a sparse octree, it seems like you could significantly cull the number of splats you have to check every frame. In addition, this potentially opens up another optimization, you can add a gaussian LOD system. Once you have created all your gaussian splats and organized them into your sparse octree, then at each level you simplify all sub-gaussian into a single representative gaussian, creating a meta-gaussian splat. Then when you are rendering, you can drastically reduce the number of gaussians you need to render by checking the size of the node in screen space before deciding whether to go down a level. This also opens up a clean way to make quality/performance tradeoffs at runtime, allowing you to support realtime rendering wider array of devices, and potentially sets you up for streaming data into memory.

**Comment by Snosixtyboo** [comment]
Good thinking!

But is this really an issue? 😆

**Comment by dedoubleyou1** [comment]
That's what the enhancement label is for! But totally get if it's out of scope for this repo.

**Comment by Snosixtyboo** [comment]
It's a very good idea. I believe it has some non-intuitive caveats though that put it out of the scope of this work, that's all I'm gonna say at this point ;)
