### ISSUE TITLE
Getting this error for custom dataset, but minerf dataset with bigger files are working fine. 

### ISSUE THREAD

**Issue by yogi512** [graphdeco-inria/gaussian-splatting#911]
python train.py -s './plants' -m 'output/plants' --eval
Optimizing output/plants
Output folder: output/plants [27/07 15:27:17]
Tensorboard not available: not logging progress [27/07 15:27:17]
Reading camera 401/401 [27/07 15:27:22]
Loading Training Cameras [27/07 15:27:22]
Traceback (most recent call last):
  File "train.py", line 219, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "/home/yuqi/yogi/gaussian-splatting/scene/__init__.py", line 76, in __init__
    self.train_cameras[resolution_scale] = cameraList_from_camInfos(scene_info.train_cameras, resolution_scale, args)
  File "/home/yuqi/yogi/gaussian-splatting/utils/camera_utils.py", line 58, in cameraList_from_camInfos
    camera_list.append(loadCam(args, id, c, resolution_scale))
  File "/home/yuqi/yogi/gaussian-splatting/utils/camera_utils.py", line 52, in loadCam
    image_name=cam_info.image_name, uid=id, data_device=args.data_device)
  File "/home/yuqi/yogi/gaussian-splatting/scene/cameras.py", line 46, in __init__
    self.original_image *= torch.ones((1, self.image_height, self.image_width), device=self.data_device)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 23.67 GiB total capacity; 8.02 GiB already allocated; 56.56 MiB free; 8.02 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by jaco001** [comment]
Try resize files and exit different apps to leave more space. Default res is 1600 (at long side), but you can undersize it more and get decent resoult. (All images are loaded into VRAM.)

**Comment by yogi512** [comment]
yeah working
