### ISSUE TITLE
Error for render.py. Executing instruction: "Python render.exe - m output/Output_data" reports an error(有没有大佬知道怎么回事QAQ)

### ISSUE THREAD

**Issue by jiutaojushi** [graphdeco-inria/gaussian-splatting#922]
Executing instruction: "Python render.exe - m output/Output_data" reports an error:
File "render.py", line 66, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test)
  File "render.py", line 40, in render_sets
    scene = Scene(dataset, gaussians, load_iteration=iteration, shuffle=False)
  File "/home/cver/4TDisk/thj/3DGS/gaussian-splatting/scene/__init__.py", line 49, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!

I am not lacking the directory file, but it has encountered the error

**Comment by LINHYYY** [comment]
Perhaps there is an issue with your directory structure, please check it

**Comment by jiutaojushi** [comment]
> Perhaps there is an issue with your directory structure, please check it

yes, thanks for your answer. I have already resolved the issue

**Comment by Nineteeninetynine** [comment]
when you run render.py -m<> try to add --eval.  this can help split the test and train dir.
