### ISSUE TITLE
How to train model on multi-GPUS?

### ISSUE THREAD

**Issue by zhangseammm** [graphdeco-inria/gaussian-splatting#937]
I want to train the large scale datasets such as alameda, but it only run on the GPU0 and run out of memory. It did not use my GPU1.
How to change the code?
![Screenshot 2024-08-20 at 15 05 49](https://github.com/user-attachments/assets/76bdd144-a3e2-41a4-b1b3-81c87086b787)

**Comment by AsherJingkongChen** [comment]
> How to change the code?

With a code editor, you can edit the code.

**Comment by cc1oud** [comment]
hi bro, did you solve this problem , i have same problem, and i want to know how two use my two gpus

**Comment by datouzhan** [comment]
> 嗨兄弟，你解决了这个问题吗？我也有同样的问题，我想知道如何使用我的两个 gpu

grendel-gs
