### ISSUE TITLE
Viewer: How to use key cameras to create trajectory?

### ISSUE THREAD

**Issue by yifita** [graphdeco-inria/gaussian-splatting#94]
Thank you for the amazing work! I see the key camera definition in the interactive viewer and suspect that I could use those to create a path? Is that the case? If so, could you share how to use this function?
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/8813291/3d76f167-bb6f-40e4-8e72-fc0e302b4d4b)

**Comment by Snosixtyboo** [comment]
Hi,

good question, unfortunately, I'm not familiar with all of the vast features SIBR offers. Would you consider shooting them (they list emails to contact) a mail for this?

**Comment by grgkopanas** [comment]
I don't think there is a robust and user friendly way to interpolate key
frames in sIBR this is probably an undocumented feature that not many
people know how to use.

If you need it for research purposes I can ask around.

Best,
George Kopanas

**Comment by gdrett** [comment]
Hi Yifan, I think all these features got deactivated at some point, but as GK says, these were never super robust. We'll look into it ASAP.

**Comment by yifita** [comment]
I don't think this is urgent at all. I just saw the buttons and thought i didn't find a way to utilize them. Thanks!

**Comment by gdrett** [comment]
I was looking at an incorrect version. To create a path, set your camera in the interactive viewer to the starting viewpoint/pose, and press "Add key", then move to the next (key)point on the path and press "Add key" again, etc. When you are done, you can save the with "Save key cameras.." to a file (you should get a pop up to give the filename -- I tested this only on windows however, not sure about linux). You can then "Load path" and "Play" by setting the speed to something small (0.1 or less). The "Save frames" button only save the views of the keypoints for now, I'll try and fix this soon.

**Comment by smallfly** [comment]
Hi,

First of all this is amazing. I'm just blown away by the quality of what I'm seeing.

I just tried what you explained just above, but the viewer freezes once I load a path. I'm using the pre-compiled version of the viewer.

**Comment by gdrett** [comment]
Hi, the viewer can freeze, but you can sometimes get it to unfreeze by increasing the “speed” number. Overall, the best way to generate a path is using the “Record” button (see https://github.com/graphdeco-inria/gaussian-splatting/issues/59).
We know the support for paths isn’t great — we’ll try and look into the command line player for paths (which might solve the memory issue) but we cant promise anything.

**Comment by jlartois** [comment]
I've tried this, and when I do "Save key cameras.." to a file, I name the file using extension '.lookat', for example 'posetrace.lookat'. "Load path" and "Play" then work correctly, although I recommend a lower value for "Speed" (on the right side of "Stop").

If the path does not end with '.lookat', the viewer freezes when trying to load it in. I use the pre-compiled Windows version.
