### ISSUE TITLE
Error - Depth Map Causes More Floaters

### ISSUE THREAD

**Issue by JohannesKrueger** [graphdeco-inria/gaussian-splatting#941]
Hello, thank you very much for the great work. I have already tested the new depth map feature on several datasets based on the depth maps from depth anything v2. However, significantly more floaters appear in all trained models than in the previous version of 3D Gaussian Splatting.
Although the new version delivers a higher PSNR, the many floaters and the minimal training time have become significantly negative. Are there other tests for the new version or have I perhaps made mistakes during training?

The results mentioned come from "smaller - to medium sized models" initialized with 15 - 100k splats and trained with 7k, 30k, 100k steps to approx. 300k - 3 million splats.

**Comment by fasteinke** [comment]
Just to add, my first testing of the latest version, with and without depth maps, show subjectively far worse results when depth loss is calculated - this is on a dataset with a brick end wall, and vegetation areas.

So I would also ask for possibly more explanation as how to best use this new feature ...

Thanks!

**Comment by ChchNiu** [comment]
This is the second image without applying depth loss.
![Uploading 00001.png…]()

**Comment by ChchNiu** [comment]
This is the second image without applying depth loss.
![00001](https://github.com/user-attachments/assets/be199427-0f7e-4fd9-9601-986685b6d378)

**Comment by lt-wang** [comment]
Hello, I have the same problem, have you solved it?
![00006](https://github.com/user-attachments/assets/7b8e2aa8-2055-4a67-9753-f2b917e290d7)
