### ISSUE TITLE
Why not build a new branch for the new functions???

### ISSUE THREAD

**Issue by qzhang-cv** [graphdeco-inria/gaussian-splatting#948]

**Comment by FunnyPocketBook** [comment]
Or have another branch where the original code is "preserved".
It could be that some people in the future would want to reproduce the results in the paper but are not aware that the main branch of this repo is updated with new features, which changes the metric scores

**Comment by alanvinx** [comment]
Hi, the new features are added on top of the current state of the repo. You can still reproduce the results in the paper by disabling exposure compensation and depth regularization when training: `python train.py -s [source] -m [output_model] --depth_l1_weight_init 0 --depth_l1_weight_final 0 --exposure_lr_init 0 --exposure_lr_final 0`.
