### ISSUE TITLE
new release imports cv2 while it is not included in the environment.yml and cannot be installed for the python version

### ISSUE THREAD

**Issue by Pydes-boop** [graphdeco-inria/gaussian-splatting#949]
In scene/cameras.py `import cv2` is used which is not included in the environment.yml and conflicts with some older python versions like python 3.9 where it cannot be installed.

2 possible fixes for this:
Option 1: install cv2 if this is compatbile with your python version (issue for some users because cuda 11.6 is easiest installed via ubuntu 20.04 which is python 3.9)

Option 2:
reset the repository back by 2 commits:
```
git clone git@github.com:graphdeco-inria/gaussian-splatting.git --recursive
git reset --hard HEAD~2
```
If you do this you will either also have to reset the gaussian_rasterizer repository to its previous state or just add a dummy variable for the depth camera which is output by the rasterizer in `gaussian_renderer/__init__.py`:

```
    rendered_image, radii, depth_image = rasterizer( # ! Add the missing depth_image argument here !
        means3D = means3D,
        means2D = means2D,
        shs = shs,
        colors_precomp = colors_precomp,
        opacities = opacity,
        scales = scales,
        rotations = rotations,
        cov3D_precomp = cov3D_precomp)
```

**Comment by alanvinx** [comment]
Hi, thank you for pointing this, we just added the missing package `opencv-python` to `environment.yml`.
However you should be able to run `pip install opencv-python` in a python 3.9 env.

**Comment by Pydes-boop** [comment]
ive tried to reproduce the opencv issue on my VM and youre right, it seems to have been something else on my system not working correctly. Thanks for updating the environment.yml 👍🏻
