### ISSUE TITLE
How to deal with appearance inconsistencies

### ISSUE THREAD

**Issue by lxzbg** [graphdeco-inria/gaussian-splatting#95]
First of all, thank you for your great work. I have a question, if there is lighting variation in my training data, will the algorithm be able to handle it? and if not, is it possible to add something like embedding appearance?

**Comment by grgkopanas** [comment]
There is nothing in the code-base right now that supports that. I am sorry

**Comment by lxzbg** [comment]
> There is nothing in the code-base right now that supports that. I am sorry

thank you for your reply

**Comment by yzslab** [comment]
Hi, I use a MLP to simulate lighting variation. Here is my modifications that based on this repository: https://github.com/yzslab/gaussian-splatting/commit/f64724ad19c542236c0cb987c0fc64e6b412f7f6.

Without lightning variation MLP:

https://github.com/graphdeco-inria/gaussian-splatting/assets/564361/464d6832-0acc-4f75-80cb-1054f5fce039


With lightning variation MLP:

https://github.com/graphdeco-inria/gaussian-splatting/assets/564361/e5d0ff46-3648-446f-818f-0a47e6f20c3a

Hope this can help you.

**Comment by lxzbg** [comment]
@yzslab  Thank you for your work, this is indeed the problem I want to solve, but I don't quite understand this place [rendered_image = rendered_image * appearance_factors](https://github.com/yzslab/gaussian-splatting/commit/f64724ad19c542236c0cb987c0fc64e6b412f7f6), could you introduce it specifically, and what is the reason for this treatment

**Comment by yzslab** [comment]
> @yzslab Thank you for your work, this is indeed the problem I want to solve, but I don't quite understand about this [rendered_image = rendered_image * appearance_factors](https://github.com/yzslab/gaussian-splatting/commit/f64724ad19c542236c0cb987c0fc64e6b412f7f6), could you introduce it specifically, and what is the reason for this treatment

Hi, it means that the original gaussian splatting pipeline produce an appearance consistent result, and the `appearance_factors` change its appearance so as to match to the input image.

**Comment by tonyyu0822** [comment]
@yzslab Thanks for your work! I am trying your codebase with a custom colmap dataset. It runs smoothly with train.py but it seems to give me this error when running render.py:

> Traceback (most recent call last):
  File "render.py", line 79, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test, args.appearance_embedding)
AttributeError: 'Namespace' object has no attribute 'appearance_embedding'

and the printed arg shows appearance_embedding attribute is missing as well. When I look at the normalized_appearance_embedding.json file it produces, it simply:
{
    "1": 1.0
}. Could you help me with this confusion? Thanks

**Comment by yzslab** [comment]
> @yzslab Thanks for your work! I am trying your codebase with a custom colmap dataset. It runs smoothly with train.py but it seems to give me this error when running render.py:
> 
> > Traceback (most recent call last):
> > File "render.py", line 79, in 
> > render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test, args.appearance_embedding)
> > AttributeError: 'Namespace' object has no attribute 'appearance_embedding'
> 
> and the printed arg shows appearance_embedding attribute is missing as well. When I look at the normalized_appearance_embedding.json file it produces, it simply: { "1": 1.0 }. Could you help me with this confusion? Thanks

Hi, try to add `--appearance_embedding 1` (the value `1` is the key of the dictionary in `normalized_appearance_embedding.json`) when you running `train.py`. I will fix it later.
If you haven't define appearance groups, it will simply use the colmap camera id, which means that the images taken by the same camera have a consistent appearance. Your `normalized_appearance_embedding.json` means that your image set only have single camera. Please take a look [this file](https://github.com/yzslab/gaussian-splatting/blob/main/generate_image_apperance_group.py) about how to define groups.

**Comment by tonyyu0822** [comment]
@yzlab thanks for the response, did you mean adding value 1 during render.py? I didn't see an argument in train.py

Also, I  have another question about this implementation. If--appearance_embedding 1 should be added to render.py
For the viewer result you've shown, did you compile with a trained model(cfg.arg (produced at the end of the training phase))? If the --appearance embedding 1 is added in the rendering phase but not training phase, how will the viewer reflect this change in appearance when the viewer? Thanks so much

**Comment by Bin-ze** [comment]
Hello, very nice implementation! I want to know where do the gradients used to optimize the appearance pre-embedding come from? I looked at the code and you didn't modify the reverse in the rasterizer, so does that mean the gradients are passed directly from rendered_image = rendered_image * appearance_factors to appearance_factors?

**Comment by yzslab** [comment]
Hi, you are right!
