### ISSUE TITLE
I can not train my dataset

### ISSUE THREAD

**Issue by daodan666** [graphdeco-inria/gaussian-splatting#952]
when I want to train my dataset,it stop

`(Pytorch) PS D:\download\gaussian-splatting-main\gaussian-splatting-main> python train.py -s data -m data/output
Optimizing data/output
Output folder: data/output [28/08 19:06:46]
Reading camera 185/185 [28/08 19:06:46]
Loading Training Cameras [28/08 19:06:46]
Loading Test Cameras [28/08 19:06:49]
Number of points at initialisation :  6751 [28/08 19:06:49]
Training progress:   0%|                                                                        | 0/30000 [00:00<?, ?it/s]T
raceback (most recent call last):
  File "train.py", line 252, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpo
int_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 94, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg, use_trained_exp=dataset.train_test_exp)
  File "D:\download\gaussian-splatting-main\gaussian-splatting-main\gaussian_renderer\__init__.py", line 86, in render     
    rendered_image, radii, depth_image = rasterizer(
ValueError: not enough values to unpack (expected 3, got 2)
Training progress:   0%|                                                                        | 0/30000 [00:00<?, ?it/s]
(Pytorch) PS D:\download\gaussian-splatting-main\gaussian-splatting-main> 
` 
my  coda is 12.4.Can't it train me on this dataset?

**Comment by alanvinx** [comment]
Hi, the rasterizer was updated and you can get the new version by running: `git submodule update --remote submodules/diff-gaussian-rasterization` then  you should reinstall it using `pip install submodules/diff-gaussian-rasterization`.

**Comment by daodan666** [comment]
Thank you for your help
