### ISSUE TITLE
The SIBR viewer discards some gaussians near the cameras

### ISSUE THREAD

**Issue by Master-cai** [graphdeco-inria/gaussian-splatting#963]
Hi guys! I'm using other implement of gaussian-splatting to train the gaussians,  and I convert them into the SIBR style to use the SIBR_viewer. But the rendered images seem weird that the SIBR drops some gaussians in the "Splats" model, but works normal in other two model: "Initial Points" and "Ellipsoids". I don't know what's going on. The following is some examples when snapping to camera 0:

### in Splats model
<img width="1532" alt="image" src="https://github.com/user-attachments/assets/431e6884-1c4a-4a45-b058-0a5eee114054">

### in Initial Points model
<img width="1532" alt="image" src="https://github.com/user-attachments/assets/15abb653-ea89-49bd-869d-6bf50254de7c">

### in Ellipsoids model
<img width="1532" alt="image" src="https://github.com/user-attachments/assets/d901d0c1-d6b3-4eff-b770-eba3ad485eec">

cc @Snosixtyboo @graphdeco @gdrett

**Comment by ERGOWHO** [comment]
Hi same problem here, did you solve this issue?

**Comment by Snosixtyboo** [comment]
This looks like a potential problem with znear culling. Is it possible that the trained scene is using a very, very small extent?

**Comment by ERGOWHO** [comment]
> This looks like a potential problem with znear culling. Is it possible that the trained scene is using a very, very small extent?

Thanks reply, yes, my scene is very small, the input image is only 584x328, but I already set the znear as 0.000001, still when I save the render_image from render_pkg, some items closer to the camera will become weird and part of gaussians on it disappeared

**Comment by Master-cai** [comment]
@Snosixtyboo Thanks for the key clues!

Yes, the scene scale is very small, for example 0.04968649782240391 or 0.021322472207248214. I also tried to set the znear to a very small value as mentioned by @ERGOWHO , but it changes nothing. I'm confused why the Ellipsoids model works well but the the rendered images are incomplete. 

I'll try to normalize the scene scale and it would be great if you can provide some idea to fix the SIBR viewer directly!

**Comment by ERGOWHO** [comment]
> @Snosixtyboo Thanks for the key clues!
> 
> Yes, the scene scale is very small, for example 0.04968649782240391 or 0.021322472207248214. I also tried to set the znear to a very small value as mentioned by @ERGOWHO , but it changes nothing. I'm confused why the Ellipsoids model works well but the the rendered images are incomplete.
> 
> I'll try to normalize the scene scale and it would be great if you can provide some idea to fix the SIBR viewer directly!

Did you try saving the rendered image and check if the rendered image also have the same problem. Not just checked with SIBR, cause I tried my gaussian model using online gaussian viewer it does not have the guassians closer to camera disappear issue, but with SIBR this issue comes out, and I saved rendered images it also has some gaussian closer to camera get miss up.

**Comment by ERGOWHO** [comment]
I am using my own small scene dataset feed into gaussian training, turns out some gaussian closer to camera mass up, but I try the same small dataset images generated from colmap and then feed into the gaussian training, it look normal.

**Comment by ERGOWHO** [comment]
Hi I have proved this issue is gaussian scene too small, if you scale up points scale, you can see this issue is gone.

**Comment by Master-cai** [comment]
> but with SIBR this issue comes out, and I saved rendered images it also has some gaussian closer to camera get miss up.

@ERGOWHO In my case, the rendered images are normal.

> if you scale up points scale, you can see this issue is gone.

And I want to ask are you scaling the scene by multiplying the means by a coefficient? If so, should the Intrinsic, Extrinsic and the scale of the gaussians be multiplied?

**Comment by ERGOWHO** [comment]
> > but with SIBR this issue comes out, and I saved rendered images it also has some gaussian closer to camera get miss up.
> 
> @ERGOWHO In my case, the rendered images are normal.

Then I guess you only need to scale up the scene this SIBR issue will gone.
> 
> > if you scale up points scale, you can see this issue is gone.
> 
> And I want to ask are you scaling the scene by multiplying the means by a coefficient? If so, should the Intrinsic, Extrinsic and the scale of the gaussians be multiplied?

The way I did is scale up both points xyz by*10, and camera pose T (do not change R).

**Comment by Master-cai** [comment]
@ERGOWHO Thanks!

**Comment by Keunmo** [comment]
Hi, I faced same issue, and I could fix it by make little change in [cuda_rasterizer/auxiliary.h](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/9c5c2028f6fbee2be239bc4c9421ff894fe4fbe0/cuda_rasterizer/auxiliary.h#L166). 
in function `in_frustrum()`, it ignore if gaussian point's z distance is less than `0.2f`.
so, you can render near camera gaussians by changing this value that adequate to your scene.

**Comment by Master-cai** [comment]
@Keunmo Great! Thanks!
