### ISSUE TITLE
make_depth_scale.py - No module named 'read_write_model'

### ISSUE THREAD

**Issue by lileaLab** [graphdeco-inria/gaussian-splatting#966]
I created a depth image and tried to run `make_depth_scale.py`.
However, I got the following error
`ModuleNotFoundError: No module named 'joblib'`
I did `conda install joblib` to install the module.

However, when I ran python again, I got the following error
`ModuleNotFoundError: No module named 'read_write_model'`
The module was not found by either `conda install` or `pip install`.

Where can I get this from?

**Comment by alanvinx** [comment]
Hi, we reverted the `main` branch to its previous state but this should be fixed in the `dev` branch now.

**Comment by lileaLab** [comment]
I was able to process it successfully.Thank you for your response!
