### ISSUE TITLE
3D overlapped

### ISSUE THREAD

**Issue by KunWang123** [graphdeco-inria/gaussian-splatting#968]
I used the official code, but used the metashape data as the initial point cloud. The reconstruction looked like two objects overlapped, with about 70% overlap. Individual objects can be seen at different angles. 
eg. 
![image](https://github.com/user-attachments/assets/fa418768-f724-48db-8a3e-9d8ecf372b9b)
![image](https://github.com/user-attachments/assets/33abe078-679e-4147-a780-9a36d25c38e0)

Some advice given?

**Comment by jaco001** [comment]
Point cloud have 'double shoe'? Can you put here pic too?

**Comment by KunWang123** [comment]
@jaco001 Thanks for your answer. My initial point cloud only one shoe. 
like this 
![image](https://github.com/user-attachments/assets/62f9e014-9ed2-4dc8-847e-d97dea8b2b43)
I ignored some processing in the code ?

**Comment by jaco001** [comment]
Do you merge sparse/0 and sparse/1 ?
Script use only one sparse/0 (AFAIK)

**Comment by KunWang123** [comment]
Solved. THANKS
