### ISSUE TITLE
Colmap on Windows on own Material

### ISSUE THREAD

**Issue by janoschsimon** [graphdeco-inria/gaussian-splatting#97]
Hey there first of all im blown away by the results! i tried your samples and they are all breathtaking :)
then i tried my image set and ran it through colmap.bat on windows (the onne click download) but when i try on that images gaussian-splatting says its need simple pinhole or pinhole... then i tried to run the convert.py but that also didnt work :( anyone got a workflow to get an imageset in the right format for gaussian-splatting?
thx Janosch

**Comment by Snosixtyboo** [comment]
Hi,

what exactly doesn't work with the ```convert.py```? Is there some error output? The workflow described in the readme should work, otherwise we need to fix it.

**Comment by janoschsimon** [comment]
this is the error message i get

`(gaussian_splatting) D:\AI-Stuff\gaussian-splatting>python convert.py  --source_path D:\AI-Stuff\gaussian-splatting\input
[option_manager.cc:815] Check failed: ExistsDir(*image_path)
ERROR: Invalid options provided.
ERROR:root:Feature extraction failed with code 1. Exiting.`

inside the input folder is the output from the windows colmap.bat
<location>
|---images
|   |---<image 0>
|   |---<image 1>
|   |---...
|---sparse
    |---0
        |---cameras.bin
        |---images.bin
        |---points3D.bin

after i run the python convert.py i have in the input folder a new folder distorted and inside that sparse

is my syntax wrong?
with the viewer i use it exactly the same.
im on windows 11 pro and use miniconda.

and thx for the fast answer :)
Janosch

**Comment by Snosixtyboo** [comment]
Hi,

so you already have your colmap result. According to the readme, you can try to create the following structure:
```
<location>
|---input
|   |---<image 0>
|   |---<image 1>
|   |---...
|---distorted
    |---database.db
    |---sparse
        |---0
            |---...
```
and then run (because you already did most of the steps)
```
python convert.py -s <location> --skip_matching [--resize]
```

The standard workflow is to put **only** the images into ```<location>/input```, nothing else, and then call the ```convert.py -s <location> [--colmap_executable <path_to_colmap.bat>]  [--resize]```, without ```--skip_matching```. This is better tested by us, but will take longer because it would redo all the steps you already did manually in the bat.

**Comment by janoschsimon** [comment]
still the same error :( 
`(gaussian_splatting) D:\AI-Stuff\gaussian-splatting>python convert.py  --source_path D:\AI-Stuff\gaussian-splatting\input --colmap_executable D:\AI-Stuff\COLMAP-3.8-windows-cuda\COLMAP.bat
[option_manager.cc:815] Check failed: ExistsDir(*image_path)
ERROR: Invalid options provided.
ERROR:root:Feature extraction failed with code 1. Exiting.`

and when i just type colmap in anaconda it seems to work:
`(gaussian_splatting) D:\AI-Stuff\gaussian-splatting>colmap
COLMAP 3.8 -- Structure-from-Motion and Multi-View Stereo
              (Commit Unknown on Unknown without CUDA)

Usage:
  colmap [command] [options]

Documentation:
  https://colmap.github.io/

Example usage:
  colmap help [ -h, --help ]
  colmap gui
  colmap gui -h [ --help ]
  colmap automatic_reconstructor -h [ --help ]
  colmap automatic_reconstructor --image_path IMAGES --workspace_path WORKSPACE
  colmap feature_extractor --image_path IMAGES --database_path DATABASE
  colmap exhaustive_matcher --database_path DATABASE
  colmap mapper --image_path IMAGES --database_path DATABASE --output_path MODEL`

thx janosch

**Comment by Snosixtyboo** [comment]
Hi,

pleaes try
```--source_path D:\AI-Stuff\gaussian-splatting```
instead of
```--source_path D:\AI-Stuff\gaussian-splatting\input```

Hth,
Bernhard

**Comment by Snosixtyboo** [comment]
Unless your images are actually in 
```
D:\AI-Stuff\gaussian-splatting\input\input
```
, then I'm not sure what is wrong

**Comment by janoschsimon** [comment]
thats it now its working HURRAYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY hehe what a fight but well worth it excited to check my result on my own images and experiment ALOT :)
thx again janosch
btw Bernhard sounds german? :) im from germany too :)

**Comment by Snosixtyboo** [comment]
Sure thing, glad it worked!

I'm from Austria, actually 😄
