### ISSUE TITLE
Issues about the Fov Y in SIBR viewer.

### ISSUE THREAD

**Issue by jzhu98** [graphdeco-inria/gaussian-splatting#977]
The initial Fov Y when opening the SIBR viewer is too large, which makes it far away from the actual view. How to solve this?

**Comment by leblond14u** [comment]
Hi, 
I think I'm having a smiliar issue.
My camera objects **FoVx** and **FoVy** are correct but when seen from the SIBR viewer the **FoVx** seems totally off (way too wide).
When I tried to invert the **FoVx** and **FoVy** in my `camera.txt file ` the SIBR viewer FoV seems more right. 
I'd like to understand what's going on there. 

Could you give more details about how you solved this issue ?

Best regards,
