### ISSUE TITLE
Novel View Synthesis from render.py

### ISSUE THREAD

**Issue by MilesMena** [graphdeco-inria/gaussian-splatting#984]
I would like to render a novel view using render.py. I've been able to render training images, but I need to render the gaussians from views unseen in training. I've tried adjusting the 'Camera' object that is created from a training image and lives in a 'Scene' object. In particular, I've adjusted the camera's 'full_proj_transform' and 'world_view transform', but this doesn't seem to move to a novel view. Instead of adjusting the 'full_proj_transform' and 'world_view_transform', I'm going to initialize my own Camera object with similar 'R' and 'T' values.

I'd appreciate if someone could explain what each of the parameters of 'Camera' Mean:

```
class Camera(nn.Module):
    def __init__(self, resolution, colmap_id, R, T, FoVx, FoVy, depth_params, image, invdepthmap,
                 image_name, uid,
                 trans=np.array([0.0, 0.0, 0.0]), scale=1.0, data_device = "cuda",
                 train_test_exp = False, is_test_dataset = False, is_test_view = False
                 ):
```

I'm a bit confused by 'image' and 'image_name', because why would the function 'render' require a previous image if it's creating novel views from a location and orientation.

**Comment by lt-wang** [comment]
The purpose of using “images” is to facilitate subsequent rendered images and GT images to calculate psnr, etc. I think so.

**Comment by MilesMena** [comment]
I see, so render.py is only used compare rendered 2D gaussians to the ground truth images. Do you know if there is anything within the code base that will allow me to render NOVEL images? I have some projects I'd like to build that require a novel_rendering script. Using interactive viewers like SIBR or Nerf Studio don't seem to fit my use case.

**Comment by lt-wang** [comment]
> I see, so render.py is only used compare rendered 2D gaussians to the ground truth images. Do you know if there is anything within the code base that will allow me to render NOVEL images? I have some projects I'd like to build that require a novel_rendering script. Using interactive viewers like SIBR or Nerf Studio don't seem to fit my use case.

 Rendering with a custom camera？Maybe this  #574  can help you.

**Comment by lt-wang** [comment]
Rendering with a custom camera？Maybe this #506   can help you.
