### ISSUE TITLE
branch dev: TypeError: __new__() got an unexpected keyword argument 'antialiasing'

### ISSUE THREAD

**Issue by zhangwenniu** [graphdeco-inria/gaussian-splatting#994]
Hi, when I try to run the dev branch, i got the error: 
```TypeError: __new__() got an unexpected keyword argument 'antialiasing'```
This error occurs in recent days, full error logging are list below: 
```
Optimizing data/output/test9
Output folder: data/output/test9 [24/09 13:06:32]
Tensorboard not available: not logging progress [24/09 13:06:32]
Reading camera 100/100 [24/09 13:06:32]
Loading Training Cameras [24/09 13:06:32]
Loading Test Cameras [24/09 13:06:35]
Number of points at initialisation :  30840 [24/09 13:06:35]
Training progress:   0%|                                                                                                                                          | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 252, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 94, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg, use_trained_exp=dataset.train_test_exp)
  File "/home/zhangwenniu/github/gaussian-splatting-docker/gaussian_renderer/__init__.py", line 49, in render
    antialiasing=pipe.antialiasing
TypeError: __new__() got an unexpected keyword argument 'antialiasing'
Training progress:   0%|            
```

I think this problem maybe relate to one recent commit of antialising code updates. 
[commit b4332aa](https://github.com/graphdeco-inria/gaussian-splatting/commit/b4332aae6a77ce57f8834489b1f625a8f5f05c7b#diff-8c727bf8c5ac33322e087f17ee568f526e50d21635cb0f22c314e0755cc7e609R50)

**Comment by zhangwenniu** [comment]
@alanvinx Hello, I was wondering if there might be a connection between the bug and this commit?

**Comment by xuzijian-hik** [comment]
I've met the same error when running the dev branch

**Comment by alanvinx** [comment]
Hi, can you please send the commit's tag that you are currently using for the rasterizer? You can see it by running `git log` inside the `submodules/diff-gaussian-rasterization` folder.

**Comment by xuzijian-hik** [comment]
> I've met the same error when running the dev branch

OK I solve it. The reason for this problem is that the author has updated the contents of the diff_gaussian_rasterization, just  uninstall it and reinstall the new version.

**Comment by zhangwenniu** [comment]
Thanks for your help. The code has been updated, but the library in the conda environment for gaussian_splatting has not been updated, which is why training is failing. 
The solution is
```
conda activate gaussian_splatting
pip uninstall diff_gaussian_rasterization
submodules/diff-gaussian-rasterization
```

**Comment by nagexiaochengzi** [comment]
Is it downloaded from the main page of this link? Then, I ran python setup.py install and the installation was successful, but I still have this problem "https://github.com/graphdeco-inria/diff-gaussian-rasterization"

**Comment by kaixin-bai** [comment]
I cannot solve the problem by reinstalling submodules/diff-gaussian-rasterization.

**Comment by iambrc** [comment]
> I cannot solve the problem by reinstalling submodules/diff-gaussian-rasterization.

I solve it.  Check if there are two diff_gaussian_rasterization folders in your conda environment : `.\envs\3dgs\Lib\site-packages` . And only keep `diff_gaussian_rasterization-0.0.0-py3.10-win-amd64.egg`.

**Comment by twinkle-w-s** [comment]
But I still can't fix it by using these following apllications

**Comment by JianxiangL** [comment]
3dgs-accel分支才行

**Comment by meghabhamare** [comment]
Below steps has helped me 
conda activate gaussian_splatting
git submodule update --init --recursive
pip uninstall -y diff-gaussian-rasterization
pip uninstall -y simple-knn

# delete all possible build/install artifact
rm -rf ./submodules/diff-gaussian-rasterization/build
rm -rf ./submodules/diff-gaussian-rasterization/*.egg-info

rm -rf ./submodules/simple-knn/build
rm -rf ./submodules/simple-knn/*.egg-info

pip install -v --no-cache-dir --force-reinstall ./submodules/diff-gaussian-rasterization
pip install -v --no-cache-dir --force-reinstall ./submodules/simple-knn

I had to do the same for fused-ssim as its a submodule. 
So, here I have re-built the code from scratch for my specific environment and that has helped fix the issue. 

Post this you can run the train.py .

Regards.
